### ISSUE TITLE
Pinned Subscriptions should be displayed at the top

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1027]
`pin_to_top` https://github.com/zulip/zulip-mobile/blob/d1793a715fb2d3e63a9b5bfa29bd51d6416fd306/src/nullObjects.js#L56 should be used

**Comment by borisyankov** [comment]
Not sure if we will implement it or if we do, if it will be like this.

**Comment by kunall17** [comment]
@borisyankov All this means is we should sectionize the streams list and display the pinned streams at top, maybe using SectionList. 
I'll work on this after your confirmation?

**Comment by borisyankov** [comment]
Nope. We will not implement this for now. Maybe never.
It certainly isn't working well for a lot of cases on the web app and it might be reworked.
Closing it for now. We can always reconsider later (we might have a 'favorite' tab with pinned Streams, Users etc.)
