### ISSUE TITLE
All streams tab should not display the switches by default

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1028]

**Comment by borisyankov** [comment]
What do you mean?

**Comment by kunall17** [comment]
It would be better if these switches are not displayed on switching to this tab instead there should be a button to toggle their visibility

<img src="https://user-images.githubusercontent.com/12700799/29271146-bc4059be-8117-11e7-9eb4-ab129235670f.png" width="40%" />

**Comment by borisyankov** [comment]
Why would it be better though?

**Comment by kunall17** [comment]
* Generally a list controls are not shown by default
* It looks little filled up 

The only problem I see if the control's are hidden by default is it will look a lot like the subscribed list!

**Comment by borisyankov** [comment]
Exactly. My point was that this can be improved for sure, but also we might think of something better later, and I wouldn't consider it an issue for now.

**Comment by timabbott** [comment]
Yeah, I'm not sure I see an obvious improvement we can make here.
