### ISSUE TITLE
Unread streams should not be expanded by default in unread tab in left drawer 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1029]
Atleast the muted streams should not expanded

**Comment by borisyankov** [comment]
Not having collapsible streams is intentional for now.
No further action on this, until we hear feedback from real users.

**Comment by timabbott** [comment]
Should unread messages on muted streams appear in this view at all?

**Comment by borisyankov** [comment]
Good point. For now, they show quite dimmed (which I implemented after your feedback).
Let's wait and see how it does in practice? Maybe the backend will omit these even if we see people don't like them.

**Comment by timabbott** [comment]
Yeah, getting feedback sounds good.  I can also imagine sorting them to the bottom under a "Muted streams" heading or something.

**Comment by borisyankov** [comment]
@timabbott after latest discussion, I actually think not showing them at all is the best option and we should try it (will push this soon)

**Comment by borisyankov** [comment]
Closing as implemented the hiding of muted streams & topics.
