### ISSUE TITLE
Compose box text input not correctly placed in android 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1030]
The Input seems to be below (not completely) from the compose box

**Comment by keithw** [comment]
Am also encountering this -- here is a screen shot (app version 1.0.16 on Android 7.1.2 on a Google Pixel):

![screenshot_20170815-200900](https://user-images.githubusercontent.com/208955/29345993-3cb06a8c-81f7-11e7-93d0-cc217ca75724.png)

**Comment by kunall17** [comment]
Fixed in #1046
