### ISSUE TITLE
Narrowing conversation from drawer shows only sender messages

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1031]
Noticed only when narrowing to a private chat not a group chat

**Comment by borisyankov** [comment]
Does it happen always for you? I can not reproduce. @Sam1301 have you noticed this?

**Comment by Sam1301** [comment]
Me neither, tried on current master with different private conversations. @kunall17 any particular steps to repro this bug?

**Comment by borisyankov** [comment]
I have heard this being reported, but have not experienced it.
@kunall17 if you can reproduce consistently, please try and fix it.

**Comment by kunall17** [comment]
No specific steps, I'll try to fix this one!

**Comment by kunall17** [comment]
Some more info: 
It happens only when conversations are grouped like this
<img src="https://user-images.githubusercontent.com/12700799/29274167-7cbad686-8124-11e7-85c8-f7909d8dc0a8.png" width="40%" /> 

Cannot reproduce on master though!

**Comment by borisyankov** [comment]
These should not even be grouped like that :)

**Comment by kunall17** [comment]
This is fixed, can be closed now!
