### ISSUE TITLE
Outbox items do not group correctly

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1032]
When you send a message, it gets a temporary subheader in the message list, and once it is sent the subheader disappears. This subheader should not appear at all!

**Comment by borisyankov** [comment]
@kunall17 this one is not resolved correctly.
This will likely improve with the selector approach we discussed.

**Comment by kunall17** [comment]
Yeah, I did this purposely as I thought it will be better if the outbox messages could be easily noticed if they have the header, but now realized that in a topic narrow (and in general too) it doesn't look good

**Comment by kunall17** [comment]
Fixed, can be closed now!
