### ISSUE TITLE
Testflight v1.0.16 blocks all UI actions for ~10 seconds on load.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#1035]
When the app gets past the phase of the spinner and loads you into whatever narrow you are in, clicking on the sidebar buttons will not do anything for around ~10 seconds on my phone (iPhone 6s), and then finally all actions will happen at once (as the queue is suddenly able to process events).

This also leads to interesting states such as both sidebars being open at the same time because all the events process quickly together after the physical event.

If you look carefully, you'll notice both sidebars are open.

![img_1358](https://user-images.githubusercontent.com/10321399/29292265-61c0ae92-80fb-11e7-959e-48fe1a5bc4d0.PNG)

**Comment by borisyankov** [comment]
I saw the exact same thing, so this is reproducible (and super annoying).
@Sam1301 already did a fix that helps with this, I am looking into what else is happening to cause this.
Definitely a new version with these fixes coming in 1-2 days. This is not OK.

**Comment by borisyankov** [comment]
@brockwhittaker try the latest TestFlight. It is more of an intermediary/quick fix, that hmmm, behaves inconsistently. In fact, on the test iPhone 5 it does behave badly, but works pretty well in my Simulator on the Macbook.

**Comment by borisyankov** [comment]
Closing, as significantly improved (or fixed).
Will be in next TestFlight.
