### ISSUE TITLE
Message contents is overlapping on scroll.

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#1061]
<img width="377" alt="screen shot 2017-08-19 at 8 07 08 pm" src="https://user-images.githubusercontent.com/18511177/29487646-9917216e-851a-11e7-9d4c-b3272de922b4.png">
<img width="374" alt="screen shot 2017-08-19 at 8 07 28 pm" src="https://user-images.githubusercontent.com/18511177/29487647-9986a0ac-851a-11e7-996c-2cec6903e121.png">

**Comment by Sam1301** [comment]
yeah I am also getting this error on current master
with this warning
```
Error: Bad value for 'anchor': undefined
```

**Comment by borisyankov** [comment]
Get the latest `master` for the bug @Sam1301 is referring to.

**Comment by borisyankov** [comment]
The other bug, I guess i am calculating incorrectly the MessageHeader index. Will try to fix.

**Comment by Sam1301** [comment]
this is fixed for me on latest master

**Comment by vishwesh3** [comment]
fixed for me too. 👍
