### ISSUE TITLE
Master build is failing 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1067]
- [ ] `TypeError: (0 , _narrow.specialNarrow) is not a function` 
- [ ]  Flow errors the Avatar bugs which is maybe due to usage of defaultProps (seems to be a library bug but we need to have a workaround) 

If you have leads how to solve these, do post a PR or send them here!

**Comment by borisyankov** [comment]
The Flow errors appear and disappear depending on the commit. Really looks weird ;)

**Comment by borisyankov** [comment]
Closing as fixed.
