### ISSUE TITLE
Continuous fetching of messages for some narrows

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-mobile#1072]
When I tried to reload and switch to narrows with limited messages, I sometimes get the following warning.

```
Error: API usage exceeded rate limit
```

short video: https://drive.google.com/open?id=0Bx5B8iZLs6VBMkpkSnhZaHNnUzg

**Comment by borisyankov** [comment]
I have had that with quite an older version. Test or rebase branch to the very latest `master` and see if it happens.
Also just test the latest master to see if any issues.

**Comment by Sam1301** [comment]
yeah, the latest commit fixed this error me 👍 , I could repro the error on previous commit 2baf53a761ca939eb985eb6f683b9c74eefb7fcb
