### ISSUE TITLE
Unsubscribing from a stream with unread messages doesn't remove it from unread tab

### ISSUE THREAD

**Issue by hdorothea** [zulip/zulip-mobile#1083]
If you Unsubscribe from a Stream with unread Messages the Stream still shows up in Unread Tab but as a gray Hash Mark
<img width="376" alt="screen shot 2017-08-23 at 5 56 21 pm" src="https://user-images.githubusercontent.com/4699570/29640335-7b205f76-882c-11e7-906f-fc5231e15843.png">
<img width="374" alt="screen shot 2017-08-23 at 5 57 44 pm" src="https://user-images.githubusercontent.com/4699570/29640382-bcaf52d0-882c-11e7-88cd-ed632330748d.png">

**Comment by hdorothea** [comment]
**@zulipbot** claim

**Comment by borisyankov** [comment]
Closing as fixed. (long time ago)
