### ISSUE TITLE
Markdown rendering <span> should be display: inline equivalent.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#110]
As you can see in the code block below, the <span> tags inside of a code block are perhaps being rendered as <text> which needs to have a particular flex attribute list. Something like:

```javascript
span: {
        flexWrap: 'wrap', 
        alignItems: 'flex-start',
        flexDirection:'row',
}
```

<img width="487" alt="screen shot 2016-11-18 at 12 32 47 pm" src="https://cloud.githubusercontent.com/assets/10321399/20445983/42c0c1d2-ad8c-11e6-992c-9435d4bd427e.png">

**Comment by borisyankov** [comment]
Fixed.
