### ISSUE TITLE
[Android] Buttons are too much rounded on lower API devices 

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#1107]
<img width="402" alt="screen shot 2017-08-30 at 7 46 41 pm" src="https://user-images.githubusercontent.com/18511177/29879118-d1f78c6c-8dc1-11e7-9d19-cef1570029cc.png">

**Comment by borisyankov** [comment]
@vishwesh3 confirm if fixed with latest `master`.

**Comment by vishwesh3** [comment]
yup! it is fixed.
