### ISSUE TITLE
Better Message headers and chat header

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#112]
- [x] Stream text color becomes white or black depending on background
- [x] Stream - subheaders show only topic, title is stream, has color, has 'private' or not
- [x] Stream+Topic - no message headers, title is stream + topic
- [x] Aggregate (Home/Search etc) - show stream + topic in message headers or private message header, title lists search criteria
- [x] Private chat or group chat - do not show message headers, title is name(s) (and maybe avatars)

**Comment by timabbott** [comment]
For group private message threads, the title area should just show the users' avatars (that's probably the only thing that would fit with 3+ other people).  If you touch the avatars in the title area, it should pop down a list of the people/avatar pairs so you can easily get precise clarity as to who is on the thread.
