### ISSUE TITLE
Remove Immutable completely

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#113]

**Comment by neerajwahi** [comment]
I think Immutable is quite useful for at least the list of messages. Could you elaborate on how we can get rid of it entirely?

**Comment by borisyankov** [comment]
For the list of messages, I benchmarked and tested how many we do render in normal use, and it is from 20ish to lower hundreds. When new data arrives we will duplicate the array, which of course is just duplicating the refs only, so is performant.

I don't think we will have any perf issues. But will simplify usage a lot.
