### ISSUE TITLE
Set a different icon compared to the "released" version

### ISSUE THREAD

**Issue by strugee** [zulip/zulip-mobile#1133]
I have both the original zulip-android and this app installed via the Google Play Store. While this is convenient for various reasons it makes it hard to know which one I'm opening. It'd be nice if this one's icon had a beta badge on it or something, at least until release, to make it easier to differentiate.

**Comment by Chiamaka** [comment]
can I work on this? @borisyankov

**Comment by borisyankov** [comment]
I am not sure it is a task that can be worked on, as in the solution might not be via source code :)
Maybe the only way to do it is to do it manually... but you can research that, I might be wrong.

**Comment by pulkonet** [comment]
Since the zulip-android app is deprecated, this is no longer needed. Can be closed.

**Comment by borisyankov** [comment]
@strugee are you still using both apps?

**Comment by strugee** [comment]
@borisyankov not really. There are a few quirks with the new one (which I should probably report bugs for...) but it's so much better than the old that I basically never use that one.
