### ISSUE TITLE
Disappearing messages on iOS

### ISSUE THREAD

**Issue by geekdave** [zulip/zulip-mobile#1142]
Hey all - On the latest testflight `1.0.21 (1)` I'm experiencing the following:
1. Create a new topic/message on iOS app
2. Hit send
3. See the message in the channel for 1/2 second
4. Message disappears from iOS app
5. Switch to desktop app.
6. The message I sent in step 2 is visible on desktop

**Comment by pulkonet** [comment]
I think this issue is fixed with the webview. Can be closed.

**Comment by borisyankov** [comment]
Yeah, fixed.
