### ISSUE TITLE
Share a picture directly from stream view

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#1144]
Not really an issue as much is a suggestion to make the UI better.

Right now when you press and hold on a picture in a message the area the message is in has this lighting up animation, but nothing really happens. In rocket.chat it would let you share pictures (and I don't mean a link to the picture which is something the current share feature gives you - it took the downloaded copy of the picture and let you share it as a picture, but I suppose a shareable link wouldn't be too bad either) to other apps. This is especially useful i.e. when sharing concepts from the app to people on whatsapp or similar apps.

**Comment by borisyankov** [comment]
Good suggestion, thanks.
We will definitely look to implement it.

**Comment by vishwesh3** [comment]
@zulipbot claim
