### ISSUE TITLE
[iOS] Status bar not showing up when in landscape

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1185]
Padding is there instead of the status bar
![simulator screen shot 18-sep-2017 4 10 48 pm](https://user-images.githubusercontent.com/12700799/30538563-2d8c8efa-9c8c-11e7-8a74-535a470374f3.png)

Works fine on android!

**Comment by kunall17** [comment]
Btw tried this on simulator, not sure if this is the problem of simulator!

**Comment by borisyankov** [comment]
I think the simulator is flaky about this. But I tested several other apps, and we will make this the official behavior (it can be configured).

**Comment by vishwesh3** [comment]
is this fixed now? On simulator I am getting 
<img width="673" alt="screen shot 2017-10-13 at 10 22 58 am" src="https://user-images.githubusercontent.com/18511177/31530826-b03cd120-b000-11e7-8c0e-4f2fa52d1ad1.png">

**Comment by borisyankov** [comment]
I think it is a setting we can set. Actually, we likely want it hidden.
