### ISSUE TITLE
Network requests have no timeout

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#12]
There's currently no timeout for network requests. For instance, if a user attempts to login to a non-responding server, the UI will lock up.

Fixing the issue will likely involve wrapping the `fetch` promise with a timeout in `ApiClient.js`

**Comment by timabbott** [comment]
We should be sure to do this in a way that has a reasonable retry strategy (probably wants to have some sort of slow exponential backoff thing, perhaps with a way for the user to override and check now...).

**Comment by borisyankov** [comment]
Timeout is implemented. 
The 'retry' part would be a more major feature which I'll separate in another issue.
Any unsent message and other similar actions that do not complete successfully, should be persisted and resent next time there is a connection.
