### ISSUE TITLE
Clicking on any compose button results in exceptions

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#120]
Clicking on the 'picture' icon results in:
```
null is not an object (evaluating
'_this.state.noMore')
```

Clicking on other buttons result in future exceptions of this variety when continuing to use the app:
```
null is not an object (evaluating
'internalInstance.getHostNode')
```

**Comment by borisyankov** [comment]
Fixed these exceptions.
The options are not yet ready to be used, so also hid them.
