### ISSUE TITLE
Consider using react-native-orientation

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1202]
Consider using https://github.com/yamill/react-native-orientation for orientation detection, as our current implementation gets confused by keyboard popping up.

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by vishwesh3** [comment]
Implemented by https://github.com/zulip/zulip-mobile/pull/1300
Good time to close this now :)

**Comment by borisyankov** [comment]
Closing as implemented.
