### ISSUE TITLE
Pressing back button on a narrowed view exits the app

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1219]
We had a recent implementation on this, but is this a know issue, or developed like this?

**Comment by mrijke** [comment]
https://github.com/zulip/zulip-mobile/pull/1367 got merged not too long ago, and should be in the current version. However, I'm still seeing this behavior. Is this intended?

**Comment by jmandel** [comment]
Just want to comment that this is still an issue and it is my number one problem trying to use zulip on Android.

**Comment by jmandel** [comment]
Thought I was already in the beta, but evidently not -- just joined! Thanks.

**Comment by jmandel** [comment]
Beta program membership went through. @borisyankov let me know when to update. Thanks!

**Comment by borisyankov** [comment]
@jmandel update the Beta to the latest version and give it a try.
The drawer becomes the 'root' view and all narrows open a new screen.
Going from one narrow to the next preserves the history like a browser.
You can go back by pressing the Back button.

**Comment by jmandel** [comment]
Whoa -- cool! Thanks for the rapid turnaround. This is a big help already -- though I miss being able to slide the drawer out over the main app area; because now if I go back, I can't go "forward" again.

**Comment by borisyankov** [comment]
We've been cooking this for a while. I just released it as a Beta :)
I am not sure if the next Betas and Public releases will contain this, but I am intent on including it soon.
Depends on feedback. Use it for a day or two and please share if you like it more than before.
We are definitely going to add several features that will make the navigation even more natural.

**Comment by jainkuniya** [comment]
We have reworked on this, can be closed now.
