### ISSUE TITLE
Debugging: RawText "" must be wrapped in an explicit <Text> component issues

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1223]
Currently its hard to track these issues down, and we have 6 issues from 2 users in the sentry (https://sentry.io/zulip/zulip-mobile/issues/355390348/) currently and they have server name as localhost
I tried to reproduce this on the latest master of the server (https://github.com/zulip/zulip/commit/f0f0176517f7db447c77d80db92aa813553ce30f) but no error's I found, so using sentry we can send the markdown of these, but then comes privacy issues, can we avoid them somehow maybe by not using the zulipchat servers? @timabbott 

**Edit: This error occurs when the app fails to render particular case of markdown!**

**Comment by timabbott** [comment]
We try to avoid having any message content going into logs/error reports/etc.  One thing we do in the backend that could be helpful here is removing the content from the message but still reporting the structure.  E.g. for our markdown processor, we'll record in the logs the error-inducing code with all alphanumeric characters replaced with `x`s as the balance between debugging and privacy.  It might be that for this, we could at least report which HTML elements were involved (but not the message content involved) and it'd be clear what's going on.

**Comment by kunall17** [comment]
I'll send a PR to log the markdown with replacing the alphanumeric as * as you said 👍

**Comment by jainkuniya** [comment]
Can be closed now, as with new `render-html` technique, it is newer reproducible.
