### ISSUE TITLE
explain or remove device info / ID permission

### ISSUE THREAD

**Issue by mfc** [zulip/zulip-mobile#1229]
curious why Zulip needs the device ID permission since it doesn't use phone numbers for user ID (unlike Signal for example). probably worth explaining the permissions requested on the Google Play page.

**Comment by borisyankov** [comment]
Good question. We are not using it, so we should not request it.

I've found the likely related cause discussed here:
https://github.com/facebook/react-native/issues/5886

@vishwesh3 do you want to work on this issue?

**Comment by mfc** [comment]
good sleuthing! i would just add that the mass storage permission is also asked by Zulip, and seems also because of this react bug. So if it is not needed by Zulip i would also remove that.

**Comment by vishwesh3** [comment]
Should we close this now. In latest beta 2.1.33
![screenshot_20171007-081754](https://user-images.githubusercontent.com/18511177/31304962-32dad0aa-ab4c-11e7-807d-19bd1479af53.jpg)




we will be requiring storage permission as we have feature to download photos.

**Comment by borisyankov** [comment]
Great!
Yeah, we will add photo/file upload soon.
