### ISSUE TITLE
Issue with line spacing in message rendering

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#123]
Looks like newlines are being suppressed. I think this is a recent issue

**Comment by borisyankov** [comment]
@neerajwahi @timabbott I spent few hours on this. Not gonna be fixed easily.
This, I am sure, have never worked. The html parsing code is too simple to handle these case.
It renders a P tag, but needs to parse deeply (the new line is a BR inside a P tag)
The same issue exists for PRE tag for code emebeds. 
The solution for these is completely different though.
(or the same, if we implement WebView)

**Comment by borisyankov** [comment]
Closing that, as it can not be fixed for P1, and without major rework of how message rendering works.
Tracking all issues here:
https://github.com/zulip/zulip-mobile/issues/128
