### ISSUE TITLE
Navigation stack unstability

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#124]
Especially noticeable with the login flow

**Comment by borisyankov** [comment]
Fixed a couple of more serious issues related to navigation, like scroll from left to right fighting between drawer and previous states etc.

Behavior that I think you mean is unfortunately currently normal for NavigationExperimental, though they might be fixing it.

Also React Router will soon have React Native support and might be an option too.

I'll add another task to revisit this in few weeks.
