### ISSUE TITLE
Unable to log in on iPhone. JSON Parse error

### ISSUE THREAD

**Issue by toshism** [zulip/zulip-mobile#1252]
I am unable to log in to our private hosted zulip server after the most recent app update. After entering our server URL and hitting enter I get the message. `JSON Parse error: Unrecognized token '<'`. 

iOS 11.0.1
zulip app 2.0.32

If there is any other info I can provide please let me know.

**Comment by timabbott** [comment]
@toshism what version of Zulip are you running?  And can you check /var/log/zulip/errors.log?  

The mobile apps require 1.6 at this point.

**Comment by toshism** [comment]
Ah, I wasn't aware of the version requirement. I don't know the version (I'm just a user) but I will see if I can find out.

**Comment by toshism** [comment]
Zulip version is 1.5.1 so it would appear that is the problem. Thanks and sorry for the noise.

**Comment by borisyankov** [comment]
Thanks for the report. Definitely not noise ;)
I feel like we should be giving you a better error message.

**Comment by toshism** [comment]
Yeah, an error message about version requirements would be helpful. I also don't see the minimum server version specified anywhere for the iPhone app. This has caught our entire team at work off guard.
