### ISSUE TITLE
Message Render Issues

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#128]
A list of message render issues.
Any easy to fix issues were already fixed. These require a much more advanced html parsing and rendering, or WebView which I recommend.

- [x] Italic text is rendered as normal text
- [x] Blockquote do not have grey bar shown (left-border)
- [x] Code block is rendered on a single line
- [x] @ Mentions are not styled correctly
- [x] New lines within the same message are rendered on the same line
- [x] List items, when wrapped, 2nd line is not offset
- [x] Strikethrough is rendered as normal text (no line through it)
- [x] code blocks can be styled better
- [x] Tables are not rendered at all!
- [ ] BR tags inside P tags should render a new line

**Comment by timabbott** [comment]
Let's split this into issues for the individual items; some things (like tables) are super not important; whereas other are somewhat important.

**Comment by timabbott** [comment]
(We can use a label to keep these together if needed)

**Comment by borisyankov** [comment]
@timabbott consider if any of these are critical, if not lets move to M6.

**Comment by borisyankov** [comment]
@timabbott Actually moving it to M6, but if you find any of these is too important to delay, we can create a new issue for it specifically.

**Comment by timabbott** [comment]
Yeah that sounds good.

**Comment by timabbott** [comment]
Should we just close this in favor of #280 for the remaining item?

**Comment by borisyankov** [comment]
Yeah sure.
