### ISSUE TITLE
[Android]Text input box doesn't scroll properly with five lines of input

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1283]
Just the top 4 are shown. 
https://chat.zulip.org/user_uploads/2/8f/0Ce9DMtPEoAUi8g5cz0o_lD2/Screenshot_20171009-202724.png

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Might be related to fixes or bugs that React Native do in Yoga - the layout engine. (just to be clear, we intentionally want this limited to that hight, but correctly scrollable)

**Comment by vishwesh3** [comment]
I don't think there are bugs in RN or something to do with Yoga (or might be :)).
Because I tried simple `TextInput` and it is working as per our requirement.
https://snack.expo.io/HkZlOXi3-

**Comment by vishwesh3** [comment]
https://github.com/facebook/react-native/issues/12799

**Comment by jainkuniya** [comment]
Closing as fixed by https://github.com/facebook/react-native/commit/0bef872
