### ISSUE TITLE
Cannot scroll in the message view

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1294]
It happens often, and cannot scroll in either direction

![ezgif-4-7e9bc798ee](https://user-images.githubusercontent.com/12700799/31479966-9c7e1c16-af38-11e7-8bdf-3abdac52e24f.gif)

To reproduce: After opening the app, sometimes it happens

**Comment by kunall17** [comment]
Fixed, can be closed now!

**Comment by borisyankov** [comment]
@kunall17 really? I am not sure it is yet?

**Comment by kunall17** [comment]
Haven't really noticed this one and I use android!

**Comment by borisyankov** [comment]
To be fixed via WebMessageList.

**Comment by borisyankov** [comment]
Closing as no longer relevant.
