### ISSUE TITLE
gsoc.zulipchat.com doesn't offer GitHub auth on Android

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1297]
I thought we added this feature recently; is it just disabled on Android?

**Comment by vishwesh3** [comment]
On current master, GitHub auth is available.
<img width="395" alt="screen shot 2017-10-13 at 8 20 41 am" src="https://user-images.githubusercontent.com/18511177/31528301-0eecb854-aff0-11e7-9c43-7437b2f35cec.png">

Our last public release was `2.0.32` and we added GitHub auth in `2.0.33` (https://github.com/zulip/zulip-mobile/releases/tag/2.1.33) . So no public release after adding it. Github auth is working fine in beta `v2.0.35`

**Comment by timabbott** [comment]
OK, makes sense.  We should get a release out.
