### ISSUE TITLE
Weird performance issue with the hamburger menu

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1298]
One of things I often experience as a performance issue in the app is that right after opening the app, I often want to open the hamburger menu/drawer widget.  Hitting the hamburger menu usually seems to do nothing though, for several seconds, even on my home 200mbps network.

However, oddly, sliding out the the drawer works fine for several seconds before the hamburger menu works (I even tried opening the drawer, closing it again, and hitting the hamburger menu, and it still delays).

This is from testing against chat.zulip.org.

**Comment by borisyankov** [comment]
Closing as resolved. 
We should keep improving the performance and keep an eye on any regressions.
