### ISSUE TITLE
Add support for adding a first emoji reaction

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1304]
I got a request for this at the Google Summer of code mentor summit.  I assume it'd just be a new UI widget in the long-press menu on a message.

**Comment by borisyankov** [comment]
I assumed we will do a full emoji-picker thing, though on mobile it is much more heavy-handed.
An emoji-picker will definitely take full screen and doing a search via the keyboard will be an unpopular option.

I just tested FB Messenger and Skype - both use a small popup consisting of what we have as the 'most popular reactions'.

**Comment by jayvdb** [comment]
Is this a dup of https://github.com/zulip/zulip-mobile/issues/303 ?

**Comment by jmandel** [comment]
It sure looks like one. In any case, it'd be a helpful feature on mobile!

**Comment by gnprice** [comment]
Closing in favor of #303.
