### ISSUE TITLE
Add the ability to create a new stream

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-mobile#1313]
The ability to add a new stream from the app would be great rather than having to use the web client. 

I currently use slack and one of best things about that is the ability to do most things like creating channels in the app itself. Useful for those predominantly on a mobile device.

**Comment by borisyankov** [comment]
Thanks for the suggestion. We were thinking about this, but now that you requested it, I'll bump it up in our to-do list. 👍

**Comment by adambirds** [comment]
Excellent, thanks @borisyankov

**Comment by borisyankov** [comment]
Closing as implemented and shipped.
