### ISSUE TITLE
Add quick organization switcher

### ISSUE THREAD

**Issue by waozixyz** [zulip/zulip-mobile#1321]
In the desktop app you have the convenient sidebar to switch between organization.
maybe having a menu option?

another idea would be to use the same idea as in rocket.chat, they use a two finger swipe up to change the server when the app is starting

**Comment by kunall17** [comment]
We don't have the gesture detection atm, but the switch works from the drawer -> settings! 

Thanks for the suggestion 👍

**Comment by timabbott** [comment]
@kunall17 while there is a switcher, I think ideally we'd want it to be faster than it is and allow you to receive push notifications for multiple Zulip realms at the same time.

**Comment by borisyankov** [comment]
Yeah, we will want to store the server icon's urls and make the picker more easily accessible.
Assigning this to me, as I have a decent idea how to do that, but we'll focus on the big issues we discussed with Tim, until all of them are resolved before doing this.

**Comment by mkaito** [comment]
To add to the conversation here, I would like to point out that there's no way to know what the currently active realm is except going to the switcher. Would be useful to have the realm icon visible somewhere.

**Comment by borisyankov** [comment]
@mkaito as with many other things a mobile app has to have much more focused screens with way less extra details. 

While we will not make the account icon always visible, we are going to make the account switcher faster to access which will be quite an improvement.

**Comment by BartMassey** [comment]
Without the ability to conveniently monitor multiple realms, the mobile Zulip app is basically useless to me. What can I do to help get the development process restarted for this feature? I am not really a JS programmer, so PRs are probably out, but I am happy to help how I can.
