### ISSUE TITLE
Scrolling down in the home view never reaches the latest messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1335]
I got a report from a user about this, and was able to confirm it: If you open the home view and happen to get placed 100+ messages above the latest (which happens to me all the time and is probably its own bug needing attention!  We should be placing you with the first unread message at the middle of the screen, or at the bottom), and then scroll down, at first it loads new messages.  

But after loading new messages when you get to the bottom like 3-4 times, you get to the bottom, and it doesn't load anymore, even though comparing with web, one will see there's actually another 50 messages below where it leaves me.

This is verified with the latest beta.

**Comment by borisyankov** [comment]
There are two parts to this issue.
The positioning and the 'not loading'.
I am investigating the second part, as I think I encountered it at least once.

The first part, about positioning it too early - we need to improve that somehow.
We are just doing an 'anchor' get, so the result is backend-dependent.
It is either a bug on the backend or correct behavior that we might want to rework?
Also, are we still using a different method of positioning on the web frontend?

**Comment by timabbott** [comment]
@borisyankov the way we do positioning on the web frontend is that we get back the messages via the `GET` with `use_first_unread_anchro`, and then in JS we scan through the result to find the first unread message (through looking at the `flags` on the result), and set the scroll position to have that be about 1/3 of the way down the screen (or scroll to end if there no unread messages).

**Comment by borisyankov** [comment]
Hmmm, we use `use_first_unread_anchor` in the same fashion.
That is weird that we might load old messages this way.

**Comment by timabbott** [comment]
So, to be clear, in the home view, it can load messages from a few days old, but I assume that's a different code path in the app.  (Are you using `pointer` for this?).  So might be a separate but related bug.

For narrows, my experience is that the app loads only a few dozen messages back, which makes me think the issue is solely about setting the scroll position after correctly fetching the most recent N messages (e.g. 
I see this often when there are 0 unread messages, so everything fetched should be rendered above).

**Comment by borisyankov** [comment]
Closing as fixed.
