### ISSUE TITLE
Sharing links directly to the app

### ISSUE THREAD

**Issue by cdikibo** [zulip/zulip-mobile#1351]
Our competitors show up when it's time to share a link. We should also be able to share links from outside sources without having to copy and paste.

**Comment by borisyankov** [comment]
I fully agree. @vishwesh3 is working on this in #674
We should prioritize it more I think. @timabbott what do you think about this?

**Comment by timabbott** [comment]
Yeah, agreed, this deserves priority attention.

**Comment by gnprice** [comment]
Closing in favor of #117.
