### ISSUE TITLE
New message doesn't add to the list.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1354]
One case is:-
If the messages in narrow are few (one or two), i.e full screen is not occupied, then new messages is not appended at the bottom. (tested in topic narrow)

Also in Android if message list doesn't occupy full list then list's scrolling is not enables, thus only way to get new message is via re narrowing.

on iOS scrolling is enabled even if message list have one message, so one can scroll to get new message.

Will try to debug. @zulipbot claim

**Comment by borisyankov** [comment]
I can confirm this issue. It is even more prominent when tested on a tablet, as the screen is larger.
Have you been able to fix it? If not, I'll tackle this before releasing the next Beta?

**Comment by vishwesh3** [comment]
Found one more case. Fixed by #1363. It might have introduced scrolling issues. Added more descriptive comment https://github.com/zulip/zulip-mobile/pull/1363#issuecomment-339217800.
Ya! we need to fix in next beta 👍

**Comment by jainkuniya** [comment]
Closing as no longer relevant.
