### ISSUE TITLE
[Android] Sometimes top loading indicator is not visible.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1362]
<img width="398" alt="screen shot 2017-10-25 at 7 28 48 am" src="https://user-images.githubusercontent.com/18511177/31976646-3f19c00c-b956-11e7-9bbe-5e337dee2407.png">

**Comment by borisyankov** [comment]
Sometimes it happens for the bottom one too.

**Comment by jainkuniya** [comment]
Closing as with new MessageList, no longer relevant.
