### ISSUE TITLE
Some icons are not visible (? is shown instead)

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#1381]
icons such as

- [ ] Google icon in AuthScreen

- [ ] Cross Icon in AvatarList in CreateGroupScreen

- [ ] Cross Icon in Switch Account Screen.

This might be a bite-size (haven't followed last few commits, so not sure), 
But will be a great learning for new comers :)

**Comment by borisyankov** [comment]
Hmm, have you pulled the latest `master`?
I think I've fixed at least two of these yesterday.

**Comment by cdikibo** [comment]
@borisyankov I just pulled the latest master branch I'll see if I get question marks.

**Comment by cdikibo** [comment]
Update: I didn't get those problems you mentioned @vishwesh3  
![simulator screen shot - iphone 5s - 2017-11-01 at 19 25 36](https://user-images.githubusercontent.com/8525347/32304424-1c2984b4-bf3d-11e7-9a9b-1456a3065adb.png)

**Comment by vishwesh3** [comment]
yes! it got fixed :+1:
