### ISSUE TITLE
Flexbox glitch -subscribed 

### ISSUE THREAD

**Issue by cdikibo** [zulip/zulip-mobile#1396]
This is the third time this happened on the iOS app for me while using the simulator. I don't know if this is mirrored for everyone else. The first time clicking on subscribed from starting up the app it appears like below   

![simulator screen shot - iphone 5s - 2017-11-04 at 12 40 17](https://user-images.githubusercontent.com/8525347/32407901-95ad7e54-c15d-11e7-8259-6869807184b6.png)

**Comment by borisyankov** [comment]
Yes, I do have the same issue.
It is a bug in `react-navigation` or in the `react-native-tab-view` component that they use.
