### ISSUE TITLE
Messages containing @all or @everyone are not sent

### ISSUE THREAD

**Issue by thelamb** [zulip/zulip-mobile#1404]
**Reproduce**
Try to send a message containing `@all ` or `@everyone`

**Expected**
- Confirmation is asked like in the web version (?)
- Message is sent and everybody is @-mentioned

**Actual**
- The message disappears from the input field, and is not sent to the stream
- No error is displayed

**Additional notes**
- 'all' and 'everyone' are not among the suggested autocomplete entries after typing '@' 
- Sending any other unknown @-mention works (e.g. @noonebythisname) 
- Confirmed on both Android and IOS

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by vishwesh3** [comment]
Can we close this now?
Fixed by https://github.com/zulip/zulip-mobile/commit/4ea72e8d12314bf7c70b5c7ec4fa862d2ed907ec

**Comment by borisyankov** [comment]
Closing as fixed.
