### ISSUE TITLE
Improve account switch experience

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1411]
- Sometimes some data is not cleared and reflected in other account.

- Show error instead of infinite loading when switched account is not reachable.

https://chat.zulip.org/#narrow/stream/mobile/subject/currently.20published.20Android.20app/near/316004

Mostly related to debugging.

**Comment by gnprice** [comment]
I believe the two different issues here have been fixed.

If someone sees symptoms resembling either of them, please file a new issue with details.
