### ISSUE TITLE
Image upload. 

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1445]
- [x] Topic of uploaded image is always '(No topic)' irrespective of text present in topic field.

- [x] image quality https://chat.zulip.org/#narrow/stream/mobile/topic/Sending.20a.20picture.3A.20image.20quality

- [x] Not able to view image in light box just after uploading
https://chat.zulip.org/#narrow/stream/mobile/topic/Viewing.20a.20picture

**Comment by jainkuniya** [comment]
@zulipbot label "list"

**Comment by borisyankov** [comment]
Closing as improved/fixed.
