### ISSUE TITLE
Sometimes the app doesn't pick up messages

### ISSUE THREAD

**Issue by Lyla-Fischer** [zulip/zulip-mobile#1465]
Intermittently, on the Android app from the Play Store, I will check the messages in a particular stream, but I will only actually be able to see 0-8 of 8 reported unread messages (for example). It varies widely how many I am able to see, and there is nothing that I seem to be able to do in order to make it refresh and try to fetch the messages again.

**Comment by chrisbobbe** [comment]
Hmm, there's a chance that this issue is being tracked in https://github.com/zulip/zulip-mobile/issues/3654.

Is this still happening on the latest version of the Zulip mobile app? If so, please let me know.

**Comment by chrisbobbe** [comment]
I'll close this, considering how old it is and how much work has been done since, but please do let me know (on #3654, or an appropriate existing issue, or a new issue) if this is still happening, as of course I don't want to close a bug report in error.
