### ISSUE TITLE
Merge Unreads/Subscribed/All streams

### ISSUE THREAD

**Issue by yukiisbored** [zulip/zulip-mobile#1470]
It's a nuisance to have them separated, having just one panel that lists all of the streams in the order of streams with unreads, streams that you're subscribing, streams that you're not subscribing would be way better and more clear to the user.

**Comment by sniok** [comment]
Definitely agree. Having one list for streams makes sense. Unreads should be just an indicator.

**Comment by kunall17** [comment]
The advantage of splitting them is the unread tab shows all the **unmuted** streams and **unmuted** topics with unreads
Subscribed shows all the streams (muted or unmuted) with unreads of streams which are subscribed
And All streams shows all the streams even if not subscribed, with the option of creating new stream.

If we merge all these tabs together there will be a lot of data to display in one tab, thus having it different feels convenient.

**Comment by yukiisbored** [comment]
@kunall17 Honestly, it doesn't make any sense. It just adds more confusion. For example, why can't I open the stream on All streams?
I doubt I need a dedicated section just for the streams that I haven't subscribed with big switches.
It's more of a UX problem since most people used to applications like Mattermost and Slack where everything is merged and categorized neatly instead of separating them into it's own section.

**Comment by yukiisbored** [comment]
I don't mind if there's an option to switch between the two styles. I personally find it annoying and confusing to use.

**Comment by borisyankov** [comment]
@yukiisbored I think it really depends on how many of each you have.
For example, having 100 streams will be a bit unwieldy to list them all.
Merging read and unread makes a bit more sense, but leaving 'all' separate also does.
Rest assured, we agree that switching is suboptimal, but we are not yet sure what is the best solution (we actually have another cool thing that will soon be merged that will be an alternative)

**Comment by pulkonet** [comment]
This is fixed and can be closed. @borisyankov

**Comment by borisyankov** [comment]
It was improved upon, not implemented exactly, but for now we are ok with what we have.
