### ISSUE TITLE
Build artifacts on CI

### ISSUE THREAD

**Issue by yukiisbored** [zulip/zulip-mobile#1471]
By continuously building artifacts, developers and enthusiasts can test and use the latest "bleeding edge master" version right away. Which will make it easier to use each revisions of the application and give feedback.

An example of this would be something like Chromium Canary.

**Comment by borisyankov** [comment]
I agree nightly builds will be cool, but I was assuming it will be non-trivial to implement.
Do you have any idea what service supports mobile continuous delivery?

**Comment by yukiisbored** [comment]
@borisyankov The roughest way we can achieve this is by building it on Travis-CI and deploy the artifact to GitHub releases.
https://docs.travis-ci.com/user/deployment/releases/

**Comment by borisyankov** [comment]
Closing as 'stale'.
