### ISSUE TITLE
Loading indicator always displayed at top of screen

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#149]
The loading indicator in the scroll view is always displayed at the top of the screen even if new messages are loaded from the bottom. This is unintuitive and provides a bad UX.

(Also, scrolling stops when the load indicator is encountered. I think it'd be nicer to allow scrolling to continue as new messages get pulled in.)

**Comment by borisyankov** [comment]
Agree partially. CCing @timabbott 

I was thinking about that... 
I will move the progress bar indicator inside the list itself, so it is visible only if the list is at top.
Actually I will investigate in detail how it is handled in other chat apps.

One thing that got very improved over the last few years in UI regard, but I know many of us devs or tech guys that are not UX guys didn't caught up to is that showing a progress indicator is distracting and often gives the impression of slowness. For example Facebook and now a lot of other apps have the 'not yet loaded, but looking like content' type of thing that is the grey blocks imitating not loaded text (hope you know what I am talking about)

**Comment by timabbott** [comment]
Yeah, I like the idea of moving it into the list itself and displaying it at top or bottom.  What do you think @neerajwahi?  Not sure grey blocks totally makes sense, since we don't know the size; but I think having the single top-of-feed or bottom-of-feed indicator display as a loading indicator if we're trying to fetch more makes a lot of sense (and display as something more definite if we're at the end).

**Comment by neerajwahi** [comment]
I like the grey block approach for a couple of reasons:
1. I agree that users are conditioned to find loading indicators slow nowadays
2. With placeholders we can let the user continue to scroll uninterrupted (with the blocks filling in with content underneath). I think this will make the app feel a lot snappier (because the user interaction doesn't get interrupted)

@timabbott Definitely agree that not knowing the size of the blocks makes this a bit tricky. Hard to know without a prototype how it'll feel. Perhaps instead of blocks it could be a gradient, or just a background with a loading indicator that allows the user to continue scrolling while it's displayed.

@borisyankov Btw the news feed in the Facebook app actually seems to use loading indicators when scrolling.

**Comment by borisyankov** [comment]
The Facebook feed uses a 'not yet loaded' news type of thing, exactly what I proposed. 
It has an animated gradient though. Also it loads super fast so is on screen for a very short time only.

**Comment by neerajwahi** [comment]
@borisyankov why did you close this? It's still an open issue, no?

**Comment by borisyankov** [comment]
@neerajwahi I just implemented it. Not yet a PR though.

**Comment by neerajwahi** [comment]
Cool. Let's leave issues open until merged into master and you can reference it in your PR. Easier to keep track that way :)

**Comment by neerajwahi** [comment]
@borisyankov Could you send along the branch as a preview (even if it's not ready)?

**Comment by borisyankov** [comment]
It is in the `cache` PR.
