### ISSUE TITLE
App crashes when trying to sign in with Github/Google

### ISSUE THREAD

**Issue by Ivche1337** [zulip/zulip-mobile#1494]
## Reproduce the bug

- Enter server URL
![image](https://user-images.githubusercontent.com/19243015/33575793-163f9cbc-d93e-11e7-9665-56202061343f.png)
- Try to sign in with Google/Github
![image](https://user-images.githubusercontent.com/19243015/33575836-354ee518-d93e-11e7-9b84-cab549c25041.png)
- Crash
![image](https://user-images.githubusercontent.com/19243015/33575848-3e3c54a8-d93e-11e7-9731-912f3b578d34.png)
- System Info
![image](https://user-images.githubusercontent.com/19243015/33575871-50ce7f6a-d93e-11e7-94c7-1eb13fd5bf3e.png)

**Comment by borisyankov** [comment]
Thanks for the report.
This likely has something to do with the Android version, we rarely test on 4.x (though we support it)
