### ISSUE TITLE
Dark Mode - Colour recommendation

### ISSUE THREAD

**Issue by anirudhjain75** [zulip/zulip-mobile#1511]
![screenshot_20171208-002827](https://user-images.githubusercontent.com/14249589/33733656-5bc09c54-dbb0-11e7-8440-9589bc141e68.png)
It would be better if the colour used would be White instead of Grey, So it would be much more visible.

Nexus 6
Android 7.1.1
Zulip Beta -> From App Store

**Comment by jainkuniya** [comment]
This is also fixed now. Can be closed now.
