### ISSUE TITLE
Startup Misbehaviour

### ISSUE THREAD

**Issue by anirudhjain75** [zulip/zulip-mobile#1512]
The App loading screen is Misbehaving on Startup
![giphy](https://user-images.githubusercontent.com/14249589/33734514-9d9cb304-dbb2-11e7-97e0-341e2ef5df6d.gif)

Device Information:
NEXUS 6
Android 7.1.1

**Comment by borisyankov** [comment]
@jainkuniya would you have a look at this? I think the latest React Native version changed something with border-radius styling.

**Comment by jainkuniya** [comment]
cool! will look into it.

**Comment by jainkuniya** [comment]
@zulipbot claim
