### ISSUE TITLE
Indicator for 'start of messages'

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#154]
Most of chat competitors have a clear indicator that there are no older messages.
For users, in Slack there is a text like 'This is the start of your chat history', in Facebook Messenger there is a bigger user avatar and some info about the user.

**Comment by timabbott** [comment]
I think for v1 we can just show a centered black Zulip logo at the top (like we currently do on chat.zulip.org), which we can use both as the loading indicator space as well as the thing that gets swapped into place if we find we're at the top of the feed.  The important constraint is that the loading indicator have the same height as the top-of-feed marker.  We'll likely revise the design at some later point, but this seems like a reasonable provision thing to do.
