### ISSUE TITLE
Spinners don't spin, just freeze

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#1546]
I've played with 5.0.46 for about an hour and a half today, and I think I've never seen one of our spinners spin. Instead I've seen them appear, then hang out in a frozen state. I remember spinners working nicely in the past, so this is a regression.

Here's a typical example, in the midst of scrolling up through messages:

![](https://chat.zulip.org/user_uploads/2/99/JU-06ShK_5eO-JgoLOWWkwUq/IMG_1670.PNG)

If I do a lot of scrolling, so that I see the spinner a lot of separate times, it's often at different frames of its animation at different times. But whatever frame it first appears at, it stays there until that spinner disappears.

The spinner on the startup screen behaves the same way, though I was a bit too slow when I tried to grab a screenshot of it.

**Comment by borisyankov** [comment]
Message rendering blocks the spinners. (sad, these spinners are cool)
Keeping it open for now, will be mostly irrelevant when we merge the WebView message list.

**Comment by jainkuniya** [comment]
WebView message list got merged and we have also reworked on spinner. Can be closed now.
