### ISSUE TITLE
Message view suddenly jumps forward

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#1548]
I was catching up (in 5.0.46 on iOS), and suddenly the message view was far forward of where I'd been.

If I remember right (this was about an hour ago), what actually first happened is that it blanked out, like this:
![](https://chat.zulip.org/user_uploads/2/ee/BB1bD6CPWMI8y0Oga6BglvSx/IMG_1665.PNG)
Then when I touched the screen to scroll slightly, it reappeared, and I was here:
![](https://chat.zulip.org/user_uploads/2/55/OYBdQhu7Z1Ziwf6I7ubwFnEk/IMG_1666.PNG)
But where I'd been before this happened was about here (I scrolled back up to where I remembered being, then took a screenshot to record it):
![](https://chat.zulip.org/user_uploads/2/3/5PUoPymxYWfYbQvf9MV2oD3J/IMG_1667.PNG)
Which is something like a couple of screenfuls higher.

There wasn't a new message in my current view around that time -- the last message to that stream was from me, a couple of minutes before that.

**Comment by borisyankov** [comment]
@jainkuniya this might also be related to the scroll code you wrote. But not sure.

**Comment by jainkuniya** [comment]
One cause is, sometimes `keyboardWillShow` is called (unnecessary) with wrong keyboard height, which is then passed to scrolledView. As scroll value is not correct, scrollView interpret it as `0` and scrolls to top.

This will be automatically solved once we are done with `WebView` :)

will fix it @zulipbot claim

**Comment by borisyankov** [comment]
@jainkuniya make a judgment call on these issues.
If it is a simple fix, we will want to have it in the next release, that is due in 1-2 days. 
If it is not a short job, we will indeed fix via the new implementation.

**Comment by jainkuniya** [comment]
Submitted #M1582.

**Comment by jainkuniya** [comment]
Now with the newer MessageList, it is no longer relevant, can be closed now.
