### ISSUE TITLE
Usernames or full names aren't displayed properly

### ISSUE THREAD

**Issue by Vamshi99** [zulip/zulip-mobile#1554]
Letter descendants in usernames or full names are not displayed properly. Can't see letters `y, g, j, q, p` completely, down part of those is missing.

![screenshot_2017-12-14-23-39-39-599_com zulipmobile](https://user-images.githubusercontent.com/20969586/34029364-29afd520-e18e-11e7-8910-2f101ab76cf4.png)

**App details:**
Android 5.0.46

**Comment by dhruvdutt** [comment]
I think we can close this as it should be fixed in web view.
(Based on the discussion in [#1560](https://github.com/zulip/zulip-mobile/pull/1560))

**Comment by borisyankov** [comment]
Indeed, it will soon be fixed.
@Vamshi99 thanks for reporting it though. Do not hesitate to report more bugs you find. 👍
