### ISSUE TITLE
Can't delete draft messages

### ISSUE THREAD

**Issue by Vamshi99** [zulip/zulip-mobile#1557]
Can't delete draft message until we send some message in that stream.

**App details**
Android 5.0.46

**Comment by kunall17** [comment]
To delete it basically you can delete the message from the stream narrow, but it can be a pain! 

Do you recommend some kind of settings screen of draft lists, or maybe to disable the drafts, or some other suggestion?

**Comment by borisyankov** [comment]
Reproduced and working on it.

**Comment by borisyankov** [comment]
Closing as fixed.
