### ISSUE TITLE
Can't get available topics in a stream.

### ISSUE THREAD

**Issue by Vamshi99** [zulip/zulip-mobile#1558]
**Reproduce:**
Move to subscribed streams tab.

**Expected:**

- Shows available topics in each stream.
- Option to move to a particular stream.

**Actual:**

- Doesn't shows available topics in each stream.

**App Details:**
Android 5.0.46

**Comment by kunall17** [comment]
PR for this lying around here, https://github.com/zulip/zulip-mobile/pull/1398

Maybe we can do that if we all agree what do we exactly need to do to solve this?

**Comment by kunall17** [comment]
@jainkuniya @borisyankov We can show the topics in the stream info screen from the toolbar as well?

**Comment by jainkuniya** [comment]
@borisyankov This can be closed now, as now we have topic list screen.
(if required we open another issue for improving it)

**Comment by borisyankov** [comment]
Yeah, I will be improving this further, but at least it exists now :)
