### ISSUE TITLE
The ios app is generally slow

### ISSUE THREAD

**Issue by WYSIATI** [zulip/zulip-mobile#1575]
All are from ios app

1. When I open the app, it takes more than 10 seconds to fetch the latest messages, the message section stays blank until messages are rendered. Although the unread notification on the home page is instantly display.

2. If I have unread messages when I open the app, I would click the banner, but no response or sometimes super slow.

3. After a few clicks on different buttons, the app stunned.

**Comment by borisyankov** [comment]
This is definitely not the usual behavior of the app. Please, help us identify your issue.

What iOS device are you using? (if it is old, maybe it is a performance issue we need to tackle)

And what server are you connecting to? (if it is your custom server, maybe the server just responds slowly?)

Any chance you are connecting via very slow network?

As a comparison, I just tested the app on a 3-year-old iPad and it loads in 3 seconds. I

**Comment by borisyankov** [comment]
I have also tested on an iPhone 5, which is the slowest device we support, it was still 2-3 seconds boot. We need to figure out what is causing your particular slowdowns.

**Comment by kunall17** [comment]
I tested the latest app on TestFlight on an iPhone **4s** today and the results were fine, under 4 seconds it loaded into the Chat screen. 
Maybe this timing diagnostics in the settings screen screenshot would be a little help for this issue?

**Comment by borisyankov** [comment]
@WYSIATI we have released a version that is much faster than before. Give it a try.
