### ISSUE TITLE
Make JS executable (postMessage working) on lower Android version.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1583]
- [ ] Android 8.0.0 (just check if it works)

- [x] Android 7.1.0 #1584

- [ ] Android 6.0.1 JS is executing but postMessage is not working.

- [ ] Android 4.4.4

- [ ] Android 4.3

- [ ] Android 4.2.2

- [ ] Android 4.1.1

**Comment by borisyankov** [comment]
Before releasing, we should test on older Androids, but with the `es3.js` file I suspect some of the issues will be resolved automatically.

**Comment by borisyankov** [comment]
Closing as implemented.
