### ISSUE TITLE
Emoji support for web message list

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1589]
- [x] inside messages rendered 
- [x] inside reactions

**Comment by borisyankov** [comment]
@jainkuniya you might be interested in this one? :)

**Comment by jainkuniya** [comment]
yea! sure 

@zulipbot claim

**Comment by borisyankov** [comment]
@jainkuniya have you started on this? Because if not, I researched it and am starting on it.

**Comment by borisyankov** [comment]
Closing as implemented.
