### ISSUE TITLE
Update data inside web view

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1591]
- [x] replace completely
- [x] update messages on changed data
- [x] preserve position on loading previous
- [x] ensure correct anchoring

**Comment by jainkuniya** [comment]
There are some issues with completely replacing webView data. So can we split checkbox for Android & iOS.

(Somewhere I have read that on Android webView will not update if it content contains `#` )
https://github.com/facebook/react-native/issues/13574

**Comment by borisyankov** [comment]
Closing as implemented.
