### ISSUE TITLE
[BUG] Stream Side-Menu closes itself while typing in the search box(Mobile Web).

### ISSUE THREAD

**Issue by MadElf1337** [zulip/zulip-mobile#1631]
* Whenever a person tries to search for a stream in the search box provided in the streams' side menu in 
   mobile version of chat.zulip.org, the menu closes itself.

## Instructions For Reproduction:-
1. Go to https://chat.zulip.org from the mobile browser.
2. Login with valid credentials.
3. Open the side-menu of streams.
4. Tap on the search box to enable keyboard.

* After following these steps, one sees that the menu closes itself to go back to the home-page.
(GIF attached below)

![bug](https://user-images.githubusercontent.com/34575523/34339764-875225c6-e99e-11e7-94d9-f3b51452bdaa.gif)

**Comment by tommyip** [comment]
Hey @MadElf1337 this repo is for the react native app. What you are showing is the webapp in a mobile browser, can you move this to the zulip/zulip repo?

**Comment by MadElf1337** [comment]
This issue was moved to zulip/zulip#7896
