### ISSUE TITLE
Compose box shown when not usable

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#164]
The compose box is shown even when it is not usable. For example, in the home view with multiple streams and topics, the compose box is visible but doesn't have an effect.

**Comment by borisyankov** [comment]
That is intentional. The send button is disabled.
I am not entirely sure if we should hide it (the logic is there since the button disables itself correctly)

**Comment by neerajwahi** [comment]
I think having a compose bar visible but not usable is very confusing (and a UX anti-pattern).

Better to hide it until it's usable, or let the user choose a stream and topic when clicking into it (this was my original thought)

**Comment by timabbott** [comment]
Agreed.  We should just let the user choose stream+topic for the compose box in the home view (and choose topic when in a stream narrow).  We may need to make compose a bit more similar to how the existing Android app compose works for these narrows (but I think it's great to have it not require specifying where you're sending to in stream+topic narrows and PM threads, as we currently have it)
