### ISSUE TITLE
Ios app unread messages not updating

### ISSUE THREAD

**Issue by gauthamzz** [zulip/zulip-mobile#1674]
In ios unread messages don't come. Everytime i need to go to home to see the unread messages.

**Comment by borisyankov** [comment]
Hey, are you using the app from the App Store or are you a Beta tester?

**Comment by gauthamzz** [comment]
App store.

The app crashes also when I click on reply to any. 
iOS 11 iPhone 6

**Comment by borisyankov** [comment]
Thanks for reporting it. Sounds quite serious.
We will make sure to resolve this quickly.

**Comment by gauthamzz** [comment]
@borisyankov this issue is solved, there are some app crashes when you click reply to a message other than that the problem of messages not refreshing is solved.

**Comment by borisyankov** [comment]
OK, closing it then. I'll have a look at the crashes when replying.
