### ISSUE TITLE
Android App: Unresponsive app when clicking on `mark topic as read`.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-mobile#1684]
When I open the app and click on the top banner saying `mark all as read`, the app comes to a halt. I often have to reopen the app.  

Platform: Android 6.0.1 Marshmallow
Phone: Moto G Turbo Edition
Network: 4g Mobile Data (~16-20 mbps usually)

**Comment by jainkuniya** [comment]
@ViRu-ThE-ViRuS Thanks for the report.
Just curious to know whether ANR or crash dialog is show or not?

**Comment by ViRu-ThE-ViRuS** [comment]
no. It just stopped responding.

**Comment by borisyankov** [comment]
Did you have a lot of messages that were marked as read?
It is possible that this is some performance issue, though I haven't encountered it myself.

**Comment by ViRu-ThE-ViRuS** [comment]
28 new messages. The network is fast and the phone is also mid-spec. Just google chrome (1 tab) was running in the background.

**Comment by borisyankov** [comment]
Thanks. It is something else then. We'll need to reproduce first, but will likely not be hard to fix.

**Comment by jmandel** [comment]
I am experiencing the same issue on a Pixel 2 running the latest Android OS. Happy to help with debugging if you can provide instructions!

The net effect of this issue is that zulip will not remember where I am or what I have done, and I have to scroll way down every time I open the app.

**Comment by jmandel** [comment]
With 7.6.60 I see the same: I see "99+ unread messages", and clicking on "mark all as read" gives a quick button tap animation (which is rectangular in shape, despites the fact that the button itself is a rounded rectangle) and then nothing appears to happen. Is the "unread issues" text supposed to disappear? Is the view supposed to scroll down to the latest message?

**Comment by borisyankov** [comment]
Are you in 'Home' when you are narrowing or are you in a Stream / Topic?

**Comment by jmandel** [comment]
I was in "Home" just now.

**Comment by borisyankov** [comment]
Cool. I reproduced it. Will look into fixing next.

**Comment by ViRu-ThE-ViRuS** [comment]
![screenshot_20180131-131513](https://user-images.githubusercontent.com/16427330/35630329-27c41aba-06c7-11e8-826e-6f87b775c104.png)
This is what i get in the latest release from google play store.

**Comment by borisyankov** [comment]
Closing as 'fixed'. The fix will be available in the next release.
