### ISSUE TITLE
UI Bug in Android App: Misalignment of Hashtag and Topic Label

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-mobile#1685]
![a](https://user-images.githubusercontent.com/16427330/34517298-acfa3086-f0a4-11e7-8327-9211f67d4fbd.png)
The hashtag and the topic label are not horizontally level. This is a very minor thing, but it gives the user the feeling of lack of finesse.

**Comment by jainkuniya** [comment]
Good find @ViRu-ThE-ViRuS, it is issue in our current release.
Also it got fixed by https://github.com/zulip/zulip-mobile/pull/1648, so we can solve this one :)
