### ISSUE TITLE
UI Bug in Android App: Logo Overlap.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-mobile#1686]
![b](https://user-images.githubusercontent.com/16427330/34517376-f5a9477c-f0a4-11e7-828f-722e2d8042e4.png)
The Zulip log is overlapping with text (near the top of the screenshot) as seen. The UI bug can be easily reproduced when the topic is just a few messages (one scroll) long. You can also see this bug when you scroll to the top of the topic (above the first message).

**Comment by jainkuniya** [comment]
Seems to a regressions. Thanks for the report 👍 
(will be automatically fixed in our new webView rendering)

**Comment by ViRu-ThE-ViRuS** [comment]
@jainkuniya Good to know!

**Comment by leksyib** [comment]
Noticed this too.

**Comment by jainkuniya** [comment]
@borisyankov This can be closed now. As no longer relevant. Now we are using newer MessageList.
