### ISSUE TITLE
Android App: Non Intuitive Flow when sending emoji reactions to a message.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-mobile#1687]
I have been using the app for quite a while now. I still haven't been able to figure out how to send emoji reactions to a message. I am only able to do so when someone has already sent one. The most intuitive way to do this would have been to just long click on the message and see the option pop up. This is not really a bug, but making this change will surely improve the new user's experience.

**Comment by jainkuniya** [comment]
Nice find @ViRu-ThE-ViRuS 
But this is possibly duplicate of https://github.com/zulip/zulip-mobile/issues/1555
Soon we will he having emoji picker 👍 (I have done some work on it https://github.com/zulip/zulip-mobile/pull/646, but is quite outdated. Will rework soon)

**Comment by ViRu-ThE-ViRuS** [comment]
@jainkuniya Thanks for the response. Closing here.
