### ISSUE TITLE
Choosing a narrow results in multiple fetches

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#169]
After choosing a stream in the left sidebar, for example, the stream opens up with an initial fetch for content and then another fetch.

There seem to be two causes that we should address:
1. Move loading indicator behind content (instead of in front)
2. Load content in bigger batches

**Comment by timabbott** [comment]
For the bigger batches, I think we should move to fetching batches of ~100 (e.g. 50 in each direction); that will probably eliminate this issue.

**Comment by borisyankov** [comment]
Improved in `caching` branch.
