### ISSUE TITLE
Remove icons next to streams

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#170]
<img width="310" alt="screenshot 2017-01-02 16 44 07" src="https://cloud.githubusercontent.com/assets/4666213/21598087/b2a4bfb6-d10a-11e6-8101-e2199fa37db8.png">

**Comment by timabbott** [comment]
Yeah these are unnecessary clutter.  We should still display the lock icon next to private streams, though.

**Comment by borisyankov** [comment]
Wouldn't a # work better? I couldn't find such an icon quickly thus put this one temporarily.
Since we use #stream in the messages, and the designs showed a colored # next to the names instead of blocks?

**Comment by timabbott** [comment]
Oops, you're right, these should just change to `#` since that's the long-term design plan.
