### ISSUE TITLE
The "Settings Page" Link from the Welcome Bot crashes the app

### ISSUE THREAD

**Issue by Chua19** [zulip/zulip-mobile#1712]
Whenever you try to open the "Settings page" from the link the Welcome Bot sends you, the entire app crashes. The other links that the bot gives seem to work fine, it's just the Settings link causing trouble. 

![home](https://user-images.githubusercontent.com/17691779/34650767-45023ba2-f394-11e7-9899-47ca3dd2b0d9.png)

**Comment by borisyankov** [comment]
Thank you for reporting this issue.
I did fix it and the next release of the app will work correctly.
