### ISSUE TITLE
Splash screen spinner not spinning 

### ISSUE THREAD

**Issue by pranay414** [zulip/zulip-mobile#1732]
I opened the Zulip app and found that splash screen spinner is not spinning.
![zulip](https://user-images.githubusercontent.com/16045021/34817370-be9f3acc-f6dd-11e7-970d-b8ebfdfe2b29.jpeg)

**Comment by dhruvdutt** [comment]
Hey, @pranay414 
Can you be a little specific about your iOS version and the medium you used to install Zulip mobile app?
Is this happening at the time of initial loading?

**Comment by borisyankov** [comment]
The latest public version contains a new spinner that stops spinning if the UI thread is blocked.
I did rework the spinner, fixing that, and it is in `master` (but not deployed yet).
Closing as resolved.
