### ISSUE TITLE
Some emojis which are not updated results in undefined 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1744]
This is an example of `clinking_glasses` emoji name 

<img width="229" alt="screen shot 2018-01-13 at 8 08 42 pm" src="https://user-images.githubusercontent.com/12700799/34906990-94d9d438-f89d-11e7-9a2f-3363b339dcf7.png">

**Comment by borisyankov** [comment]
This will be resolved with #1698

**Comment by kunall17** [comment]
Nope, `clinking_glasses` is not a realm emoji!

**Comment by borisyankov** [comment]
Then I am not sure what you mean.
This is the updated list of supported emojis:
https://github.com/zulip/zulip/blob/master/tools/setup/emoji/emoji_map.json
and it isn't there too.

**Comment by timabbott** [comment]
@borisyankov we have a new emoji system using data from iamcal ( see details http://zulip.readthedocs.io/en/latest/subsystems/emoji.html#tooling) -- the old `emoji_map.json` is not well-maintained upstream and thus doesn't have newer emoji names.  @HarshitOnGitHub can provide details but I think you want to be downloading copies of the `static/generated/emoji/emoji_codes.js` file from `static/generated/emoji/` in a provisioned Zulip development environment (and maybe some of the other files, too) to get the current emoji data set.

**Comment by borisyankov** [comment]
Oh, I knew about the iamcal ones, but didn't know the `emoji_map` was the old data.
Shouldn't be hard to upgrade this.
