### ISSUE TITLE
'Add Server' screen (during the login flow) is confusing

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#176]
<img width="375" alt="screenshot 2017-01-02 16 52 08" src="https://cloud.githubusercontent.com/assets/4666213/21598136/decc6c64-d10b-11e6-84b5-a462408d857c.png">

The 'Sign in' button is available but doesn't actually do anything here. We should remove this button and instead show the realm name greyed out along with a 'Username' and 'Password' field.

**Comment by timabbott** [comment]
I think we can just copy the interaction design present in the current Android app; that has the right flow, disabling, etc. model.
