### ISSUE TITLE
Login modal remains displayed after the login is finished

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#177]
After clicking 'Sign in' (having entered all required credentials), the login modal remains in view until it gives way to the main stream view. We should instead immediately present the stream view to the user.

**Comment by borisyankov** [comment]
On 'Sign In' a fetch_api_key request is sent.
On success we redirect to main. On fail we remain on the screen.
I see no good reason why it should redirect to an empty screen that has no data yet, and in case of wrong password go back?

**Comment by neerajwahi** [comment]
When I tested it on device, a successful sign in redirects to main but also pops open the navigation screen (for login) briefly. I meant we should fix that behavior
