### ISSUE TITLE
Content offset bug when scrolling to top of stream view

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#178]
The content inside of the scroll view is clipped

**Comment by borisyankov** [comment]
Elaborate.

**Comment by timabbott** [comment]
@neerajwahi do you have the screenshot for this?  Regardless it was very reproducible, basically the top part of the top message (i.e. who sent it) would be obscured by the main header at the top of the screen after you scroll to the top.

**Comment by borisyankov** [comment]
Reproduced. 
Does not exist on `cached` branch (tm)
