### ISSUE TITLE
Tapping a notification should bring you to the related message in the app

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1789]
- [x] Switch narrow to stream / topic / PM / group
- [x] Anchor to the first unread in narrow
- [x] Load messages around anchored message if not already loaded
- [x] For all use cases handle both app not started and already running
- [ ] Anchor to the message ID (I suspect this is better than first unread)
- [ ] Switch realm if not on the same realm
- [ ] Ask for login information if not logged in, then narrow

- [x] Work on Android and iOS

**Comment by gnprice** [comment]
@borisyankov , what's the current status of how much of this is expected to work at this point?

**Comment by borisyankov** [comment]
The important things:
* not narrowing on iOS besides just running the app
* on Android we should not be grouping all notifications in one but group by narrow
* not narrowing correctly when group notification (I'll fix that next)

Less important and complicated:
 * handle the case when not logged in (when logged in, narrow to the message)
 * the case when logged in to another realm - offer to switch

**Comment by simoneOnFhir** [comment]
I am still having this issue with Android: Tapping a notification just opens the app but doesn't narrow to the stream / conversation. Is that still an open issue?

**Comment by kunall17** [comment]
@simoneOnFhir was it a stream message, private or a group message?

**Comment by borisyankov** [comment]
@simoneOnFhir it should work and it does in most cases. We need to figure it out, it is a bug.
Are you sure you are on the latest version? Latest one is `13.2.86`

**Comment by timabbott** [comment]
I saw something similar on the latest version as well.

**Comment by simoneOnFhir** [comment]
Oh! I just realized that apparently I had a retired version of the app. I installed the new one and will let you know

**Comment by simoneOnFhir** [comment]
Huh. That did the trick. When I went to the Play Store to figure out which version I am using, I realized that Zulip showed up as "not installed", so I did, then I had two apps and the new one works correctly.

**Comment by simoneOnFhir** [comment]
yes, I guess that's what happened

**Comment by borisyankov** [comment]
Cool! Thanks for clarifying.

I am closing this issue as we are tracking the remaining sub-tasks in other issues.

**Comment by klappy** [comment]
I'm still encountering this issue and unsure of how to track it since this was closed for sub-tasks. As a user this makes it difficult to report or follow the issue resolution.

**Comment by gnprice** [comment]
Hi @klappy !

You can find notifications-related issues under our label for the "notifications" area:
https://github.com/zulip/zulip-mobile/issues?q=is%3Aissue+is%3Aopen+label%3Aa-notifications

Two current issues that are related to this particular feature of notifications are #3582 and #2295. One of those looks to be one of the original sub-tasks of this one; the other is a recent regression. Please take a look, and if neither one matches what you're seeing then please file a new bug and we can look into it.

If you can recall, I'd be quite curious to hear what you searched for when looking for an issue tracking the symptoms you're seeing. If the closest you found is this old thread tracking the original implementation of the feature, then perhaps there's something earlier in your path where we could make things more discoverable :slightly_smiling_face: 

(I do agree that it was bad practice to close this issue on account of sub-tasks elsewhere and not actually link to those sub-tasks. I think in the past year or so we've more consistently gotten that kind of thing right, for our own sakes as much as everyone else's.)
