### ISSUE TITLE
Search for a user in right sidebar cannot be cancelled

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#179]
There's no way to stop the search (and hide the keyboard) when searching for the user in the right sidebar

**Comment by borisyankov** [comment]
Can you not cancel it by clicking outside the control?

It is definitely better for the search itself to be in a separate modal window which you can go back from, thus giving another way to back off - back/cancel button or the standard back button on Android.

**Comment by borisyankov** [comment]
Addressed by https://github.com/zulip/zulip-mobile/pull/222
