### ISSUE TITLE
Scrolling issue with emoji

### ISSUE THREAD

**Issue by dhruvdutt** [zulip/zulip-mobile#1795]
Currently when scrolling messages, if a message text contains emoji, it gets on top of the stream topic section.

![screenshot_2018-01-25-14-52-24-1980699006_01_01_01](https://user-images.githubusercontent.com/5961873/35380665-fc18fd7c-01df-11e8-9aa6-044395a1d7a7.png)

This behaviour doesn't happen in emojis reactions.

![screenshot_2018-01-25-14-55-24-1883523868_01_01](https://user-images.githubusercontent.com/5961873/35380696-1047a190-01e0-11e8-84a5-43064e51f424.png)

**Comment by jainkuniya** [comment]
@zulipbot claim
