### ISSUE TITLE
Half-rendered and blank messages, after scrolling through many messages

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#1800]
On the latest Android beta, I opened up `#test here` on chat.zulip.org. Just like described in #1545 , the app first showed me messages from way back in the past, in mid-May of last year; then I scrolled down, mostly as quickly as I could. Partly to be able to see recent messages, and partly to see if it would work. :-)

And the app didn't crash! :tada: Score one for the new WebView-based message view. (Maybe also for my enormous new phone; haven't tried this recently on my iPhone 6.)

But, the display got fairly messed up -- a lot of messages didn't render, or rendered in broken or half-visible ways.

Here's the first spot where this was super conspicuous -- it's about 2017-11-01 in the stream:
![](https://chat.zulip.org/user_uploads/2/ae/8T-0wloipRzbxjz6oy6488Qy/Screenshot_20180125-110826.png)
There's an animated GIF there; it was moving, but very jerkily, showing just white on alternate frames, like this:
![](https://chat.zulip.org/user_uploads/2/34/16z36QeeVBXTzZU3xaxfh6mv/Screenshot_20180125-110824.png)
Also note that some neighboring content is blanked out -- including a few messages after the one with the GIF, and part of the date divider below. Here's what that area looks like on the webapp:
![image](https://user-images.githubusercontent.com/28173/35407913-29c858da-01c2-11e8-9873-f922ff6b6ee3.png)

Scrolling some more after that, other messages were blanked out:
![](https://chat.zulip.org/user_uploads/2/9f/Ha-3LzbhbIp7Cgvw47TM3q-A/Screenshot_20180125-110839.png)
That's actually just below the same spot; some of the messages that were visible in the shots above (e.g. Sampriti's "test 2" etc.) are blanked out here. And even when I scrolled back *up*, messages that were a few above the GIF and I'd seen when I first scrolled past them were blanked out:
![](https://chat.zulip.org/user_uploads/2/51/K4_EQPnaKyYroY7GLjr-0RgA/Screenshot_20180125-110855.png)

When I got near the end of the stream, a red error banner appeared, but it was mostly hidden by the topic header:
![](https://chat.zulip.org/user_uploads/2/7/XtXbqd33ZKTJwwUkBG_tll0Q/Screenshot_20180125-110919.png)
Also by this point many topic headers are blank, including all the ones in this shot.

Finally I got to the very end of the stream, and the "99+ unread messages" banner went away. The red error banner became slightly less hidden; it appears to say `Error: {}`.
![](https://chat.zulip.org/user_uploads/2/13/NtUYD-2-AriHvbI2Scv1zcEW/Screenshot_20180125-110943.png)

(Also that is not nearly the *actual* end of the stream; it's two months ago, and looking in the webapp there look to be hundreds of messages since then. But that seems like an issue for a separate thread.)

I'm on 6.6.53, on Android 8.1.0 on a Pixel 2 XL.

**Comment by borisyankov** [comment]
Good news is part of this is likely fixed in `master`.
Will examine the whole `test here` stream.

**Comment by borisyankov** [comment]
After doing several fixes (and releasing publicly) I can not reproduce this.
Closing as likely fixed, but please do reopen if you encounter it again.

**Comment by gnprice** [comment]
Tried with 8.1.62, and I can't reproduce this now either! :sparkles: Excellent.

**Comment by gnprice** [comment]
(The message with the skeleton anigif does show #1744 -- there's a `:skull_and_crossbones:` reaction.)
