### ISSUE TITLE
Android app crashes when opened through notification

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1815]
Notification to narrow generally seems to work if the app is already running. 
If it is not, opening it via notification crashes it!

**Comment by borisyankov** [comment]
Bug is present in latest `master` that is released as Beta.

**Comment by kunall17** [comment]
Hmmm, I tried on the master it's working fine for me I did a production release and tried on the phone works fine.
But is crashing on the beta release with the old error as here https://github.com/zulip/zulip-mobile/pull/1827#issue-292178809 and I think it should not throw this, as the function `tryInitialNotification` is being called after all the streams get initialized and all the API calls have been done! 
And the error shows it cannot get the auth.realm value when trying to fetch the messages, can you give the PR https://github.com/zulip/zulip-mobile/pull/1830/a thorough review, what else can go wrong?

**Comment by borisyankov** [comment]
What is the reason you used the `setTimeout` still? Describe in detail, that was one thing I doubt is a good idea.

**Comment by kunall17** [comment]
That setTeimout was still there so as to make sure we have loaded the streams and the other data correctly, and It shouldn't do any negative impact right? 

I tried having the console.log statements in the doNarrowAtAnchor and using react-native log-android to check from the release build and again found it's working! 

The error suggests the dispatching is not going right, as the doNarrowAtAnchor isn't able to connect to the redux to fetch auth.realm!

**Comment by borisyankov** [comment]
#1836 This either fixes it or is a step in that direction.

**Comment by borisyankov** [comment]
Now it is not crashing, but is not narrowing either ;)
Which is better, so I released this version.
In the next few days, we need to make sure the narrowing works perfectly.

**Comment by borisyankov** [comment]
Closing this as we no longer crash, but we still need to implement it to completion!
