### ISSUE TITLE
Sticky headers broken on device

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#182]
Headers (aka recipient bars) should remain fixed to the top of the scrollview while scrolling. This functionality is fine in the simulator but broken on an actual device.

**Comment by borisyankov** [comment]
This might be a bug in ScrollView. Needs investigating.
@timabbott I was actually thinking these sticky headers are not that useful and takeup important space on smaller screens. The messages are short. These should definitely not be used always and in almost all cases messages are rather short.

**Comment by timabbott** [comment]
I disagree, if you narrow to a stream where the last 200 messages all have the same topic, it's very difficult to find out what the topic of all those messages is without the sticky header!  I am confident if we ship with this implemented as-is that we'll immediately get a lot of complaints about this from our users.

**Comment by borisyankov** [comment]
Good point.

**Comment by neerajwahi** [comment]
👍 to the importance of sticky headers

**Comment by borisyankov** [comment]
Latest build tested on device. Sticky headers work.

**Comment by neerajwahi** [comment]
I'm still seeing this issue for the 'Release' configuration on device only. Investigating.

**Comment by neerajwahi** [comment]
My hypothesis is that this occurs because the `type` property used here is not available in Release configuration:  https://github.com/zulip/zulip-mobile/blob/d2accb57db95c13279cd370e392c94cfdd4fd853/src/message-list/MessageList.js#L23

**Comment by borisyankov** [comment]
That is quite a good guess.
