### ISSUE TITLE
Hold-click on a link in a message results in re-flow

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#184]
Hold-clicking on a link inside of a message will sometimes result in a reflow (and reformatting) of the whole scrollview

**Comment by borisyankov** [comment]
Maybe caused by this?
https://github.com/facebook/react-native/issues/1693

**Comment by neerajwahi** [comment]
Hmm at first glance that doesn't seem related. Not getting the `Attempted to transition from state..` warning box

**Comment by borisyankov** [comment]
Can not reproduce anymore. Maybe updating react-native fixed it.
@neerajwahi can you reproduce?

**Comment by neerajwahi** [comment]
Nope. Let's close it and we can reopen if necessary
