### ISSUE TITLE
UI Issue: Text Unreadable in Dark Mode.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/zulip-mobile#1844]
The Stream name is often unreadable in the dark mode due to its lack of contrast from the stream color.
The dark grey text is very hard to see when the stream has say yellow color. 

![screenshot_20180131-131651](https://user-images.githubusercontent.com/16427330/35630385-499c4a40-06c7-11e8-82d2-6a78d95c2c5a.png)

**Comment by AakarSharma** [comment]
**@zulipbot** claim

**Comment by AakarSharma** [comment]
**@zulipbot** claim --force

**Comment by AakarSharma** [comment]
**@zulipbot** claim

**Comment by AakarSharma** [comment]
**@zulipbot** claim --force

**Comment by borisyankov** [comment]
This one is fixed already. Closing.
