### ISSUE TITLE
Issues with compose box

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1850]
* mention is not working (not bringing names) 
* when I reply the post doesn't show until I return to the main subject
[Android 7 Huawei mate 8]

**Comment by timabbott** [comment]
> when I reply the post doesn't show until I return to the main subject

I think this might be what I was seeing with blank screens, actually.

**Comment by borisyankov** [comment]
@timabbott the good news is that the blank screen is present only in the Beta.
The public release which is one day older does not have this.
Will push a new Beta with this and likely other fixes tomorrow.

**Comment by borisyankov** [comment]
A new Beta released, reverting the navigation, thus fixing the 2nd issue.
The first issue with autocomplete is Android-specific and will be fixed tomorrow.

**Comment by borisyankov** [comment]
Closing as fixed.
