### ISSUE TITLE
Show placeholder when custom emoji unavailable

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#186]
If an inline emoji image is unavailable (and the request 404s), we should display a broken image placeholder to indicate that an image was supposed to appear. Currently nothing is displayed and the desired image takes up no space in the message.

**Comment by kanhegaonkarsaurabh** [comment]
@neerajwahi  @timabbott  I would like to work on this issue. Could you tell me a bit more about how to go about solving it??

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
@vishwesh3 I am not sure when this can happen? Maybe we are already showing a `?` in place?

**Comment by jainkuniya** [comment]
For reactions we are showing `copyright` ©  (I thinks same as web), if reaction url is not valid.
But currently for images in messages (image or inline emoji), if url is not valid, blank space is shown.

**Comment by borisyankov** [comment]
Not totally relevant with webview / not sure we need to do it now.
