### ISSUE TITLE
App crashes on device after a lot of scrolling

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#187]
We need to run this through the debugger and figure out what's causing this issue. It could be memory pressure.

**Comment by borisyankov** [comment]
This can easily be a memory issue or a layout engine issue. Having thousands of components needing rendering.

**Comment by neerajwahi** [comment]
Yep could definitely be memory or layout. Just needs some investigating :)

**Comment by neerajwahi** [comment]
I think #232 and #233 should resolve this
