### ISSUE TITLE
Reevaluate and improve the APP_REFRESH action

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1880]
The `APP_REFRESH` action is fired when our event polling gets interrupted.
It works reasonably well as it is.

Several areas we can improve:
 - [ ] consider using this the connectivity change events (`APP_ONLINE` action)
 - [ ] consider reworking some of the `APP_REFRESH` action handlers to better invalidate the states
 - [ ] find out if we are missing any reducer that should handle this action

**Comment by divyabaid16** [comment]
May I work on this issue ?
If yes, can you please guide me ?

**Comment by borisyankov** [comment]
@divyabaid16 sure you can. Though I think a lot of it is reading code and understanding the current behavior. The actual implementation might be just few lines of code.

I'd say just dive in, examine all reducers that have `case APP_REFRESH:`. Think if their behavior makes sense. Look at the other reducers that don't have this. Consider if maybe we should have it.

And if you have questions ask here and I'll give more details. Sounds good?

**Comment by anirudhjain75** [comment]
@borisyankov Is anyone working on this ?
I'd like to work on this as I can't find any unassigned issue other than this 😓

**Comment by HarshulSharma000** [comment]
Is the issue still open? I would like to give it a try.

**Comment by borisyankov** [comment]
Sure, this is still open, but since it is not well defined, a first step would be to evaluate if there is anything to fix, first. Then define what has to be done, discuss it, and after all that comes the code writing. 👍

**Comment by HarshulSharma000** [comment]
What exactly are we looking for here? Any focus on specific improvement portions? Or at least what gains are expected?

**Comment by borisyankov** [comment]
This might be a bit too vague of an issue to take as a newcomer to the project.
Have a look at how our `APP_REFRESH` event works - if we consider our app had interrupted connectivity with the server it will refresh certain parts of its data.

**Comment by borisyankov** [comment]
This is working well, closing the issue.
