### ISSUE TITLE
Add 'Invite people to stream' feature

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#1897]

**Comment by gnprice** [comment]
(We've had this for a while now.)

**Comment by borisyankov** [comment]
Sure, if you do it one by one :)
But not in the way you are asking for.

**Comment by borisyankov** [comment]
I think it is worth getting @timabbott opinion on this.
Not that hard to implement. Good for onboarding.

**Comment by timabbott** [comment]
I think invitations to the realm itself is probably the reasonable feature to dad here (though multi-use invite links, which will become available on web soon, may also mitigate this problem).  We can open a separate issue for this, but I think it's probably a P2 -- lots of other stuff are more important for daily use of the app.
