### ISSUE TITLE
Errors in executing steps as per Getting Started Documentation

### ISSUE THREAD

**Issue by ajayns** [zulip/zulip-mobile#1905]
Getting started guide (https://github.com/zulip/zulip-mobile/blob/master/docs/getting-started.md) states that the command for running the Android version is `react-native run-android` but this seems to return an error. 

I believe the steps to be followed is:
`npm run android-min` or  `npm run android-max`

**Comment by ajayns** [comment]
If this is a valid issue I'd like to work on it!

**Comment by borisyankov** [comment]
Both `android-min` and `android-max` are actually equal to `react-native run-android` as you will see in `package.json`.

It is a bit tricky to reimplement this as we do it for ios, as you need to have the virtual machines already created.

If you think you can improve this somehow, feel free to work on it 👍

**Comment by ajayns** [comment]
I noticed that in package.json. But the thing is, the command won't execute unless you have react-native installed globally. 
So the command `react-native run-android` throws `react-native: command not found` in a general scenario. I feel the method should be generalized rather than like this. I'll submit a PR?
