### ISSUE TITLE
Deleted messages don't have their unread counts removed

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1926]
I deleted all the messages in a certain topic (using the administrator "delete message" feature that completely removes it), and users found that the mobile app still showed a nonzero unread count for that topic, and of course clicking into the topic showed no messages.

The bug here is that the mobile app's unread tracking should remove a message from its unread data structures when it gets an event from the server that the message was deleted, just as though the message had been read (though we should be careful to not break the case of deleting a message that was already read).

**Comment by borisyankov** [comment]
It seems we are not even handling the delete message event for the message list!
Will add this too.

**Comment by borisyankov** [comment]
@timabbott it seems that the server does not send any event on a message deletion.

**Comment by timabbott** [comment]
Turns out the event type is `delete_message`, which you're probably not listening for.  See https://github.com/zulip/zulip/issues/8411 for a bit more detail.

**Comment by borisyankov** [comment]
Oh, sure, we aren't. Implementing this next.

**Comment by borisyankov** [comment]
Closing as implemented.
