### ISSUE TITLE
Poor use of space on settings page

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#1959]
![screenshot_20180223-003306](https://user-images.githubusercontent.com/24983958/36558548-5ba01034-1831-11e8-87bd-d00fa2508ad0.jpg)

Could've been better!

**Comment by anirudhjain75** [comment]
@zulipbot claim

**Comment by anirudhjain75** [comment]
I've made some changes in #1973

**Comment by pulkonet** [comment]
@jainkuniya can we make a slack inspired settings page, it shows user image, name, and community name and then what all we show? That would definitely be an improvement over the current state.

**Comment by anirudhjain75** [comment]
@zulipbot abandon

**Comment by pulkonet** [comment]
I have assigned it to myself. I'll fix this and send a PR.

**Comment by borisyankov** [comment]
Not sure the way this issue is defined aligns with our intentions.
Before working on more code, please do discuss what you are planning to implement, so we don't both waste efforts on something that might not get merged.
