### ISSUE TITLE
Login form improvements 

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#196]
* We should automatically append https:// to the URL if the user just enters a server name such a chat.zulip.org (without the "https").

* We should probably not allow using `http://` except to connect to localhost (production servers don't support insecure HTTP).

* Invalid password produces a traceback:

![image](https://cloud.githubusercontent.com/assets/2746074/21699963/e0c0733c-d352-11e6-86df-52c89d600866.png)

I tested this on Android but I assume these issues are present on iOS as well.  

Sorta part of the broader cleanup we should do for the login process in #176.

**Comment by borisyankov** [comment]
We have https auto append if no http is entered.
I'll look into the error.
