### ISSUE TITLE
Message list doesn't scroll to bottom

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#1960]
Message list doesn't automatically scroll to bottom, even if there are no unread messages in the particular stream.

**Comment by borisyankov** [comment]
Please elaborate.
Does it happen always? Is it just for streams? For topics? For direct messages too?

**Comment by pulkonet** [comment]
Reproduction Steps:
1. Go to a stream where you have unread messages, quickly click on 'mark stream as read' button.
2. Scroll down to the bottom.
3. Then exit the stream.
4. Then hop in back to the stream

**Comment by anirudhjain75** [comment]
I've verified this.
The position of last read message is same as when you had the unread messages.

**Comment by borisyankov** [comment]
Fixed by #2082
