### ISSUE TITLE
Indentation is odd.

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#1964]
![screenshot_20180224-143456__01](https://user-images.githubusercontent.com/24983958/36627938-4566a162-1970-11e8-8538-f71b822acebf.jpg)

**Comment by anirudhjain75** [comment]
@pulkonet Could you write down the steps or instruction to reproduce this ?

**Comment by borisyankov** [comment]
This is easily reproducable but I don't think it is worth fixing. At least currently it is done intentionally.
