### ISSUE TITLE
Reply box looks broken in topic narrow with long name

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#1966]
![screenshot_20180224-145658__01](https://user-images.githubusercontent.com/24983958/36628687-6385307a-1973-11e8-9adc-45300b91238b.jpg)

**Comment by borisyankov** [comment]
We do not have control over the Input's placeholder `ellipsizeMode`-like property.
Have a look at:
http://facebook.github.io/react-native/docs/textinput.html

The normal text usually has this property as you can see here:
https://facebook.github.io/react-native/docs/text.html

**Comment by timabbott** [comment]
Would it make sense to expand the height of the widget when the text is long?  That screenshot does look broken.

**Comment by pulkonet** [comment]
Can we not show disabled text in place of placeholder and hide it when the user starts typing or if the sting in the original text box is not empty? I guess this is just a workaround since we can't play with placeholders the way we can with normal text. @timabbott  @borisyankov

**Comment by borisyankov** [comment]
We should balance the effort with the severity of the problem.
This is an unpleasant visual issue that does not prevent the user from doing their task.
An alternative solution is to submit that as a bug report to React Navigation.

**Comment by pulkonet** [comment]
Fair enough

**Comment by timabbott** [comment]
@borisyankov this feels pretty visible as an issue to me; perhaps we should just change the text to "reply" for now, rather than including the whole topic when you're in a narrow that completely determines where your reply will go (e.g. a topic or PM thread narrow)?  I think that'd be better than the current placeholder anyway, and would eliminate this ugly issue.

**Comment by gnprice** [comment]
I agree with Tim -- this looks really broken, and I see it pretty often. Sent a PR with the fix to just say "Reply".
