### ISSUE TITLE
Typing notifications need more styling

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1967]
Right now, the typing notifications in PM threads look really close to someone saying "is typing" in the mobile app.

We should address this by some combination of:
(1) Making the "is typing" text italicized; that's part of how we indicate 
(2) Centering the text vertically in the row with the avatar (right now it's sorta aligned with the top of the avatar and I think looks less good) and/or showing the avatar slightly smaller (I think this might look better)
(3) Possibly add something like a pulsing "..." animation to make it feel active (if we do something good here, we can bring it back to web).

**Comment by borisyankov** [comment]
Implemented here #1977
I added animated dots exactly as in FB Messenger.
I removed the text as the dots replace the need for any text.

**Comment by timabbott** [comment]
Great :)
