### ISSUE TITLE
Provide a "quote and reply" option

### ISSUE THREAD

**Issue by Vamshi99** [zulip/zulip-mobile#1975]
We have this in web app, so it would be nice to have same. And also narrowing down to the message topic when we reply isn't good, what if we want to stay in stream tab itself?

**Comment by timabbott** [comment]
I think in most cases one wants to switch to the stream tab to reply.

I think adding "Quote and reply" would be reasonable.

**Comment by borisyankov** [comment]
@Vamshi99 when a person wants to quote and reply, it is almost always to part of a message.
When having a desktop and a mouse/touchpad, having the long message quoted they will delete the part that is not needed. On mobile, this is very cumbersome. That is the reason we don't think this will be useful.

In any case, the user can copy the message and paste it in the compose box with a `>` in front achieving the very same result.

**Comment by timabbott** [comment]
@borisyankov I agree deleting parts would be a pain, but because a significant portion of messages are just 1 line, I think having a UI element for quoting the whole thing and then composing a reply below would be useful.  Not a high priority compared to other issues (adding an emoji reaction is like 20x more common of a thing to want to do), and perhaps a bit tricky to do (in that I don't think our compose widget handles longer items well), but something we should do eventually.

**Comment by borisyankov** [comment]
> I don't think our compose widget handles longer items well

Are you probably mistaking the error reported? It was for the text placeholder that we can not control well. The compose box itself works well as far as I know.

**Comment by Vamshi99** [comment]
Maybe it isn't of high priority, but it would be good to have it after sometime

**Comment by borisyankov** [comment]
It will likely need to be implemented quite differently than how we do it in the web app.
A good approach to designing new features is to have a look at how this is implemented in other mobile chat apps.

**Comment by chrisbobbe** [comment]
One small note is that it was suggested that #3464 might be good to do first. Quoting from that issue's description:

> Spitballing, a fancier version would be to turn "Reply" into "Reply...", and have it pull up a second menu with options like "Reply", "Reply @${sender.full_name}", "Reply quoting message" (see #1975). But that might be best done separately after merging a first version of this.

But I don't think this is a hard requirement if it seems doable in another order.

**Comment by WesleyAC** [comment]
Looks like we already have the code for this mostly in shared, see `shared/js/fenced_code.js`.

**Comment by gnprice** [comment]
Just a note that we've again heard a user mention this as a salient missing feature in the mobile app.

**Comment by eric-wieser** [comment]
> In any case, the user can copy the message and paste it in the compose box with a `>` in front achieving the very same result.

This is not a particularly appealing solution, especially since it does not generate the message link that the webapp does. I think simply matching the webapp here would be a significant improvement, making the editor UX better can come later.

**Comment by gnprice** [comment]
We heard this feature request [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292716) again today, from @jyn514 and echoed by @timabbott.

(To simplify this thread, I've hidden some comments above that were discussing whether we want this feature at all; at this point I think it's clear that we do.)

**Comment by gnprice** [comment]
A neat bonus UI for this feature would be that you can get to it by swiping right on the message -- this is something [Signal and WhatsApp do](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292739).

But that can be a follow-up issue after we have the feature in the first place. This issue is for adding this feature as an option in the message action sheet (what you get by long-pressing on the message.)

**Comment by alya** [comment]
Popular request in user survey.

**Comment by alya** [comment]
Another bump on this feature request: https://rust-lang.zulipchat.com/#narrow/stream/122653-zulip/topic/suggestions.20from.20.22moving.20implementors.20from.20Discord.22/near/292780374

**Comment by maltokyo** [comment]
Enable "Quote Reply" in the mobile Zulip app is now one of the biggest requests from my users too.  One of their recent posts:

"The world is telling us Mobile First, but in Zulip we have to regress to the desktop?  What is wrong with a long click or swipe context menu that enables us to quote reply, with some other options too"

Thank you for considering

**Comment by Carnage78** [comment]
Click to ‘said’ after ‘quote and replay’ message, there is no transition on the original message 🙁

**Comment by gnprice** [comment]
@Carnage78 It sounds like you're describing something you'd like to work differently about this feature. Please file a new issue for that. When you do, please include a specific description of what you did, what happened, and what you would like to happen instead — that way we'll be better able to understand what you're asking for.
