### ISSUE TITLE
Some icons are not visible in night theme.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#1989]
In the setting tabs.

<img width="303" alt="screen shot 2017-09-29 at 5 16 55 pm" src="https://user-images.githubusercontent.com/18511177/31017147-334cf048-a545-11e7-8715-1efd23c9298d.png">

**Comment by pulkonet** [comment]
Can I work on this? I can't claim any issue as of now because I have a pending PR that needs to be seen, so in the meantime maybe I could look into this.
