### ISSUE TITLE
WhiteSpace is rendered when there are no Conversation Messages

### ISSUE THREAD

**Issue by aswinmohanme** [zulip/zulip-mobile#1999]
When there are no unread conversations half of the screen is empty and Stream view can only take up half the size of the screen.

Upon inspecting the Empty Conversations List takes up `flex:1` which when combined with the flex of Stream View takes up half the screen.

**Comment by aswinmohanme** [comment]
@zulipbot claim

**Comment by jainkuniya** [comment]
there is already a standing PR for this one #1986. :)

**Comment by aswinmohanme** [comment]
My Bad :grinning:
