### ISSUE TITLE
Number of unread messages on the bottom icon is wrong

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2004]
![screenshot_20180305-001614__01](https://user-images.githubusercontent.com/24983958/36949206-281dde62-200b-11e8-9964-d74ca063cb94.jpg)
Total number of unread chats must be shown in the bottom icon (as WhatsApp does) and not the total unread messages.

**Comment by anirudhjain75** [comment]
@pulkonet That totally depends on the what zulip is targeted to show, Though I agree that this must be the total number of unread chats

**Comment by pulkonet** [comment]
In all the other community chat apps also it is done the same way. They show the number of unread chats. Also, this might seem to be trivial at this point but with communities, with a large number of direct messages, this may get to be a big number which would be unreasonable to show.

**Comment by borisyankov** [comment]
@timabbott what do you think this number should show? Do you agree?

@pulkonet to make your case stronger, give examples of how it works in Slack, FB Messenger, WhatsApp.

**Comment by pulkonet** [comment]
![point blur_mar052018_005116](https://user-images.githubusercontent.com/24983958/36949549-f60227d0-200f-11e8-87cc-3ead9d03445f.jpg)
Here's from WhatsApp. The number shown beside chats is not the total number of unread messages
I don't have screenshot from slack at this point and messenger has no such unread chats thing in app. Though on FB web app they show the number of unread chats only.

**Comment by timabbott** [comment]
I'm not sure.  That widget feels like a notification area, where it might be most appropriate to show the total number of conversations with unread messages.  

That said, I'd prefer work on the PM threads part of the app go into showing PM threads at the top of in the main "Unreads" view, since I think that will be a better way to consume the information, and we might end up removing the unread counts from that element altogether after doing that.

**Comment by pulkonet** [comment]
@timabbott I don't quite get your point. could you please elaborate?

**Comment by pulkonet** [comment]
Also, should I work on this or leave it as it is?

**Comment by borisyankov** [comment]
@pulkonet what @timabbott is talking about is actually being polished and going in `master` today.
Don't do anything for now, but it will be more clear what we want to do later this week :)

Sometimes discussing features is important, and also is important to not act immediately but let the thought sit for a while in people's heads ;)

But that was a great point you made and will likely lead to some changes/improvements. Keep comparing the app's behavior to Slack, FB Messenger, WhatsApp (and others, but in this order of importance). If you find differences, we will very likely want to make the app more similar to what other apps do.

**Comment by gnprice** [comment]
Closing, as we don't currently plan to change this.
