### ISSUE TITLE
Sometimes all messages are visible in narrowed view.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2007]
![screenshot_20180305-014959](https://user-images.githubusercontent.com/18511177/36950639-e1f7a62a-201e-11e8-8eee-912198417553.jpg)

https://chat.zulip.org/#narrow/stream/48-mobile/subject/unread.20counts.20colors/near/525933

reported by @pulkonet

**Comment by borisyankov** [comment]
I suspect the thrown error has something to do with this, but I don't think we can figure out what is going on by this information alone.

**Comment by jainkuniya** [comment]
This might be related to #2019, as while updating again (on going back) it encountered some error and stuck in the home narrow itself. Resulting in all message are visible.

**Comment by borisyankov** [comment]
Yeah, I suspect it is relevant. If this happens in the new release we can reopen a new issue.
