### ISSUE TITLE
Optimistic UI Updates

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#201]
* Send message displays it immediately
* Adding/removing reaction updates UI immediately

**Comment by timabbott** [comment]
For sending messages, we'll want to borrow the `marked.js` (for markdown rendering) and `local_id` code path that we have in the web client for reconciling locally echoed messages with the copy that later comes down from the server via the events system.

**Comment by borisyankov** [comment]
Closing as implemented.
