### ISSUE TITLE
Clicking on 'goToBottom' button while it overlaps an image fires WebLink intent

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2011]
![screenshot_20180305-065519](https://user-images.githubusercontent.com/24983958/36953663-7641ffc4-2042-11e8-8572-c1e2a048fae1.jpg)
Reproduction:

1. Get such a configuration where the go to bottom button overlaps an image
2. Click, and intent is fired.

**Comment by pulkonet** [comment]
It is apparently firing every time clicking that button. Can anyone else confirm this?

**Comment by xamfy** [comment]
Works fine for me

**Comment by pulkonet** [comment]
You're on Android or iOS? I've tested this on OnePlus 3T Oreo 8.0.0

**Comment by xamfy** [comment]
Yes Android, Moto g4 plus marshmallow

**Comment by xamfy** [comment]
Can you send a similar image again?

**Comment by pulkonet** [comment]
It is happening even without the image as I stated in the title. I'll send a link to a screencast as soon as I get back to my laptop.

**Comment by pulkonet** [comment]
https://drive.google.com/file/d/1w48DjmMykUA4uaqCruRsr5OXozetNmLW/view?usp=drivesdk
check this!

**Comment by xamfy** [comment]
Yes there is an issue
