### ISSUE TITLE
Use particular narrow corresponding to each ChatScreen.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2019]
Currently everywhere, only latest narrow (which is at the top of stack) is used to filter messages, caught up, fetching and for other purpose.

https://github.com/zulip/zulip-mobile/blob/94063c9fdac0d0bb2555a2315e869a63ab7783fc/src/baseSelectors.js#L23

When we are on screen which is not a chat screen (like profile, Lightbox etc), then narrow becomes home, affecting all the chat screens present in the stack.

If new narrow is pushed to the stack, it changes state, thus all chat screen (in the stack) will be re-rendered. Also all the fetching etc will take place as narrow is changed. But requirement is only for newly pushed screen/narrow, and others screens should be untouched.

Other issues which are related to this:

* This lots of rendering, fetching introduced pref issues. 
* Whenever you narrow from main screen or click on info button, typing events are send and drafts are deleting. (unnecessary events are fired.)
* While going back to main screen from narrowed (except home narrow), there a intermediate frame where home view is visible. This frame is only visible for few seconds.
* Same frame can be noticed on clicking info button.
* if there are no unread messages in current narrow, but some unread message are there in home narrow, then on going back to main screen from that narrow, unread notice is spotted for a seconds. 
* Change in message list scroll on going back from lightBox/user profile/stream details https://chat.zulip.org/#narrow/stream/48-mobile/subject/Image/near/525355

Solution
Limit narrow to that particular chatScreen/narrow. Don't consider it globally.

I have almost completed work on this.
@zulipbot claim

**Comment by borisyankov** [comment]
I also noticed this!
Good find. Super high priority!

**Comment by timabbott** [comment]
@gnprice @rishig FYI; I think that this might be the cause of the issue you folks mentioned with messages being marked as read when using the mobile app's back button.

**Comment by borisyankov** [comment]
@jainkuniya a potential issue to have a look at is that there is this weird time while the route transitions. Sometimes we want to treat the code as if the active route immediately changes, sometimes wait till the end of the transition. There is a Redux event that you can differentiate it.

**Comment by jainkuniya** [comment]
closing this as implemented in #2020 and got merged!
