### ISSUE TITLE
Fetching more messages causes scroll view to jump

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#202]
When new messages are fetched, scroll position should be maintained so that scrolling feels smooth.

This is broken right now (both on master and in the `cached` PR). The scroll position jumps to the top when new messages are fetched. Probably an issue with `AnchoredScrollView`

**Comment by timabbott** [comment]
We now have the app in testflight; this is probably the top issue in terms of UX right now.  

It may be a more complicated issue than just that; it seems to jolt multiple times when one scrolls to the top of the home view (possibly doing multiple fetches to the server?).

**Comment by neerajwahi** [comment]
I think the multiple jolts is because the initial scroll position jump causes the scroll view to cross the data fetch threshold and fetch even more data, causing another scroll position jump and another data fetch, ad infinitum..
