### ISSUE TITLE
Illegible Stream names on iOS

### ISSUE THREAD

**Issue by codebu5ter** [zulip/zulip-mobile#2048]
![img_5672](https://user-images.githubusercontent.com/16636569/37300760-cb254a18-264c-11e8-87cf-19f35f70d8e8.jpg)
As can be seen from the above photo, some of the stream names are illegible.
I should add, I'm only seeing this on the iOS app downloaded from the App Store. I'm unable to reproduce this on Android as the stream names have a black font which is clearly legible.
So, is this a platform specific issue?

**Comment by borisyankov** [comment]
It is not platform-specific exactly. The iOS app is a version behind. This will be fixed soon (in 1-2 days)

**Comment by codebu5ter** [comment]
Ah! I figured that might be the case, since the iOS app was updated over a month ago.

**Comment by pulkonet** [comment]
This can be closed IMO.

**Comment by jainkuniya** [comment]
@codebu5ter are you still facing this?

**Comment by borisyankov** [comment]
That has been fixed.
