### ISSUE TITLE
Keyboard not opening up in Welcome Screen

### ISSUE THREAD

**Issue by ayushmankd** [zulip/zulip-mobile#2058]
Whenever after I dismiss the keyboard (by using the back navigation button), I am not able to open up the keyboard (to edit the text input)

**Comment by jainkuniya** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
@jainkuniya I did fix this, but not pushed.

**Comment by jainkuniya** [comment]
Ok! Cool
