### ISSUE TITLE
Recipient rows not showing fully on TestFlight/iOS10.1/iPhone 6s.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#206]
Below you can see the tops of the recipient rows and a little bit of the cut off text but not much more than that. This was visible in the narrows that were public when I would scroll up and load more messages.

![Screenshot](https://cloud.githubusercontent.com/assets/10321399/21868421/8d93841a-d807-11e6-8b58-0cf3bbae7fb4.PNG)

**Comment by borisyankov** [comment]
I think this is fixed in:
https://github.com/zulip/zulip-mobile/pull/204

**Comment by borisyankov** [comment]
Fixed.
