### ISSUE TITLE
Missing icons in the settings menu

### ISSUE THREAD

**Issue by anurag1018** [zulip/zulip-mobile#2068]
It is specially important for the "Language" option to have an icon for the scenario if someone switches to an unfamiliar language. The icon (something like a globe or a flag) would be helpful to navigate back to the language picker. While we are at it, it would be a good idea in perspective of design and accessibility to add icons to the other options available in the settings menu.

**Comment by anirudhjain75** [comment]
@anurag1018 What icon do you think will be good for a language option ? @borisyankov do you think this is to be done ?

**Comment by pulkonet** [comment]
I think this is a good UX improvement. Any suggestions? @borisyankov  @jainkuniya

**Comment by jainkuniya** [comment]
Cool!
@anurag1018 Please post icons you are thinking of.
Also guys please try other app too, how they handle such cases.

**Comment by pulkonet** [comment]
![screenshot_20180321-004822__01](https://user-images.githubusercontent.com/24983958/37677672-b697f2de-2ca1-11e8-8370-c9820e801566.jpg)
These are icons from Slack.

**Comment by anurag1018** [comment]
The icons should make the function of the options obvious. Meeting with the design standards of the app material icons(https://material.io/icons/) might be suitable here. Here are the settings options and the name of the icons I found to be suitable:
Night Mode: brightness 4
Notifications: notifications
Language: language
Diagnostic: bug-report

**Comment by borisyankov** [comment]
We use [Feather Icons](https://feathericons.com/)
Looks like a decent idea.

**Comment by anurag1018** [comment]
The app also has some Material Icons.
```
export const IconSend = (props: Object) => <MaterialIcon name="send" {...props} />;
export const IconMute = (props: Object) => <MaterialIcon name="volume-off" {...props} />;
```
They seemed a better fit here to visually segregate the function of the menu from the bottom navigation bar.

**Comment by borisyankov** [comment]
We do use these material icons only because there are no appropriate Feather icons.
