### ISSUE TITLE
Make sure we do the right thing when clicking a link to a narrow

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2075]
Since https://github.com/zulip/zulip/commit/9ea7b05cfeeb9821bf4af393479268542df61315, the webapp will now generally generate a relative link of the form `/#narrow/stream/foo/topic/bar` if you paste a link to a stream/topic pair in Zulip.  Ideally, we should make the mobile app support clicking on those links taking you to that narrow in the app.

**Comment by borisyankov** [comment]
I added several tests and confirmed that we already handle the relative link form.
