### ISSUE TITLE
Crash on trying to edit topic in compose

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2077]
This crash is happening frequently right now, to lots and lots of users -- nearly half our total crashes on Android. (Together with #2076 , these two are >90% of our crashes on Android. So fixing these two will make a big difference!)

For this one, a good handful of users have kindly reported details. Here's one such report... I'm copying from the Play Console, but actually I wrote this one myself, when I hit it this morning.
> The app crashed when I was in a stream view; tapped compose; then tapped the topic box, because I wanted to send to a different topic. Crashed exactly the same way when I reopened and retried.

I think @borisyankov may have said recently this was fixed. We should get a release out with the fix; that would save a ton of our users from some frustrating crashes.

**Comment by aswinmohanme** [comment]
I can confirm this too. 

Steps to Reproduce:
* Goto any Stream
* Compose a Message
* Select the Topic 
* Kaboom Everything goes south (A.K.A Crash)

**Comment by borisyankov** [comment]
I confirm this as fixed. The release including the fix is already pushed to Production.
