### ISSUE TITLE
App Crashing when pressing Enter without any organisation url

### ISSUE THREAD

**Issue by ayushmankd** [zulip/zulip-mobile#2095]
Whenever I press Enter without Entering any organisation url the app is crashing,
It needs to say something like no URL in toast

**Comment by codebu5ter** [comment]
I'd like to work on this.

**Comment by HarshulSharma000** [comment]
I would also like to work on this..

**Comment by borisyankov** [comment]
What version of the app? What platform?

**Comment by codebu5ter** [comment]
@borisyankov This crash is even happening on the dev version of the Android app.

**Comment by ayushmankd** [comment]
@borisyankov 
It's happening in the updated release app that I downloaded from the playstore.
