### ISSUE TITLE
When narrowing to a private message thread from the "unreads" view, positioning wrong

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2106]
Last night on the latest app, I got placed ~20 messages above the 1 new message from someone when narrowing to view their messages.  

(I also saw this with 1 random other topic, so the issue might not be constrained to private messages).  

We need to figure out an automated testing system or something for this layer of the app - we should be able to get narrow positioning right 100% of the time without doing anything crazy.

**Comment by borisyankov** [comment]
Sometimes there is a difference between narrowing to a narrow and having to fetch new messages, or trying to update existing ones plus position.

I'll have a look at this, will fix and do a quick release tomorrow.

**Comment by borisyankov** [comment]
Closing as fixed.
