### ISSUE TITLE
App crashes when responding to private message

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#211]
Tested on physical device.

App crashed when I hit send after composing a message to a private narrow (with one recipient).

**Comment by borisyankov** [comment]
Hmm, can not reproduce on an emulator. Will test on a physical device too.

**Comment by borisyankov** [comment]
It worked for me on a device too.

**Comment by neerajwahi** [comment]
@borisyankov it doesn't work for me though, so let's leave the issue open until I investigate

**Comment by neerajwahi** [comment]
I think this is fixed
