### ISSUE TITLE
Upvoting an emoji reaction appears to be broken on Android

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2116]
May also be on iOS, but I tried adding my vote to an emoji reaction today, and nothing happened.

I'm guessing this is a fairly shallow bug since this used to work, but who knows?

**Comment by jainkuniya** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
WFM now. I think we fixed this a long time ago and just didn't close this issue.
