### ISSUE TITLE
Image preview doesn't exit on clicking back button (physical)

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2127]
Once you open image preview, it doesn't exit on clicking the back button. Although the there is a button specifically for exiting the preview but the default behaviour of the back button must also serve the same function. Also, clicking the physical back button twice (not in quick succession) exits the app.

**Comment by jainkuniya** [comment]
mostly  same as #2098

**Comment by pulkonet** [comment]
Yes, but my focus is not on pressing it twice, but it is on exiting the app on clicking twice.

**Comment by jainkuniya** [comment]
ya! got it.
Will take of it 👍 


@zulipbot claim
