### ISSUE TITLE
Realm emoji reactions showing as "undefined"

### ISSUE THREAD

**Issue by yorickvP** [zulip/zulip-mobile#2129]
I'm running on v11.8.79 (android 7.1.1). This should have #1698 merged, right?.
My realm emoji's aren't showing in the app. What's going on?
![screenshot](https://pub.yori.cc/zulip-app-emoji.png)

**Comment by jainkuniya** [comment]
I am working on #2116, also #1698 is implemented by me.
And most likely fix of this &  #2116 will be same :)
Will be fixed soon. Thanks for the report.

@zulipbot claim

**Comment by pulkonet** [comment]
Related to #1744

**Comment by gnprice** [comment]
An update: this bug is at least a bit milder now, in that instead of "undefined" the emoji comes out just missing; there's a box there for the reaction, and it has the count but not the actual emoji.

I've filed #2846 with a description of the underlying problem.
