### ISSUE TITLE
Android: tapping a notification does not take me to the message that caused it

### ISSUE THREAD

**Issue by mkaito** [zulip/zulip-mobile#2137]
As the title says, I get a notification for a new message. I tap it, expecting to be taken to read the same message along with relevant context. Instead, the app opens wherever it was when I last used it.

**Comment by gnprice** [comment]
Thanks @mkaito for bringing this up! I definitely agree this is an essential feature and we need to get it working.

We have an existing issue #1789 describing the need for this, so I'm closing this one in favor of further discussion there.
