### ISSUE TITLE
Per-realm notification settings (formerly "Fine grained notification settings")

### ISSUE THREAD

**Issue by mkaito** [zulip/zulip-mobile#2138]
At the highest level, per-ream notification settings seem like they would be pretty useful.

In a more specific use-case, per-stream or even per-topic settings would be nice. Specifically, we're looking to use Zulip as part of our alerting system for the devops team, and being able to "mute everything except this stream/topic" would help.

**Comment by anirudhjain75** [comment]
Yes it will be a good improvement, @borisyankov Should I start working on this ?

**Comment by anirudhjain75** [comment]
Though I don't think per topic notification would be good, but per stream would be nice

**Comment by pulkonet** [comment]
This feature can be given to a user as an option to choose from. This would be pretty sweet if implemented correctly. I would like to work on it, but I don't think this is anywhere on the priority list.

**Comment by chrisbobbe** [comment]
I don't have an update on per-realm notification settings, but there's been some work on stream-level notification settings.

When https://github.com/zulip/zulip-mobile/issues/3449 was closed with the merge of https://github.com/zulip/zulip-mobile/pull/3765 (commit https://github.com/zulip/zulip-mobile/commit/3b9246735d0f68b3bb14426fc4c73637ade5ed63), now, stream notifications without an explicit setting will default to the user's general push notification setting. So you could "mute everything except this stream" by setting your user-level setting to off, and explicitly marking one stream as on. Hope this helps. 🙂

**Comment by chrisbobbe** [comment]
Ah, actually, looking at the code and with some manual testing, it appears that "Notifications when offline" and "Notifications when online" are being correctly set per-realm, but "Stream notifications" are not. That'll be a quick PR that, I think, should close this issue. @gnprice, thoughts?

```diff
export default (state: SettingsState = initialState, action: Action): SettingsState => {
  switch (action.type) {
    case REALM_INIT:
      return {
        ...state,
        offlineNotification: action.data.enable_offline_push_notifications,
        onlineNotification: action.data.enable_online_push_notifications,
+        streamNotification: action.data.enable_stream_push_notifications,
      };
```

**Comment by chrisbobbe** [comment]
Opened as PR https://github.com/zulip/zulip-mobile/pull/3926.

About topic-specific notification controls, it's currently possible to mute topics in both web and mobile, but I do see from https://github.com/zulip/zulip/issues/6027 that the ability to "watch" topics, not just mute them, would be popular. I'll close this issue for now, as it's pretty old and I think I've answered its concerns. (I'll reopen if not.) But if/when https://github.com/zulip/zulip/issues/6027 is accomplished, let's plan to open a new, corresponding issue for mobile with an implementation plan at the top.
