### ISSUE TITLE
Android: erratic scrolling

### ISSUE THREAD

**Issue by mkaito** [zulip/zulip-mobile#2139]
I've found that scroll behaves erratically:

* When a new message arrives, it will either not scroll into view, or it will scroll past it (2-3 pages upwards).
* Sometimes it will scroll up when no new messages arrive too.
* Tap the scroll-to-bottom button, which does as advertised, and closes the keyboard. Tap the text entry to get keyboard back, and scroll goes back up 2-3 pages.

**Comment by armaanahluwalia** [comment]
I've noticed that scrolling **upwards** on the All Messages stream causes the stream topics bar to disappear. This happens consistently on iOS app V 10.1.70

**Comment by borisyankov** [comment]
The original issue is now fixed. Closing.
