### ISSUE TITLE
Handle out of memory cases.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2142]
<img width="410" alt="screen shot 2018-03-27 at 12 56 04 am" src="https://user-images.githubusercontent.com/18511177/37928491-9f723502-315a-11e8-9131-0365e8e4fbca.png">

Not a priority but we definitely need to take care of this in future.

**Comment by borisyankov** [comment]
When does that happen?

**Comment by jainkuniya** [comment]
I don't find any specific steps to reproduce. But whenever it does at that time device is hanging (very less free RAM is available). So it might be in the optimising memory utilization project in future.

**Comment by borisyankov** [comment]
Does that happen on start? Running on a real device?
Do you think our app is causing the out of memory issue or is it just the device running out of memory?

**Comment by jainkuniya** [comment]
> Does that happen on start?

No it's in the middle of the playing with app.

> Running on a real device?

No real device, it just crashes when such error occurs. I got this error on emulator.

> Do you think our app is causing the out of memory issue or is it just the device running out of memory?

Device running out of memory. Till now we haven't much in optimising memory. It's not a priority, occurs very very rare. But in long future this might be good project to consider.

**Comment by gnprice** [comment]
Interesting, thanks for the report!

That allocation is >3MB -- it's a pretty sizable amount of memory it's trying to allocate right there. I suspect we're just consuming a ton of memory in total.

In general, handling out-of-memory situations is tough, and requires a lot of discipline in the code; I'm not sure it's even possible in an RN app. In any case we're not realistically going to be up to it for a very long time. When we run out of memory, we'll just crash. So, I'm going to close this issue as WONTFIX.

What we can do is not use so much memory. :-) If you spot a specific pattern where we're using too much memory, let's file an issue specifically for that and we can squash that.

There's also a potential future project to profile our memory use in general and squeeze it down. But that's (a) open-ended and (b) not a priority right now, so I don't think an issue is a useful place to record it.
