### ISSUE TITLE
Support copying just a link URL, rather than whole message text

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2249]
At the moment if we long press a link and then select copy to clipboard from the actionsheet the whole message containing the link gets copied to the clipboard which IMO isn't a desirable behavior. This can be fixed by only copying the link to the clipboard.

**Comment by borisyankov** [comment]
Good catch. If you want, you can work on this!

**Comment by pulkonet** [comment]
@zulipbot  claim

**Comment by pulkonet** [comment]
@gnprice I followed the style used in Slack, they just copy the link to clipboard `onLongPress`. This is particularly better than showing an action sheet because the action sheet would only show actions like `Copy Link To Clipboard`, ` Open Link` and `Cancel`. These actions will be redundant if shown on an action sheet as the user can perform the same task in one step.

**Comment by pulkonet** [comment]
@gnprice @borisyankov #3385 is almost a dupe of this. If we can fix it this way we won't have to populate two different action sheets. I can continue with #2278 or submit a fresh PR which will add features to handle both `short` and `long` presses for `images`, `links` and also normal messages.

**Comment by gnprice** [comment]
@pulkonet Ah indeed, thanks for flagging that!

I agree, this and #3385 seem to be descriptions of the same issue. I'll consolidate.

@ishammahajan is actively working on #3385 now, in #3404 . So let's hold off on any parallel work until that's done.

**Comment by ishammahajan** [comment]
Bump. This should be closed.
