### ISSUE TITLE
feature request: See who reacted with an emoji.

### ISSUE THREAD

**Issue by rishig** [zulip/zulip-mobile#2252]
Slack's implementation (long press the emoji) seems reasonable here?

**Comment by jainkuniya** [comment]
I thinks we had a open issue for this one (no matter, can't find it right now)
FB messenger also handle this nicely.

@zulipbot claim

**Comment by borisyankov** [comment]
I am adding it to 'Next' as it has already been requested several times, seems important enough.

**Comment by pulkonet** [comment]
Requested as a part in #1555

**Comment by jmandel** [comment]
just adding a perspective that having this functionality would be really useful! Our FHIR community group often uses emoji responses to coordinate things like... who is coming to dinner at a conference. Really helps to be able to check on that list when we're waiting for folks to arrive in the hotel lobby and trying to decide when we have quorum to walk to a restaurant. It has been surprisingly frustrating  not to be able to answer this question on mobile (native or web).

**Comment by gnprice** [comment]
Thanks @jmandel for that extra detail! Definitely helps for making concrete why this will be a valuable feature.

**Comment by gnprice** [comment]
With #3110, this is now implemented! :tada: It'll be in the next release.

(Well, I'm about to promote 26.16.139 from beta, where it hung out for a while due to the Thanksgiving holiday; but this feature will be in the next new release from master.)

**Comment by jainkuniya** [comment]
Excited to see it in the release 😍

**Comment by gnprice** [comment]
@jmandel @Vamshi99 and everyone: 26.17.140 is now out, with this feature!

It's available now on Android; on iOS it's out in beta, and is in Apple's review queue for the App Store.

**Comment by jmandel** [comment]
Just tried it out on Android and it works beautifully :-) Thanks so much.

**Comment by Vamshi99** [comment]
@gnprice Looks good. But some emojis don't show up correctly in the reacted people screen, they are just seen as a question mark for me.
https://imgur.com/a/vGWMtXM

**Comment by jainkuniya** [comment]
On which device are you?

**Comment by Vamshi99** [comment]
@jainkuniya Redmi Note 5 pro, Android 9

**Comment by gnprice** [comment]
Thanks @Vamshi99 for that report! I've gone and filed #3716 to continue the discussion.
