### ISSUE TITLE
Offer "declare bankruptcy" option if you're super far behind current

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#227]
See https://github.com/zulip/zulip-android/issues/326 for some details on how this should work.

**Comment by vishwesh3** [comment]
Now we have **Mark stream as read**,   **Mark topic as read**,  **Mark all as read**.
But I thinks scroll position is remaining (after marking move to latest message)
So can we close this and open another issue or edit this one?

**Comment by borisyankov** [comment]
We will also have more 'mark as read' options with the improved upcoming unread messages card UI.
Closing this.
