### ISSUE TITLE
iOS and Android apps don't show images

### ISSUE THREAD

**Issue by ababak** [zulip/zulip-mobile#2274]
They show empty square placeholders and when inspecting copied image URL, I see the local path: /user_uploads/3632/66mPvbb7lbAy6HOFSySSgXIB/image.png

In the web client, everything appears correctly.

We use Zulip Cloud if this matters.

**Comment by anirudhjain75** [comment]
@zulipbot claim

**Comment by anirudhjain75** [comment]
I guess changing the fileURI from **/user_uploads/3632/66mPvbb7lbAy6HOFSySSgXIB/image.png** to  **https://orgname.zulipchat.com/user_uploads/3632/66mPvbb7lbAy6HOFSySSgXIB/image.png** will do the trick

**Comment by pulkonet** [comment]
How come your phones aren't displaying the images? I couldn't reproduce this. Nor I could reproduce the other issue which was opened in the same context.

**Comment by timabbott** [comment]
@pulkonet this is an issue with the more advanced file storage backends that do auth, used by just about every server other than chat.zulip.org.  You can signup for a test organization on zulipchat.com to reproduce.

**Comment by pulkonet** [comment]
Thanks @timabbott Reproduced successfully!

**Comment by pulkonet** [comment]
I guess @anirudhjain75 your solution would work!

**Comment by ababak** [comment]
Will it work for self-hosted servers as well?

**Comment by HarshulSharma000** [comment]
@anirudhjain75 @ababak @pulkonet @timabbott A possible duplicate of #2281 #2126

**Comment by HarshulSharma000** [comment]
@ababak @pulkonet @anirudhjain75 I tried to apply the solution and many other possible patches but none of them works right now.

**Comment by borisyankov** [comment]
Closing as fixed.

**Comment by borisyankov** [comment]
You are right. The fix we implemented only refers to the messages in the message list.
On some servers the zoomed-in view does not yet show them. We will be working on this next.
