### ISSUE TITLE
Posting a private message to a new person doesn't show anything on my side

### ISSUE THREAD

**Issue by ababak** [zulip/zulip-mobile#2277]
It sends the message (I see the person receives it on another phone) but I can't see anything on my side. Besides, when I received a reply I couldn't see it either, only in the notification. It looked pretty weird. After some time (10 minutes maybe), some messages appeared in the phone app but not all. The person I am chatting with still not get listed in the people tab.

The web client works fine and in a predicatble manner.

**Comment by borisyankov** [comment]
@ababak Thank you for reporting this.
I reproduced this. This happens when talking to a user you've never talked to before.
Short-term, restarting the app will fix that.
A proper fix will come in the next day or two. I'll ping you here when we release the app.

**Comment by borisyankov** [comment]
I confirm the original issue has been fixed.
