### ISSUE TITLE
Clicking on narrow doesn't maintain position in stream

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#228]
Clicking on a narrow results in the stream jumping to the latest narrow in the message.

The intended behavior (consistent with the web app) is to jump to the message whose header was clicked.

**Comment by borisyankov** [comment]
@neerajwahi Have you started on this, or can I do it?

**Comment by neerajwahi** [comment]
You can do it. I left comments on some open PRs though so best if you could address those first
