### ISSUE TITLE
Messages not viewing correctly when dynamic content is present in streams.

### ISSUE THREAD

**Issue by HarshulSharma000** [zulip/zulip-mobile#2282]
**Description**-
There is a little difference between streams that have images in them and the ones that don't . To be more specific:-
**Streams with no images and having only static dom elements** - These streams(Webviews actually) are simple to render and know exactly what and how to render. As a result they render the messages view in webview correctly(as per my observation, which could be limited).
**Streams with images and having dynamic dom elements**(like images here) - These streams don't possible know exactly about the width and heights of the components that are loaded since they are loaded while rendering. As I result I did observe a little resizing in those image components while opening the chat screen. It could be the case because in web also we do face a little repaints happening because of loading of such dynamic content and as a preventive measure we wrap such dynamic content with fixed size divs so that a lot of such repaints and resizing does not occur or even if it occurs it does not affect other nodes.

**Issue Gif**-

![20180410_204027](https://user-images.githubusercontent.com/25546227/38640649-7b945620-3df2-11e8-9c29-4131d2d48a3f.gif)

**Comment by borisyankov** [comment]
Confirm if fixed by #2279

**Comment by HarshulSharma000** [comment]
@borisyankov Yes the resizing due to images seems to be resolved. But I think we should also check if any other dynamic component requires fix.

**Comment by pulkonet** [comment]
What are the other dynamic contents that popup in your mind? I can't think of anything but images.

**Comment by borisyankov** [comment]
Closing as confirmed fixed.
