### ISSUE TITLE
Create new stream is broken 

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2288]
Can't create a new stream. Even in the dummy org used for testing. Also, the button has the label update which is not the best word to be used here. `Create` is a better label IMO
![screenshot_20180412-174721](https://user-images.githubusercontent.com/24983958/38676733-94c76d76-3e79-11e8-95a9-e39b430263c8.png)

**Comment by HarshulSharma000** [comment]
@pulkonet Yes I did face this issue also could be related to the issues that Lyla Fischer was mentioning. And we do have many issues related to messages not syncing etc.

**Comment by jainkuniya** [comment]
Thanks for the report. :)

@zulipbot claim
