### ISSUE TITLE
Options to add ourselves to a group chat must not be there

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2289]
Currently while starting a group chat, we get an option to add ourselves. This isn't desirable. This is also not followed by any other group chat platform like slack, or even in WhatsApp groups.
![screenshot_20180412-175037](https://user-images.githubusercontent.com/24983958/38676940-44b512c4-3e7a-11e8-9414-5a7a6d0bba46.png)

**Comment by borisyankov** [comment]
I agree, great find!

**Comment by pulkonet** [comment]
@zulipbot claim
