### ISSUE TITLE
Sending very first messages to a new group chat is broken

### ISSUE THREAD

**Issue by pulkonet** [zulip/zulip-mobile#2296]
The messages sent to a new group chat disappear as soon as sent. This happens only until you go back once and come back. The chat performs normally after that.

Steps of Reproduction:
- Create a new group
- Send a couple of messages

Tested on Android 8.0.0 on OnePlus 3T

**Comment by borisyankov** [comment]
Hmmm, I know what is going on!

**Comment by borisyankov** [comment]
Even better, this is related to a bug I was trying to reproduce 😄
