### ISSUE TITLE
Use pointer from server on initial fetch

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#230]
We are jumping to the latest message on the server when the app is loaded (by passing in `Number.MAX_SAFE_INTEGER` as the pointer when fetching messages).

The intended behavior (consistent with the web app) is to place the user where he or she left off in the stream (by using the pointer return from the register events API call).

**Comment by timabbott** [comment]
http://zulip.readthedocs.io/en/latest/pointer.html documents the correct behavior here.

**Comment by timabbott** [comment]
Yeah this one should be M5.
