### ISSUE TITLE
Messages sent to self have incorrect header

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#231]
For example, if a user sends a message to him or herself, the header in the stream view is blank (instead of displaying the user's name)

**Comment by vishwesh3** [comment]
Can I work on this?

**Comment by borisyankov** [comment]
Should a user even be able to send a message to himself?

**Comment by neerajwahi** [comment]
I think so. Could be useful for notes and testing. In any case, the server
and web app support it so we should as well

**Comment by timabbott** [comment]
Yes, we definitely support this.  Slack supports it as well for the same reasons -- it's super nice for testing out how the features work without bothering anyone.

**Comment by borisyankov** [comment]
I'll work on it, because we are missing to put in in the store correctly. Didn't think of that case.
