### ISSUE TITLE
Navigation to Streams from links in messages

### ISSUE THREAD

**Issue by gokcan** [zulip/zulip-mobile#2312]
Related to [**this**](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Navigating.20Streams) discussion.

- Try to click inAppUrl # links (e.g. #mobile, #general) in messages.
- It does not navigate to the related stream.

The root cause is related to the stream name extraction logic from url.

**Comment by gokcan** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Keep in mind we need to support both the new and the old format.
In the new format we want to take just the ID and disregard the topic name.

**Comment by gnprice** [comment]
GitHub unfortunately clutters up this thread with tons of references to the commit that mentions it, making it hard to read. Filed a fresh version as #2760 .
