### ISSUE TITLE
Avatars not always shown in header on private chat narrows

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#235]
An avatar image for users is not always displayed in the navigation header in a private chat narrow.

If the private narrow is a 2 person chat, only the other participant's name is displayed in the navigation header.

If the private narrow is a 3+ person chat, some avatars are not displayed in the navigation header and there is otherwise no indication (in the navigation header) that those people are in the chat.

**Comment by borisyankov** [comment]
This I think is fixed in some of the PRs.

**Comment by borisyankov** [comment]
This is fixed in https://github.com/zulip/zulip-mobile/pull/222
Lets get it merged?

**Comment by neerajwahi** [comment]
My concern is that the PR adds new features (and it's quite a big PR). The reason I'm wary of adding features right now is that greater surface area usually means more bugs and we've already got our hands full for M5

**Comment by neerajwahi** [comment]
I'm going to go through and do a detailed review of all the big open PRs anyway and we can decide what to do from there. I won't get to it tonight though :/

**Comment by borisyankov** [comment]
I think all three #160 #200 #222 are relatively self contained and I work rather well, so I think it is good to merge this weekend.
