### ISSUE TITLE
Improve message caching logic

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#236]
The current message caching logic stores messages in a `messages` dictionary keyed by a narrow object.

A better approach is to store all messages in an array (merging new messages in as fetched) and filter the array when the stream is in a narrowed view. This approach ensures that all messages that are fetched in the Home view are immediately available for narrowed views, and avoids duplication of messages.

**Comment by borisyankov** [comment]
`This approach ensures that all messages that are fetched in the Home view are immediately available for narrowed views`

What do you mean? They are also available with the current implementation?

**Comment by neerajwahi** [comment]
Right now each narrow has its own list of messages: https://github.com/zulip/zulip-mobile/blob/a415373bf85794bfe3226bf1ddd0c64aa90bb5e1/src/chat/chatReducers.js#L37

So there is no cache the first time a narrow is loaded, even if a lot of messages that would have been shown in that narrow were loaded in the home view, for example.

**Comment by borisyankov** [comment]
Since we decided to not load 1000 messages at the start, that strategy is much less effective with 50 or 100 messages (which were the last proposed).

**Comment by neerajwahi** [comment]
We could always fetch 50 messages upfront to display a stream quickly and then fetch more in the background to fill in the message cache. Having one list of messages significantly simplifies things in my opinion.

Fetching a list of recent private messages recipients seems to be a bit of a special case anyway. Maybe worth adding an endpoint specifically for this @timabbott ?

**Comment by borisyankov** [comment]
We should discuss that on video IMHO.

**Comment by timabbott** [comment]
We can add such an endpoint; we already have something similar for fetching a full list of topics in a stream.

**Comment by neerajwahi** [comment]
@borisyankov assuming we add such an endpoint do you still have objections with this approach?

**Comment by borisyankov** [comment]
Yes. First, the memory savings are minimal, just the references are duplicated, meaning for 1000 messages you get a savings of 8kb memory.

Again, the current implementation is how it is cached in the main Zulip app and also in Slack...

Here is a scenario:
1. Get first 20 Home messages.
2. Switch to '#hello' stream. Get 20 messages.
3. Now go back to Home.

At this point your messagesList has 20 Home messages and 20 '#hello' stream messages. These are not the 40 most recent messages.

Having a single list of messages is completely inadequate way to implement caching.
