### ISSUE TITLE
[Android] Multiple file selection when uploading pictures.

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#2366]
Right now when I try to upload a picture from within the app it will let me choose 1 picture and will instantly upload it when selected. This makes it really annoying to upload multiple pictures, since you have to do it one by one and can't add comments with the pictures like you could do with the old app.

Maybe use Android's ability to let you use other apps (like gallery apps nearly all of which implement this functionality) as file pickers? In example from Firefox for Android when trying to upload you get this menu:
![screenshot-file-picker](https://user-images.githubusercontent.com/917126/39051299-ec2e1c08-44b0-11e8-9f57-2a0d78f7b011.jpg)

**Comment by AB261** [comment]
@zulipbot claim

**Comment by AB261** [comment]
@gnprice @jainkuniya Should I work on this? How should I start with this? Any info I need to know beforehand?

**Comment by jainkuniya** [comment]
hey @AB261 I guess there is already a PR for this https://github.com/zulip/zulip-mobile/pull/2887

**Comment by chrisbobbe** [comment]
We've had another report of this: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292530
