### ISSUE TITLE
Better 'loading messages' indicator

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#237]
When loading a new narrow use the current '5 loading messages' visual.
When loading messages from top or bottom, show an ActivityIndicator on top or bottom respectively.

**Comment by neerajwahi** [comment]
I experimented with using the black Zulip loading indicator from the web app. It works pretty well. Will open a PR

**Comment by borisyankov** [comment]
What did you use to load the svg? Or did you use the Logo component?

**Comment by neerajwahi** [comment]
I created a new `Loading` component. I rendered the SVG to PNG and used the Animation API
