### ISSUE TITLE
Prefetch new messages before reaching the end of the list

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#238]
Start fetching new messages before having reached the top or the bottom of the list. 
As long as done at the correct time, the messages should load before the user sees a loading indicator.

**Comment by TomaszKolek** [comment]
@borisyankov 
Am I right that we should increase `DEFAULT_START_REACHED_THRESHOLD`/`DEFAULT_END_REACHED_THRESHOLD` in `src/message-list/InfiniteScrollView`?

**Comment by neerajwahi** [comment]
We already fetch the messages before reaching the top or bottom. We just need to increase the thresholds to tune the performance.

@TomaszKolek that's exactly right.

**Comment by TomaszKolek** [comment]
@zulipbot claim
