### ISSUE TITLE
Cannot select chatacter when typing

### ISSUE THREAD

**Issue by dingo9** [zulip/zulip-mobile#2416]
I cannot select character when I try to type chinese when i use zulip（10.1.70） in ios（11.3）

**Comment by dingo9** [comment]
![now_gif](https://user-images.githubusercontent.com/3961786/39402723-3c107fb4-4b9a-11e8-9863-b8e1a54cab36.gif)
As the Image, when I want type some chinese character, key board do not pop some candidate to be selected...

**Comment by borisyankov** [comment]
This looks like the normal behavior of the phone's keyboard.

**Comment by gnprice** [comment]
(FTR this was indeed a bug, fixed later in 2018; details at #2434.)
