### ISSUE TITLE
notifications: Don't include quoted content.

### ISSUE THREAD

**Issue by rishig** [zulip/zulip-mobile#2419]
Currently the quoted material in a message appears alongside what the author of the message wrote (in the mobile notification), which is confusing. We should just not include quoted material in the notification.

**Comment by timabbott** [comment]
Opened https://github.com/zulip/zulip/issues/9251 for this issue, since this piece of push notification formatting is not under the control of the app.

**Comment by timabbott** [comment]
We fixed https://github.com/zulip/zulip/issues/9251, which I'll deploy to chat.zulip.org shortly.  We should make sure that the result actually looks good on the device (whether it does sorta depends on whether newlines get displayed properly).
