### ISSUE TITLE
Change navigation bar color when narrowed to a stream

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#245]
Each stream has a color associated with it. It'd be nice to change the background color of the navigation bar to match that color when narrowed.

(This isn't quite bite-sized, but I think this is a nice starter project for anyone interested in contributing)

**Comment by borisyankov** [comment]
Also, text size needs to be changed accordingly.
Can be black or white, depending on contrast.
Code already exist in codebase.

**Comment by vishwesh3** [comment]
Can I work on this?

**Comment by borisyankov** [comment]
Yes, it is free for grabs. ;)

**Comment by borisyankov** [comment]
Just make sure to reuse the color code already there.
The function I mentioned is `foregroundColorFromBackground`.

**Comment by vishwesh3** [comment]
ok :)
