### ISSUE TITLE
Messages go over sticky headers

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#246]
This is likely related to latest fork and changes to ScrollView

Some messages, go over the sticky headers when scrolling up.

![image](https://cloud.githubusercontent.com/assets/867242/22367382/f0d4a912-e489-11e6-86b3-be3076374b80.png)

**Comment by borisyankov** [comment]
@neerajwahi probably you should look into it.

**Comment by neerajwahi** [comment]
@borisyankov Trying deleting `node_modules`, running `yarn cache clean` and then `yarn install`

**Comment by neerajwahi** [comment]
Let me know if that worked. If not I'll investigate

**Comment by borisyankov** [comment]
Yeah. That might have fixed it.
If it reappears I'll reopen.
