### ISSUE TITLE
Messages are not marked as read in some topic narrow.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2475]
For some unread topics, the messages were not marked read after scrolling through the list... This didn't occur for all topics consistently
screencast: https://drive.google.com/open?id=1hivF-AcBCHMhadjUeJdqpWjlCt8DEOFc
app version : 13.2.86
platform: iOS 11.2.6

https://chat.zulip.org/#narrow/stream/48-mobile/topic/unread.20topic.20messages

@zulipbot claim

**Comment by borisyankov** [comment]
@jainkuniya I have a fix for that.
