### ISSUE TITLE
Visual jerkiness/rerendering of the message view after sending a message

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2483]
More than half the time, if I send a message to a topic narrow I'm caught up on, the mobile app has the following sequence:
* I hit send, we hide compose, and the message appears (with a loading indicator in the timestamp slot)
* The message finishes sending, and the loading indicator disappears
* We get the message from the server, and it does a jerky, very visual rerender, that seems to bounce the screen up and down a bit.

**Comment by borisyankov** [comment]
Yeah, I've noticed that for sure. It might be unavoidable in some cases (a difference between client and server rendering), but I think in the majority of cases it should be avoidable.

I think now that the loading and positioning issues are mostly resolved, this is important enough to tackle next?

**Comment by timabbott** [comment]
Yeah, I think there's two things we can do with this:
* You can just compare the content between client and server and only do a rerender if they're different; that's 90% of what we do in the webapp
* We could get smarter about the way we execute the rerendering, to avoid having the scroll position bounce around.  The Zulip webapp certainly does this every time something is edited without a visual glitch, and since it's a webview in mobile see any reason we should have a problem doing that on mobile.

**Comment by borisyankov** [comment]
@timabbott this is our 'outbox' feature where we render the message when you send it vs the message got from the server. I think the spinner might also be changing the widths. Might not be too complicated to fix.

**Comment by timabbott** [comment]
Yeah, we do the exact same thing in the webapp (it's called "local echo" there; tons of code in `echo.js` for it).
