### ISSUE TITLE
Log in with username (LDAP) not possible

### ISSUE THREAD

**Issue by stiobhan** [zulip/zulip-mobile#2488]
With version 13.2.86 on Android

**Actual Behaviour**

I start the app and enter our organization's URL, then I see two buttons labeled "Log in with password". If I select the first one, a dialog shows up to enter email and password. If I press the second one a dialog shows up to enter username and password. In *both* dialogs the Log in button is greyed out until I enter a password and something that looks like an email address. 

**Expected Behaviour**

One button should be labeled "Log in with email and password", the second one "Log in with username and password", or shorter "Log in with email" and "Log in with username". Then if selecting to log in with username the Log in button should be enabled if a password and valid username is entered. At the moment the Log in button is only activated if something that looks like an email address is entered in the username field, hence log in with username that is not an email address is not possible.

**Comment by borisyankov** [comment]
Thanks for the detailed bug report.
I'll work on this next and this will be fixed soon.
