### ISSUE TITLE
Update Android target API level to 26

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2494]
Google Play now gives me the following warning when I upload a new release for Android:

> Target API level requirements from August 2018
> Warning:
> Your app currently targets API level 22 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.
>
> From August 2018, new apps must target at least Android 8.0 (API level 26).
> From November 2018, app updates must target Android 8.0 (API level 26).

So we have a deadline of November -- but this is a bit of housekeeping it'd be good to do anytime. Updating means we'll adapt our app to use certain new APIs when on newer Android versions, in order to make friendlier use of system-level resources like permissions, notifications, and background execution. (This won't affect our ability to keep running on older versions.)

Detailed documentation here:
https://developer.android.com/distribute/best-practices/develop/target-sdk

The steps I'd follow to do this are
* Go one version at a time, following that doc: level 23, then 24, then 26. (25 was a minor version.)
* For each version, try bumping `targetSdkVersion` in `android/app/build.gradle`. Build the app and test manually, especially the areas called out in the upgrade docs.
* Make any needed updates, following the docs.

A good PR to begin with would be an update to level 23, including any needed changes. For that one, we will need to make sure we request needed permissions at runtime. It's possible our dependencies take care of this; we'll need to check.

**Comment by SouvikBan** [comment]
Hi! I am a newbie and I would like to work on this.

**Comment by gnprice** [comment]
This will come along as part of upgrading to RN v0.56 (#2789).

**Comment by mafuz** [comment]
does it mean existing app bellow target 26 will be band?

**Comment by borisyankov** [comment]
Targeting a higher API version simply means that we can take advantage of new stuff offered in it.
We do not have any immediate plans to reduce the Android versions we support (currently 4.4 and newer)

**Comment by gnprice** [comment]
Tracking this in detail at #3075 ; closing this issue in favor of that one.
