### ISSUE TITLE
Double-sending bug in mobile app

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#2502]
We seem to have a double-sending bug in the mobile app that I've seen a few times recently.  Here's a case where it happened to me:

https://chat.zulip.org/#narrow/stream/31-production-help/subject/Git.20upgrade.20fails.20at.20yarn.20install/near/578549

Fundamentally, this seems like the kind of thing that happens when you have buggy "error retry" logic that retries even for some non-error cases, so we should give that code a quick read.

**Comment by borisyankov** [comment]
I am bundling this with the 'sending visual jerkiness' and 'sending code refactoring' and will work on this next.

**Comment by borisyankov** [comment]
Closing this issue in favor of the duplicate #2374
Will be working on this next.
