### ISSUE TITLE
"SyntaxError: Unexpected identifier" in webview

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2505]
https://sentry.io/zulip/zulip-mobile/issues/554709208/

```
Error: {"message":"Uncaught SyntaxError: Unexpected identifier","source":"https://chat.zulip.org/","line":1,"column":212137,"error":{}}
    at src/webview/webViewEventHandlers.toUpperCase(webViewEventHandlers.js:172)
    logErrorRemotely(new Error(JSON.stringify(event.details)), 'WebView Exception');
    at src/webview/MessageListWeb.this(MessageListWeb.js:40)
    const handler = `handle${eventData.type.charAt(0).toUpperCase()}${eventData.type.slice(1)}`;
...
(13 additional frame(s) were not displayed)
```

**Comment by gnprice** [comment]
More details in #2640 from @adambirds, who ran into an instance of this issue.

**Comment by Felixeltoro** [comment]
VM1790:1 Uncaught SyntaxError: Unexpected identifier

**Comment by gnprice** [comment]
> VM1790:1 Uncaught SyntaxError: Unexpected identifier

@Felixeltoro Is that a description of an error you're seeing? If so we'd be very interested to hear more details -- please file a new issue for it:
https://github.com/zulip/zulip-mobile/issues/new
