### ISSUE TITLE
Trigger refetch on app state change

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#251]
If the user puts the app in the background, they may miss messages until they return to the app. In that case we should trigger a refetch to make sure we're up to date.

We can do this by resetting `state.chat.caughtUp` on app state change.

**Comment by timabbott** [comment]
The correct thing to do here is to check the `get_events` query, and if it returns that the queue doesn't exist, trigger a full reload.

**Comment by borisyankov** [comment]
The best way to implement this is a background task.
Currently only supported on Android:
https://facebook.github.io/react-native/docs/headless-js-android.html

**Comment by borisyankov** [comment]
Another option is to continue fetching while in the background:
https://github.com/transistorsoft/react-native-background-fetch

**Comment by timabbott** [comment]
Continuing to fetch in the background might be the right strategy, since then one can have more of an instant open experience.  If we want to make the background action super cheap, all it really needs to do is keep checking in with the server and save the events in a queue; doesn't need to actually process them until the user opens the app again.

**Comment by neerajwahi** [comment]
I would consider background fetch as more of an optimization (that we can add later) because it's out of our control when (and if) it runs, so we can't count on it.

For now I think we should trigger a full reload on app state change if there's no queue available. The full reload is necessary because messages may have been edited (along with added), but we can do the reload and silently merge the changes with the current messages so that the user can still interact with the app while it catches up.

**Comment by timabbott** [comment]
Yeah, we have to do that even if we're doing the background fetch, so let's start with that and then we can add background fetch later.  

We can open a separate issue in M6 for background fetch?

**Comment by neerajwahi** [comment]
👍

**Comment by neerajwahi** [comment]
This should be an M5 issue -- otherwise the user will see stale data when reloading the app

**Comment by neerajwahi** [comment]
We now trigger a refresh if the event queue is stale or missing when the app is reopened

**Comment by borisyankov** [comment]
I will open another issue about this. Ideally, we will keep the messages updated while the app is running, but it is quite an involved thing, and am not sure there is good support for that in React Native, so it will be for a future milestone.
