### ISSUE TITLE
Show bot conversations

### ISSUE THREAD

**Issue by agzuniverse** [zulip/zulip-mobile#2521]
When there are no conversations (As in the case of this empty realm)
![screenshot_20180517-134148](https://user-images.githubusercontent.com/22353313/40164913-6d07ed86-59d8-11e8-97aa-0becdfea992b.png)

The "No recent conversations" text does not come up, and it just displays an empty screen, because there is a default conversation from welcome-bot that is not being shown.

**Comment by borisyankov** [comment]
This can be reframed as 'show bot conversations'

**Comment by agzuniverse** [comment]
Resolved by #2562 , thanks @borisyankov !
