### ISSUE TITLE
Fix rare exception in webview on Android

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2538]
Rendering some messages (very rarely, but consistently) throw an error on Android.

**Comment by borisyankov** [comment]
It seems the error happens when we send some html messages to the phone (when transitioning from 'loading' to 'some messages loaded' state).
When the messages already exist, they are rendered properly.

**Comment by gnprice** [comment]
@borisyankov says this issue may be related to #2505 and #2558.

**Comment by gnprice** [comment]
Fixed in 787c4a53b (from #2854) a couple of weeks ago, along with #2505 and #2558.
