### ISSUE TITLE
clean up UserAgent to match other Zulip apps/scripts

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#257]
We should make the User-Agent format start with `ZulipMobile/1.0`; that's the style we use for all of our other apps/integrations/etc., and it's nice to be able to use the same parsing code for them all.

**Comment by borisyankov** [comment]
I changed it a bit. Now it says:
`ZulipMobile/1.0 (iOS 10.2)`

Do you mean we should strip the `(iOS 10.2)` part?
Because I think it is useful, at least to differentiate iOS vs Android.

**Comment by timabbott** [comment]
That's great.  We just need the first part to be of a consistent format.
