### ISSUE TITLE
Message list jerks when compose menu is expanded

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2572]
Reported by @jainkuniya in #2565. See screen captures:
https://chat.zulip.org/user_uploads/2/a1/E2ni2cyBSY-NbdOHLysj4OjF/before-self-narrow.mov
https://chat.zulip.org/user_uploads/2/d7/thaZMo_sTidyhDIxWOBQgONh/before-pm-narrow.mov

**Comment by gnprice** [comment]
And copying my thoughts from there on ways to address this:

Playing with Facebook Messenger as one comparison, since they also have a compose box with a similarly-styled expanding menu, I see they do at least two things differently from us that would help -- in fact either of these would prevent the jerks in the videos:

* When the compose box shrinks to get out of the way of the menu, there's no overshoot. It just goes to the width it'll be at, and not any narrower.
* Before the compose box starts shrinking in width, it's reduced to one line (and excess text is just clipped). So it never blows up to be taller after shrinking than it was when the user was actually typing into it. I like this as a UI cue, too, actually -- we already have an issue where it's kind of surprising that e.g. the image option sends an image as a standalone message, rather than adding it to the message you're drafting, and this would de-emphasize the compose box when the menu is expanded, which would help signal that.

**Comment by borisyankov** [comment]
We should not be switching the Input from multi-line to one-line. Implementation-wise it is a property change for us but a new native component is recreated, and there are some consistency issues that (losing focus I think it was last time) that make it more complicated/buggy.

**Comment by borisyankov** [comment]
As a reality-check... this is a minor issue that does not deserve huge efforts, versus other parts of the app these efforts can be better spent.

**Comment by timabbott** [comment]
I think that this sort of jerkiness is pretty important to how the app feels.
