### ISSUE TITLE
Text input gets very slow on some Android devices

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2589]
On some Android devices, in some specific cases, the 'compose' input responds very slowly to a point of being unusable.
Reported here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/speed

The issue was reproduced on Pixel 2, so it is not a purely performance problem.

Very likely, it is related to:
https://github.com/facebook/react-native/issues/19126

The fix then seems to be to make our compose box not-controlled.

This is not a bad idea as it will be a performance improvement regardless of the specific bug encountered, and something I wanted to do before this issue was reported.

**Comment by gnprice** [comment]
An update: a couple of days ago (2018-06-06) we released a fix for this to all users through the Play Store, as version 13.5.89.

That version is in this repo (as a tag, and on a stable branch) but not merged to master; it's a preliminary version of #2595 which solves this Android-only problem (working around an Android-only bug in React Native) nicely, but in turn triggers a different, iOS-only bug in React Native.

I'm leaving this issue open here until we have a fix merged into master, though it's already fixed for users.
