### ISSUE TITLE
Some emojis are missing compared to main app

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#260]
Warning example:
```
Warning: Failed prop type: Invalid prop `name` of value `double_exclamation_mark` supplied to `Icon`, expected one of ["100","1234","interrobang","tm","information_source","left_right_arrow","arrow_up_down","arrow_upper_left","arrow_upper_right","arrow_lower_right","arrow_lower_left","keyboard","sunny","cloud","umbrella","showman","comet","ballot_box_with_check","coffee","shamrock","skull_and_crossbones",
```

@timabbott can we auto generate a file in this format (slight difference of how emoji codes are presented):
https://github.com/zulip/zulip-mobile/blob/master/src/emoji/emojiMap.js

**Comment by timabbott** [comment]
Probably; should be a not-too-hard patch to `tools/setup/emoji/build_emoji` in the Zulip backend, which generates static/generated/emoji_codes.js.

**Comment by borisyankov** [comment]
Assigning to M5. Breaks when missing emoji is used.
