### ISSUE TITLE
Selected Account and button have the same styling in Switch Accounts.

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#261]
![screenshot_1485633664](https://cloud.githubusercontent.com/assets/18511177/22464653/fadb93ba-e7dd-11e6-88f9-f7265d48d4ea.png)

@neerajwahi @borisyankov Can you please suggest a style for the button. I would like to work on this.

**Comment by saketkumar95** [comment]
@vishwesh3 This issue can be closed now.

**Comment by vishwesh3** [comment]
yup! :+1:
