### ISSUE TITLE
settings: Build a better UI for choosing language

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2611]
This will be a bit complex to build, and I think right now we have a number of equally complex areas of UI work to do that will be higher-value. (Most users will only ever touch this screen either zero or one times.) But I'm getting down some thoughts now, since I was looking into this thanks to #2610.

Our screen for choosing the UI language looks like this:
![image](https://user-images.githubusercontent.com/28173/40869056-72e1a48e-65c9-11e8-92f3-d4beccbbc32b.png)
Apart from some small layout issues (those are #2610) which shouldn't be hard to fix, there are a few problems with this:
* It uses national (more or less) flags to represent languages. This is confused about the world (many languages are spoken widely in several countries, and many countries have several primary languages), and isn't super helpful anyway.
* It names all the languages in English only.
* It's a long list, in an unavoidably arbitrary order (it can't be in the order of the user's own language, because the point of the screen is we don't know that yet), with no search.

Good language selectors I see in mobile apps:
* don't use flags
* name each language in the current UI language, and in itself
* provide a search box -- which searches through both those names for each language

The Wikipedia app (the official one from Wikimedia) does an excellent job of this. It's actually significantly different in details between their Android and iOS apps, but both are good models.

**Comment by anh2111** [comment]
@zulipbot claim

Hi, I am new to Zulip repo and looking for an issue to get started. This one looks doable. I'll follow Wikipedia's language screen on Android and make a WIP PR soon.

**Comment by anh2111** [comment]
The PR is ready for review.

**Comment by gnprice** [comment]
Now done, with #3231. Thanks again @anh2111 !
