### ISSUE TITLE
message list: Show when a message is starred

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2627]
In the message list, we should display an indication of whether a message has been starred. For consistency and ease of understanding, it should look a lot like what we do in the webapp, which is a "star" icon in the upper-right of the message.

This will fill in a significant UX gap in the interaction of starring a message, which is that there's basically no feedback to confirm to the user that it worked.

**Comment by jackrzhang** [comment]
I'd be interested in trying to implement this.

@gnprice Can I claim this?

**Comment by gnprice** [comment]
@jackrzhang Sure! You should be able to do it with zulipbot.

**Comment by borisyankov** [comment]
We do support that actually. It is shown as a `starred` text at the bottom of the message.
Possibly an actual star will be an improvement.

**Comment by borisyankov** [comment]
@jackrzhang The relevant file is:
https://github.com/zulip/zulip-mobile/blob/master/src/webview/html/messageTagsAsHtml.js

Another argument in favor of using an actual star - we are not currently translating this.

**Comment by gnprice** [comment]
> We do support that actually. It is shown as a starred text at the bottom of the message.

I just tried this to make sure I wasn't imagining things, and I don't see it. So there's some other bug, then.

In any case, I think an actual star will be clearer. Good to know about that bit of code, though!

**Comment by jackrzhang** [comment]
I see the `starred` tags, but they seem to be really unresponsive. When I star/unstar a message in the application, the menu that pops up shows the correct action - either 'Star message' or 'Unstar message' - but the message tag itself doesn't update.

Agreed, I think a visual star would be more intuitive - so for now, I'll just remove the `starred` tag.

@zulipbot claim
@zulipbot add "area: layout"

**Comment by jackrzhang** [comment]
As discussed with @gnprice, I think it would be good to debug the behavior of the message tags first before moving forward with this. Will open a separate issue for that investigation.

**Comment by jackrzhang** [comment]
Opened #2676 / #2677.

**Comment by jackrzhang** [comment]
@gnprice I think this should have been closed with the resolution #2627 and #2677.

**Comment by gnprice** [comment]
I've just filed #3593 for the remaining task of converting the design to an actual star. Closing this one -- thanks @jackrzhang for fixing these bugs!
