### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-mobile#2640]
## Issue Summary
Just got the below when using the mobile app on chat.zulip.org.
Thought it would be worth raising.
## Issue Screenshot
![screenshot_20180606-063013](https://user-images.githubusercontent.com/13500254/41019248-bbd81dd2-6955-11e8-9258-bc3500f0220b.png)
## Versions
Zulip Mobile Version: v13.4.88
OS: Android
Phone: Samsung Galaxy S7 Edge
## Extra Information
Let me know if you need any more information, or to grab any logs if you can show me we're to find them.

**Comment by gnprice** [comment]
Thanks @adambirds for the report! Folding this into #2505, which appears to be the same issue.
