### ISSUE TITLE
Replace SPACING and HALF_SPACING constants with numbers

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2641]
After looking and thinking about how these show up in our code (prompted by reviewing #2614), I'd like to eliminate `SPACING` and `HALF_SPACING` from our codebase. Instead, I'd like to simply write 16 and 8 respectively where appropriate.

My reasoning is:

* These are never going to change. They're simply small multiples of the 4px grid that is fundamental to Material Design. Even in a future where we decided at some point to move away from Material as a model (and adopt Microsoft's Fluent, or something else?), it's not going to be just a matter of changing these constants in `styles/index.js` -- it'll be a complex project, and this won't help much.

* We already have other multiples of 4px around the codebase, which are closely related to these. In `composeBoxStyles.js` we say `SPACING * 3 / 4` a couple of times, which is cumbersome and less clear than just `12`. Elsewhere, we just write the numbers.

* In writing #2630 I paid attention to how this felt. The lengths I wrote down in the code there include 2, 4, 12, 16, 24, and 72. Those are all derived from Material guidelines, and they're all related to each other and to the 4px grid. It was pretty clear to me that the code is clearer with those as numbers than as multiples of `SPACING`.

This should be a pretty straightforward sweep to make.

**Comment by agzuniverse** [comment]
@zulipbot claim
