### ISSUE TITLE
Cannot add emoji reaction on the phone as a client (chrome tested)

### ISSUE THREAD

**Issue by an3l** [zulip/zulip-mobile#2643]
Emoji reaction when writing private message is enabled and works.
Emoji reaction on someone's message is enabled, but when it is pressed gui appears for 1 second and disappears.

**Comment by borisyankov** [comment]
Hey @an3l, are you referring to using the website version in a Chrome browser on a phone?
If so, please direct this issue to https://github.com/zulip/zulip/issues

**Comment by an3l** [comment]
Hi @borisyankov yes.
I specified this issue there, but issue was closed and they told me to put it here, so it's done  :).

**Comment by borisyankov** [comment]
Haha, maybe they misunderstood you :)
This repo is only for the native app, which I encourage you to use and give feedback on (though the adding of a reaction is a feature we are yet to add)

**Comment by an3l** [comment]
Added again there, let see where issue will end :). Will definitely try and will let you know if I find something interesting to point out.

**Comment by gnprice** [comment]
Thanks @an3l for reporting this issue! Closing here, because it sounds like your report is about the web app on mobile.

For reference, our issue for this feature on the mobile app is #303.
