### ISSUE TITLE
[Feature Request] Seperate Notification Settings Per Server

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-mobile#2647]
I would like the ability to be able to have seperate notifications settings/preferences per server.

The main reason being I have both my own production server in there as well as chat.zulip.org.

Now I'd like to enable stream notifications for my production server but have them disabled for chat.zulip.org. Currently this doesn't seem to be possible.

**Comment by kunall17** [comment]
I'm assuming this is related to the push notifications. The stream notifications can be disabled in the settings of either the web or the mobile.

**Comment by adambirds** [comment]
It's this bit I'm on about. You may able to shed some more light.

![screenshot_20180607-064628](https://user-images.githubusercontent.com/13500254/41080544-f6a82ce4-6a1e-11e8-91d0-39b7511c3f9c.png)

I'd ideally want these settings to be per server on the app rather than global for the app.

**Comment by kunall17** [comment]
So these notification settings is with respect to any realm, as in if you're logged in for chat.zulip.org then change the notification settings, then it would be reflected for only this realm and not other ones, so disable the stream notif for the chat.zulip.org and enable for the rest of the servers.

If something ain't working please report it here!

**Comment by adambirds** [comment]
@kunall17 so that is how I would want it to work. Bur unfortunately, it doesn't seem to. If I disable in one realm, it disables in the other as well.

**Comment by kunall17** [comment]
Hey, @adambirds I tried to reproduce it and couldn't to do so, any steps to do so?

**Comment by adambirds** [comment]
This is no longer an issue. Closing.
