### ISSUE TITLE
Lightbox on iOS fails to show uploaded images

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2654]
This is similar to #2618 , but affects an additional part of the UI, and only on iOS.

To reproduce:
* On iOS, log into an org on zulipchat.com, or possibly any other server running a recent release and on Xenial. (Not chat.zulip.org, which is on Trusty.)
* Find a conversation with a user-uploaded image in it. (Or just upload one.)
* Tap the image, bringing up the lightbox.
* The image doesn't appear. We just have the lightbox's black background, and its top and bottom bars.

I just tested this with 13.4.88 on iOS 10. With 13.5.89 (which differs only in one unrelated bugfix) on Android, it works fine.

Given that this happens on a Xenial but not a Trusty server, it's almost certainly related to our feature to require authentication to see uploaded files (which doesn't work on Trusty and is disabled there.) We're either not passing the authentication info, or not following the redirect, or both.

**Comment by a-b** [comment]
This problem is still present in the latest iOS 12.
Unable to enlarge images from the chat is a major issue for our organization. Any guess when this could be fixed?

**Comment by jackrzhang** [comment]
I'm claiming this.

(@zulipbot is disabled for this repository at the moment)

**Comment by gnprice** [comment]
Cross-referencing here what we learned in d873e22fc, which fixed this: the underlying issue here was
https://github.com/alwx/react-native-photo-view/issues/101 , in the library we use for displaying the image. It was fixed upstream in April, but upstream hasn't made a release since last year; we fixed by upgrading to the version from Git that has the fix.

**Comment by gnprice** [comment]
Following up for @a-b and anyone else watching this thread: the fix went out to all users a few days ago in 17.1.98.
