### ISSUE TITLE
Fix layout of <ul> in messages

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2671]
Here's what a message with an unordered list looks like, in my emulator for a Pixel 2 XL running Android 8.1:
![image](https://user-images.githubusercontent.com/28173/41309108-a0b54aa2-6e32-11e8-9018-a0e45b0e4f3d.png)

There are two issues here:
* The bullet glyphs are clipped at the left.
* There's excess space between the preceding graf and the first list item.

For comparison, here's the webapp on the same message, if I narrow the window to make the text flow the same way:
![image](https://user-images.githubusercontent.com/28173/41309269-33c4078e-6e33-11e8-80dc-c80910108ca5.png)

I think even that might be improved by slightly less space before the first list item; but we're showing way more than that.

I noticed this while reviewing #2665 , but it was already the same way before that change.

**Comment by jackrzhang** [comment]
(just a note) The bullet glyphs are similarly cut off in iOS.

**Comment by agrawal-d** [comment]
@gnprice I think this issue can be closed.

**Comment by ray-kraesig** [comment]
This was indeed fixed by #2687. Closing.
