### ISSUE TITLE
Update state.narrows on topic/stream edits

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2688]
(new description written 2021-07 by @gnprice)

When a message gets edited, we reflect the edit in `state.messages`, but not in other data structures that know about the message. In particular `state.unread` (that's #4840), and `state.narrows`.

This means that if a message has its topic and/or stream change, then if you've already seen that message in a message list (so that we have an entry in `state.narrows` for that narrow), it will still be in the old narrow if you go and look there.

Conversely, if you've already looked at the *new* narrow where it should appear, so that we've fetched from that narrow covering the point where the message would appear, I believe this means the message won't show up there. (But if you first visit the narrow only after the edit happened, then it will, because we fetch the relevant messages from the server.)

A particularly salient way for this to show up is if you're looking at a topic narrow, and edit a message's topic yourself. You're looking right at it in that narrow, and it won't disappear. (This was reported as #4830.)

The way we'll fix this is to add a case for `EVENT_UPDATE_MESSAGE` in `narrowsReducer.js`. It should be sure to
* handle stream edits as well as topic edits (see also #3957);
* handle whole-stream narrows as well as topic narrows;
* add to the new narrows, if applicable, as well as remove from the old.
  * For the nuances of "applicable", see jsdoc on `NarrowsState` and `CaughtUpState`, and the existing logic that `narrowsReducer.js` has for the `EVENT_NEW_MESSAGE` case.

**Comment by gnprice** [comment]
I just merged @roberthoenig 's #2842 , which, by normalizing the "narrows" state as distinct from "messages", makes this code a lot more straightforward! I think this issue is now ripe to work on.

**Comment by gnprice** [comment]
Reported again today, by @jyn514 [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292558). I've bumped this to P1, as it's pretty conspicuously broken when it happens.
