### ISSUE TITLE
notifs: Use Android's fancy "notification group" feature

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2691]
Android has a handy feature we should use to make all our notifications a "group", with one for each conversation.

Upstream [tutorial docs here](https://developer.android.com/training/notify-user/group). An illustration from that doc, to help make clear what feature I'm referring to:
![image](https://user-images.githubusercontent.com/28173/41548988-4e5286b6-72d9-11e8-996a-851f02894ff5.png)

One key benefit of this is that each conversation's notification can take the user to the respective conversation.

This works great for Gmail (as in the illustration) and FB Messenger, and we should do the same thing.

(This Android feature was introduced in Android 7.0 Nougat, and we support some lower versions, so we'll need an appropriate conditional and fallback. But [as of 2020-04](https://chat.zulip.org/#narrow/stream/48-mobile/topic/platform.20versions/near/863756), >95% of our users are on Android 7 or higher and so will benefit from this feature.)

**Comment by jainkuniya** [comment]
I am working on this and submitted WIP PR #3407

**Comment by gnprice** [comment]
Android 11 was just released today, and it introduces some further fancy features in this direction: "conversations" and "bubbles".
https://developer.android.com/guide/topics/ui/conversations
We should target those too. I haven't yet read about these new API features in detail; it may be that it'll make most sense to target them at the same time as this older "notification group" feature. (Which after all is aimed at a highly overlapping use case.) If not, we'll make a new issue for these new Android 11 features.

In general our userbase is [fairly quick to upgrade](https://chat.zulip.org/#narrow/stream/48-mobile/topic/platform.20versions/near/1012192) to new OS releases; if the Android 11 rollout goes like Android 10 did before it, then a sizeable chunk of our Android users will get it over the next few months, and a majority will within a year.

**Comment by gnprice** [comment]
This will probably require some improvements to the data structure we keep as `ConversationMap` in the notifications code. There's some comments pointing in that direction by the definition of that type. I'll file a specific issue for that in a bit.
