### ISSUE TITLE
Emoji cut off at bottom

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2693]
A user reported that it "seems iOS app emoji are being cut off at the bottom", providing the following screenshot:

![](https://chat.zulip.org/user_uploads/2/e/jxuYnpeMdQaBZDGbPndSYV49/IMG_0054.PNG)

Looks like this is a message containing only an emoji, as the last message shown. Not sure exactly what range of conditions lead to the bug, but it shouldn't be hard to reproduce and play with.

**Comment by jackrzhang** [comment]
Hm, the bug is not present in the generated HTML/CSS from `MessageListWeb`, which makes me think this has to be specific to iOS.

**Comment by armaanahluwalia** [comment]
Sorry for not being more descriptive. This was a private message inbox with one other user ( hence the blacking out by me ). The emoji was the last message received from the other user.

**Comment by gnprice** [comment]
We learned more about this in #2706 ; see comment thread there, and [this chat discussion](https://chat.zulip.org/#narrow/stream/2-general/topic/Unicode.20Emoji.20Accessibility).
