### ISSUE TITLE
Fix misleading uses of "group"

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2694]
As touched on in #2609, discussing where we used to say "Members" above a list of the other people in a group PM thread:

> I'm also not a fan of the term "members" here, as it sounds like a model where you could add and remove people to/from the group while the group keeps its identity -- like groups in FB Messenger and similar SMS-inspired systems.

We fixed that screen, but we have a few other places that sound like that model. One is "Create group", on the PMs screen of the main nav; for a new user, this is likely to look like what they want when they're actually looking for how to create a stream, because in those other systems the thing that's most like a Zulip stream is called a "group".

From a quick grep, the other strings that look suspicious are:

New group chat
Message group
No messages in this group

**Comment by jackrzhang** [comment]
@gnprice 

Another two closely related items to adjust might be the `groupNarrow` and `isGroupNarrow` functions in `narrow.js`, which are identical to the `privateNarrow` and `isPrivateNarrow` functions, except that a `groupNarrow` refers to more than one email.

From the conversation in #2613, I think "recipients" is the preferred term here.

Here are possible rewordings I have in mind:
- "Create group" -> "Message new recipients"
- "New group chat" -> (also) "Message new recipients"
- "Message group" -> "Message recipients"
- "No messages in this group" -> "No messages for these recipients"

Thoughts?

**Comment by borisyankov** [comment]
I never refer to people I want to talk to as 'recipients'. Does feel like a term we would use in code (we do) and not conversationally.

**Comment by armaanahluwalia** [comment]
I agree recipients is ok in a specific situation but not as an overall label. Why not "New Group Chat"? or  "New Group Message"?

**Comment by jackrzhang** [comment]
Hm - another possible criticism of "recipients" is that it's too broad here; in that every message sent has a recipient or group of recipients.

Maybe "group PM" instead? So rewordings might be:
- "Create group" -> "Create group PM"
- "New group chat" -> "New group PM"
- "Message group" -> "Message group PM"
- "No messages in this group" -> "No messages in this group PM", or "No messages in this thread", or I could see the term "recipients" being used here: "No messages for these recipients"

**Comment by borisyankov** [comment]
PM means nothing to a normal person :)

**Comment by borisyankov** [comment]
"New group chat" does not imply in any way that a "group" is created, the other names are misleading though.

**Comment by jackrzhang** [comment]
The abbreviation of "private message" as PM, especially in the context of internet forums, is not new.

**Comment by borisyankov** [comment]
`old !== established || widely_recognized`

Few times users of Zulip asked me what do I mean by 'PM', so that is not a wild guess.

**Comment by jackrzhang** [comment]
I didn't intend for that comment to imply that just because something is not new it's conventional; at the same time, just because something isn't widely recognized doesn't mean that it isn't relevant.

**Comment by jackrzhang** [comment]
The string "New group chat" only appears in the translations files, which means that it isn't being displayed anywhere on the UI. I'll submit a PR to remove it.

**Comment by jackrzhang** [comment]
I think the term 'group PM' could be associated with both  messages sent to private streams and private messages sent to more than one recipient and not associated with any Zulip stream. So, on a technical level, it might be accurate.

Messages sent directly to recipients - that is, messages not associated with a stream - might be considered a subset of all private messages.

**Comment by gnprice** [comment]
We've just fixed "Create group" in #4602, making it "Group PM". I don't feel that that's 100% clear either, but really nothing that fits in a button label will be 100% clear to a new user, and this is a lot better.

> New group chat

This one has been gone for a long time, as mentioned at https://github.com/zulip/zulip-mobile/issues/2694#issuecomment-432430078 .

> Message group
> No messages in this group

These two are still around. But they're a lot more OK -- they both appear in a context where it's clear what's meant, because you're already looking at a group PM conversation:
* `Message group` is used as placeholder text in the compose box
* `No messages in this group` is used in the `NoMessages` component, i.e. it goes where the messages would be if there are none

We can always tweak the text there, as we might elsewhere in the app, but I think we don't need this issue anymore to track an intention to do so.
