### ISSUE TITLE
webview: Sender name cut off at the bottom

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#2696]
I've noticed that the text for sender names is cut off - for example, see the letter 'g' from 'Jack Zhang':

![image](https://user-images.githubusercontent.com/12771126/41582964-e4883756-7357-11e8-88b4-7046f34d4f65.png)

The bug seems similar to #2693 (at least on a surface level).

**Comment by jackrzhang** [comment]
A bit of quick investigation shows that the text is being cut off by the `overflow: hidden` CSS declaration. We don't want to remove the declaration, since it's used along with `white-space: nowrap` and `text-overflow: ellipsis` to truncate long sender names. Increasing the line-height of the text would fix this.

@zulipbot claim
@zulipbot add "area: layout"

**Comment by borisyankov** [comment]
@jackrzhang we did add the `overflow: hidden` to ensure some weird html don't overflow, but since then we have improved the sizing css. Maybe we no longer need that? Worth investigating.

**Comment by borisyankov** [comment]
Some types of text would make the message container width too wide. For example `averylonguninterruptedword' or some other uncommon things.

**Comment by jackrzhang** [comment]
I think the `overflow: hidden` is part of what's constraining the width of the message containers for unusually long text. (unless I'm understanding you incorrectly)

**Comment by borisyankov** [comment]
It really depends on how we've specified the styles of the containers. 
`overflow: hidden` will not prevent the overflow, but will prevent the message from becoming scrollable. 

While hiding parts of the message is not optimal, making it scrollable is even worse ;)

It is worth exploring how our current styling behaves without this `overflow`.

**Comment by jackrzhang** [comment]
I mean we should continue utilizing the strategy of truncating into an ellipsis for the `.username` rule-set, which is the use of `overflow: hidden` here. Otherwise, entering a really long name results in this behavior:

![image](https://user-images.githubusercontent.com/12771126/41629191-0f8f52a6-73dd-11e8-9813-0e5e3fb0a479.png)

**Comment by borisyankov** [comment]
I have a test realm full of these long crazy names ;)

BTW, try with `overflow-x: hidden;`

**Comment by jackrzhang** [comment]
`overflow-x: hidden` does not fix the bug :p
