### ISSUE TITLE
Floating action button positioning makes it difficult to create group chat

### ISSUE THREAD

**Issue by agzuniverse** [zulip/zulip-mobile#2709]
The `FloatingActionButton` in `UserPickerCard` is positioned to be on the bottom right of the list which expands with the number of users instead of being fixed on the bottom right of the screen.

This makes the button appear out of position when the list is small:
![screenshot_20180622-163309](https://user-images.githubusercontent.com/22353313/41774967-802f7a40-763f-11e8-82e8-3a1d2cc5b039.png)

But it's much more worse when there is a very large number of users, in which case a user will have to scroll all the way to the end of the `UserList` to find the button:
![screenshot_20180622-170827](https://user-images.githubusercontent.com/22353313/41775042-c9e4eb7a-763f-11e8-9462-f06f8f7f40fb.png)

This issue also applies to `InviteUsersScreen` since it uses the same `UserPickerCard` component.

**Comment by agzuniverse** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
Thanks @agzuniverse for reporting this! Now fixed. :smile:
