### ISSUE TITLE
Pass data using navigation props instead of getting from global state/selectors.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2746]
Currently we are using selector to get data (stream, account & topic) from global state according to the route. Which is causing some problem and also not following good pattern:

Let's take an example of `StreamEditScreen`, currently we are getting current stream data via selector 
https://github.com/zulip/zulip-mobile/blob/1f9ad56f197896533ca8cf519fee44f0ca73504f/src/subscriptions/subscriptionSelectors.js#L43
Now the problem is, as soon as StreamEditScreen is pushed navState changes and it's params also changes. Resulting in change of `getStreamFromParams` output too. Actually as soon as screen is pushed it takes some time to update params, so first `NULL_STREAM` is returned from `getStreamFromParams`, then required stream is returned (according to params) then again at the time of popping out screen, params become null (changes) instantly but takes time to unmount component, so again screen is repainted with `NULL_STREAM`.

Same thing also goes for topic screen and account detail screen.

Also it's also not good pattern of extracting/getting data.

There are open PR's for fixing this issue:
#2455, #2456 and #2452 needs rebasing, will do it @zulipbot claim

**Comment by gnprice** [comment]
Fixed in #2748 . There's one remaining selector that looks like an example of this bug but isn't; I filed #2813 for a small followup to clean it up. Thanks again @jainkuniya !
