### ISSUE TITLE
Topic list always requested from server on topic input focus

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2750]
**Context:**
We request a topic list for the current stream when a user focuses on a topic input.
This is done so we can offer auto-complete.

**Issue:**
We do a new request every time a user focuses even if we already have the data.

**Expected:**
We should do a server request only if we don't have the data.

**Comment by chrisbobbe** [comment]
Confirmed (by reading code) that this is still happening.

**Comment by jeevanpuchakay** [comment]
claim

**Comment by TarunTomar122** [comment]
Is this issue still active? I would like to fix it.

**Comment by tusharojha** [comment]
@zulipbot claim.

**Comment by tusharojha** [comment]
I would like to work on this issue.

**Comment by tusharojha** [comment]
@zulipbot claim
