### ISSUE TITLE
Type error in webview's getMessageIdFromNode

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2751]
Webview throws an exception: `msgNode.getAttribute` is not a function.

This happens both on Android and iOS (the only other known issue is Android-specific)

**Comment by chrisbobbe** [comment]
It looks like 65e3ea3bd0b5e451253a27e6696b0c56badc9527 types `node` as `?Node` instead of `Node`, but this wouldn't catch the problem Greg pointed out:

> So somehow we're getting a `msgNode` that is truthy, but doesn't have a `getAttribute` method.

Also, getMessageIdFromNode was deprecated in 7f968e5685372d38b6f370f89835f7a1c1fcf45c, but it still has six call sites.

**Comment by gnprice** [comment]
Looking at Sentry events, we've had no cases of this in (at least) the past 90 days:
https://sentry.io/organizations/zulip/events/?project=191284&query=%22msgNode.getAttribute%22&statsPeriod=90d

To try to confirm that's not just a lack of data: the way these would get reported to Sentry is that the same `window.onerror` which puts up that red banner (or a less detailed one, in release builds) also posts an event through `sendMessage`, which gets processed here in `webViewEventHandlers.js`:
```js
    case 'error':
      logging.error(`WebView exception: ${JSON.stringify(event.details)}`);
      break;
```

And we do get other exceptions reported through that path:
https://sentry.io/organizations/zulip/events/?project=191284&query=%22WebView+exception%22+%22TypeError%22&statsPeriod=14d

So it seems this got fixed at some point. :man_shrugging: If we hear a fresh report, we'll reopen.
