### ISSUE TITLE
Internal links to streams and narrows don't work

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2760]
Reported in chat [here](https://chat.zulip.org/#narrow/stream/48-mobile/subject/Hyperlinks.20within.20stream.20view.20don.E2.80.99t.20work/near/608487) and previously [here](https://chat.zulip.org/#narrow/stream/48-mobile/subject/Navigating.20Streams/near/559780).

We actually have logic that attempts to do this, but it's too narrow in the forms of URLs it handles, and in particular it doesn't handle the form the server/webapp migrated to some time ago where IDs are included.

#2312 is a previous version of this bug. #2313 was a previous attempted PR to address it. See comments on #2313 for some details on how to address the issue.

**Comment by gnprice** [comment]
Copying a comment by @borisyankov on the previous thread, which is otherwise in danger of being lost amidst the noise GitHub makes out of commit references:

> Keep in mind we need to support both the new and the old format. In the new format we want to take just the ID and disregard the topic name.

**Comment by agzuniverse** [comment]
@zulipbot claim

**Comment by armaanahluwalia** [comment]
@gnprice This is not the most helpful comment but I feel like this should be a high priority issue.

**Comment by timabbott** [comment]
I think that actually is a helpful comment; this probably should be on our P1 list.

**Comment by jackrzhang** [comment]
@gnprice @borisyankov Is this currently being worked on - or can I give this a shot?

**Comment by borisyankov** [comment]
@jackrzhang I got a branch for this that will turn into a PR maybe tomorrow.
