### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [zulip/zulip-mobile#2763]
Hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by chrisbobbe** [comment]
Hi, @teneresa! Thanks for your kind offer.

Currently, there may be some higher-value UI/layout design work to do, but it may fall outside graphic design of logos, icons, etc.; https://github.com/zulip/zulip-mobile/issues/3632 comes to mind. If you're interested in that kind of work, please let us know! 🙂  But I'm closing this, as it's been almost two years, and there hasn't been a lot of activity.
