### ISSUE TITLE
[Feature Request] Add possibility to direct share Screenshot/File to Zulip

### ISSUE THREAD

**Issue by hmr-it-jr** [zulip/zulip-mobile#2776]
A cool feature for Zulip would be if you take a screen shot and then you can share it directly to Zulip.

WhatsApp offers this and after sharing it to WhatsApp you can choose a group or a contact you want to share it to.
In Zulip there should be a select for channels and for private chats to share the screenshot/file with.

In this Video you see that some apps offer already direct sharing and you can see that zulip is missing.

<a href="https://ibb.co/kGr6mo"><img src="https://preview.ibb.co/ixymmo/ezgif_com_video_to_gif.gif" alt="ezgif_com_video_to_gif" border="0"></a>

**Comment by jainkuniya** [comment]
Thanks @hmr-it-jr for the feedback!
We prioritise features according to the feedback.
We are tracking this down in #117. And will be soon in the app.
