### ISSUE TITLE
Renaming a stream makes it appear as 'unsubscribed'

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2782]
If someone renames a stream, we correctly handle the name change itself, but we then fail to correctly consider it 'subscribed'.

**Comment by chrisbobbe** [comment]
Hmm, if this is still happening, I suspect there's something going wrong with one of our Redux reducers; perhaps `subscriptionsReducer`.

**Comment by gnprice** [comment]
Agreed.

This is likely a case of #3918. It's a bug in itself, and we should be able to fix it even without changing how we identify streams anywhere -- but also it sounds like it probably involves looking up subscription data by stream name, and if we fixed this case of #3918 by using stream IDs instead then that should fix this too.

**Comment by gnprice** [comment]
This appears to have been fixed: I just attempted to reproduce, and things worked fine. Specifically, on the tab showing subscribed streams, the stream changed names and didn't go away. Also, on long-press there, the stream action sheet shows an option "Unsubscribe".

We've made a long string of fixes to different cases of #3918, so it's likely that one of those fixed this.
