### ISSUE TITLE
[Feature Request] Add possibility to set group icon

### ISSUE THREAD

**Issue by hmr-it-jr** [zulip/zulip-mobile#2785]
At the moment a picture is generated of the initial letters of the group members. I would prefer it to upload a custom image as a group icon. 
<a href="https://ibb.co/jn0j7T"><img src="https://preview.ibb.co/hVq6Mo/Screenshot_20180710_082426.jpg" alt="Screenshot_20180710_082426" border="0"></a>

I think it's useful to have the possibility to change the group icon if you have many groups where the first memebers are the same and beginning at the fourth member the members are different. It's a quick way to find the right group you want to write to.

**Comment by jainkuniya** [comment]
Hi @hmr-it-jr, thanks for the feedback. 
For uploading group icon, we will be requiring backend support.
But ya we do have plans for improving current icon #482
