### ISSUE TITLE
Add visual feedback on stream/topic button press.

### ISSUE THREAD

**Issue by roberthoenig** [zulip/zulip-mobile#2794]
Currently, when pressing on either a topic of a stream,  there is little to none visual feedback that this specific topic/stream was pressed:
![ezgif com-optimize](https://user-images.githubusercontent.com/7950151/42626771-6bee0664-85cb-11e8-91e3-2db2417871e4.gif)

Either there is only a quick green flash, or (when the narrow is fast enough) there is no feedback at all.

This makes it hard to be confident that the app recognized the press. It also makes it hard to be confident that the correct stream/topic has been pressed.

Two things to improve:
* The visual feedback should show as immediately as possible.
* The visual feedback should be visible for a couple hundred milliseconds, or until the narrow finishes (whatever is quicker).

**Comment by roberthoenig** [comment]
@agzuniverse FYI.

**Comment by borisyankov** [comment]
There is a Touchable so the feedback should show.
A very likely solution to this problem (depending on the actual cause, this is an educated guess):
Add a [`setTimeout`](https://developer.mozilla.org/ro/docs/Web/API/window.setTimeout) when doing the new narrow. This will allow the UI thread to respond to the touch before performing the actual transition. (delay of 0 makes sense)

**Comment by agzuniverse** [comment]
@zulipbot claim

Will look into this.

**Comment by gnprice** [comment]
Thanks again @roberthoenig for this writeup, and thanks @agzuniverse for the fix!

I've just filed a followup issue #2837 , for the long tail of less-central places in the app that show similar symptoms.
