### ISSUE TITLE
Remove all instances of NavigationScreenProp type.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2811]
Currently it is present in `ChatScreen`, `LightboxScreen`, `AuthScreen`, `RealmScreen`.

I just tested changing type to

```
type NavigationProps = {
  navigation: NavigationScreenProp<*> & {
    state: {
      params: {
        email: string,
      },
    },
  },
};
```

and accessing like this:

```
export default connect((state, props: NavigationProps) => ({
  initialRealm: props.navigation.state.params.realm || '',
}))(RealmScreen);
```

**Expected behaviour**: Flow should give error because type specify email but I am accessing realm.
But it didn't.

```
Vishweshs-MacBook-Pro:zulip-mobile vishwesh$ npm run test:flow

> ZulipMobile@1.0.0 test:flow /Users/vishwesh/Desktop/Work/githubClones/zm-48/zulip-mobile
> flow --max-warnings 0

No errors!

```

So this is just adding reductions and we are confirm that we are right but not. SO better to remove all this redundant/code which is making as confusion.

We should also remove other instances in existing code too. Doing it now.

@zulipbot claim

**Comment by borisyankov** [comment]
It is the `<*>` that throws Flow off.

**Comment by jainkuniya** [comment]
Tried with only
```
type NavigationProps = {
  navigation: {
    state: {
      params: {
        email: string,
      },
    },
  },
};
```
Then also it is not throwing error.

**Comment by jainkuniya** [comment]
This is no longer relevant.
Closing.
