### ISSUE TITLE
Show button in PasswordInput is aligned at bottom instead of right on Android API 28 only (checked on lower Android API & iOS, it works fine).

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2814]
<img width="273" alt="screen shot 2018-07-14 at 9 03 47 pm" src="https://user-images.githubusercontent.com/18511177/42725929-d24ad006-87a9-11e8-9d64-7a4eab90d1fa.png">

@zulipbot claim

**Comment by gnprice** [comment]
Thanks @jainkuniya for reporting this!

I believe it was fixed last month with Boris's 2fd7ba5ef.
