### ISSUE TITLE
Hide status bar when side drawers are open

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#282]

**Comment by borisyankov** [comment]
We should not hide it, but add BRAND_COLOR background behind so they are visible.

**Comment by neerajwahi** [comment]
A lot of similar apps hide the status bar (at least on iOS) but we can revisit this later

**Comment by neerajwahi** [comment]
I actually think it looks really weird to have the status bar prominently displayed when the drawers are open. Almost every other app with drawers on iOS hides the status bar as the drawer begins opening.

Going to open a PR that adjusts this behavior.
