### ISSUE TITLE
given action "REALM_INIT", reducer "userGroups" returns undefined

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#2859]
Sentry [shows this error](https://sentry.io/zulip/zulip-mobile/issues/626034816/) hitting a bunch of users, ever since 15.0.92 came out:

> Given action "REALM_INIT", reducer "userGroups" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

(That is an admirably clear error message. Thanks, Redux!)

Here's the relevant code:
```
const realmInit = (state: UserGroupsState, action: RealmInitAction): UserGroupsState =>
  action.data.realm_user_groups;
```

Seems like that field isn't included in the response we got from the server.

I suspect these are older servers that just don't have this feature. Checked one at random, and it's on 1.7.1:
```
$ curl -s https://[...]/api/v1/server_settings | jq .zulip_version
"1.7.1"
```

We should be compatible, of course, so I guess we need to have this code handle it properly.

**Comment by borisyankov** [comment]
Started working on this. It seems we are not consistent in how we handle this. I'll rework all reducers to do the same reasonable thing in this case.
