### ISSUE TITLE
Auto refresh in chat view loses the content of the message box

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#2861]
When an app has been closed (or switched away from) for a while with chat open and then re-opened the app will then refresh the whole chat view in order to get the latest messages. Sadly, if anything has been typed in the message box before the refresh (sometimes the refresh takes a few seconds to actually happen, in which case you already would've had enough time to write parts of your message) will disappear as the screen is refreshed. This can be quite frustrating as you now have to re-type the message you had already started to type.

**Comment by gnprice** [comment]
I just hit this issue running 18.0.99 (a version I sent to our alpha channel yesterday), which has #2931. So apparently that didn't fix it as we'd hoped. :-/ Reopening this issue.

The specific sequence I happened to see today is a bit different from the OP:
* I'd been using the app, and started writing a reply message in a narrow.
* Then I got to my desk, and put down my phone for a while. (> 10 minutes.)
* I picked up my phone, and either it was already in Zulip or I went and switched to Zulip. It was still in that narrow, and showing my reply message.
* After a second or two, the refresh happened (the messages were replaced by the "loading" animation, then went back to showing the messages); and my draft reply was gone.

I.e., the draft message I lost was from before re-opening the app, not after. But I don't know of a reason the behavior would be different in those two cases.

**Comment by borisyankov** [comment]
Thanks for the detailed explanation.
I did reproduce it in a controlled environment and working on it.

**Comment by borisyankov** [comment]
Another update: The issue does not exist with a controlled input component.
But, I did find where and why this happens, so a fix is coming next.
In fact, it is kinda fascinating and unexpected why this happens (to be read about in an upcoming commit message)

**Comment by borisyankov** [comment]
A fix is ready.
