### ISSUE TITLE
Floating button is not visible on inviteUserScreen and groupScreen.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2867]
Also selected users list (horizontal avatar list is not pinned/floats on top on scroll)

There is already PR for this issue. #2307

(Just opening issue to track this down)

@zulipbot claim

**Comment by jainkuniya** [comment]
(oh! there was already issue #2709)

**Comment by gnprice** [comment]
#2709 is earlier, so let's consolidate there.
