### ISSUE TITLE
Emoji in message list don't render if names have changed. 

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2868]
<img width="292" alt="screen shot 2018-08-05 at 12 41 50 am" src="https://user-images.githubusercontent.com/18511177/43679803-6bf01acc-9849-11e8-8720-1100e42e023b.png">

@zulipbot claim

**Comment by gnprice** [comment]
This looks to me like a case of #2846. Does that fit what you're seeing?

**Comment by jainkuniya** [comment]
#2846 if for realm emoji right?

But this issue is for unicode emoji. :)

**Comment by armaanahluwalia** [comment]
Can confirm. Have a look at https://chat.zulip.org/#narrow/stream/179-Testing/topic/test.20topic on mobile 18.0.99

**Comment by armaanahluwalia** [comment]
Additionally trying "Add a reaction" with ```umbrella_on_ground`` doesn't work at all.

**Comment by gnprice** [comment]
Fixed in #2869 / c8f4d0030 .
