### ISSUE TITLE
Nothing happens when select image to upload

### ISSUE THREAD

**Issue by frg-tarasov** [zulip/zulip-mobile#2873]
Android 7.1.1
Smartphone Sony Z5 Compact.

Zulip self-hosted installation.

Photo with camera also nothing not send to chat.

Thanks.

**Comment by frg-tarasov** [comment]
**@zulipbot** claim

**Comment by gnprice** [comment]
Hmm interesting. Thanks for the report!

I don't think we've seen reports of symptoms like these before, and uploading images is a pretty frequently-used feature; so I suspect there's something different about your server that is part of what's happening here. If so and if we can identify that, then we'll be in good shape to figure out how the app should handle it.

It sounds like you're interested in debugging this yourself, which is great. :) I have a couple of suggestions of things to try for comparison:
* Join chat.zulip.org (the Zulip community's own server), and try uploading there; `#test here` is a good stream to send test messages to.
* Make your own test organization on zulipchat.com, and try there. That's the major cloud Zulip service, run by Zulip core developers (including me), with a pretty different configuration from chat.zulip.org.

**Comment by frg-tarasov** [comment]
@gnprice I will be try debug this problem, thanks.

**Comment by gnprice** [comment]
We just fixed in 3529c3155 a bug that, at least on iOS, was causing the "use camera within app" part of these symptoms. It's possible the same bug was the cause of those symptoms here, but I was never able to reproduce the issue on Android (only on iOS, 100% of the time there), so I'm not sure.

The "select image to upload" part of these symptoms shouldn't be affected by that fix, though, so there's definitely still an open bug here.

**Comment by gnprice** [comment]
(that commit was from #2972, for cross-reference)

**Comment by frg-tarasov** [comment]
@gnprice When will be release in to Google Play?

**Comment by gnprice** [comment]
@frg-tarasov I've just sent a version with this fix (17.1.98) to all Google Play users!

When you get a chance, please try that version out and see if either or both of these symptoms ("select image to upload" not working, and "photo with camera" not working) are resolved for you.

**Comment by frg-tarasov** [comment]
@gnprice Thanks, i now will be test this issues.

**Comment by frg-tarasov** [comment]
@gnprice I'm sorry. Now i try send photos and problem stay.
After i check nginx log and see that nginx return error for upload request with exceed body size limit.

Change nginx setting client_max_body_size resolve both this issues.

I close this issue, thanks.
