### ISSUE TITLE
Font size is too large in the application.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#288]
The body font size in the application seems to be much too large such that it doesn't seem to be space efficient. Perhaps decrease the font size by around 20% or so?

<img width="320" alt="screen shot 2017-02-06 at 12 52 32 pm" src="https://cloud.githubusercontent.com/assets/10321399/22665865/369b3928-ec6b-11e6-9e3d-338da8a035a1.png">

**Comment by borisyankov** [comment]
The font size is perfect, you are looking it zoomed in on a mac :D
An iPhone 5 is just a tiny device with small screen.
The font size is exactly the same as Slack.
The headers wouldn't be `tappable` if they were smaller - they are around 44-50px.

**Comment by brockwhittaker** [comment]
The font size is definitely too large. Here's a comparison of the Slack App on the iPhone 6S and the Zulip Mobile app on the iPhone 6S.
![slack-vs-zulip](https://cloud.githubusercontent.com/assets/10321399/22671337/b10a1848-ec82-11e6-8156-9a7421be9d58.jpg)

**Comment by brockwhittaker** [comment]
There's something strange going on. When mapping the iPhone 6S and the iPhone 5 outputs it appears as if the iPhone 5 seems to be a larger font size than the 6S relative to the screen. This isn't super high priority right now, I'll passively look into it. Don't worry about it for now. :)

**Comment by borisyankov** [comment]
I suggest comparing Slack screenshots for iPhone 5/6/6Plus.
