### ISSUE TITLE
Images not shown in image viewer on iOS

### ISSUE THREAD

**Issue by sstangl** [zulip/zulip-mobile#2888]
Filing an issue on behalf a non-technical member of our organization. We're investigating moving to Zulip from Slack.

On the most recent version of the iOS app (installed yesterday), the user claims that images display in-line, but when he touches them to make them full-screen in the image viewer, only a black screen is shown, and the screen remains black even after waiting for a long time. This happens even on wireless, on a fast connection.

On the Android app, the black screen also appears initially, but it's quickly replaced by the image after it finishes downloading.

It would be useful to:
1. Display something more meaningful than a black screen -- possible a spinner, that a background download is in progress?
2. Investigate why images aren't loading on iOS.

If you need more technical information, I'd be happy to relay that.

**Comment by TrystanOakley** [comment]
"non-techical" member here. I have witnessed a few more bugs if you would like me to file issues for them.

**Comment by TrystanOakley** [comment]
I also can not download and/or save the image to my phone.

**Comment by jpellman** [comment]
We're encountering something similar with YouTube videos- videos will appear as expected when the preview is clicked on in the browser, but on the Desktop and Android/iOS apps the video does not appear (i.e., we just get a black screen).

**Comment by timabbott** [comment]
@jpellman adding a separate issue for YouTube videos would be good; for those, we have some custom code in the webapp that I expect will need to be ported to the mobile apps.

**Comment by gnprice** [comment]
Thanks @sstangl and @TrystanOakley for the reports!

The failure to load on iOS (but only in the lightbox, and working fine inline in the message list) is actually a known issue: #2654 . I agree it's an annoying one.

> Display something more meaningful than a black screen -- possible a spinner, that a background download is in progress?

Hmm, good thought. This wouldn't really be an improvement when there really isn't a download happening (i.e. the bug on iOS), but it'd be good for the case when the connection is just slow.

**Comment by borisyankov** [comment]
I was considering showing a low-rez thumbnail while the high-rez one loads, now that we support thumbnailing.

**Comment by a-b** [comment]
Thanks for update @borisyankov Any guess when the corresponding fix could be released?

**Comment by gnprice** [comment]
For cross-reference: the videos issue became #2895 (thanks @jpellman !), and I filed @sstangl 's suggestion of a loading spinner as #2896.

The central issue, that on iOS the lightbox doesn't show images at all, is a serious one; we're tracking it in #2654. Closing this issue in favor of tracking it there.

**Comment by gnprice** [comment]
@sstangl @TrystanOakley @a-b and others following this: the fix for this issue went out in version 17.1.98 to all users early this week. Thanks again for the reports!
