### ISSUE TITLE
Embedded YouTube Videos Do Not Display When Clicked

### ISSUE THREAD

**Issue by jpellman** [zulip/zulip-mobile#2895]
Embedded YouTube videos do not appear as expected when users click on the video preview in the Desktop and Android/iOS apps (i.e., users just get a black screen).  This occurs in version 2.3.3 of the Desktop app and version 15.0.92 of the mobile app.  This issue does not occur when logged in via web browser.

**Comment by timabbott** [comment]
We have explicit code in the webapp for Youtube videos that involves reading `data-id` from an image with the `youtube-video` class on it in the `static/js/lightbox.js` code, so probably we need to replicate that in the app.

**Comment by gnprice** [comment]
Thanks for the report!

(It looks like the desktop side of this is https://github.com/zulip/zulip-electron/issues/537 , which they believe is fixed in master.)
