### ISSUE TITLE
Do not include debug build launcher app icon in release APK/package.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2898]
Currently there is no logic which says, `ic_debug_launcher` is only used in debug build, so it is also present in release build. We can save few space (but very less). But for future this might be helpful, when we have more build based resources.

For reference:
https://stackoverflow.com/questions/33760518/android-gradle-have-both-debug-and-release-resources-in-different-flavors

**Comment by jainkuniya** [comment]
@zulipbot label "good first issue"

**Comment by prateek3255** [comment]
@zulipbot claim

**Comment by prateek3255** [comment]
I want to work on this issue.

**Comment by prateek3255** [comment]
@jainkuniya can you review my PR #2916 for this issue.
