### ISSUE TITLE
Cannot connect to self-hosted organization

### ISSUE THREAD

**Issue by nmagerko** [zulip/zulip-mobile#2909]
When I try to connect to my organization's self-hosted chat server during onboarding on Android, the application shows the error "Cannot connect to server". 

The only related issue I found to this is #1191. I don't think this is related to an SSL error since our server is not using a self-signed certificate (as is much of the focus of that issue) but it's hard to say. For reference, the organization is hosted under zulipchat.engr.illinois.edu.

This problem does not occur during onboarding on the desktop application, so I believe it is something specific to the mobile application.

**Comment by timabbott** [comment]
@gnprice this one is interesting; their server is on the public Internet and SSL seems correct.

**Comment by nmagerko** [comment]
Is there anything I can do to help debug this? Not too familiar with this codebase, but perhaps I could help come up with a solution.

**Comment by borisyankov** [comment]
@nmagerko I did some digging. 
I was surprised that iOS worked but Android did not.

When stripped from our app, using directly the `HttpOk` library, the error is:
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by borisyankov** [comment]
Testing with another utility on Android, completely unrelated to our code returns:
```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found
```

**Comment by nmagerko** [comment]
Problem was caused by issues with intermediate certificates. Thanks for the guidance!

**Comment by steffenabel** [comment]
I face the same problem with a ProxyPass Installation. IOS works, Android not.
@nmagerko do you know how your IT deparement fixed the problem?

**Comment by nmagerko** [comment]
Unfortunately I wasn't part of the communication that ultimately fixed it ☹️. Sorry!

**Comment by gnprice** [comment]
For reference for people coming across this in the future: there's discussion of intermediate certificates and "chain issues" in our documentation here:
https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html

That includes
* a couple of options for testing whether your setup has such an issue
* a link to nginx documentation with more discussion and with instructions on how to properly provide the full certificate chain to nginx.
