### ISSUE TITLE
[iOS] white screen visible when switching views in dark mode

### ISSUE THREAD

**Issue by lukasIO** [zulip/zulip-mobile#2914]
When I have dark mode activated and click on either of the home, starred or mentioned buttons,I can briefly see a white flash from what seems to be the opened view having a white background md then switching colors to the drk mode colors

**Comment by chrisbobbe** [comment]
![Jan-28-2020 10-41-27](https://user-images.githubusercontent.com/22248748/73294614-0b26bf80-41bb-11ea-8cac-049b7fbc4139.gif)

Hmm! It's this, right? I've started to notice this disruption; in a dark room, I like to use night mode so I don't hurt my eyes, and this flicker is quite bright.

I'll open a PR for this soon; it seems to be that the WebView for the message list just shows white by default before it's finished initializing. It looks like one working solution is to use the startInLoadingState and the renderLoading props of WebView, to make the background dark in night mode during that time.
