### ISSUE TITLE
Autocomplete popup behaves erraticly

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2917]
A recent regression leads to visual issues in the autocomplete popup.
The actual issue is hard to describe but manifests in appearing/disappearing or varying heights of the item list.

**Comment by jainkuniya** [comment]
Most probably it is introduced in b4cd7c829a7d17888902f5468d4ea0a0f1084c42.

**Comment by gnprice** [comment]
I just filed #2997 to describe more specifically an aspect of this that I see. Between that and #2791 , @borisyankov , do those cover what you had in mind here?

If not, let's get another issue filed with a more specific description; then let's close this one in favor of the more concrete issues.

**Comment by gnprice** [comment]
Maybe also #2943 ? Though I don't 100% understand what #2943 is saying.

**Comment by gnprice** [comment]
Closing this in favor of the various more-specific issues.
