### ISSUE TITLE
New messages sometimes might not load

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2918]
Issue reported on 16.2.96 / iOS.

Reported as:
> From the unread screen clicking on the stream name instead of the topic name (of an unread message) seems to be the action that shows this behaviour the most. for me it's the behaviour that the new messages simply don't load. I see the old messages, but the new ones are not being loaded.

> The messages load in chunks and I press the down arrow multiple times to get to the newest ones.
But in this case they simply don’t show, the workaround for me is to open the topic narrow instead of the stream, then the behaviour is as expected (loading dynamically in chunks).

**Comment by lukasIO** [comment]
Hm. In the last days since filing this issue, the symptoms have disappeared for me.

**Comment by gnprice** [comment]
Closing because the reporter found it stopped happening -- thanks @lukasIO for the report and the update!

We continue to sometimes have bugs with similar symptoms, but it's likely they have separate causes; we'll file them as we see them.
