### ISSUE TITLE
cant login to zulipchat when not on X.zulipchat.com (blahdeblah.zulipchat.blah.blah.edu)

### ISSUE THREAD

**Issue by angrave** [zulip/zulip-mobile#2932]
For student privacy (FERPA) purposes we're running zulipchat on our own VM at a university-

https://blahblah.zulipchat.blah.blah.edu
which when opened in a web browser redirects to 
https://blahblah.zulipchat.blah.blah.edu/login

(blah is a placeholder - the exact name of the server is hidden for privacy)

However the Android app always reports that it cannot connect to the server. 
We've tried including/excluding '/login' and including/excluding 'https://'
but the app always reports that it cannot connect to the server.

Other UI mobile Android nits: Copy-paste doesnt work. In portrait mode the text entry does not scoll to the right, so you cant read what you type.

**Comment by borisyankov** [comment]
@angrave there is a possibility you have problems with your SSL certificate. This is the most common reason for the app not being able to connect on Android.

If you want to check if that is the case, either PM me on https://chat.zulip.org with the actual realm URL, or use an app on Android like DevNetworkTool.

**Comment by borisyankov** [comment]
Can you elaborate on the copy-paste issues you are having? I tested this now and it works.

**Comment by angrave** [comment]
Update: US Universities use https://www.incommon.org/certificates/ to create https cert; these certs cannot be validated by Android because incommon intermediate certs are not included yet  in Java/Android cert stores (but they are included in common web browsers).
Thus this bug could be a 'wont fix' or -
- add common intermediate certs to the application.
- Another recommendation would be in the install docs (which everyone reads right?) to recommend universities to use letsencrypt certs instead (though in practice their IT policies may prohibit this), otherwise the mobile app wont work

**Comment by timabbott** [comment]
@angrave have you tried concatenating the appropriate intermediate certs between you and an Android-trusted CA together into an appropriate `nginx` certificate bundle?  Or is what you're saying that incommon.org isn't signed by any other CA present in Android?  http://nginx.org/en/docs/http/configuring_https_servers.html#chains may help.

**Comment by angrave** [comment]
Thanks Tim, yes that turned out to be the issue - IT had not properly configured the certificate bundle on the server. This was discovered using 

https://www.ssllabs.com/ssltest/

(It is interesting that all of the regular web browsers, Chrome,Firefox,Safari were silent on this). Fixing the bundle made the whole problem go away. i.e Now the certificate and intermediate cert on the server is properly configured I can connect to the server using the mobile app. "curl" also now happily connects. Thanks for your help.

**Comment by timabbott** [comment]
Should we add a link to https://www.ssllabs.com/ssltest/ on https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html#manual-install ?  That might help a lot for other folks doing a custom SSL cert.

**Comment by timabbott** [comment]
Can you explain that idea in more detail?
