### ISSUE TITLE
stuck typing in all caps

### ISSUE THREAD

**Issue by scottrus** [zulip/zulip-mobile#2938]
This is reproduced on iOS iPhone 8.

1. On mobile app, compose a reply to this thread but do not yet hit the send button. I used the phrase "This is a test."
2. Be sure you space after the final period so that the keyboard is showing it will auto cap the start of the next sentence.
3. Using 3D Touch, move the insertion point back to "is a" and start typing again. Initially the newly entered text will be lower case but eventually automatically shift to uppercase. For this typed about 3-6 lower case chars to observe the problem.

The trigger for what I'm seeing seems to be:

1. The sentence is complete with a period followed by a space and the keyboard shows the next letter to be typed will be uppercased
2. Move the insertion point into the just typed text and start typing a few chars.

Reference to this: https://chat.zulip.org/#narrow/stream/48-mobile/subject/stuck.20typing.20in.20caps/near/641171

Reportedly not reproduced with PR #2886

**Comment by gnprice** [comment]
I just tried and couldn't reproduce this. (v26.28.151, iOS 12.4.1, iPhone 6.)

Very likely it was fixed when we turned the message input box "uncontrolled", in #3095 which was the successor to #2886. This is definitely the kind of behavior I'd expect to be affected by a controlled vs. uncontrolled input.
