### ISSUE TITLE
Remove chat.zulip.org default/placeholder in login flow

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#294]
Only the Zulip developers are on chat.zulip.org; only a tiny fraction of Zulip users use chat.zulip.org, so we shouldn't suggest it's the default thing to do.

We may also want to edit the copy in the server prompt to make it more clear that you should be entering the domain of your Zulip server (e.g. zulip.example.com).

**Comment by borisyankov** [comment]
Do we want to suggest another domain instead?

**Comment by timabbott** [comment]
No, I think we should just not suggest a domain (for users using the zulipchat.com SaaS service, they would still need to ender e.g. customername.zulipchat.com anyway).  So I think the main real optimization we could make is having a ".zulipchat.com" button on the relevant keyboard :).

**Comment by borisyankov** [comment]
Investigated creating a custom button, it is definitely not trivial. ;)
