### ISSUE TITLE
Message position is sometimes incorrect

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#2940]
It was reported that on our latest release we sometimes incorrectly calculate the message position.
One specific case is on apps startup the position would match message that was last read on the phone but not the actually latest read messages.

**Comment by gnprice** [comment]
The specific issue described here, i.e.:

> One specific case is on apps startup the position would match message that was last read on the phone but not the actually latest read messages.

was fixed in f53f8311a, as part of #2843 . (Rather a while ago, soon after this issue was filed.)

The symptom "incorrect position" can happen with other causes, but we'll track those as separate issues. See #3457 and #3301 for two that are open now.
