### ISSUE TITLE
Organization URL must end in zulip.com

### ISSUE THREAD

**Issue by jvasile** [zulip/zulip-mobile#2941]
I have a user on Android Pixel 2 who installed the most recent version of Zulip mobile.  He reports that he cannot enter the organization url we use because the field is pre-populated with ".zulip.com" and he cannot edit that portion of the field.  Another user also reports this problem, though I don't know what platform she is on.

Is there another way to specify the URL?  Or is this a UI bug?

Thanks!

**Comment by borisyankov** [comment]
Hey @jvasile 

We do support arbitrary URLs (non zulip.com/zulipchat.com)

We used to have this issue a few versions ago. Ask the user to check if they have the latest version (16.2.96) and if not to update.

Once updated, ask the user to just write the whole URL, once they type a dot we will not auto-add the domain.

**Comment by borisyankov** [comment]
I am curious to know what happened. It would be great if they were on an older version.
If the input was just confusing, we need to address that.

**Comment by jvasile** [comment]
The version is indeed 16.2.96 and it isn't actually buggy.  We got it to work after mass confusion.  It wasn't until the fifth person tried to enter it that we figured it out.

The confusion was that the field is pre-populated, and you can't edit the end of it.  You also can't paste into it.  If you type the URL, when you get to the 'dot', it will remove the 'zulip.com' part of the field, but all of us stopped typing before we got there.  We mistakenly expected different behavior in such fields, which is that when you start typing, the original default text goes away.

File this one under 'user error' but also under 'confusing ui'.

Thanks!

**Comment by lilpolymath** [comment]
I guess that this issue can be closed then. @gnprice

**Comment by alya** [comment]
Closing based on discussion above.
