### ISSUE TITLE
Hang while switching servers

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#295]
I got a report from one user that first entered chat.zulip.org and then tried to switch to another server that the app hung until he restarted it.

**Comment by timabbott** [comment]
Got a second report of this, so definitely worth fixing :)

**Comment by borisyankov** [comment]
Not sure if related but I found a thing we are not handling.
In eventActions.js we have this:
    while (true) {
It needs to break if we switch accounts.

**Comment by neerajwahi** [comment]
I'm not sure that's related either but will open an issue for that

**Comment by borisyankov** [comment]
@neerajwahi will your PR address this issue or should I be working on it?

**Comment by neerajwahi** [comment]
It fixes the event queue not breaking when switching accounts, but not sure if that's the root cause of this issue

**Comment by borisyankov** [comment]
I haven't encountered the main issue apart from that, so I suggest we treat it as fixed.
If reported again after the release, we can open a new issue.

**Comment by timabbott** [comment]
I think this is a pretty reproducible flow -- starting with no special state, try logging into one server (but fail) and then switch to another and try to login.  So we should just try that recipe; if it works now, close; otherwise, fix :)

**Comment by borisyankov** [comment]
Hmmm, that is a very different scenario from what I envisioned. I'll try to reproduce.
