### ISSUE TITLE
Subscribe button not working on Android in v16.2.96

### ISSUE THREAD

**Issue by brettcannon** [zulip/zulip-mobile#2953]
The Material Design press action is visible, but it never subscribes me. Happening on Android app trying to subscribe to the core/sprint channel for Python.zulipchat.com .

**Comment by borisyankov** [comment]
Thanks for the report @brettcannon 
We did fix this bug a week or so ago. 
Expect the next release to include the fix!

**Comment by gnprice** [comment]
Following up: 17.1.98 went out to all users early this week, and had the fix for this bug. Thanks again @brettcannon for the report!

(See also #2889 , which was a previous report of this bug.)
