### ISSUE TITLE
For group private message narrows, support touching the top bar to see a dropdown with the list of users

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#296]
Right now, if you don't recognize an avatar, it's not super easy to figure out who it is.

(We may want to have a little caret or or something next to the list of avatars to show it's clickable?)

**Comment by vishwesh3** [comment]
Can I work on this?

**Comment by timabbott** [comment]
Sure, go for it @vishwesh3!

**Comment by vishwesh3** [comment]
We can close this now as done in https://github.com/zulip/zulip-mobile/pull/821
