### ISSUE TITLE
iOS: camera image not sent if permissions are requested

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#2973]
Copying over the description from #2972:

> On iOS, when sending a message via directly taking an image from the camera for the first time, iOS will ask for 3 permissions via modal - first, to access the camera, second, after taking the image, to add to the photo library, and third, to access the photo library (read and write). The first time after granting these permissions, the taken image will not send, which is a bug.

The iOS Camera access setting is binary, and the iOS Photos access setting has 3 options - 'Never', 'Add Photos Only', and 'Read and Write'.

**Comment by chrisbobbe** [comment]
Hmm, if this is still being considered, I wonder about some UX side effects -- if the user has to grant or deny permissions as their very first interaction with the app, without context of why they're needed, it can be distracting, as discussed in this article:

> Don't bombard users with a slew of permission requests the moment the app launches for the first time. This approach, a common mistake, can be overwhelming. When faced with multiple dialogue requests in a row, especially during launch, people tend to get frustrated and might even just tap “Don’t Allow” for everything.
> [...]
> We've found the best time to hit the user with a permission request dialogue is when it's absolutely needed.
(https://savvyapps.com/blog/how-to-create-better-user-permission-requests-in-ios-apps)

Unless this is still a necessary change (and perhaps it is; we've got #3813 and #3787 active now), I wonder about closing this issue from 2018.

**Comment by ray-kraesig** [comment]
In particular, rather citing than a random blog article, I should point out that this is inconsistent with Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/).

I've amended the issue to only describe the problem it was trying to fix, rather than specifying a solution. If the problem no longer persists (which I haven't yet tested), we can close it.

**Comment by chrisbobbe** [comment]
I've just tested this on iOS 13.3.1, with the beta v26.22.145 release, and this issue isn't happening for me, so I'm closing this. But we can reopen if there are more reports.
