### ISSUE TITLE
[Android] layout: Styles of account item is not consistent across Android & iOS.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2982]
on iOS
<img width="368" alt="image" src="https://user-images.githubusercontent.com/18511177/45840466-a04ab600-bd34-11e8-89e5-fbc0c880b70f.png">

on Android

![](https://chat.zulip.org/user_uploads/2/57/uyn-zqh6Nr531e3mW_uDSEZi/Screenshot_20180921-002434.jpg)

Notice the space between different account cards.

**Comment by borisyankov** [comment]
Yeah, that is part of the annoying Android 8.x layout issues.

**Comment by borisyankov** [comment]
Try my RN 0.57 PR and see if this issue is not magically fixed by two versions of React Native. 
Also would be a good signal if there are more issues to work on.

**Comment by gnprice** [comment]
After #3013 , is this fixed now?

**Comment by borisyankov** [comment]
Yes.
