### ISSUE TITLE
Create extended user mention syntax when needed.

### ISSUE THREAD

**Issue by aero31aero** [zulip/zulip-mobile#3000]
Recently, in zulip/zulip#10243 we merged support for the following mention syntax to zulip/zulip:

`@**Full Name|1234(id)**`

This is to allow us to mention users with the same full name, and is optional. The web app intelligently adds the new syntax only when the users have the same full name, and uses the simpler syntax for others.

Example: https://chat.zulip.org/#narrow/stream/7-test-here/topic/user.20mention

We should:

1. Add support for this syntax in the mobile app.
2. Ensure that it is behind a feature flag because it would break mentions in older servers/any non CZO server for now.

**Comment by jainkuniya** [comment]
> Ensure that it is behind a feature flag because it would break mentions in older servers/any non CZO server for now.

This feature is behind which feature flag?  🤔

**Comment by aero31aero** [comment]
I'm sorry, I meant a version check. I believe this is part of the 1.9
release so that should work.

**Comment by chrisbobbe** [comment]
It looks like this was taken care of in ebcaae257cb5931eb1eb6714f2941e4257fef3ea (#4094), so I'm closing this.

It wasn't done with a feature flag, but 1.9 is pretty old.
