### ISSUE TITLE
Autocomplete popup auto-scrolls for a long time when many options

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3007]
When you go to the compose box and type something like `@p` , we'll show an autocomplete popup for @-mentioning a user whose name starts with "p". In a large org, there may be a ton of users this could be. Our current behavior in this situation is that we'll spend seconds and seconds adding more and more matching users to the list, as previous candidates scroll off the top of the screen.

This is related to #2997 , in that the popup extends way past the top of the screen.

Vamshi Bommerla recorded this screencap that nicely demonstrates the issue:
https://imgur.com/gallery/oJHAXxV

**Comment by jackrzhang** [comment]
This seems to have been solved by the `maxHeight` set in https://github.com/zulip/zulip-mobile/commit/f69d2acf4a709b4d13d9236d042e94d19e78074d.

<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/47199955-d7f35080-d328-11e8-8aff-dd925547657e.gif" width="650" />
</p>

**Comment by borisyankov** [comment]
Indeed. That crazy height was the reason for the scrolling.
