### ISSUE TITLE
Login server page looks broken when screen is rotated.

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#302]

**Comment by neerajwahi** [comment]
We need to lock the orientation to portrait mode and that should fix several issues like this

**Comment by borisyankov** [comment]
Absolutely every other chat app supports landscape orientation, so just locking it to portrait is kind of crutch.
Supporting landscape is likely simple to implement too.

**Comment by neerajwahi** [comment]
We can discuss whether or not to eventually support it, but it's not true
that every chat app does. Take a look at Slack

**Comment by borisyankov** [comment]
Slack on Android does support it. And every other chat app that I tested (FB Messenger, Hangouts, Whatsapp, etc.)
10% of people use their phone in Landscape mode.
There is no point to so easily dismiss a trivially implemented improvement to the app.

**Comment by neerajwahi** [comment]
How am I dismissing it? I said we should discuss it

**Comment by neerajwahi** [comment]
@borisyankov and to be clear, I don't have objections around supporting landscape mode but I don't want to prioritize it over all the other M5 tasks we have.

if you think landscape mode will be trivial to fix (less than 30 mins of work, for example), we should go ahead and fix it for M5. Otherwise, let's disable landscape mode for now and then I'll add a task to fix it in M6 or M7.

**Comment by borisyankov** [comment]
Just tested. The only thing that is broken is a bit of misalignment on the login page.
Everything else works. It is not needed to disable landscape for this.
I'll fix next.

**Comment by neerajwahi** [comment]
Did you test it on iOS as well? Message headers also seem broken when switching between portrait and landscape

**Comment by borisyankov** [comment]
Yes, trivial. I'll add a more elaborate task for later.
For example on landscape we can hide the statusbar to make it more usable.
For this I'll just fix the layout for password.
Headers look good to me?
