### ISSUE TITLE
Loading indicator on unreads screen

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3025]
After the app launches, it takes us too long to get to showing up-to-date information on the unreads screen (the home screen of the nav). After the spinner completes and the unreads screen shows up, it at first shows stale data from when we last ran, while asking the server for newer data; the update to newer data takes ~2s for me on a good connection, often 3-5s, and for some users longer.

The fact that it takes that long is a problem in itself, and we should do better. That's a matter for another issue; it won't be simple to fix.

A thing that exacerbates the effect of this slowness is that for those seconds while we're showing stale data, we don't show any indication of this at all -- the screen looks exactly like it would have when that information was fresh, hours or days ago. That undermines users' trust in what they see in the app.

So, in this situation we should show an indication that we're still connecting. One reasonable form for this would be a banner a lot like our `OfflineNotice`, but instead of "No Internet connection", saying something like "Connecting to server...".

**Comment by gnprice** [comment]
The title just says "unreads screen" for brevity, but I'm pretty sure we want it on at least the PMs and streams screens too for similar reasons.

**Comment by armaanahluwalia** [comment]
@gnprice I’d like to work on this. @zulipbot claim.

**Comment by sstangl** [comment]
Instinctively, if I know that the screen is out of date, I usually attempt swiping up, to scroll down "past the end" of the screen, which in many native applications induces refresh behavior.

The app does not support scrolling past the end -- normally, apps will let you do that, and then give a little flick up back to the locked scroll position. Secondly, that action doesn't do anything.

Even if the server took a while to load messages, that would be more OK if I felt that I could instruct the app to try to fetch more messages by swiping down / scrolling up. At least then I would know that the messages are coming. Currently I don't know what the internal app state is at all.

**Comment by gnprice** [comment]
@sstangl Yeah, I agree. I forgot to cross-reference when I filed this issue: #2712 and #2713 call for pull-to-refresh behavior like you describe.

I think even if we already had pull-to-refresh, this loading indicator would still be important. In particular for the path from "load the app for the first time in a while" -> "see up-to-date conversations, and be confident they're up to date", which is a common interaction that it's important to make quick and easy wherever conditions make it possible. Once we have a loading indicator and a user learns to expect it, they'll get that confidence in a few hundred ms when it doesn't appear.

**Comment by gnprice** [comment]
We keep hearing from users who regularly see stale data and take several seconds, or more, to update. Typically the symptom is reported as simply "Zulip doesn't update with new messages".

Bumping the priority accordingly -- it's long past time we added this basic piece of UI for any networked application.

(Often the reports focus on the message list, not the unreads screen -- particularly after following a notification, so the message list is the first screen the user sees. I'll file a separate, related, issue for that.)
