### ISSUE TITLE
Add support for reacting to a message that doesn't have any yet

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#303]
We can do this via a longpress menu on a message.

**Comment by trueskawka** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
There's a bit more discussion on #1304 , which was a dupe of this.

**Comment by armaanahluwalia** [comment]
@gnprice Is anyone currently working on this?

**Comment by agzuniverse** [comment]
@armaanahluwalia this has been solved in #2775 , which has been merged into the master branch.
