### ISSUE TITLE
travis: Check if generatedEs3.js is consistent with latest js.js or not.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3035]
`generatedEs3.js` is used by webView. We write js in the `js.js` and use babel to convert it to `generatedEs3.js`, so that it is compatible with mobile phones webView. But many times it is noticed that `js.js` is updated in the commit, but we forgot to update `generatedEs3.js`. Which will result in old js been executing, and we are thinking that new js is executing. To avoid such situations, there should be some check mechanism, which can warn such situations and maintain consistency between `generatedEs3.js` and `js.js`

@zulipbot claim

**Comment by borisyankov** [comment]
A potentially better option is to generate the file itself automatically when the project starts (depends on whether this is now supported the Metro bundler).

**Comment by jainkuniya** [comment]
Yup! in future it's better option.
But for now I guess this is sufficient and necessary test, at least for now. We can definitely improve in future :).
