### ISSUE TITLE
layout: Limit the max height of compose box.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3048]
Currently compose box size can expand to whole chat screen. We should limit this height to something like every chat app does.

Both FB messenger and WhatsApp have limited this height to 6 lines of text (message).

on current master
<img width="485" alt="image" src="https://user-images.githubusercontent.com/18511177/46902580-58f3b780-cee5-11e8-9eb7-276de82e4c36.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/18511177/46903594-e1c61f80-cef4-11e8-8926-2cdb43e63a53.png">

@zulipbot claim

**Comment by gnprice** [comment]
Closing this, per discussion in the companion PR #3049.
