### ISSUE TITLE
Compose box starts forcing capital letters

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3052]
This is a bug I've seen multiple times but is notoriously hard to reproduce. Basically when editing text, sometimes the input box gets confused and starts forcing capital letters on the user. The whole writing experience is basically unusable at that point.

If my memory serves me correctly this happens when either you paste in some text and try editing an earlier line in the message or some such case. Could also be when you leave the app and come back to drafting a message. No deterministic reproduce yet unfortunately.

Its happened often enough that I now use notes to draft long messages and paste them in instead.
I tried looking into the code but couldn't see anything that would obviously cause this. It may be a RN bug itself since AFAIK we're not doing anything too fancy with the inputs.

**Comment by borisyankov** [comment]
Is that iOS or Android?

**Comment by armaanahluwalia** [comment]
This is on iOS 18.0.99

**Comment by gnprice** [comment]
Fascinating! Thanks for the report.

This feels to me like the kind of bug that's very likely to be an RN bug. One useful direction to investigate would be to search the RN tracker for existing reports of it; finding one, and linking it here, would be extremely informative. (When reading RN issue threads, note that we're still on RN v0.55 as of 18.0.99, though we won't be much longer.)

Obviously a deterministic reproducer would be very helpful too. :-)

**Comment by gnprice** [comment]
(I applied the "area: iOS" label as a bit of a conjecture -- this issue feels very likely to be in a layer where the code is platform-specific, so any given issue is very likely to affect only one platform or the other.)

**Comment by borisyankov** [comment]
I have confirmed this behavior in the past and is related to the controlled input on iOS.

**Comment by gnprice** [comment]
This was most likely fixed the same way as #3053 -- either by switching the input to uncontrolled, or by the RN upgrade just before that :slightly_smiling_face: . Closing, but please reopen if reproduced on master, or on the upcoming 20.0.103 or later.

Thanks again @armaanahluwalia for the report!
