### ISSUE TITLE
Search can race, showing results for a previous query

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3058]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/18511177/46956841-eab11f80-d0b3-11e8-8e2d-68d54d5a467e.png">

As user entered `h` and then `i`. 
After entering `h` app releases a fetch request with search param as `h`. Before it's response is received another request is fired with search param as `hi`. Unfortunately this second request response arrived first, messages in the state are updated and shown to the user. Now result of first request arrives, which as no messages. Thus again state is updated with `[]` as new messages and **no result** text is shown. Which also resulted in sudden splash of message list.

(Debugging logs are shown in above image)

@zulipbot claim

**Comment by gnprice** [comment]
@zbenjamin reported this issue today, thus:
> I saw some very strange behavior while searching this morning. At first, messages with my search term in their topic weren’t included in my search results.
>
> Later, when I tried to reproduce the issue, I somehow got it to search for query that didn’t match what was in the search box. Reselecting the search box and hitting “search” didn’t change the result. However, I think that the results I was shown were for a just-corrected typo. That is, I tried to search for “party,” accidentally typed “path,” quickly corrected it to “party,” and was shown results for “path.” I sadly can’t reproduce it right now, but this all points to a timing bug

In a bit of playing around just now, I was also able to reproduce a couple of times.
