### ISSUE TITLE
design: The same 'home' icon is used for the 'All messages' screen and the 'Unread' screen.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3063]
I think higher-level changes to how navigation currently works would be beneficial; at the moment though, it's pretty confusing just to see the same icon twice on the 'Unread' screen.

The web app uses a 'home' icon for 'All messages', so I think a quick improvement could be to use a different icon for the 'Unread' screen on the bottom navigation bar, even if it doesn't represent the concept of a sidebar or 'Unread' screen super accurately.

<p align="center">'Home' screen:<p/>

<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/47196422-43332780-d315-11e8-83cc-32404caaf25d.png" width="350" />
<p/>

<p align="center">'All messages' screen:<p/>

<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/47196547-f439c200-d315-11e8-9b8d-350425a968b8.png" width="350" />
<p/>

<p align="center">Web app:<p/>

<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/47196513-bc327f00-d315-11e8-9e7e-0b8c7d707328.png" width="550" />
<p/>

**Comment by borisyankov** [comment]
I agree that changing the 'Unread' icon is better. Any ideas what icon would be appropriate?

I decided to use 'Home' for that tab initially as it was supposed to have other key info in the screen, though it still doesn't ;)

**Comment by jackrzhang** [comment]
Maybe the [comments icon](https://fontawesome.com/icons/comments?style=regular) could be appropriate here?

![image](https://user-images.githubusercontent.com/12771126/48460801-84d4b800-e785-11e8-96aa-bf155b3a4143.png)

@gnprice Any thoughts?

**Comment by rishig** [comment]
I like the idea of the unreads screen being the "Home" screen, and de-emphasizing "All messages". 
And we can replace the icon on the webapp as well; the reason it's a Home icon is for historical reasons. 

Maybe some options:

The top half of
![image](https://user-images.githubusercontent.com/890911/48462215-2f4fd980-e78c-11e8-8da0-f48202c79c7e.png)

![image](https://user-images.githubusercontent.com/890911/48462311-805fcd80-e78c-11e8-905d-fef7fe423969.png)

![image](https://user-images.githubusercontent.com/890911/48462328-95d4f780-e78c-11e8-8807-ce0ce01ab819.png)

![image](https://user-images.githubusercontent.com/890911/48462335-9ec5c900-e78c-11e8-8186-cdfda282abaf.png)

**Comment by jackrzhang** [comment]
> Is that for 'Unread' on the bottom or 'All messages' on the top?

I was thinking of the 'Unread' screen.

> rishig said he never uses the 'All messages' on mobile. Me neither. A realistic option is to remove the icon completely.

Just a data point - I've actually never used the 'All messages' feature on neither mobile nor web!

@rishig Are those icons all from font awesome? It's possible that icons from different sets might look a bit odd in conjunction.

**Comment by jainkuniya** [comment]
![screenshot_20181114-124229__01](https://user-images.githubusercontent.com/18511177/48466107-d83d1980-e80a-11e8-8cc5-95abb835fb54.jpg)


Slack uses this icon for all threads

**Comment by borisyankov** [comment]
BTW, we are using Feather Font for the UI of the mobile app, not Font Awesome.

**Comment by jackrzhang** [comment]
Ah, thanks for clarifying that!

**Comment by jackrzhang** [comment]
I think the image of multiple files aligned in a stack fits, but I'm not convinced that the "map" concept is obvious for this context.

**Comment by gnprice** [comment]
This was resolved with #3232 , a little while ago.
