### ISSUE TITLE
Fix notch handling, with `SafeAreaView`

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3064]
When iPhone X was released, new functionality to iOS was added to indicate `safe area` - to help with apps handling optional notches, rounded corners or the ...

A good article explaining all this here:
https://medium.com/rosberryapps/ios-safe-area-ca10e919526f

We started using a component `react-native-safe-area` to handle this.

It isn't working perfectly and we need to fix it. 
Testing on iOS X or Simulator with it makes few layout issues obvious.

Better yet, use the now built-in component:
https://facebook.github.io/react-native/docs/safeareaview

**Comment by gnprice** [comment]
(The Poco F1 issue is #3068 .)

**Comment by gnprice** [comment]
It looks like we promptly duplicated this issue as #3066. There's more discussion there; closing in favor of that thread.
