### ISSUE TITLE
Runtime error after some recent merge

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#307]
App was running fine, but when I updated my copy with latest master branch it is showing this error
![error](https://cloud.githubusercontent.com/assets/18511177/22818738/c0dc3e26-ef94-11e6-80e7-3e4f59897f69.png)

**Comment by neerajwahi** [comment]
Ah this is on Android. Thanks for the bug report @vishwesh3 !

@borisyankov do you have an Android emulator set up to take a look at this? I've been focusing on iOS and still need to set up my environment for Android development :)

**Comment by borisyankov** [comment]
Yeah I got Android, and the exception looks to be in the latest emoji code I wrote. Will try to reproduce and fix.

**Comment by borisyankov** [comment]
@vishwesh3 Can you try this PR:
https://github.com/zulip/zulip-mobile/pull/309

**Comment by vishwesh3** [comment]
Yes it is working
