### ISSUE TITLE
Set a channel on Android notifications (minimal, to unbreak SDK 26+)

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3076]
This is a requirement of #3075 . See https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels .

This feature of Android O is documented here:
https://developer.android.com/training/notify-user/channels

There are a lot of useful things we could do with it, distinguishing e.g. PMs from @-mentions from stream messages, and distinguishing different accounts. None of those are possible without rather more overhaul of our notifications code, though -- in particular, we always display just one notification (in fact we give it a single hard-coded ID!)

So, pending that greater overhaul, we'll just tick the checkbox: we need to set a channel on our notifications. We'll have just one channel. See the doc on creating notifications:
https://developer.android.com/training/notify-user/build-notification#builder
and search for mentions of "channel" to see how to
* create the notification channel at app startup time, and
* set the notification channel on the notification.

**Comment by anirudhjain75** [comment]
This was something I planned on working for the previous GSoC project, nevermind I'll be working on this.

**Comment by gnprice** [comment]
This was a pretty critical issue. I just went and resolved it myself; see the linked commit.
