### ISSUE TITLE
Message list only works the second time

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-mobile#3078]
On the Android client, beta channel, any time I navigate to a topic I see only old messages. I have to navigate away from the topic and then navigate back to cause it to display new messages. This significantly hampers the usability of the client.

**Comment by gnprice** [comment]
Thanks @jmandel for the report! These sound like pretty nasty symptoms.

A few questions:
* When did you start seeing these symptoms?
* When you navigate away from the topic, do you do it by going back out to the main navigation? Or something else?
* When you come back to the topic and now things work, are you doing anything differently than you did to go to the topic in the first place when it didn't work? Or are you just doing the same thing twice, and the second time it works?
* What OS version are you running?
* What version of Chrome do you have installed? (Go to the Settings app > Apps & Notifications > search for Chrome.)

**Comment by gnprice** [comment]
Oh, I guess another question:
* When you say "old messages" vs "new messages", what do you mean exactly? Are there recent messages (like from the last few minutes/hours/days) that don't get shown; or do you get something like a snapshot of messages up to the present, and it doesn't get updated with messages people send while you're already looking at it?

**Comment by jmandel** [comment]
This is on Android 9. Chrome 69.0.3497.100. Here's a demonstration and explanation of what I am seeing: https://photos.app.goo.gl/hgqhu1L9MqHPYEWP9

**Comment by gnprice** [comment]
Thanks @jmandel for that screencast! That's helpful.

In a [chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/subject/messages.20don't.20load/near/656303), we learned some further information from other users seeing similar symptoms:
* Everyone who tries your workaround of going back to the navigation screen, then re-entering the desired message view, reports that it's 100% effective for them.
  * This seems like a pretty strong indication that we're successfully going and fetching the new messages, and they're making it into our Redux store, but we're just failing to get the update to the inside of the webview. One hypothesis for this is #3080.
* Everyone else who's reported their Chrome version is on 70 if they're seeing the bug (3 people), and 69 if they aren't (2 people). So it's a bit puzzling that you're on version 69.
  * Do you perhaps have a different version chosen as your "WebView implementation"? This is an Android developer option; if you've enabled developer options on your phone, then you can search settings for "webview" and you should find it.
* I was not seeing this bug myself, on Chrome 69. Then I installed Chrome Beta from the Play Store (version 71 right now), chose that as my WebView implementation, and I reproduce! That will help us a lot in fixing it :slightly_smiling_face:

**Comment by jmandel** [comment]
Thanks -- it looks like I was reporting the version of Chrome listed in the Play Store -- but when I view settings in Chrome itself, it's 70; so I'm probably on 70 after all (sorry for the confusion on this point).

**Comment by gnprice** [comment]
Great :) -- thanks for the update!

**Comment by gnprice** [comment]
Fixed, and I've cut 19.2.102 and sent it to beta on Android! Thanks again @jmandel for the report -- please update, and enjoy a working app again :-)

**Comment by baumnkz** [comment]
Great! It works now!

**Comment by jmandel** [comment]
As noted on the Zulip chat, this is working for me -- thanks so much for the quick turnaround!
