### ISSUE TITLE
Unable to narrow to a certain group PM

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3087]
I encountered a case where trying to narrow to a group chat with 4 existing users is failing.
The API returns an error and the app is unable to load messages.

The issue could be that the app constructs the narrow incorrectly or could even be a server-side issue. Needs further investigation.

**Comment by gnprice** [comment]
Closing because we don't have the details we'd need to really debug this, and it's been inactive for a number of months.

If someone sees a similar issue in the future, we can reopen or just file a new issue.
