### ISSUE TITLE
Investigate layout inconsistencies in Android 9

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3091]
There are several layout bugs that exist on Android 9, possibly with the same origin.
We need to figure out if there is a single cause for them and fix accordingly.

Some of the symptoms:
* `ChatScreen` on Android 9 (it does work correctly on older versions) does not resize correctly when the keyboard is popped up, hides the nav bar and overlaps the `ComposeBox`
* `RealmsScreen`, `PasswordAuthScreen` on Android 9 does not resize correctly when the Keyboard pops up

All this points to different behavior of `KeyboardAvoidingView` on Android 9 vs 4-8.

**Comment by jainkuniya** [comment]
> does not resize correctly when the keyboard is popped up, hides the nav bar and overlaps the ComposeBox

This seems to be same as of https://github.com/zulip/zulip-mobile/issues/2981

Now I am frequently using app, I am on Android 9. For me all seems to be fine in terms of layout especially when keyboard pops. 

Images on this issue, will really help to debug this :).

**Comment by gnprice** [comment]
Thanks @jainkuniya for looking at this!

I think we've most likely fixed this since it was originally reported, so closing. We can reopen if we see a concrete example in a recent version of the app.
