### ISSUE TITLE
message list: Show users associated with reactions.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3092]
This is a feature request! (for the longer term)

On the web application, users can see the users associated with a reaction via text that appears after hovering over the reaction.

On Slack's mobile application, a list of users associated with reactions to a message slides up from the bottom of the screen after a long press on one of the reactions to the message.

(@zulipbot label "area: message list")

**Comment by jainkuniya** [comment]
(#2252)

**Comment by timabbott** [comment]
Yeah, I'd really love to see this too; it's one of the few places where the mobile app just doesn't offer you information you might need to interpret message content.

**Comment by jainkuniya** [comment]
(on it)

**Comment by gnprice** [comment]
Closing as a duplicate of #2252 .
