### ISSUE TITLE
Do performance profiling

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#311]
The app is currently performing well.
Still, it is not a bad idea to do some profiling and see if there are easy ways to optimize.

This task is well suited for contributors, that want to learn new things.

A nice guide can be found here:
https://auth0.com/blog/optimizing-react/

I would encourage everyone interested to give it a try.
This is not a task that has to be done by one person exclusively.
Anyone interested should give it a try and share his/her findings.

**Comment by cdikibo** [comment]
I'm going to give this a try.

**Comment by HarshulSharma000** [comment]
@borisyankov Reactotron does provide it's own performance measuring utility should I use that and get to work?

**Comment by borisyankov** [comment]
@HarshulSharma000 that sounds like a good general idea, but I am closing this issue as we have improved the performance a lot since this was created and we don't need to track it.

In any case, if you find something can be made faster, this will be a good thing to improve. Just focus on slow tasks. Improving 20% something that takes one second is quite preferable than making something 5 times faster but it takes 1 msec.
