### ISSUE TITLE
Messages disappear on send

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3117]
@sschueller reports:

> I have this issue on 18.0.99 android. Messages I write only appear after I go out of the chat and back in. It happens every time. Server is a zulipchat.com instance.

The report was originally a comment on #2413, an issue with very similar symptoms; but as discussed there, we fixed an issue back in July that I'm pretty sure was the cause of most, if not all, of the reports of those symptoms back then. So this is likely to be a completely separate issue.

**Comment by gnprice** [comment]
I actually ran into symptoms like these myself earlier today; 19.2.102 on Android.

For me, the sequence was:
* I followed a notification, landing in a PM conversation. (A group PM conversation, I think.)
* I typed and sent a message in reply.
* The message promptly disappeared.
* I typed a second message and sent it; same thing.
* I hit the "back/up" button at the upper left to return to the main nav screen, and then navigated to the same conversation. All the messages showed up nicely.

I haven't seen this any other time recently. I also haven't noticed symptoms like #2800 , which back in the spring / early summer was caused by the same underlying bug (fixed in a0cc3dc36 ; see commit message for details) that caused these symptoms (as #2413 and #2539). But maybe it's there and I just haven't noticed.

**Comment by gnprice** [comment]
A possible cause of these symptoms would be if we're not getting the `message` events for some reason, e.g. that we've stopped getting events from the queue entirely. That was the effect of last spring/summer's bug mentioned above. If that's what's happening in this issue, then the symptoms will have been greatly mitigated in last week's 20.0.103 release, with #3094.

Alternatively, @borisyankov points out this possible route to causing these symptoms:
> One hypothetical case (not reproduced):
> * user gets back from a notification, or otherwise, queue is dead
> * we reset caught up to be false
> * queue is established successfully, position is at the bottom though
> * new message comes, we do not add it to the visible list since we are not 'caught up'

Which seems quite plausible to me. Thinking about which step in that we'd want to change, or to describe as the bug, I think my answer is at step 2 -- where we get into a state where
* we're showing the latest messages we know
* but we're neither caught up
* nor trying to fetch more messages.

If indeed this is what's happening, it will interact closely with #3151 . So we'll keep this in mind while doing that work.

**Comment by gnprice** [comment]
The next step on this would be to attempt to reproduce it on a current version.

The key thing will be to write down specifically what was done to try to reproduce it. The last report was a long time ago, so if it doesn't reproduce then we can close. But it's a kind of bug where it's not too hard to try to reproduce, and if it *does* reproduce it's a significant one, so we should make the attempt first.

Note that the reported sequence involves opening the app from a notification -- probably from the app being closed. So that will be an important thing to do when trying to reproduce.

**Comment by chrisbobbe** [comment]
I'll look into this now — since these reports all seem to be about private messages, I suspect it may be https://github.com/zulip/zulip-mobile/issues/3799, which shared a cause with https://github.com/zulip/zulip-mobile/issues/3654, and both were fixed with PR https://github.com/zulip/zulip-mobile/pull/3877). But I'll see if I can get a consistent reproduction before that fix, and see if the fix fixes it.

**Comment by chrisbobbe** [comment]
> I followed a notification, landing in a PM conversation. (A group PM conversation, I think.)

Ah, and I've paused here, pending https://github.com/zulip/zulip-mobile/issues/3647.

**Comment by gnprice** [comment]
Closing this as we haven't had a repro in a long time.

If someone does see symptoms like this, please do file a new issue!

See also #3881 which is an umbrella issue about the "outbox" system -- any symptom like this one is likely to be related to that.
