### ISSUE TITLE
Fix "Login with SSO" in the mobile app.

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#3126]
From https://github.com/zulip/zulip/pull/10788#issuecomment-437301602: @gnprice @borisyankov it appears that the mobile implementation of SSO login accidentally has the trailing slash stripped for `/accounts/login/sso`; my guess is the right fix here is to just change that end (since the general convention for the Zulip webapp is trailing slashes in URLS; it'll redirect to add the slash if omitted, but probably that redirect isn't working with the mobile HTTP library).  

I suspect @codebit-de would be up for testing.

(This is for https://zulip.readthedocs.io/en/latest/production/authentication-methods.html#apache-based-sso-with-remote-user, which I thought we'd tested manually when we added the code, but I can easily see a typo having gotten in there between testing and merge and it never worked after merge, since that backend isn't widely used, and a lot of sites using it have Zulip running behind a corporate firewall that they don't let phones on).

**Comment by codebit-de** [comment]
I'll test the next beta app und report my results.
