### ISSUE TITLE
Image upload in stream narrow goes to wrong topic

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3130]
Steps:
* Narrow to a stream, and open the compose area.
* Edit the topic.
* Upload an image -- I just now tested with an existing image, but I believe using the camera has the same result.
* The message doesn't go to the topic you asked for! Instead it goes to... the topic of the latest message visible, maybe.

This is a common experience when intending to start a new conversation.

**Comment by gnprice** [comment]
#2887 makes a lot of changes to uploading images; I believe one effect is to fix this issue.

**Comment by JayjeetAtGithub** [comment]
I checked just now. This issue is solved

**Comment by JayjeetAtGithub** [comment]
I would like to work on this issue
