### ISSUE TITLE
 Custom emoji in the emoji picker and auto complete? 

### ISSUE THREAD

**Issue by 0rmi** [zulip/zulip-mobile#3135]
Unless it's some bug in my app, custom emotes don't show up in the auto complete list when you start typing :emotename and also can't be found in the emoji picker. Any plans to implement this? Alternatively, could someone point me in the direction of the piece of code where the app grabs the list of emotes to display for auto complete, and the emote picker, so maybe i can try to implement it in my spare time?

**Comment by gnprice** [comment]
Thanks @0rmi for the report!

We're tracking this issue as #2846 .
