### ISSUE TITLE
message list: Top bar becomes white after switching to landscape orientation from the lightbox.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3139]
Here's a screenshot, simulating an iPhone 7 running iOS 12:

<p align="center">
<img alt="top-bar-becomes-white-bug" src="https://user-images.githubusercontent.com/12771126/48460034-a92e9580-e781-11e8-9cdb-46fb8e358c02.gif" />
</p>

(#2962 and #2965 are also observable.)

(@zulipbot add "area: message list" "area: iOS")

**Comment by jainkuniya** [comment]
Just tested will be fixed by #2810.

Thanks @jackrzhang for tracking this in a issue 👍
