### ISSUE TITLE
Use a distinct Zulip notification sound, on Android

### ISSUE THREAD

**Issue by kalzekdor** [zulip/zulip-mobile#3150]
I've recently started using the Zulip client for Android. One thing that seems missing is the option to use a custom notification sound. Any notifications use the default notification sound. I heavily prefer having different notification sounds for different things, so I can tell without looking at my phone what's asking for my attention. The ability to customize the notification sound is a major QoL feature for me, even better would be the ability to set a per-stream notification sound.

Are there any plans along these lines?

**Comment by borisyankov** [comment]
Thank you for raising this issue. I can see how that is important.
We have thought about that but I don't think we considered this a priority.
The more we hear about a certain feature requested, the more we bump it up.
Do you expect the default sound to be different/better or customizable and be able to be set by you? (I think the first option, being simpler has better chance of being implemented sooner)

**Comment by kalzekdor** [comment]
I'm not sure what you mean by a different default sound. It's using the default notification sound as dictated by Android. I can change this in the Android settings, so it's not a problem with the particular sound. I would definitely like to be able to set a customized sound particular to Zulip.

Having this on the roadmap is good enough for me. I don't have any experience with Android development, though I've been meaning to pick it up. Might see if I can take a crack at it if I can find the time.

**Comment by borisyankov** [comment]
I think I did explain it incorrectly. I meant different default sound for the Zulip app (not the system).

 But if you are interested in trying to do it yourself, would be even cooler. 👍

**Comment by kalzekdor** [comment]
No, I was referring to the sound played by the push notifications.

**Comment by gnprice** [comment]
Thanks @kalzekdor for writing in!

Zulip actually has a custom notification sound specific to Zulip, which we've used in the webapp for a long time and which we recently fixed our notifications on iOS to use. There's code in the app that's intended to do this for Android too -- so the fact that it isn't is a bug.

It sounds like if we fixed that bug it would largely cover what you really want here, so I've taken the liberty of retitling this issue to reflect that bug. Conveniently we *also* just added support in the webapp for customizing the notification sounds, which in the future the mobile app will also support; see #3204 for that.

Personally I normally have notification sounds disabled system-wide on my phone ("ring volume" turned down to zero), so I've never noticed. I tested just now (on Android 9), and I reproduce -- I get the system default sound just as you do. So we just need to debug and fix.

**Comment by gnprice** [comment]
PS: here's that code in the app:
```
android/app/src/main/java/com/zulipmobile/notifications/GCMPushNotifications.java

        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
            AudioAttributes audioAttr = new AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_NOTIFICATION).build();
            builder.setSound(Uri.parse("android.resource://" + mContext.getPackageName() + "/" + R.raw.zulip), audioAttr);
        } else {
            builder.setSound(Uri.parse("android.resource://" + mContext.getPackageName() + "/" + R.raw.zulip));
        }
```

The sound that's intended to play is `android/app/src/main/res/raw/zulip.mp3`.

**Comment by jainkuniya** [comment]
@zulipbot claim

**Comment by kalzekdor** [comment]
@gnprice Sounds good! I tried looking into implementing a setting for a custom sound, but I ran into some problems getting the React framework communicating with native android intents. I unfortunately don't have a lot of time to spare for side projects, so glad to hear about those changes.

**Comment by gnprice** [comment]
I've retitled this to reflect what we actually want to do here, for the reasons I explained at https://github.com/zulip/zulip-mobile/pull/3233#issuecomment-450245374 back in 2018.

New chat discussion here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/notification.20sound/near/1280133
