### ISSUE TITLE
Await compatibility check prior to rendering the rest of the application.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3155]
I've noticed this while working on #3073 - the 'Unreads' screen is displayed for a moment, and then the compatibility check is resolved and the compatibility screen pops up:

<p align="center">
<img alt="compatibility-screen-not-awaited" src="https://user-images.githubusercontent.com/12771126/48743975-4bcf9400-ec1a-11e8-8890-e099c2d50bea.gif" />
</p>

This is happening because the `checkCompatibility` network request is resolving after `CompatibilityScreen` mounts and renders for the first time.

To reproduce this, the if statement in the logic below can just be commented out:

https://github.com/zulip/zulip-mobile/blob/b6bf38a3ce0e561fdba1fc1e55fa360ed2c84d0c/src/boot/CompatibilityChecker.js#L22-L29

In a smoother experience, the compatibility screen would just show up if the check fails.

**Comment by jackrzhang** [comment]
As another piece of context, this is the component hierarchy currently rendered by `ZulipMobile`:
https://github.com/zulip/zulip-mobile/blob/b6bf38a3ce0e561fdba1fc1e55fa360ed2c84d0c/src/ZulipMobile.js#L22-L36

**Comment by borisyankov** [comment]
> In a smoother experience, a compatibility screen would just show up if a check fails.

I agree this will be a smoother experience... but only in cases where you fail the compatibility check.
In all the other case about %99.99 of them (currently actually 100% as we haven't used it :) ) there will be a delay in rendering the UI.

**Comment by jackrzhang** [comment]
> I agree this will be a smoother experience... but only in cases where you fail the compatibility check.
> 
> In all the other case there will be a delay in rendering the UI.

Yeah - the delay would be unavoidable. It be pretty seamless if it fit into the timing of the spinner; I haven't looked at the code for that yet.

**Comment by gnprice** [comment]
The check will inherently sometimes be slow, and so sometimes we're going to get a negative result after we've already displayed the normal UI (unless we delay the UI by a lot when the check is slow, which is a bad tradeoff.) That means this sequence will always be possible.

If there were an easy way to start the check request sooner, that'd be a nice small improvement; but we're already doing it at basically the earliest possible moment after RN starts up, so any earlier seems pretty complicated. And the case where it matters is much to uncommon to be worth that.
