### ISSUE TITLE
Support Zulip extra emoji, i.e. `:zulip:`

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3171]
The "Zulip extra emoji" -- of which there's just one, namely `:zulip:` -- render fine in message bodies, but don't autocomplete in compose, don't appear in the emoji picker when adding a reaction, and don't render in reactions.

This issue is parallel to #2129 and #2846, which were for "realm emoji" i.e. custom user emoji. The fix will look a lot like the relevant pieces of #3170, which fixed those.

**Comment by pranavpandey1998official** [comment]
@gnprice is there any unicode assigned to zulip emoji if yes can you tell me if, not I have a workaround it ready to commit  

@zulipbot claim

**Comment by gnprice** [comment]
This was completed a couple of weeks ago, with #2375 . Thanks again @jainkuniya !
