### ISSUE TITLE
home screen: Jitter on Scroll.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3176]
@armaanahluwalia reported:
> I'm seeing some very distracting and weird behaviour is observed while scrolling the unreads screen on 20.0.103. The title bars position seems to be moving around.  
[Link to video](https://streamable.com/4zfjg)

This is a upstream issue.

Read more at https://chat.zulip.org/#narrow/stream/48-mobile/topic/Jitter.20on.20Scroll

**Comment by borisyankov** [comment]
The upstream issue is here:
https://github.com/facebook/react-native/pull/22025

This affects our unread screen `UnreadCards`, all users screen and user picker screen (that use the `UserList` component)

**Comment by gnprice** [comment]
Fixed upstream in facebook/react-native@e4fd9babe, which landed in v0.59. So this should be resolved when we complete #3399 .

**Comment by gnprice** [comment]
And in fact with #3399 complete, this is now fixed! I just went and scrolled a ways through the list of users on czo (from "people" icon -> "Search" button), and the heading stayed firmly in place.
