### ISSUE TITLE
New messages get loaded again when switching views

### ISSUE THREAD

**Issue by lukasIO** [zulip/zulip-mobile#3180]
This is probably more of a question:

When I click on a notification to read new messages, it takes a while and the new messages appear on the bottom of the screen. 
If I switch the appview now to "All Messages" or switch from a narrow "#example:topic" to the stream "#example", the whole process starts again. the new messages are not there, seemingly triggering a request to the server again to fetch the new messages... 
Is this by design and thus unlikely to change (ever) or is there a way to reduce the loading to only happening once?

**Comment by chrisbobbe** [comment]
I expect we’ll run into some obstacles with the way navigation works, but I do want to bump the priority of some investigation of this, as it would be a solid contribution to our efforts to reduce data consumption with images, tracked in https://github.com/zulip/zulip-mobile/issues/3853 and https://github.com/zulip/zulip-mobile/issues/3026#issuecomment-581011808

**Comment by gnprice** [comment]
> our efforts to reduce data consumption with images

One bit of context here is that there are (at least) two quite different kinds of loading going on:

* Fetching the messages in a given narrow, with their HTML content and a bunch of metadata like emoji reactions.

  This is done in our own code in the RN environment. It's triggered by the `fetchMessagesInNarrow` call (more precisely, by the `dispatch` around that) in the implementation of `doNarrow` in `messagesActions.js`. It's completely under our own control; see `isFetchNeededAtAnchor` for how we already avoid a fetch in certain cases.

  I interpret this issue report as being about this kind of fetch. I think we can address it mostly by expanding `isFetchNeededAtAnchor` in the direction sketched by a comment there:

      // Ideally this would detect whether, even if we don't have *all* the
      // messages in the narrow, we have enough of them around the anchor
      // to show a message list already.  For now it's simple and cautious.

  Maybe plus some logic to e.g. take advantage of what we know about a whole stream when you go to a topic within it.

* Fetching the images referred to by the HTML of the messages in a narrow.

  This is done by the browser, in the course of rendering the webview we use for the message list. For many users this is also important. I think it's best tracked as a separate issue from re-fetching the message data itself, though.

  #3382 is an important part of this (it covers the case of user avatars); there's also files people have uploaded to Zulip, and images elsewhere that are shown as previews when people link to them.

  #3853 is related, but focuses on the case where you're not even navigating around, and things are just getting updated (like new messages arriving, people leaving reactions on messages, etc.)

**Comment by WesleyAC** [comment]
This is superseded by #4641 and #4642 — once we do those, this problem should be fixed.
