### ISSUE TITLE
Password field shows blank (but works), sometimes

### ISSUE THREAD

**Issue by MikeMason3** [zulip/zulip-mobile#3182]
When running in debug mode, Using react-native run-android, we have found 3 error when logging into the application:
1- When asked for a password the application will not show the borders around the password or username
2 - The password section will not show the cursor or the enter characters and appears blank
3 - The "Hide" button for the password will not show or hide the password. 

Entering the correct username and password works, You just get no visual feedback when entering the password 

*attached are screenshots that can better help understand- the first pictures are Android phone and the second and third pictures are iphone example of correct implementation of code. *
![android](https://user-images.githubusercontent.com/27503563/49315818-9ec80780-f4b4-11e8-96cc-e0a476823cce.jpg)
![iphone zulip](https://user-images.githubusercontent.com/27503563/49315800-92dc4580-f4b4-11e8-8ec5-9d4501bfa304.png)
![iphone zulip1](https://user-images.githubusercontent.com/27503563/49315813-9a9bea00-f4b4-11e8-899f-dea3d9c08e76.png)

**Comment by gnprice** [comment]
Thanks @MikeMason3 for the report and these screenshots! This is very helpful.

This is a pretty bad bug when a user is first setting up the app; it'd be a great one to fix quickly.

**Comment by gnprice** [comment]
@borisyankov reported reproducing this on iOS, and @jainkuniya reported that he can sometimes reproduce, and sometimes not. So I think this isn't dependent on OS after all; @MikeMason3 was just lucky on an iOS device and less lucky on an Android device.

**Comment by mbuotidem** [comment]
@gnprice Yes, we were indeed running a recent version from master. @MikeMason3 is a classmate.
