### ISSUE TITLE
Emoji added from iPhone adding extra characters

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3183]
I noticed that using an apple keyboard emoji on the iPhone ( the shrug emoji in a shade of brown ) adds extra characters after sending. Attaching an image for reference. Can also be seen in [this message](https://chat.zulip.org/#narrow/stream/153-hacker-news/subject/Spectrum.20is.20joining.20GitHub/near/666857)

<img width="299" alt="screen shot 2018-12-01 at 3 09 35 am" src="https://user-images.githubusercontent.com/322991/49316542-48d87b80-f517-11e8-8822-7d701a0439a1.png">

*Shrug*

I've definitely seen this bug in the past and tried searching for an issue with appropriate keywords but came up empty. Sorry if this is a duplicate.

**Comment by armaanahluwalia** [comment]
Embarrassingly I also realized at full-screen resolution that the emoji is not my gender ( that would be a PEBKAC error ).

**Comment by gnprice** [comment]
Thanks @armaanahluwalia !

I think this is #1746.
