### ISSUE TITLE
feature: upload a file (not just image/video), on Android

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3184]
@diolwe mentioned:
> The current mobile app lacks features like file-upload (pictures only) and is not as clear as the browser version. That's why we use the browser with Zulip on phone and tablet.

in zulip/zulip#10645, by way of background in reporting an issue with the webapp on a mobile browser.

This feature is probably most relevant on Android, where there's a shared filesystem all apps can use.

This isn't a common request, so it isn't currently a priority, but it makes sense as a feature we'll want to add at some point.

**Comment by lukasIO** [comment]
I think the lack of video upload support makes the current situation a lot worse.

**Comment by jainkuniya** [comment]
@zulipbot claim

**Comment by cyphase** [comment]
I'd like to voice my fervent support of this feature :). How difficult would this be to add? What's required?

**Comment by borisyankov** [comment]
I don't think it is too difficult.
Maybe @ishammahajan is interested in working on this?

**Comment by ishammahajan** [comment]
Sure! I'll take it up.

**Comment by carlanwray** [comment]
I don't know what is involved in adding file upload, but in teams where they run support for a mobile worker (think construction or trades that need to feed info back to their team) the ability to do voice messages is extremely desirable. (I realize that this isn't exactly related to file upload I know that we would need to complete https://github.com/zulip/zulip/issues/9081 to get inline previews of the audio files but it might be something to consider as you work on this. I'm new to the Zulip project so I am just getting familiar with things but I'll help in any way I can.

**Comment by ishammahajan** [comment]
Have pushed a potential solution. Works on Android, would be great if someone tested on iOS after iCloud support has been added.

**Comment by gnprice** [comment]
Adding a cross-reference so we can find related discussion: #117 is for us to receive (on Android) things shared from other apps, including files. I think these two features cover a lot of the same use cases.

**Comment by gnprice** [comment]
> Have pushed a potential solution. Works on Android, would be great if someone tested on iOS after iCloud support has been added.

Hmm, in fact let's consider that a separate feature and discuss it separately. It's not clear to me that it necessarily should or will work the same way.

Several of the users who have asked for this feature are specifically thinking of Android, and I don't know of any who are thinking of iOS. In the years that I was an iOS user, this wasn't a kind of feature I remember trying to use; and looking at Slack just now, on an iPhone where I'm logged into iCloud, I don't see any kind of "upload from iCloud" feature -- in the spot in the UI where Slack on Android will open a file picker, Slack on iOS just offers to open my camera roll.

So I'm going to narrow this issue to be explicitly just about Android. If anyone *is* specifically interested in a version of this feature for iOS (either from iCloud or some other variation), please file a new issue and link to this one.

**Comment by gnprice** [comment]
Bumping the priority because I think this is probably closer to resolution than #117, and will cover a large chunk of what people want from that feature request.

**Comment by andreasoc** [comment]
is very important this features for mobile users

**Comment by andreasoc** [comment]
ieeeeeeeeeeee

**Comment by gnprice** [comment]
@andreasoc :smile: 

I just sent 26.1.124 to beta, with this feature; please [join the beta](https://github.com/zulip/zulip-mobile#using-the-beta) if you haven't already, and give us feedback on what you see!

**Comment by lukasIO** [comment]
> Several of the users who have asked for this feature are specifically thinking of Android, and I don't know of any who are thinking of iOS. In the years that I was an iOS user, this wasn't a kind of feature I remember trying to use; and looking at Slack just now, on an iPhone where I'm logged into iCloud, I don't see any kind of "upload from iCloud" feature -- in the spot in the UI where Slack on Android will open a file picker, Slack on iOS just offers to open my camera roll.

i find this a bit odd. 
uploading other files than photos (the only thing possible right now on iOS) is something that iOS users don't want? I'm on iOS and I would be very happy about pdf/video/etc. upload. 
the way it seems to me is that the divergence (on a supposedly cross platform repo) is being widened by picking out issues like this one and closing it by saying "well, we'll just implement it for android, until someone complains". 
because you mentioned slack: when I open slack I get the option to choose from any file on my iCloud drive, not sure what you are seeing there or maybe it's a recent feature?

**Comment by jbowkett** [comment]
@gnprice I just updated to the beta version 26.5.128 on Android version 9 on my Google pixel xl and after a restart I don't see share to zulip (for instance from the photo gallery).  Do I need to activate it somewhere in the settings?

**Comment by andreasoc** [comment]
> @andreasoc 😄
> 
> I just sent 26.1.124 to beta, with this feature; please [join the beta](https://github.com/zulip/zulip-mobile#using-the-beta) if you haven't already, and give us feedback on what you see!

joined ! 
i tried uplaod an pdf and work fine, but if open the file on zulip receive an messagge: ' impossible to opne the file "name of file". If open the file from the Windows App, the files opens

**Comment by maltokyo** [comment]
I joined the beta with iOS, and still cannot upload video.  Only photo upload is possible.

**Comment by gnprice** [comment]
@lukasIO Thanks for the feedback! We have an issue now for this same feature on iOS: #4586.

@maltokyo Thanks for the report! That sounds like an independent issue, and I see you went on to file it as its own thread: it's #3624, for cross-reference for anyone reading this thread in the future.

**Comment by gnprice** [comment]
@jbowkett That feature is #117 and is coming soon :slightly_smiling_face: . This thread was about the flow when you're already in the Zulip app, composing a message, and you attach a file from there.
