### ISSUE TITLE
Set `priority: high` in GCM for notifications of messages

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3185]
As explained in [upstream GCM reference docs](https://developers.google.com/cloud-messaging/http-server-ref): 

> **`priority`**
> Optional, string
>
> Sets the priority of the message. Valid values are "normal" and "high." On iOS, these correspond to APNs priority 5 and 10.
> 
> By default, notification messages are sent with high priority, and data messages are sent with normal priority. Normal priority optimizes the client app's battery consumption, and should be used unless immediate delivery is required. For messages with normal priority, the app may receive the message with unspecified delay.
> 
> When a message is sent with high priority, it is sent immediately, and the app can wake a sleeping device and open a network connection to your server.

and in [a guide doc](https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message) linked from there:

> GCM attempts to deliver high priority messages immediately, allowing the GCM service to wake a sleeping device when possible and open a network connection to your app server. Apps with instant messaging, chat, or voice call alerts, for example, generally need to open a network connection and make sure GCM delivers the message to the device without delay. Set high priority if the message is time-critical and requires the user’s immediate interaction, and _beware that setting your messages to high priority contributes more to battery drain compared to normal priority messages_.

We're letting our GCM messages default to "normal" priority; they should be "high".

This is made a little subtle by the fact that we've begun to send messages that *shouldn't* be high priority, namely "remove this notification" messages. So a bit of thought will be worthwhile in setting the right API for the Zulip app server and the bouncer to communicate about this.

I have some thoughts on this and the start of a branch; will finish up sometime and send.

**Comment by gnprice** [comment]
(ISTR from when @borisyankov and I dug into this that on the APNs/iOS side, our messages are already being handled appropriately in this respect. In any case for reference here's [the corresponding reference doc for APNs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns); the corresponding setting there is an HTTP/2 header called `apns-priority`.)

**Comment by timabbott** [comment]
On the backend, it's a slightly different code path for the "new message" vs. "remove message" things anyway, so I don't think it'd be challenging at all to set a different priority level for those two paths.
