### ISSUE TITLE
Cannot cancel unsent messages

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-mobile#3186]
Might have gone overboard with the blurring, but here's a screenshot -
![image](https://user-images.githubusercontent.com/917126/49382321-d1753880-f71e-11e8-8b61-6c9a6375742a.png)

Basically I have two messages that failed to send for some reason and I cannot cancel them (the cancel button in the menu that comes up does nothing). I've tried force closing and clearing the cache (haven't tried reinstalling the app yet) but the messages always pop back up after I open the chat. Basically the end result is that I have two messages that are always stuck at the bottom that won't send and can't be cleared.

**Comment by borisyankov** [comment]
I think the 'Cancel' option is a bit misleading here. It is duplicating a functionality that is standard in IOS and means 'Cancel this menu'.
You should see a 'Delete' option and that should work for you.

Restarting the app should trigger a proper resend, though it is a bit weird that you have such old messages that are still not sent.

**Comment by zingmars** [comment]
There is no "Delete" option though. All I'm offered are the "Copy to Clipboard", "Share" and "Cancel" options.

**Comment by borisyankov** [comment]
Do you mean that they recently got sent? Or at the time you sent them?

So the bad news is we have few bugs around the unsent messages retrying, duplicating, and now I guess not cleaning up. The good news is that they happen rarely so we didn't got many reports about them.

**Comment by zingmars** [comment]
I actually have no idea when exactly they got sent. In the other person's log the messages appear to be in the right order though so either they got sent when they should have been or during the initial retry. I'm actually not quite sure why they didn't send in the first place (maybe I had a bad signal?).

Anyway, other than clearing all app data and relogging, how would clear those messages out?

**Comment by borisyankov** [comment]
I just did fix another bug, the fix to which I hope will be available soon.
We actually do support the deletion of unsent messages but we incorrectly hide the option!

**Comment by zingmars** [comment]
Alright, I'll wait for that then.

**Comment by gnprice** [comment]
It sounds like the bug here was that the "Delete message" option wasn't showing; that was fixed in #3189.
