### ISSUE TITLE
Unsent message stays stuck with spinner even after sent

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3203]
@armaanahluwalia observed the following on 20.0.104 (as summarized by @gnprice after some debugging):
"""
* A message didn't send initially,
* but then it did send almost an hour later,
* and we got new messages in that thread (maybe via the event queue, maybe via a fetch when you went back to that narrow, not sure yet) -- including that message itself,
* but we didn't match up that message with the message we'd tried to send, so we've kept showing the trying-to-send message.
"""

The "unsent" message is always shown at the bottom, so it makes it look like we're also not getting new messages -- they just show up above the old, "unsent" message.

---
Original description:

An issue about messages failing to be sent has been reported several times in the chat:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Unread.20message.20bug
https://chat.zulip.org/#narrow/stream/48-mobile/subject/messages.20not.20loading

Starting investigating the issue and marking this as P0 as it looks frequent enough thus severe.
If it is a regression it a release blocker.
If not a regression but an existing behavior, still a high-priority issue to work on.

**Comment by borisyankov** [comment]
I decreased the severity to `P1` as it seems this happens from time-to-time and not always for the people who reported it.
This is pointing to an existing (bad) behavior and not a regression.
I am working on that actively.

**Comment by borisyankov** [comment]
@armaanahluwalia we did just discuss this issue with @gnprice and it seems there are two issues, one might happen sometimes but is more minor, the one I describe here.
The other is the server queue is not being reestablished. And this is the thing that causes you to not get any new messages.

**Comment by gnprice** [comment]
We dug into the state on @armaanahluwalia 's device, and learned that the issue was not what it seemed!

I'm editing this issue to reflect that report, which is the one we've learned the most about; we'll make a separate issue (or two) for the other reports.

**Comment by gnprice** [comment]
After our debugging, my hypothesis for what happened is that: when we eventually sent the message, we didn't have a live event queue.

That would cause us to not get an event for the message -- which would indeed cause us to continue showing the "unsent" message indefinitely.

A couple of things we can do to fix this:
* We shouldn't try to send messages when we don't currently have an event queue we believe is live. That just sets up this situation... and if our chances are reasonable for successfully sending a message, we should also be able to get an event queue established soon anyway, so this is not much of a limitation.
* When we successfully re-establish an event queue, we should drop all outbox messages with `isSent: true`. These are messages we know we've successfully sent, but are keeping around so as not to have the jarring experience where a message briefly disappears on send and then reappears. When we re-establish an event queue, we know we're going to be fetching for any narrows we look at, so we'll get the message that way and don't need the outbox placeholder version.
