### ISSUE TITLE
Search header

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#321]
For 'Search Messages' and 'Search People' use a custom Screen component.
Instead of the search box being below the header, it should be inside the header (look for example at mobile YouTube).

**Comment by TomaszKolek** [comment]
Will try:
@zulipbot claim

**Comment by TomaszKolek** [comment]
I'm investigating how it works and I found one thing that I'm not sure about:

In `Screen.js` we execute:
`const { keyboardAvoiding, title, nav, children, popRoute } = this.props;`
the props look like:
```
props: {
    keyboardAvoiding: boolean,
    title: string,
  }
```
as far as I know `children` is the ReactNative magic prop but what with `nav` and `popRoute`?
`connect` looks like:
```
export default connect((state) => ({
  orientation: state.app.orientation,
}))(Screen);
``` so it doesn't bind `boundsAction`

Could you explain me how does it work?

**Comment by borisyankov** [comment]
Just noticed your question from before...

This part:

```
props: {
    keyboardAvoiding: boolean,
    title: string,
  }
```

is Flow type definition and is not always up to date.  (we need to improve upon that in future)

Meaning you can pass whatever props you like, even if they are not listed there ;)
