### ISSUE TITLE
refactor updateExistingStream: Reduce api calls on changing stream details.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3222]
Currently if user changes stream name and description, then we are making two API calls. On the other hand `streams` API endpoint is generic and can handle multiple properties at the same time. So redactor `updateExistingStream` method, so that in such cases only one request is send to server.

https://chat.zulip.org/#narrow/stream/3-backend/topic/api.20.2Fstreams.2F.24.7Bid.7D

@zulipbot claim

**Comment by gnprice** [comment]
This was fixed by be12766bc2451afda2ff99b26b219b617c9055be / #5341 .
