### ISSUE TITLE
account screen layout issue: Component under `ComponentList` are not rendered properly.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3228]
![image](https://user-images.githubusercontent.com/18511177/50283369-b7a45700-047b-11e9-83b2-9c2d3e07a6de.png)

**Comment by gnprice** [comment]
Huh fascinating -- thanks for catching and diagnosing this!

I'm curious what broke it. Do you know anything about what caused this to break? You use the term "regression" in your PR, which sounds like saying that you do.

**Comment by gnprice** [comment]
Also I get different behavior, even on the parent commit of your PR:
![image](https://user-images.githubusercontent.com/28173/50469516-9d79e580-0961-11e9-9097-71c7d0f52ccb.png)

Still broken layout, but the information is all there; just not spaced appropriately, and the "Send private message" button is missing. That's on both Android 8 and 9, on an emulated Pixel 2 and a real Pixel 2 XL respectively. So whatever's causing this is at least a little subtle.
