### ISSUE TITLE
Refactor narrow patterns.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3230]
Currently for stream narrow, narrow object is like:
 ```
{
operand: "NLP"
operator: "stream"
}
```

Now the problem is:
What if user is in such narrow and stream name changes? Our `getIsActiveStreamSubscribed` will start returning false. As we are comparing names
```
subscriptions.find(sub => narrow[0].operand === sub.name)
```

How to reproduce:
* Narrow to any stream.
* Change it's name, via Clicking on info button in nav bar in chatScreen.
* Now navigate back to chat screen after changing name.

Observation:
* "Not subscribed" message is displayed instead of `ComposeBox`.
* NavBar is gray.

Same goes for PM narrow, on changing email.

@gnprice @borisyankov 
What should be the priority of this issue?

@zulipbot claim

**Comment by borisyankov** [comment]
This is not the only issue. We will be trying to fetch more messages for a non-existing narrow too.

**Comment by borisyankov** [comment]
I think the title of this issue is quite generic and misleading, rename to something that better reflects the problem.

**Comment by borisyankov** [comment]
`ChatScreen` needs to have its `params.narrow` changed.
What we need to do:
```
if (stream renamed && we are narrowed to it) {
  goBack();
  doNarrow(newStringNarrow);
}
```

That will be a bit disruptive UI-wise though, but that is fine for a rare occurrence.

**Comment by gnprice** [comment]
Tracking this now as part of #4333.
