### ISSUE TITLE
Handle invalid API key by logging the user out

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3253]
On a successful login, we receive an API key from the server to be used for API calls.
There are cases where this API key might become invalid.

Currently, one way to do that is to request a new API key from `Settings => Your account => Api key => Show/change your API key`.
There might be other events that might require the API key expiration (security reasons etc).

In any case, when the API key is no longer valid the app is not handling this at all.
There is no way for the app to recover from that state, it can't make API calls nor request a valid API key.

The correct behavior is to log out the user and let them login again.

**Comment by gnprice** [comment]
This should not have been filed as a new issue; it was a dupe of #2770 .
