### ISSUE TITLE
messages: Sending a new PM in the app shows up in browser tab.

### ISSUE THREAD

**Issue by trueskawka** [zulip/zulip-mobile#326]
When sending a private message in the iOS app to another user:
- the web app browser tab shows the new PM icon,
- there is no desktop notification.

The browser tab should not show a new PM icon for the message sender.

**Comment by timabbott** [comment]
Ahh, yeah, one can detect messages sent by you in various ways; what we do on web I think is that we check if 'read' is in message.flags, and only notify you about unread messages.

**Comment by timabbott** [comment]
(One can also just check if the sender's user_id is yours)

**Comment by borisyankov** [comment]
Is the app missing to do something?

**Comment by trueskawka** [comment]
I think the web app is actually missing something in `static/js/unread.js` - since it's a web app issue, I'll close this one and open a new one in the main repo.

Thanks!
