### ISSUE TITLE
Scroll position got disturbed when keyboard show/hides

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3264]
Ideally: When compose box is focussed, keyboard pops and message list should scroll so that content shift upwards.
And then when keyboard hides, again message list should scroll to make sure that content shift downwards. 
This behaviour is normal and almost all chat apps follow this.

When this feature was implemented, this was working as expected. But recently, it seems to be broken.
Before it was working as expected on iOS. And on Android there was a small issue when list scroll is near to bottom. But now it is completely broken.

I have been working on it, and I guess I have figured out the problem. Will submit PR soon :)

@zulipbot claim

**Comment by borisyankov** [comment]
Another related issue is that the position is affected with `UnreadNotice` shown/hidden.
