### ISSUE TITLE
Support reading and setting own Away status

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3266]
This should be in our next release.
The back-end supports most of that, but there are more changes upcoming.
That work will evolve with it.

We should be able to:
* display other users' away status
* set own status
* fetch `user_status` on initial fetch
* be able to set textual 'busy/away' statuses like 'On vacation'
* display these statuses on the user's account page

**Comment by gnprice** [comment]
This was implemented a while ago, by #3263.
