### ISSUE TITLE
Can't copy and paste from previous messages.

### ISSUE THREAD

**Issue by daschuer** [zulip/zulip-mobile#3270]
I want to quote single sentences from a previous message.
The mobile client only allows to copy the whole message.
It is quite annoying to delete all the unused stuff from a long copied message.
It would be convenient to enble to select and copy the quoted sentence via the usual way.
With the two blue dots.
I use the Gboard keyboard and Zulip Android 21.2.106

**Comment by borisyankov** [comment]
I can imagine how we can implement this, but I am not sure of how often people need that.
Are there other chat apps that allow selection of parts of a message?

**Comment by daschuer** [comment]
GitHub in Chrome browser can do this. 
In Zulip, there are already the markers, but you just cant copy. Please enable it.

Alternative a kind of "Answer Inline" feature will also be great, something that does not allow to mess with the cited text.

**Comment by timabbott** [comment]
I would expect this to be particularly useful in Zulip in comparison to other chat apps, because people send a lot more multi-sentence messages in Zulip.

**Comment by timabbott** [comment]
(Options for improving this could include making it more convenient to delete the unused stuff from a copied message)

**Comment by borisyankov** [comment]
I could not find any app that does selective copying of text (even half of the apps did not offer any copy). This includes:
 * FB Messenger
 * Slack
 * Discord
 * Twitter
 * Facebook
 * Reddit

(the last two included because they have longer posts)

**Comment by borisyankov** [comment]
I am confused about what is the suggested solution?
The text in the compose box can already be selected and deleted in the normal and expected way with draggable handles. I am not sure we can improve much on that.

**Comment by daschuer** [comment]
Yes you can, but it is quite annoying, if the source message is a wall of text and you want to cite only a single line, all that on a tiny mobile phone screen with scrolling involved. 

> I am confused about what is the suggested solution?

The proposed solution is that it should work like here in GiHub (just done):
* scroll to the line you like to quote.
* long press the part you need. 
* adjust the marked region in the line in a long message using the two blue handles
* Copy the part
* Drop the Part into the edit window

**Comment by borisyankov** [comment]
The long-press gesture conflicts with our already existing message menu that we activate on a long-press.

Also, selection would have been very tricky to do but luckily we use a WebView, which makes this selection at least possible.

I am not sure what the best UI that would not conflict with our other interactions.

**Comment by borisyankov** [comment]
@jainkuniya about this #1790 issue you fixed long time ago.
How bad was it? Did you decide to fix it yourself or was someone complaining?

**Comment by borisyankov** [comment]
A modal is a possibility I didn't think of. Seems a bit heavy-handed but would work, as long as we render the message as HTML of course.

The other implementation I examined is 'Copy to clipboard' to be turned to just 'Copy message' and we actually select the message in the WebView, then the user can copy parts of it.

During experimenting, I managed to start Google Translate, apparently, some of these gestures on a webpage start it, and also the app crashed for some reason 😄 Does not look as straightforward of a solution.

**Comment by daschuer** [comment]
> The long-press gesture conflicts with our already existing message menu that we activate on a long-press.

What is on the short press? Can this start the context menu?
If this is not possible, the context menu can be started on the headline only.
I like the soution shown in Zulip in Mobile chrome browser very much.

**Comment by gnprice** [comment]
> In Zulip, you can set the selection cursor int previous messages.

I'd be curious to hear more about this. If I understand correctly what you mean, then I'm unable to reproduce it (on v24.0.113 on Android 9).

Could you post a screenshot of what it looks like when you do this?

When I long-press on the text in a message (which is the usual gesture I use for selecting text), I get our long-press menu. Even if I arrange things so the text I long-pressed on is still visible after the menu comes up, I don't see it selected.

**Comment by daschuer** [comment]
I am now at v23.3.112 and I cannot set the selection in a previous message anymore.

**Comment by gnprice** [comment]
> I am now at v23.3.112 and I cannot set the selection in a previous message anymore.

Good to know -- thanks for the update! And thanks for writing in with the original feature request.

For the reasons @borisyankov mentioned above, I think we won't end up adding this feature as described. You may be interested in following #1975, which is for a "quote and reply" option -- and once the message is quoted in the compose box, you can of course select and delete the parts you don't want, even if that's not quite as convenient when you want one sentence of a really long message.

The quirk where selection half-works sounds like a bug; since you can't reproduce it anymore and nor can I, we'll presume it was fixed sometime since 21.2.106. If anyone sees that behavior again, please file an issue for it and we can investigate.
