### ISSUE TITLE
More sophisticated system for uploading images

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3271]
Sending an image message takes two steps:
 * uploading the image
 * sending the message with the image

Two problems with that:
* If the first step fails, the upload is never retried
* we show a message preview only after the image upload succeeds, which is the longer part of the process

Ideally, we will track all image uploads and retry them if they fail.

**Comment by gnprice** [comment]
This is a multi-issue issue, which is better tracked as separate issues. (Something like this could be useful if describing work on a specific system to address the issues, but this one never functioned as that.)

The lack of a preview or other feedback is #2684. For the retry, I'm dubious that just always retrying is the right thing anyway. #3829 describes the foundational thing I think we want here, for messages in general; and we can file specific issues for further upload-specific wrinkles as we get into them.
