### ISSUE TITLE
Keyboard overlaps the compose box on iOS

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3273]
This is a release-blocker issue on `master` and `107`

Discussed here
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Keyboard.20placement.20on.20iOS

**Comment by gnprice** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/28173/51139940-126e6b80-17fa-11e9-9729-f52a255c9365.png)
