### ISSUE TITLE
Scrolling through topics on iOS is not working

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-mobile#3286]
Trying to scroll, topics jump around and won't stop scrolling. https://photos.app.goo.gl/hK1bj9RmvLTBF8i2A demonstrates the behavior on @vietdnguyen's phone (and @rhausam is experiencing the same).

**Comment by gnprice** [comment]
Thanks @jmandel for this report!

It turns out this is the same as another issue we'd filed a couple of months earlier: #3176 . Which in turn is fixed in master since yesterday.
