### ISSUE TITLE
Placeholder Text padding shows irregularity

### ISSUE THREAD

**Issue by Jigar3** [zulip/zulip-mobile#3295]
![whatsapp image 2019-01-18 at 10 51 59 am](https://user-images.githubusercontent.com/32068121/51367146-3f2ec580-1b0f-11e9-8aa1-a8a78bb7d0b9.jpeg)
The placeholder text padding is not perfect when I opened it for the first time.

![whatsapp image 2019-01-18 at 10 52 00 am](https://user-images.githubusercontent.com/32068121/51367143-3d650200-1b0f-11e9-8a18-ed197937ef8b.jpeg)
After clicking on the inputbox, the padding becomes correct.

I want to take up this issue. Can anyone explain what might cause this behaviour to happen?
@zulipbot claim

**Comment by borisyankov** [comment]
@timabbott has indicated that this is an important issue to fix quickly.

I suggest we give @Jigar3 a chance to find the issue if he has time in the next few days, if not @jainkuniya you should find and fix the issue 👍 

@Jigar3 indeed `git bisect` is your best bet. Also, a great opportunity to learn how it works (I am not assuming you already do, as most people don't).

You can see all the tags with `git tag`. This was likely introduced in one of the most recent releases. Check 106, or 105 and once you've found a commit that this issue does not exist use bisect to (surprisingly) quickly find what commit did introduce this bug.

**Comment by Jigar3** [comment]
@borisyankov I will definitely try to resolve this issue thanks for the chance

**Comment by gnprice** [comment]
Thanks @Jigar3 for reporting this issue! We'd been noticing it for a little while, but hadn't gotten around to taking care of it. And thanks @jainkuniya for some good systematic debugging and for the fix :smile: .

FTR I'll quote here @jainkuniya 's observations from debugging, as recorded in commit 6351c8e07 which fixed it:

```
* Only reproducible when compose box is shown after message loading
  (GIF like loader) after narrowing on Android.  Can't reproduce on
  narrows whose messages are cached and immediately visible after
  narrowing.

* If on the topic input (a) the `this.getCanSelectTopic()` condition
  is removed and (b) the `multiline` prop is set, it starts showing
  the issue, just like the message input.

So from this it can be inferred that:

* It is a `multiline` input issue, which occurs when its parent first
  got rendered with `display: none`.  Normally it is not reproducible
  on topic input because at the time of first render (when style is
  `display: none`), topic input is not rendered (because
  `this.getCanSelectTopic()` is false).

So to fix this issue, use the normal React pattern for conditional
rendering, so that the input component doesn't get created at all
until we want to show it.
```
