### ISSUE TITLE
Attached picture is posted before caption is typed

### ISSUE THREAD

**Issue by Be-ing** [zulip/zulip-mobile#3299]
When attaching a picture to a post, the picture is posted in its own post before I can type a caption. I wanted to post the picture and caption in the same post, but someone else commented on the picture before seeing the context I provided with the text caption.

**Comment by armaanahluwalia** [comment]
This will be addressed by #2887

**Comment by chrisbobbe** [comment]
Thanks for the request! Closing as a duplicate of #4540, fixed in #5474.
