### ISSUE TITLE
Cannot connect to server - Wildcard SSL cert

### ISSUE THREAD

**Issue by msirkoch** [zulip/zulip-mobile#3308]
I'm running into the same issue described in #2909 with our hosted Zulip server and connecting to it with the Android app.  My SSL cert is valid and seems to be installed correctly based on what I can tell from the desktop web browser.  One thing to note though, my SSL cert is a wildcard cert.  Does the Android app support wildcard certs?  If so, can someone please point me in the right direction in terms of how I can look at the logs generated by the Zulip Android App?

**Comment by gnprice** [comment]
Thanks @msirkoch for writing in, and sorry this response is probably too long delayed to be helpful for you. For anyone finding this in the future:

Take a look at https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html#troubleshooting . The most likely issue is that your SSL certificate isn't installed correctly (e.g. you haven't provided a proper certificate chain to nginx). In particular some browsers will accept an incomplete chain, but not others and not the Zulip mobile or desktop apps.
