### ISSUE TITLE
Android emoji being horizontally cropped on ending line

### ISSUE THREAD

**Issue by whoodes** [zulip/zulip-mobile#3318]
Running on Android, emojis are being cropped incorrectly if they are on the bottom line of the message and written without accompanying text.  The following screenshots demonstrate the issue:

![zulip-emoji-bug1](https://user-images.githubusercontent.com/39782863/51874850-b251ec00-2306-11e9-91f4-5f2fb07ac884.jpg)

![zulip-emoji-bug](https://user-images.githubusercontent.com/39782863/51874853-b67e0980-2306-11e9-8be4-f966547c3609.jpg)

**Comment by pranavpandey1998official** [comment]
i want to work on this issue

**Comment by gnprice** [comment]
Thanks @whoodes for the report and screenshots! This is #2693.
