### ISSUE TITLE
Emoji being shown twice when enclosed within a bold or italic markup

### ISSUE THREAD

**Issue by SivagiriVisakan** [zulip/zulip-mobile#3321]
When a message is sent with an emoji wrapped inside a bold or italic markup , for example as `** :tada: some text**`, then the emoji is shown twice.(see screenshot attached)

![image](https://user-images.githubusercontent.com/27341353/51995219-4e7f1d00-24d8-11e9-8474-b2a2ac2c3759.png)

See discussion: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Emoji.20issue.20when.20enclosed.20within.20bold.20or.20italics.20markup

**Comment by jainkuniya** [comment]
This is a server side issue #11621. So will be fixed there, no need to do any changes in the `zulip-mobile` codebase.

**Comment by gnprice** [comment]
Fixed on the server, as zulip/zulip#11621 . Thanks @SivagiriVisakan for the report!
