### ISSUE TITLE
Mention Autocomplete Popup Visibility Problem

### ISSUE THREAD

**Issue by armaanahluwalia** [zulip/zulip-mobile#3340]
When I type in a message longer than one line, the mention autocomplete popup does not appear as it should.

May be related to #2917

See attached video for a reference
[Bug Video](https://streamable.com/oi48k)

**Comment by jainkuniya** [comment]
#3290 will fix it, Thanks for the report @armaanahluwalia

**Comment by gnprice** [comment]
Thanks @armaanahluwalia for the report and the helpful video!

> #3290 will fix it

In fact, following a link from there, it looks like this issue is the same as #3289. Closing this one to avoid duplication.
