### ISSUE TITLE
Travis CI build failure due to lint

### ISSUE THREAD

**Issue by AB261** [zulip/zulip-mobile#3353]
The command "tools/test --full --coverage" is exiting with return value 1 and is preventing PR from getting accepted. The problem lies in lint 
![lint_problems_zulip_mobile](https://user-images.githubusercontent.com/17261046/52987970-73a1e400-3423-11e9-9ccc-096af9876ff6.png)

**Comment by AB261** [comment]
@zulipbot claim

**Comment by gnprice** [comment]
Fixed in #3533. Thanks @AB261 for the report!
