### ISSUE TITLE
accountDetails: Presence status is being shown on avatar.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3361]
In account details screen, we already show presence status below avatar. So there is no need of showing it on avatar image too.
![image](https://user-images.githubusercontent.com/18511177/53250905-6154ce00-36e1-11e9-92a4-290b9ca3e7b6.png)

@zulipbot claim

**Comment by gnprice** [comment]
Thanks @jainkuniya for reporting this!

@borisyankov , I think one of the changes you had queued up in a PR was going to fix this. Please mention this issue in that commit. :slightly_smiling_face:
