### ISSUE TITLE
Warn on @-mentioning someone who won't see it because not subscribed

### ISSUE THREAD

**Issue by opensource21** [zulip/zulip-mobile#3373]
Referenced users do not receive notifications from unsubscribed streams. See github issue. Unfortunately there is no warning at mobile-client :-( This is a ugly pitfall if you think you have notice someone, but the person didn't get any information.
See https://chat.zulip.org/#narrow/stream/48-mobile/topic/Referenced.20users.20on.20unsubscribed.20streams/near/709487

**Comment by timabbott** [comment]
Yeah, we should fix this.  

For this category of things, there's a few parts of the webapp code we may want to study/adapt. 
* `exports.notify_local_mixes` in `static/js/notifications.js`  (things we do after you send a message)
* `validate_stream_message_mentions` and the handful of functions after it in `static/js/compose.js` (validation/warnings/etc. we do before you send a message)
* The `$(document).on('usermention_completed.zulip', function (event, data) {` handler in `static/js/compose.js`, which is where the webapp checks for this particular issue (this happens right after completing the mention in the typeahead)

**Comment by gnprice** [comment]
Bumping the priority, because this can be pretty frustrating for everyone involved when it happens.

**Comment by sumukhah** [comment]
working on the issue

**Comment by sumukhah** [comment]
@gnprice 
I would like to take this issue..
But i have no idea, where to begin, if you could help me i am happy to work on this :)

**Comment by chrisbobbe** [comment]
Looks like zulip/zulip#14966 was just closed, so work on this can continue! 🙂  Thanks @akashaviator and @timabbott!
