### ISSUE TITLE
[Android] composeBox: Nothing happens after selecting item in autocomplete pop up.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3378]
This is Android specific. On iOS it works absolutely fine.

With the awesome `git` tool, `git bisect` I was able to find out which commit introduced it. And it was my commit only. I have never imagined that just `backgroundColor` can affect in such a way.

Commit which introduced this is: 041ce55e

I guess issue is in RN, when there is `absolute` component inside a `view` which has `backgroundColor` property on Android, then it doesn't receive any touchable event. And thus in our case nothing happens on touching items in autocomplete list. Also not able to scroll the autocomplete list.

Reported: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Problem.20with.20mention.20popup

@zulipbot claim

**Comment by gnprice** [comment]
Thanks @jainkuniya for tracking this down!

And glad `git bisect` worked well for you. It is indeed a powerful tool -- especially helpful for diagnosing an issue like this one that is triggered by something totally surprising that seems like it shouldn't have any connection. :smile: 

One further observation: it's not quite that *nothing* happens when you tap an item in the popup. Instead, the touch event goes right "through" the popup, and hits the message list. For example, if you tap a spot in the popup that's hiding a sender avatar, or a topic recipient bar, you'll navigate to the account details or the topic narrow respectively.

We had a previous bug with exactly the same symptoms, of taps on the autocomplete popup going through to the message list. Let's see if I can find it...

**Comment by gnprice** [comment]
The previous issue was #3209 . That one happened only some of the time.

That one was also Android-only, and like this one it was pretty mysterious:

> This is a regression in 21.0.104 (and 21.1.105). Using `git bisect` to do a binary search, I found that it was introduced in 824c908cc aka #3065. It doesn't seem obvious how that caused this issue, though, even when I reread it now knowing that it somehow did.

That one was fixed by #3210 aka 3910f2d69 . Hmm, and that fix also involved avoiding `position: 'absolute'`:
```
-      ...(canSend ? {} : { opacity: 0, position: 'absolute' }),
+      ...(canSend ? {} : { display: 'none' }),
```

**Comment by gnprice** [comment]
Copying back here a comment you made on your PR #3379 to fix this:

> I tried to reproduce it on new RN project, but can't. May be I am not able to get exact scenario where it will be reproducible or may be there is not RN issue, just we are doing something wrong.
> 
> But on the current master if we just remove
> 
> ```js
> backgroundColor: 'rgba(127, 127, 127, 0.1)',
> ```
> 
> from `style` then it is not reproducible.

**Comment by gnprice** [comment]
Given that we've run into probably the same underlying RN issue twice now, it would be a very good use of time to track that underlying bug down and get it fixed.

Trying to reproduce it in a fresh RN project was a very good step. Given that that didn't work, here's the next thing I'd recommend trying:
* Start from our app, in a version where the issue reproduces, and start radically cutting out parts of the app while ensuring it still reproduces.
* In particular, try to cut out all the things that require data from the server -- that will also help you cut out most of the UI.
* For example, perhaps try a sequence of steps like this:
  * Cut out all the pieces of ComposeBox that seem completely uninvolved in reproducing the issue: TopicAutocomplete, ComposeMenu, the topic `Input`, the send button. Keep AutocompleteView and the message `Input`.
  * Replace the `AutocompleteView` with just a big `Touchable`.
    * Or if that makes the issue stop reproducing, do it in smaller steps: first, hard-code it to `PeopleAutocomplete`. Then, in `UserItem` remove almost everything except the `Touchable` and maybe some fixed text to fill it. Then make `PeopleAutocomplete` just use some hard-coded data to show a few items. Etc.
  * Take out the `connect` calls in `ComposeBox` and its remaining subcomponents. Replace the data with hard-coded data.
  * Similarly, gut `Chat` and `ChatScreen` -- remove `connect` calls and everything unnecessary.
  * Make `ChatScreen` the only screen of the app.
  * Remove Redux entirely.
  * Delete almost all the code -- everything not used in the one remaining screen.
  * Delete almost all the dependencies -- everything no longer being used.
* Any time cutting something makes the issue stop reproducing, cut it in smaller steps. Like the `AutocompleteView` example above.
* Make new commits constantly :smile: -- basically every time you cut something and confirm it still reproduces, make a commit. This will help out a ton whenever you go too far and have to put something back.
* Currently we're very "lucky" in that the issue reproduces 100% of the time. Try to keep it that way -- if one way of cutting makes it only sometimes reproduce, look for another one. 100% reproduction makes it a lot easier to make progress.
* If at some point you think you have an idea why your fresh app didn't reproduce the issue, maybe go back to the fresh app and try the idea there. But if not, that's fine -- this process will probably lead you to a small app eventually.
