### ISSUE TITLE
Misc feedback to be considered before release

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#338]
* [ ] There's no way to pick a stream/subject when composing a message, or recipient(s) when composing a DM. All you can do is respond to whatever is in the current view.
* [ ] As a byproduct of the above, you also can't fork a new conversation by modifying the subject.
* [x] There's no long press menu on messages. The old app had a really useful long press menu (eg, reply to stream, reply as DM).
* [x] Last message state isn't synced with other clients. The app always takes you to the most recent message, instead of the oldest unread message.

**Comment by neerajwahi** [comment]
> Last message state isn't synced with other clients. The app always takes you to the most recent message, instead of the oldest unread message.

This one is half fixed now. The app takes you to the oldest unread message, but it still doesn't sync the unread state.

**Comment by timabbott** [comment]
The rest are basically all mainly about issue of "we haven't built a compose box that can send to arbitrary recipients"; we should probably prioritize doing so.
