### ISSUE TITLE
Cannot scroll to the bottom in buddy list

### ISSUE THREAD

**Issue by overide** [zulip/zulip-mobile#3381]
When it reaches the halfway, it starts scrolling to the top (or at least seems like it). Please see the video for more detail - https://bit.ly/2Ewj0Rb

**Comment by pulkonet** [comment]
I have confirmed this behaviour, I am digging into the code to see what is causing this.

**Comment by jainkuniya** [comment]
I guess this issue from RN upstream, when using sticky header. @pulkonet can you once try removing it?

**Comment by pulkonet** [comment]
Yes, sure.

**Comment by pulkonet** [comment]
@jainkuniya Hi, I tested as you said and it is indeed an issue from RN upstream. The sticky headers aren't performing well. A fix has been submitted but the fix wasn't perfect IMO [PR here](https://github.com/facebook/react-native/issues/20956)

**Comment by pulkonet** [comment]
Shall we remove it altogether ?

**Comment by pulkonet** [comment]
There was a similar removal of sticky headers from the Unread Messages in #3305.

**Comment by gnprice** [comment]
Thanks @overide for the report and video, and @pulkonet for the investigation!

Our original report of this issue is #3176; closing to consolidate discussion there.
