### ISSUE TITLE
Correctly display user's status when 'unavailable'

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3384]
We support the user setting themselves to unavailable, but we don't yet correctly display when a user is unavailable.

This means two things:
* The icon should be the one we've chosen and now have on the web (rather than a gray disk.)
* The user shouldn't be described as "Active now", or "Active 15 minutes ago" etc.

More discussion here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/user.20status/

[edited by @gnprice ; corresponding original text below]

---

 * introduce the new 'Unavailable' status and do not treat it as 'Offline'
 * Render that new state exactly the same as on the web (a bit more tricky than the purely css solution)
 * Change the text for 'last active' if 'unavailable'

[See also #3406 for another followup previously included here.]

**Comment by gnprice** [comment]
Thanks @borisyankov for filing this!

I'm going to narrow this issue down to the most critical/urgent points, the better to track getting those taken care of; I'll file a separate issue for the rest.

**Comment by gnprice** [comment]
This was implemented by #3384.
