### ISSUE TITLE
Loading indicator on message list when data is stale

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3387]
Similar to #3025, but for the message list. This is an especially important UI surface for this situation because users often start the app by opening a notification, which navigates straight to the message list past the unreads screen.

One simple, good design for an indicator would be a banner a lot like our `OfflineNotice`, but instead of "No Internet connection", saying something like "Connecting to server...". That's a common design among other messaging apps.

**Comment by thedeveloperr** [comment]
New contributor to zulip mobile. Have only worked on zulip backend. Is this a first good issue for new contributor?

**Comment by anh2111htd** [comment]
@gnprice I notice this animation when loading messages:

![image](https://user-images.githubusercontent.com/19589970/55006391-9f168080-5018-11e9-8b15-d478f9d82faa.png)

It indicates the list is loading to me. In `MessageList`, by default,  `showMessagePlaceholders` is true, and this animation will show whenever `isFetching && noMessages`. For this issue, should I use the same check used for this animation and add a banner to make the indication clearer?

**Comment by anh2111htd** [comment]
@gnprice Fixed this in #3430, please review.

**Comment by chrisbobbe** [comment]
Hmm, once https://github.com/zulip/zulip-mobile/issues/3802 is fixed (which will probably be soon), will this still be a shortcoming in handling the loading state, or will it maybe be time to close this rather old issue and its PR?

**Comment by ray-kraesig** [comment]
I don't believe a fix for #3802 would help with this; the user would still be looking at old state for some time after clicking the notification.

**Comment by chrisbobbe** [comment]
> the user would still be looking at old state for some time after clicking the notification.

Mmm, right! The proposed fix for #3802 eliminates the "No messages" message during the period when we are re-registering, by showing the stale data, but it still doesn't indicate that the messages are stale. I like the idea of a banner for this, as mentioned here, since it's still helpful to see even stale messages when possible.

**Comment by gnprice** [comment]
> If I've understood the scope of this issue, this particular loading period (during, and only during, the /register request) is global and should be shown no matter what screen you're looking at (similar to the "No Internet connection" banner mentioned above). Actually, if this is correct, I believe #3025 may be identical to this issue.

Hmm, yeah, this may be the best way to do it. Certainly there's a long tail of screens that show data from the server, and that should have a loading indicator when our data from the server is stale; and it'd be best not to try to handle them one by one.

There are a few screens that shouldn't have this banner, because they aren't about any one server.
* The various onboarding and login screens might be taken care of for free, because it might be the case that `session.loading` is never true when we're on them. Needs investigation, though, as part of a PR.
* `AccountPickScreen` might be the most interesting: I believe if you hit "Switch account", you'll get to that screen but there's still an active, logged-in account and `session.loading` might still be true.
* The settings screens don't really need the banner, but it wouldn't seem out of place there either.
