### ISSUE TITLE
The upper edge of an iPhone X screen covers part of the UI in landscape orientation.

### ISSUE THREAD

**Issue by jackrzhang** [zulip/zulip-mobile#3389]
This really isn't a severe blocker in terms of usability, but I figure it's still worth reporting - 

On any iPhone X model, the upper edge of the screen covers part of the application UI in landscape orientation:
<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/54060091-76ddf380-41c9-11e9-9ec6-81b4326f60e7.png" width="610" />
</p>
<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/54060080-6594e700-41c9-11e9-96e6-f46d48baa2bc.png" width="650" />
</p>

Some of the code for a fix for this might be related to #3370.

I don't have a physical iPhone X device to use for testing, so it's also possible that this reproduces only on a simulator.

(@zulipbot add "area: iOS" "area:layout")

**Comment by gnprice** [comment]
Thanks @jackrzhang for this report and the screenshots!

This sounds like it's probably one of the symptoms of #3066 . I'm going to fold it into that one as a dupe, and copy these handy screenshots there so we have a nice concrete repro to test fixes against.
