### ISSUE TITLE
Doesn’t update my own avatar

### ISSUE THREAD

**Issue by andersk** [zulip/zulip-mobile#3397]
My mobile app never refetched my avatar after I created it on Gravatar. It still shows the autogenerated pattern in the bottom bar and the user list, although it shows the correct picture with my messages in the message list.

**Comment by borisyankov** [comment]
Thanks for reporting this.
I did investigate the issue and luckily it was easy to determine its cause:
https://github.com/zulip/zulip-mobile/blob/master/src/users/usersReducers.js#L33

**Comment by timabbott** [comment]
This actually highlights something we should be doing as preparation for the Queue 2.0 project.  Once we move to Queue 2.0, our data structures will no longer be automatically reset all the time by doing new `/register` requests.  As a result, data tracking bugs like this (and another that Greg and I were talking about yesterday with topic editing), which previously might have auto-correct on the next /register might result in semi-permanent incorrect state.

So we should probably prioritize doing a full audit of all of the event types produced by the zulip backend and whether the mobile app is correctly updating its data structures.  I think reading `zerver/lib/events.py` and/or `static/js/server_events_dispatch.js` is a good way to produce a list of things to audit.

**Comment by borisyankov** [comment]
That is a good point. I have started the audit and will document anything missing in a new issue.

FYI: I am already working on the users updating code as that is the most important missing functionality for Queue 2.0

**Comment by chrisbobbe** [comment]
Closing as fixed in 7296551876e91674330624212dd3a41bb8c30128.
