### ISSUE TITLE
Edit message from another stream

### ISSUE THREAD

**Issue by ungps** [zulip/zulip-mobile#3413]
Hello,

At the moment it is possible to edit a message in a stream from another stream. This seems to be an effect of #2757 .

Preview:
![issue](https://user-images.githubusercontent.com/24317622/54492338-54855d80-48ce-11e9-8484-862c2b17ac14.gif)

**Comment by ungps** [comment]
@zulipbot claim

**Comment by jainkuniya** [comment]
This is an old issue.

There are several PR to fix this
https://github.com/zulip/zulip-mobile/pull/2911

**Comment by ray-kraesig** [comment]
As this is just a symptom of #2757, closing in favor thereof.
