### ISSUE TITLE
Long messages in compose box make it overflow

### ISSUE THREAD

**Issue by Hypro999** [zulip/zulip-mobile#3414]
Once a message becomes long enough android users tend to face 2 issues:

1. Can't scroll down to view the rest of the message.
2. Can't hit send.

![screenshot](https://user-images.githubusercontent.com/29123352/54505065-5a298480-495c-11e9-8872-735f8f7f98d2.png)

thread (topic) on Zulip to discuss this issue: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Issues.20with.20long.20messages

**Comment by ungps** [comment]
@zulipbot claim

**Comment by ungps** [comment]
The send button is still there when writing in a topic, but it disappears when writing a long message in a stream (so the cause is probably the topic input box). I am going to look more into this when I get back from university.

**Comment by ishammahajan** [comment]
@ungps how does adding a multiline limit to this sound (referring to WhatsApp for example, which adds 6 lines before it stops expanding the text box)?

**Comment by gnprice** [comment]
Thanks @ungps for this report!

Take a look at #3369 (and in particular the video there). Does that appear to describe the same issue? Or if not, can you describe how this one is different?

**Comment by gnprice** [comment]
Putting a bound on the height is a reasonable direction for solving this, but it's important that we not limit it too tightly. See previous discussion on #3049 :

> I've definitely composed messages longer than 6 lines of text in the current Zulip app (and I think copying Messenger and WhatsApp isn't right for our context, because Zulip, being a work tool, is generally going to have more reason to send long messages explaining complex ideas). I do think we need to have a reasonably scrolling situation for this, but I think limiting to 6 lines is counterproductive.

That was followed with a sketch of the logic we would want:

> Then we want to grow the compose box up to the height of the whole screen when the keyboard is popped up. (height = screen.height - keyboard.height).
> If the user wants to see what was written, they can hide the keyboard.

but it doesn't look like it ever happened. So that would be a good solution.

@ungps , thanks for taking a shot at this with #3420! Want to try implementing the logic described above?

**Comment by borisyankov** [comment]
This is trickier to implement than it seems at first sight.
The ideal solution will consist of no manual calculations but will be only style-based with maybe some components moved around and optionally wrapper `View`s etc. added.

That might not be easy or even possible but is worth exploring.

The alternative is what Greg is saying, not only Keyboard should be considered but layout changes in general. So orientation change, or even the app screen changing its size - both Android and iOS now support multiple apps on the same screen.

**Comment by Hypro999** [comment]
@gnprice It's definitely a similar issue though not the exact same. In this case, I can't access the send button at all after a certain point. The topic also becomes completely inaccessible.

![](https://user-images.githubusercontent.com/29123352/54806826-3c805600-4ca1-11e9-85b6-f00bc2d8d0ab.png)
![](https://user-images.githubusercontent.com/29123352/54806829-3c805600-4ca1-11e9-93fa-f1901178aa11.png)

**Comment by jainkuniya** [comment]
I don't think this will get solved by just setting `maxHeight`.
Few observations:
* This is happening in stream narrow, not in PM.
According to me if it is related to message box height then what it it not happening in topic or PM narrow. 

If i would have to guess that this is related to view wrapper or topic input. Because it only happens when topic input is present.

**Comment by gnprice** [comment]
Thanks @Hypro999 for the reply! And for the screenshots.

> It's definitely a similar issue though not the exact same. In this case, I can't access the send button at all after a certain point. The topic also becomes completely inaccessible.

Hmm -- that seems like a small quantitative difference in the same issue. Here's a frame from @armaanahluwalia 's video in #3369:
![image](https://user-images.githubusercontent.com/28173/54960990-3d70ec00-4f1c-11e9-9ac8-d8047a54cc91.png)

Note that the send button is about 90% covered; and the topic is completely invisible, though part of the bottom padding in its input box still peeks through.

Let's consolidate this discussion on the original thread, #3369.
