### ISSUE TITLE
Subscriptions screen shows all streams as muted

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#342]
All streams appear muted even if they are not

<img width="371" alt="screen shot 2017-02-15 at 7 55 47 am" src="https://cloud.githubusercontent.com/assets/4666213/22982499/32ff109c-f354-11e6-9281-b4c28ad399f0.png">

**Comment by vishwesh3** [comment]
Will try:
@zulipbot claim

**Comment by borisyankov** [comment]
I did that already. Forgot to assign.

**Comment by vishwesh3** [comment]
ok :+1:
