### ISSUE TITLE
Android App Accept User Certs

### ISSUE THREAD

**Issue by DominikRobert** [zulip/zulip-mobile#3425]
Hello, I have the problem that I have a certificate from our CA and want to run zulip. In newer android version the certificates from the user are not used. So is it possible to allow user certifiactes?

The android Manifest should look like:
```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
      android:networkSecurityConfig="@xml/network_security_config">
```
and the @xml/network_security_config 

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true"></domain>
        <trust-anchors>
          <certificates src="user"/>
        </trust-anchors>
    </domain-config>
</network-security-config>

```

Can creat a pull request, so I paste my code here to solve this issue. Is it possible to integrate this in the official zulip app. With that the imported user certs are allowd under android devices.

**Comment by eurich** [comment]
Just a note: It's currently impossible to use **internal** servers (with a certificate signed from an internal CA) with the offical zulip mobile app.. 

I'd highly appreciate some kind of feedback from an offical team member here :)

**Comment by gnprice** [comment]
Hello! Thanks both for writing in.

I think this is the same issue as #3312 , so I'm going to close this thread to consolidate discussion there.
