### ISSUE TITLE
"Every time you say something my wrist vibrates."

### ISSUE THREAD

**Issue by glyph** [zulip/zulip-mobile#3431]
## The desired behavior

Please detect when I'm literally looking at a Zulip window, actively typing back and forth to another user, and don't send me a mobile notification for every message they send me.

## The setup

I use Zulip chat for work.  Sometimes, this means that Zulip is a really high-priority source of interrupts, and I need to pay attention immediately when a message is directed at me, so I want notifications on my phone and watch.  (These really should be more granular, since not *everything* should interrupt me when I'm having dinner, and I'd really like rules for that, but that is a separate issue.)

## The problem

I'm idling by the water cooler at work and chatting as one does.  I get a notification on my wrist because of an urgent issue.  Great!  The system is working.  I sit down at my desk.  I open up a private message with the person who needs help.  I ask a question.  They reply.  *Bzzt*.  My wrist buzzes.  They reply with five more messages.  *Bzzt bzzt bzzt bzzt bzzt*.  Now I'm really annoyed and I want to turn off mobile notifications entirely, but I can't, because maybe I'm going to be by the water cooler again at some point in the future.  *Bzzt*.

**Comment by timabbott** [comment]
@glyph can you check your "notification settings" in the webapp?  There's a setting called "mobile notifications always (even when online)" which it sounds like you have set but would prefer to not have set.

![image](https://user-images.githubusercontent.com/2746074/55263164-584da400-522d-11e9-82b2-c3dabed56ca0.png)

**Comment by glyph** [comment]
@timabbott I think that was in fact the problem.  I think I misunderstood what "offline" meant.  I've adjusted the settings and it *seems* to be doing roughly the right thing now.  So this might just be a minor doc bug?  I definitely don't think about "online" and "offline" this way any more.

**Comment by glyph** [comment]
Not clear if this is actionable so I'll close it myself to reduce the noise.

**Comment by timabbott** [comment]
FWIW, we've made some edits in the webapp's descriptions of our notifications settings in part inspired by this; there will be further ones in the coming weeks as well.

**Comment by glyph** [comment]
Thanks!
