### ISSUE TITLE
Update stream settings page for new server-level API

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#3449]
We're doing a big change to how Zulip's stream-level notification settings are managed (https://github.com/zulip/zulip/pull/11507) to make them more sane. In particular, now the user-level values (e.g. page_params.enable_stream_push_notifications) will be defaults for streams, whereas previously they were defaults for new stream subscriptions only.

So in particular, what's changing is that when a user changes the top-level notification setting for e.g. push notifications on streams, that will now change the behavior for all streams (and the user can click over individual streams to have those do something different).

The purpose of this change is in part to make it easier to manage this configuration, and in part to also support a setting of the form "push notifications for pinned streams", that would make it convenient to set an override for a category of streams, not just a single one.

On the backend, this means we're now storing the stream-level data with a NullBooleanField, with True/False being an explicit override of that stream to a specific value, and None meaning no override to the user-level defaults.

After some discussion, we are doing the following for backwards-compatibility is this:

* Have the server only send True/False, never None (at least for now) for the subscription-level values to clients that don't explicitly indicate support for `None`. This will lead to temporary buggy behavior in the mobile app after one changes the defaults for all streams, but re-register will fix it and this issue exists because we should fix that for the next mobile release.
* Clients that support `None` as a valid value can send `notifications_none_supported=True` in the `/register` request alongside similar booleans like `include_subscribers`.  And supporting those values probably involves something like the proposal I mentioned here: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/notification.20settings/near/715557:

> The code we'll want to add on the mobile app is something like this for the processing of this field (except for mobile, etc.) to handle the `None` input in code before the checkbox/toggle rendering code path:
```
+    if (sub.push_notifications !== null) {
+        return sub.push_notifications;
+    }
+    return page_params.enable_stream_push_notifications;
```

See https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/notification.20settings/near/715507 for the full discussion on the topic.

**Comment by gnprice** [comment]
Thanks @timabbott for these details!

(NB for readers: `None` is the Python version of JS and JSON's `null`, so it's what `null` looks like inside the Zulip server. Where Tim mentions `None`, read it as `null`.)

Breaking this task down into pieces, I believe it'll look like this:
* [ ] Change the expected type for the `push_notification` field on `Subscription`, from `boolean` to `null | boolean`. This should cause a type error where we use the field (if it doesn't, there's a gap somewhere in our typing which we should also fix!). Resolve that by adding logic like Tim's example code above.
* [ ] Add the appropriate flag (`notifications_null_supported: true`, or whatever name we settle on in the linked chat thread) to our `/register` aka `registerForEvents` call.
