### ISSUE TITLE
@-mentions in muted topics not visible elsewhere

### ISSUE THREAD

**Issue by cyphase** [zulip/zulip-mobile#3472]
When a topic is muted, the app does not show messages in that topic that @-mention you (unless you're narrowed into that topic); not in the stream narrow, and not in the @-mention narrow. This is inconsistent with the web/desktop apps.

Steps to reproduce:

1. Mute a topic in which you're @-mentioned.
2. Check the stream narrow for the stream the topic is in.
3. Check the @-mention narrow.

**Comment by gnprice** [comment]
Good catch -- thanks @cyphase for the report!

For someone to fix this, I think the relevant bit of code is `shouldBeMuted`, in `src/utils/message.js`. I recommend
* finding the corresponding bit of the webapp's code, in static/js/ of the zulip/zulip repo
* looking for any other changes we should make to match that code's behavior
* adding appropriate cases to the unit test
* making the change!
* pointing to that webapp code in the commit message or a comment, so the reader can follow along :wink:

**Comment by WesleyAC** [comment]
We got another report of this today (#4791), so I'm going to go ahead and push a fix for at least the mentions narrow part of this today.

**Comment by WesleyAC** [comment]
Removing P1 label now that #4807 is merged.
