### ISSUE TITLE
Subscription list does not update when a stream is deleted.

### ISSUE THREAD

**Issue by ungps** [zulip/zulip-mobile#3474]
Hello,

Last week when I was working on #3448, I found that subscription list does not get updated when a stream is deleted (although the stream list is updated).

Steps to reproduce:
1. Open the mobile app and the web app.
2. Delete a stream (which you are subscribed to) from the web app. 
3. The deleted stream should disappear from subscription list, but it does not.

I tried to trace the root cause of this problem and it seems that `getSubscriptions` in `getSubscribedStreams` in  `src/subscriptions/subscriptionSelectors.js` returns the same list before & after deleting a stream. This could be easily fixed like I did in this [commit](https://github.com/ungps/zulip-mobile/commit/e13cba1644e6db9a4c78eb99eb49169fc770871f), but I think this shouldn't be fixed here. It seems it is more of a server problem and should probably be posted on https://github.com/zulip/zulip/issues, but I want a confirmation before posting there. 

P.S: The subscription list is updated properly .when a user unsubscribes.

**Comment by borisyankov** [comment]
@timabbott this will be fixed with #3479 but I am surprised there is no 'unsubscribe' event for the Stream being sent. 

Is this something we should fix on the back-end or is this intentional?

**Comment by gnprice** [comment]
Thanks @ungps for the report!

> @timabbott this will be fixed with #3479 but I am surprised there is no 'unsubscribe' event for the Stream being sent.
> 
> Is this something we should fix on the back-end or is this intentional?

To be explicit here: we get a "stream delete" event, but no "unsubscribe".

The "stream delete" seems like it carries all the information, doesn't it? So it seems fine to not also have an "unsubscribe".

In particular: if the server did send an "unsubscribe" in this situation, what would be the meaning of a sequence where the client sees "stream delete" but doesn't yet see "unsubscribe"? What is the state of things at that point?

It's hard to see a meaningful interpretation of that state that is different from getting both "stream delete" and "unsubscribe". So, if the client is correctly handling "stream delete" -- i.e., it's updating its internal data to some kind of meaningful, consistent state -- then if it later gets an "unsubscribe" it will do nothing at all with it. Which makes it seem pretty unnecessary to send it.
