### ISSUE TITLE
Improve API error handling

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3482]
Implement some of the suggestions in the review of #3254
Some ideas listed here are enablers of these suggestions, others are just related and good to do.

* Add custom exception on API error (change `makeApiError') We are not doing this because React Native's build tools and/or Flow were having issues with custom error object. We should check if this is still true and if so whether there are workarounds. An alternative solution, that I do not prefer, would be is to check the form of the error object (is there an 'httpStatus' property).

* Type the responses and error object better and more strictly. The response from the server is a bit too varied (in some error cases it is even an html response and not json) and we have not documented or typed that extensively enough.

**Comment by chrisbobbe** [comment]
I believe this was resolved with https://github.com/zulip/zulip-mobile/pull/3639, which was marked as superseding https://github.com/zulip/zulip-mobile/pull/3484, but please let me know if I'm closing this in error.
