### ISSUE TITLE
Enable zulip bot on the mobile repository.

### ISSUE THREAD

**Issue by ishammahajan** [zulip/zulip-mobile#3486]
The zulipbot for the mobile repository was closed down because it was generating a lot of spam -- for example when someone labelled issues with a label with the same name as zulip/zulip, the entire subscriber base for that label in the main repository was notified of this issue, even though this issue might have been only very slightly related to that team.

There are multiple advantages of initialising a bot for the mobile repository. Besides giving support for self assignment of issues, self labelling of issues (although without the notification to the different groups (to reduce spam) or with a better system for identifying what labels send notifications -- perhaps something like `area: message list --server` to send notifications to server or `area: message list` with another label `notify: server help required` to notify the specific area in the server if it exists) would be a great help to the quality of the repo.

I have forked the zulipbot repository and have modified the [config file](https://github.com/ishammahajan/zulipbot/blob/config-for-mobile/config/config-example.js) to suit the needs of the mobile repo as detailed in the previous paragraph (this solution simply does not inform the server teams at all, instead of requiring another label to do so - the more complicated solution would be better off discussed in a separate issue in the zulipbot repository). However, someone of higher authority is required to initialise an instance of the bot specifically for the mobile repo as suggested by @gnprice in a [chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/zulip.20bot/near/730553).

cc @timabbott (for the creation of an instance.)

**Comment by timabbott** [comment]
We should think about whether we just want to use the beta `triage` permission on the mobile app repository to solve these problem.

**Comment by ishammahajan** [comment]
I don't understand the suggestion (since I couldn't find any github blog or source pointing towards a `triage` permission, nor can I find a similar feature in the settings of repositories which I have write access to). Would you please expand on the it?

I did find a link which points to a request for the feature https://github.com/todogroup/gh-issues/issues/14; There a github employee suggests:-
>While not ideal or a permanent solution, you can currently use protected branches to empower this role in most workflows.

**Comment by timabbott** [comment]
@ishammahajan Greg can provide more details, but it's a private GitHub beta that the Zulip project has access to, which is why you can't find it.  Basically it lets us give users the ability to do issue triage stuff without full write access to the project.

**Comment by ishammahajan** [comment]
Ah, thanks! @gnprice would this solution be implementable?

**Comment by ishammahajan** [comment]
Ping @gnprice in case this was missed.

**Comment by ishammahajan** [comment]
Closing because this has been resolved.
