### ISSUE TITLE
Uploaded PDF can't be viewed

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3487]
A user reports:

> I did send out several of PDFs to private messages of my members.
> Everybody that uses the App could not open the PDFs. The message was "Cannot open PDF".
> The members with web application had no problem opening the PDFs

The recipients they've heard from are all on Android; we don't know if the issue is also present on iOS.

Apparently it did work for another recipient, though, also on Android!

> now I got feedback from somebody with Android and the App and it worked! How about that?

So that could be a very interesting clue.

I briefly experimented trying to reproduce it: I uploaded a PDF from the webapp, sent the message, saw it on the mobile app, and tried following the link. For me with v24.0.113 on Android 9 aka P, the issue
* **does** reproduce on an org on zulipchat.com;
* **does not** reproduce on chat.zulip.org -- things work fine there.

When it reproduces, the behavior is:
* The PDF viewer app appears on screen, and shows its "working" animation
* Shortly thereafter, the PDF viewer goes away and the Zulip message list returns to the foreground
* A "toast" (a temporary bubble near the bottom of the screen) appears, with the message "Cannot display PDF ( sagas.pdf cannot be opened)" (where `sagas.pdf` is the filename of the PDF; extra space _sic_)

The difference between servers is presumably because chat.zulip.org hosts uploaded files locally, while zulipchat.com hosts them on S3. In particular on zulipchat.com (and with the S3 backend generally), when the client requests an uploaded file, the server returns a redirect to a URL in S3; we may not be handling the redirect properly.

If so, this may be another symptom of the same underlying issue as the cause of #3124 .

**Comment by gnprice** [comment]
Other related issues:
* The setup is reminiscent of #2308, but the symptom is different. That one was reported on iOS.
* #3303 sounds like it should be the very same situation, but the reported symptom is different. I don't know what causes the difference.

**Comment by borisyankov** [comment]
Maybe also this #2115

**Comment by borisyankov** [comment]
After some research and experiments, that looks to be the same issue as #3303 

The difference is the platforms:
* on Android - after opening fails we go back to the message list
* on iOS - we get a login screen

**Comment by gnprice** [comment]
Thanks @borisyankov for the investigation, and the additional link!

Based on those findings, I'll close this to consolidate on #3303 -- though as noted there, the set of reports is still a bit confusing and doesn't quite fit any pattern we yet understand. (In particular the original report in #3303 is on Android but describes a login screen.)
