### ISSUE TITLE
Heavily compress / downsample all media

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#3499]
See also #2749
This issue extends the scope, in the sense by adding Gif files, and videos to the 

I have been testing other apps for a while, and it is apparent that most if not all of them are very aggressive about downsampling and compressing all the media they are serving. While we should ideally keep an original file on the back-end, and should optionally add a feature to download it, the majority of the time the user should be looking at a file, severely reduced in size.

That is key for snappy experience is for us to do that everywhere. Also, people are complaining about bandwidth, and that is another important concern to be addressed.

**Comment by borisyankov** [comment]
@ishammahajan that is potentially a good task to tackle as part of GSoC.

**Comment by ishammahajan** [comment]
Hmm. Seems like easy to fix in the first look. 

There are a couple of things I have questions about before beginning work on this.

- I went through #2887, and there has been a lot of work already done dependent on a different dependency to support this feature, seems like a wasted work if this was to be implemented in the new library again. Should I wait for a response on that, or is this a big enough priority that it should be fixed urgently?
- It wasn't clear from reading the docs/issues that we use thumbnails already. If it is not, I would also want to address that issue in related PR.

**Comment by borisyankov** [comment]
I wouldn't say this is urgent but it is important.
Also, it would consist of multiple related tasks. I wanted to file an issue so it is not forgotten about.

Back-end thumbnailing needs to be enabled for sure, I am not sure if it works for GIFs, if not it should.
I also suspect it does not work for video (yet?!?)

We should do similar work client-side for all types of media.

I'd suggest this to be one of the things you plan on moving forward during GSoC (not fully implement everything but do some)

**Comment by timabbott** [comment]
For backend thumbnailing, we should have a conversation on czo; the backend can definitely provide what you need for that with a bit of work on top of what we already have implemented.

**Comment by ishammahajan** [comment]
> For backend thumbnailing, we should have a conversation on czo; the backend can definitely provide what you need for that with a bit of work on top of what we already have implemented.

@timabbott I didn't understand this. Would you please elaborate? Primarily what is czo (Google returned apparently random results, except one where I could find `require('czo')`. Also what kind of extension to the backend are we talking about?

**Comment by maltokyo** [comment]
@timabbott is it possible to do this somehow in any other settings?  My users upload 2-3MB JPEG files etc, and then complain that they are "slow to display".  We cant ask users to downsize them before uploading from their phones etc.

**Comment by timabbott** [comment]
@maltokyo unfortunately that isn't currently possible.  We plan to address this in a way that resolves the issue for everyone (without requiring a special setting) when we can.

**Comment by gnprice** [comment]
I've just filed #3790 for a crisper description of what I believe is the main concrete thing to do here: we should be using the server's thumbnailing feature to avoid downloading giant versions of images, in the message list where we only ever show images at up to a certain size anyway.

#2749 covers another possible thing we might do, which is to downsample when we *upload*.

If there are specific things that come up that those don't cover (e.g. if we run into limitations in the types of media the Zulip server's thumbnailing covers), let's file those as specific issues. Closing this one.
