### ISSUE TITLE
Add forced update feature

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#35]
This would prevent a user from using the app if the version is too old

We decided the implementation of this should be as follows:
* [ ] We check for an error returned by events_register with some specific error code that means "You need to upgrade"
* [ ] Additionally, we add a new small endpoint on zulipchat.com (or configurable app endpoint) that is passed the current zulip-mobile app version and returns whether it needs to upgrade or not.  Tim can quickly write the backend endpoint as soon as we're ready to work on this.

**Comment by borisyankov** [comment]
@neerajwahi @timabbott We'll treat P1 as non final, so delaying this to P2.

**Comment by timabbott** [comment]
I think we decided the implementation of this should be as follows:
* [ ] We check for an error returned by events_register with some specific error code that means "You need to upgrade"
* [ ] Additionally, we add a new small endpoint on zulipchat.com that is passed the current zulip-mobile app version and returns whether it needs to upgrade or not.  Tim can quickly write the backend endpoint as soon as we're ready to work on this.

**Comment by borisyankov** [comment]
@timabbott Is the api ready for this?

**Comment by timabbott** [comment]
Haven't worked on this yet; what do you think we should call the endpoint?  That's basically the hard part :)

**Comment by borisyankov** [comment]
@timabbott Do we intend to use both approaches? events_register and and API call?
Why we need both?

I suggest we have the call called something like 'compatibility`.
We should also do soon the code push part where we upgrade the JS without app needing update.

Additionally we should notify about the optional updates.

So stages are:

1. JS only updates. Silently upgrade.
2. Compatible upgrades. Some notifications.
3. Server is incompatible. Force upgrade.

**Comment by borisyankov** [comment]
BTW app version is already passed via the `User-Agent` headers.

**Comment by timabbott** [comment]
Opened https://github.com/zulip/zulip-mobile/issues/257 for making the User-Agent match our other stuff.

I'll add a quick endpoint that always returns success at `/compatibility`.

**Comment by timabbott** [comment]
I test-deployed https://github.com/timabbott/zulip/commit/d0d7dbfde285228aac3c465850a0a91cd172ccff to chat.zulip.org; can you verify that works @borisyankov?  You can test success as normal, and failure using `ZulipInvalid/5.0` as the User-Agent.  Note that it expects the user-agent format I suggested in #257.

**Comment by neerajwahi** [comment]
@borisyankov I think we need both `events_register` a separate API call on a fixed endpoint because they serve different use cases. The `events_register` endpoint lets a server admin enforce a minimum version, whereas the API call (to a fixed endpoint) allows an app publisher (for example, Kandra Labs) to force an update for all users regardless of realm.

I agree we eventually want JS only updates (with something like CodePush), but let's focus on a simple 'You need to upgrade this app' function first.

**Comment by borisyankov** [comment]
@timabbott What do you think about the last @neerajwahi comment. Is that the intent?
Do we want to differentiate between the `api/register` and `/compatibility` in that sense?

**Comment by timabbott** [comment]
OK, after thinking about this more I think this is the actual proposal we want:
* `/compatibility` would be queried against `https://zulipchat.com` to allow us as app publishers to force everyone to upgrade from e.g. a broken version.  I guess this should happen in the background on app startup.
* The `/api/v1/register` endpoint would be queried against the actual server they're using (zulip.example.com) case would be an error code we handle in that endpoint that's about whether the app is new enough to connect to a particular server (so that a specific server or Zulip version can expect something in particular).

**Comment by borisyankov** [comment]
I will add the api call url to the config.js, on fail I'll show a screen that has no `back` button, telling them to upgrade.
