### ISSUE TITLE
Replay Message in Zulip Mobile not working

### ISSUE THREAD

**Issue by McpCyber** [zulip/zulip-mobile#3505]
Hi There
i working on zulip for chat Solution in my company . some problem exist in Mobile app , for Example : Replay to a Message not working , right to left not working when i use mix sentences Farsi and English.
good news is on the web all needs worked correctly !!!!
is it possible to correct those issues ???

**Comment by chrisbobbe** [comment]
Hi! Are you still seeing the issue with replying to a message? If so, it would be really helpful to get more details; whether you're using iOS or Android, what version of the Zulip mobile app you're on (shown if you press the gear ⚙️icon, then Diagnostics), and some screenshots if you can.

There's an open issue for right-to-left text support [here](https://github.com/zulip/zulip-mobile/issues/2755), where you can track the progress of that.

**Comment by chrisbobbe** [comment]
Closing, but if you provide steps that help me reproduce the problem with replying to a message, I’ll reopen. 🙂
