### ISSUE TITLE
Differing left spacing for `message-full` and `message-brief` in WebView.

### ISSUE THREAD

**Issue by ishammahajan** [zulip/zulip-mobile#3508]
After a recent merge (for pull request #3188), the spacing on the messages on the left hand side got a little wonky. This might be a result of switching sizing to px instead of em, or due to changes in margin/padding.

![Screenshot 2019-06-01 at 12 04 04 PM](https://user-images.githubusercontent.com/33200024/58823087-88af2580-8656-11e9-99d2-c422eccd78b7.png)

Notice that a full message has different spacing than a brief message.

@zulipbot claim.

**Comment by borisyankov** [comment]
This should fix it:
https://github.com/zulip/zulip-mobile/pull/3188/commits/eeef9440e1809ec8dc38b5c2b9e9891ef02863fc

**Comment by gnprice** [comment]
> This should fix it: [eeef944](https://github.com/zulip/zulip-mobile/commit/eeef9440e1809ec8dc38b5c2b9e9891ef02863fc)

Interesting, thanks @borisyankov for the reference! (Looks like that's part of #3188.)

That commit is described as basically a refactor:
> The values are not always mathematically the same, but the intention is always preserved

so it's interesting that there's this significant behavior change.

@ishammahajan I'd love to merge a focused commit that just fixes this issue, if you'd like to go ahead and prepare one; that will also later help us make a version of eeef9440e that's more cleanly a refactor. You might find that commit helpful for pinning down a good spot to make the fix.

**Comment by ishammahajan** [comment]
Pushed a fix! :)
