### ISSUE TITLE
Enlarge avatars in message list, to 40px

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3515]
The avatars we show in the message list for messages' senders are 32px.

For commit 3dd5fb4de (part of #3188), @borisyankov studied several comparable uses and determined it'd be good to expand them to 40px:

    After comparing the size of the WebView avatar to the web app and
    few competitors, I found out we are showing them rather small.
    
    Web app has them 35px x 35px, but several other mobile chat apps
    have them at around 40px and that is what we chose.

That commit caused #3508 , a misalignment between sender-showing messages (which moved further inward to make room) and sender-implicit messages (which didn't). So for now we're reverting the expansion with #3511.

This task is to make them 40px again, while aligning other elements to match.

**Comment by gnprice** [comment]
I've just merged the parts of #3188 that converted us to using px for alignment rather than rem; I think that will make a solution to this cleaner than it would have been before. (We were in a bit of a mixed state, from having merged some previous bits of #3188.)

**Comment by ishammahajan** [comment]
I don't think this is the right move to make, to be honest. The avatars are big enough for us to be able to visually make them apart and understand their contents without being overly big.

> After comparing the size of the WebView avatar to the web app and
> few competitors, I found out we are showing them rather small.

I don't agree with this. Infact, when I compared our avatar's size with those in Discord and Instagram direct, I found that ours are actually bigger (on default system display size and font size)! 

Adding 8 more px to avatar size is going to make them larger for no reason, since if the user wants to see enlarged avatars they can simply click the avatar to go to the profile page.

Adding 8px to the avatar size is also going to make lesser space available for our messages, and they will expand vertically, taking more vertical space in turn.

**Comment by gnprice** [comment]
> > After comparing the size of the WebView avatar to the web app and
> > few competitors, I found out we are showing them rather small.
> 
> I don't agree with this. Infact, when I compared our avatar's size with those in Discord and Instagram direct, I found that ours are actually bigger (on default system display size and font size)!

Hmm interesting! That is good data, then. Boris didn't add any specifics about which apps he compared with.

I'll go look around at a few others now...

**Comment by gnprice** [comment]
With default font size (and default display density, though that one really *shouldn't* affect things), comparing against our v25.3.117:
* FB Messenger:
  * Inside a conversation, avatars look exactly the same size as ours (so 32px/32dp, I guess), except circular.
  * In the conversation list, the avatar for a 1:1 conversation is much bigger -- maybe 64px? Even for a group conversation, where two smaller avatars are overlaid, each is a little bigger, perhaps 40px or 44px. (In our conversation list, they're the same 32px as in the message list.)
* WhatsApp: No avatars in message list.
  * In conversation list, it's much like Messenger 1:1s.
* LINE: Much like Messenger -- 32px in message list, ~64px in conversation list (at least for 1:1 conversations.)
* Slack: Bigger than ours -- about 48px in the message list. I have a guess now what app Boris was most thinking of when he wrote that. :wink:

**Comment by gnprice** [comment]
OK, with that data and with the points you made about space, I'm convinced -- let's leave the avatars at 32px in the message list.

I have a couple of related thoughts, from staring at this... and hmm, I'll go put those in chat rather than here. Closing this -- thanks again!

**Comment by gnprice** [comment]
For cross-reference: the resulting chat thread is here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/avatar.20layout/near/752153

It then led to #3529, which increased avatar size in the PM conversations list and also in the message list after all.
