### ISSUE TITLE
Convert all colors in our CSS to HSL

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3516]
(Expanded from https://github.com/zulip/zulip-mobile/pull/3491#issuecomment-498802902 .)

The webapp makes a practice of using HSL instead of RGB (there are a few exceptions, but I think those are where people just didn't know and it wasn't caught in review.)

There are good reasons for this, because it makes it easier to understand what the color is, and also to make changes to it. See [here](https://stackoverflow.com/questions/26059228/css-hsl-or-rgba-colors) and [here](https://css-tricks.com/hsl-hsla-is-great-for-programmatic-color-control/) for some good explanations.

We aren't currently consistent about this ourselves -- in the CSS for the message list WebView, it's about half and half, ignoring colors that are just flat gray. Let's convert to all HSL.

Here's a search that I think finds all the colors expressed as RGB:
```
$ git grep -Phoi -e 'rgb.*?\)' -e '#[0-9a-f]+' src/webview/css/ | perl -pe 's/, ?/, /g' | sort
```
Or to get them in context / with line numbers:
```
$ rg -i -e 'rgb.*?\)' -e '#[0-9a-f]+' src/webview/css/
```

A way to go about this:
* First, convert all the zero-saturation colors, where R == G == B. These will be pretty mechanical, I think, so one or a handful of commits can sweep through them. As the first command (the one with `grep -o` and `sort`) shows, these are a large fraction of the total.
* Then, take one color at a time (or a few closely-related colors, like `#008000` and `#00a000`), and convert it everywhere. Find an RGB->HSL converter on the web to compute the new values. Be sure to identify how you did the conversion (e.g. link to the converter), in the PR and at least the first commit message.

**Comment by gnprice** [comment]
A good follow-up would be to do the same for colors in our RN code. The syntax is basically the same:
  https://facebook.github.io/react-native/docs/colors

Let's do that as a separate series of commits, though -- the diffs will look a little different, so I think it'll be easier to read that way.

**Comment by ishammahajan** [comment]
#3519 fixes this issue (commenting for notification).
