### ISSUE TITLE
Message content shows through in compose area

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3518]
Reported by @zbenjamin, who's been seeing this on 25.0.114 and for a while before that (presumably 24.0.113, which was the latest beta for some time.)

![](https://chat.zulip.org/user_uploads/2/7e/-XYwcJiJtP_jf8GLH1cy5suw/IMG_1204.PNG)

That's on an iPhone 7. I was also able to reproduce it, on an iPhone 7 in 25.2.116:

![](https://chat.zulip.org/user_uploads/2/f/Mf_KlOBF_DzBlEO0ap2vYA13/IMG_1993.PNG)

![](https://chat.zulip.org/user_uploads/2/53/-iIwbf-CPwzolHWn-YiiouMy/IMG_1994.PNG)

It doesn't always happen. Zev suggested

> I think it happens when you open the compose box while messages are still loading

I found that hard to pull off at first, and as I played around with narrowing to various streams and opening the compose box I didn't see it for a while. I first reproed it after following a link in a message, navigating back from the resulting browser view, and quickly opening the compose box again.

Then once it had started happening, it seemed to persist indefinitely (at least in a given narrow): even though it was a conversation where we had all the messages already, if I opened the compose box, I got this symptom every time.

Another time I saw it: I'd followed a link in a message; navigated back from the resulting browser view; the message list was showing the loading animation; I opened the compose box; and the symptom appeared.

**Comment by gnprice** [comment]
@jainkuniya did some investigation described in #3536, and it looks like this is a bug in the version of `react-native-webview` we use (which was spun out of React Native itself.)

Later versions of `react-native-webview` seem to have fixed the bug, so we should upgrade. Filed that specific task as #3550 .

**Comment by gnprice** [comment]
(Didn't mean to close this with that commit -- it's only "expected to fix" this issue.)

@jainkuniya , were you able to find a way to reproduce this reliably? Would you try reproducing it now that #3550 is fixed, to confirm whether this is fixed?

**Comment by jainkuniya** [comment]
yup, it got fixed .

**Comment by gnprice** [comment]
Thanks @jainkuniya for confirming, and for the fix!

@zbenjamin This fix was included in v25.8.122, which went out this morning to the iOS beta. If you see it after upgrading, please let us know!
