### ISSUE TITLE
Don't provide 'Reply' option in message action sheet when narrowed to the `topic` narrow.

### ISSUE THREAD

**Issue by ishammahajan** [zulip/zulip-mobile#3528]
This is unexpected behaviour and bad design to have a feature in the app which essentially does nothing -- in particular situations. 

The 'Reply' option in `messageActionSheet` should not be displayed when in the topic narrow since it can potentially confuse users.

See [chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Reply.20not.20working/near/754610) for reference.

**Comment by agrawal-d** [comment]
I have created a [PR](https://github.com/zulip/zulip-mobile/pull/3797) that fixes this.

**Comment by ray-kraesig** [comment]
Shouldn't this option also be removed in PMs?

**Comment by agrawal-d** [comment]
Shouldn't this option also be removed from narrows where only administrators are allowed to post ( such as #announce in CZO )

**Comment by ray-kraesig** [comment]
> Shouldn't this option also be removed from narrows where only administrators are allowed to post ( such as #announce in CZO )?

Almost certainly. (If you're not an admin, anyway.) That's sufficiently functionally different that I should probably file a new bug.
