### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by JasMich** [zulip/zulip-mobile#3532]
Are there any plans to support Windows UWP or Windows Phone. I know, most iOS and Android users forget about but still, Windows has a notable market share.

**Comment by gnprice** [comment]
Windows certainly has a large market share as a desktop OS! And Zulip very much supports Windows. You can get our desktop app here:
https://zulipchat.com/apps/windows

---

I believe Windows Phone is a very different story. Here's an obituary for it, in 2017:
https://www.vox.com/2017/7/17/15984222/microsoft-windows-phone-mobile-operating-system-android-iphone-ios

Graph from that news story:
![image](https://user-images.githubusercontent.com/28173/67227911-0ea4f080-f3ed-11e9-8582-98c94291c814.png)
Windows Phone was at 0.1% market share then, and Microsoft has ended support for it.

So I don't think we'll ever be interested in putting effort into supporting Windows Phone.

**Comment by JasMich** [comment]
But Windows Phone is not Windows 10. Any Windows UWP-App runs on Windows 10. And Windows 10 is the mostly used Desktop-System worldwide. This would still increase the UX as UWP apps offer native UI.

**Comment by gnprice** [comment]
> Any Windows UWP-App runs on Windows 10. And Windows 10 is the mostly used Desktop-System worldwide. This would still increase the UX as UWP apps offer native UI.

Have you tried the Zulip Windows app?
https://zulipchat.com/apps/windows

That and the webapp are our two recommended clients for Windows -- same story as on macOS or Linux.

The Zulip mobile app has a UI optimized for mobile-size displays, with a touchscreen and no physical keyboard. The desktop app, like the webapp, has a UI optimized for laptops and desktops with a bigger screen and a real keyboard. There are a lot of UI choices that go differently for those two very different environments, so even if the app were made to run on Windows it would be quite difficult for it to beat the UX of the desktop app and webapp.

**Comment by gnprice** [comment]
If someone is excited about making the app run with e.g. [`react-native-windows`](https://github.com/microsoft/react-native-windows/blob/master/blog/Roadmap2019.md) (TIL!) I will certainly be curious to see what they come up with :smiley:

I think most likely we would not be keen on merging a PR for it, though -- it'd have to fit in quite cleanly without requiring a lot of changes across the app, and that seems tough.
