### ISSUE TITLE
Heavy message traffic leads to "Oh no! Something went wrong. Try Again?"

### ISSUE THREAD

**Issue by swallitsch** [zulip/zulip-mobile#3539]
When a user is looking at a stream/topic and a lot of messages are being posted to that stream or topic, the red "Oh no! Something went wrong! Try again?" banner will briefly appear, despite all the messages updated and no connection issues occurring.

This seems related to the "New Messages" banner, as users don't seem to be able to self activate the error- it only occurs when someone else is sending messages.

Tested by typing gibberish and hitting return a bunch.

![image](https://user-images.githubusercontent.com/32879218/60040958-01f6d280-966f-11e9-8ebc-b16bf6760175.png)

Observed on:
* Google Pixel 3 XL - Android 9 - Build number: PQ3A.190605.003
* iPhone Xs, OS version 12.3.1

Latest Zulip app as of this message, Zulip server is 2.0.3

This issue was only seen on mobile- desktop users do not see the banner or have any connection issues.

**Comment by gnprice** [comment]
Thanks @swallitsch for the report!

The next step for someone to debug this is to reproduce it, and look at the app's error log, e.g. with `adb logcat`. That will have more detail on the error.

If reproducing in a debug build of the app, the banner will also be longer and have more detail on the error.

We also log these errors to Sentry. Looking, [here's one](https://sentry.io/organizations/zulip/issues/812537889/?project=191284) that looks like a match -- the relevant bit of JSON blob is
```
{"message":"Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.",
"line":436,"column":49,
"error":{
"stack":"Error: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.\n    at Object.handleUpdateEventMessagesRead [as read] ...",
```

That should be a solid lead for debugging.

**Comment by gnprice** [comment]
Some detailed debugging by @jainkuniya in the duplicate issue #3544 .
