### ISSUE TITLE
webview: Getting lots of exception because of selector being empty  

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3544]
![image](https://user-images.githubusercontent.com/18511177/60766673-b7437480-a0ca-11e9-9707-a07c96fa8769.png)

![image](https://user-images.githubusercontent.com/18511177/60766799-8c5a2000-a0cc-11e9-8281-3057554bf8df.png)

I can reproduce it while narrowing to PM from notification. This may also be responsible for #3117. 

In `js.js` we have 
```
 const selector = uevent.messageIds.map(id => `[data-msg-id="${id}"]`).join(',');
  const messageElements = arrayFromNodes(document.querySelectorAll(selector));
```
if `messageIds` is empty then `selector` will be "" which is throwing error. 

**Solution:** Check in webView for `messageIds` is not empty.

But what is point of sending empty array to webView, better fix it on RN side.

Currently we are simply using `===` to check equality (in webViewHandleUpdates.js)
```javascript
  if (
    prevProps.backgroundData.flags
    && prevProps.backgroundData.flags.read !== nextProps.backgroundData.flags.read
  ) {
    uevents.push( updateRead(prevProps, nextProps));
  }
```
Which can not be used in js, as they are objects.
![image](https://user-images.githubusercontent.com/18511177/60766938-0048f800-a0ce-11e9-9484-899b7fbdc123.png)

**Solution:** Use `lodash.isequal`
```javascript
if (
    prevProps.backgroundData.flags
    && !isEqual(prevProps.backgroundData.flags.read, nextProps.backgroundData.flags.read)
  )
```

**Comment by gnprice** [comment]
Thanks for the detailed report! This will be good to fix.

A clarification: the long messy red banner at the top in your screenshot is what we show in a debug build. In a release build (so for normal users), it just says "Oops! Something went wrong. Try again?"

Can you say more about this next bit?

> This may also be responsible for #3117.

I don't see why it would. Was your idea that the exception might stop us processing the update to add the new message? That would just as likely apply to new messages from elsewhere as newly-sent messages... and in the case of a newly-sent message, it would cause the outbox version (with the spinner) to stay visible, never cause the message to disappear... and in any case, `getUpdateEvents` puts the content update first in the list. So by the time we process the read-status update and hit this exception, the content update has already happened.

**Comment by gnprice** [comment]
BTW this issue is already in the tracker, as #3539. I'm going to close this as a duplicate, and point to it from there.
