### ISSUE TITLE
Say a user is deactivated when showing their profile or composing PM

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3551]
@jainkuniya looked at how the webapp handles deactivated users, and found two helpful things we should do:

> Deactivated status is visible in user profile and at the time of sending PM.
> ![image](https://user-images.githubusercontent.com/18511177/60130402-c534f380-97b4-11e9-9c12-5c19ca21457a.png)
> ![image](https://user-images.githubusercontent.com/18511177/60130457-dd0c7780-97b4-11e9-9666-d239217827ba.png)

(Moved this from https://github.com/zulip/zulip-mobile/pull/3110#issuecomment-505607319 .)

Let's do those two things.
* Our profile screen is a lot like the user popover in the webapp, so we can use basically the same design.
* For the compose case: let's show a message above the compose box, if you focus the compose box while narrowed to a PM thread that includes a deactivated user.

This isn't a priority, so let's leave it alone for now. Filing it just so it's easy to pick up in the future.

**Comment by agrawal-d** [comment]
The Zulip api currently does not provide any information whether a user is activated or not.
(https://zulipchat.com/api/get-profile) (based on what I was able to find).

Is there any other way we can fetch that information?

**Comment by ray-kraesig** [comment]
> Is there any other way we can fetch that information?

The webapp has no special access to the Zulip server state, as far as I know; there presumably *is* a way to determine this through the API. (I'm not familiar enough with the webapp to quickly discern how it does that, I'm afraid, but it might still be a good starting point.)

**Comment by agrawal-d** [comment]
Found it. The endpoint is `https://zulipchat.com/api/get-all-users`. One of the response fields is `is_active`: A boolean specifying whether the user is active or not.

API doc: https://zulipchat.com/api/get-all-users

**Comment by agrawal-d** [comment]
Can I work on this issue?

**Comment by timabbott** [comment]
Right, the data is prefetched; I would expect the `is_active` field to be already available when you click a user's profile.

**Comment by timabbott** [comment]
While we're working on this, you should look at the precise logic for the webapp's popover; I think it also has some nice display details for bots as well.  `static/templates/user_info_popover_content.hbs` is the HTML source code for it in the webapp for comparison: https://github.com/zulip/zulip/blob/master/static/templates/user_info_popover_content.hbs

**Comment by agrawal-d** [comment]
I have created a [PR](https://github.com/zulip/zulip-mobile/pull/3807) that resolves this.

**Comment by agrawal-d** [comment]
> Right, the data is prefetched; I would expect the `is_active` field to be already available when you click a user's profile.

Turns out its not! My PR has the explanation.

**Comment by gnprice** [comment]
#3807 (thanks @agrawal-d !) resolved the part of this that's about the user's profile screen.

The part about composing PMs is still open. That's been split out as #3812 .
