### ISSUE TITLE
iOS: scrolling in views with messages is slow

### ISSUE THREAD

**Issue by antifuchs** [zulip/zulip-mobile#3557]
Since the iOS app update prior to last, scrolling in views where there are messages (inside a topic or stream) feels much more "heavy" than previously: I used to be able to "flick" the content up and scroll a significant chunk of channel contents (like you would on a Safari page). Now, it takes me maybe a screenful or two forward/backward.

This isn't so annoying when catching up on a topic, but it gets really difficult when I try to find an older message in a long-running stream (my thumbs are very nasty RSI hot spots).

**Comment by chrisbobbe** [comment]
We've had another report of this, [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Deprecate.20mobile.20app.3F/near/852292).

**Comment by gnprice** [comment]
I reproduce this on both an iPhone XR running iOS 13 and an iPhone 7 running iOS 12.

I *don't* reproduce on Android -- scrolling with a "flick" gesture works great on a Pixel 4 running Android 10. So something's happening here that's specific to iOS.
