### ISSUE TITLE
Trailing slash on realm URL can happen, and breaks `/events`

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3567]
[Original title: "Message list won't update, on iOS on physical device". Better characterized below after some debugging.]

AFAIK this doesn't appear in any actual release we've made -- but it happens on 25.7.121 and 25.8.122 (aka current master), in their respective alpha release builds, on my iPhone 7 running iOS 12.3. So we can't make a release until it's fixed.

It also happens in a debug build on that same device.

It *doesn't* happen in a debug build on an iPhone XR simulator running iOS 12.4... nor on an iPhone 7 simulator running iOS 12.4.

The symptoms are:
* When looking at a message list, it (usually!) fails to update when something changes -- a message arrives, a reaction, etc.
* When you send a message, it goes through fine... but the "outbox" object, which shows up as a message with a spinner on it, sticks around. It's still there even if you leave the message list and come back.

**Comment by gnprice** [comment]
Ohhh -- it's that we're just not getting events.

First clue to this was on looking in the debug console, seeing this happening over and over:
```
{route: "events?queue_id=1563767601%3A50342&last_event_id=-1", params: {…}, httpStatus: 404, json: undefined}
```

But wait, why was I seeing updates if I navigated out of the message list and then back to it? ... It's because we were doing a new fetch. I'm not entirely sure why that is -- don't we avoid those if we're all caught up? the log shows we had `caughtUp` of `{older: false, newer: true}` for the narrow in question, hmm -- but the log shows we were, and that certainly explains getting the updates then.

I thought I'd spotted an update another time, too, while still looking at the message list. Maybe I'd somehow provoked another fetch? Or maybe I'd just confused that with seeing an update after navigating away and back.

Anyway, that certainly explains all the symptoms. Next question: what's in turn causing it.

**Comment by gnprice** [comment]
Puzzling. Odd facts include:
* It works fine for (my usual account on) chat.zulip.org. Where it doesn't work is a test org on kandra-test.zulipchat.com.
  * Possibly another symptom of #3196, somehow? That test org still has that setting enabled.
* I'm not seeing anything corresponding to these requests when I look in the zulipchat.com server logs. There are no 404s at all in `/var/log/zulip/tornado.log` (which has numerous 200 lines for successful requests of the same type); presumably that means these requests aren't making it to Tornado, but I don't see any sign of them in `/var/log/nginx/{access,error}.log` either.

**Comment by gnprice** [comment]
Aha! The error seems to be...

in the case where it's failing, the request is going to a URL like `https://example.zulipchat.com//api/v1/events?queue_id=1234567890%3A12345&last_event_id=-1`. With a double slash at the start of the path.

I think this naturally happens if the `realm` value we've saved has a trailing slash.

And, indeed, the Redux log shows that is the case for the `realm` value on that account on that device; but not for the czo account, nor for the account as I've saved it in the simulators where this didn't reproduce.

Phew. Well, that won't be too hard to resolve, then.

**Comment by gnprice** [comment]
OK, at this point there are two puzzles, both of which go to the question of how widespread this is.

* How did I manage to have a `realm` value ending in a slash? In the current code, that should be impossible because -- well, `SmartUrlInput` (which we use for entering the URL that becomes the `realm` value) is a bit intricate, but among other things we apply `fixRealmUrl` to the URL, and that among other things strips a trailing slash.

  Going through the history, that logic was added in commit 507839a39, of 2017-05-11. ... Ah, but `git describe --contains` says it only went out in 1.0.11 -- of 2017-06-28. By then I'd surely have installed the app on my main personal device (having started work at Zulip earlier that month); and, via an iCloud backup/restore, that data was inherited by the iPhone where I'm seeing the issue. OK, that's explained then.

  * Ha, and also the logic only strips a *single* trailing slash. So by entering *two* trailing slashes at login, I've just reproduced the issue on my Android phone, too.

* What changed now? This extra slash has presumably been there for over two years, on my successive iPhones, every time I use this test org there. Which... at a minimum I use that device to smoke-test each release, and I might use czo but I'm pretty sure I've often used this test org there. Might not have been today or this week that something changed to trigger this, but surely in the last few months.

In any case, no longer a critical priority, because it's hard to trigger unless you have an install that's over two years old. I might not be the only one, though -- we should do something to clean these up.

**Comment by gnprice** [comment]
@timabbott Do you know a reason why this might have started failing recently? Summarizing what I found above:

* A request to something like `https://example.zulipchat.com//api/v1/events?queue_id=1234567890%3A12345&last_event_id=-1` -- note the double-slash -- returns 404, and doesn't make it to `tornado.log` at all.

* Other routes (`//api/v1/register` and everything else) are fine, though; only `events` is affected.

* I've almost surely been making these double-slash requests every time I use my test org, on my physical iPhone, for the past two years. I'm not certain just how recently I would have noticed if it broke (it's possible the last few times I've tested things on my iPhone have all been on czo instead of that test org)... but I'd be surprised if it was already broken by a few months ago.

Some change in our nginx and/or load-balancer setup, perhaps?

**Comment by gnprice** [comment]
Things I expect we'll want to do to clean this up:
* Tweak `fixRealmUrl` so it strips any number of trailing slashes.
* Add a migration that strips trailing slashes on `realm` in all existing accounts.

**Comment by timabbott** [comment]
Woah, that's weird.  I am not aware of server-side changes that might have caused this; `git log -p zproject/urls.py` doesn't show any recent relevant changes.  If it were affecting all routes, I would have speculated that this could be a change in upstream Django or Tornado that we took; here's what our code looks like:

```
    # used to register for an event queue in tornado                                                 
    url(r'^register$', rest_dispatch,                                                                
        {'POST': 'zerver.views.events_register.events_register_backend'}),                           
                                                                                                     
    # events -> zerver.tornado.views                                                                 
    url(r'^events$', rest_dispatch,                                                                  
        {'GET': 'zerver.tornado.views.get_events',                                                   
         'DELETE': 'zerver.tornado.views.cleanup_event_queue'}),                                     
```

So those should behave the same.  A Tornado upgrade might be the source; `zerver/tornado/application.py` defines the Tornado URLs, and `/register` isn't one of them.  Not much to test with that theory, since only `/events` is user-facing.

**Comment by gnprice** [comment]
Huh, odd, then.

Well -- I guess that will stay a mystery, then. Most likely it's been this way for some months, which at least means the fact nobody noticed before is a good sign that this is affecting very few people.

**Comment by chrisbobbe** [comment]
> Things I expect we'll want to do to clean this up:
> 
> * Tweak fixRealmUrl so it strips any number of trailing slashes.
> * Add a migration that strips trailing slashes on realm in all existing accounts.

This sounds pretty straightforward, if those are the only required changes.

**Comment by chrisbobbe** [comment]
Hmm, while working on https://github.com/zulip/zulip-mobile/pull/4034, I found that, apparently, we're accessing the social auth endpoints with a double slash, every time —

`https://chat.zulip.org//accounts/login/social/google`

— and it works fine in production, but I get a 404 with a dev server. (Why the difference, I wonder?)

This isn't really related to how the realm URL is stored in Redux, but I'm posting this here in case it leads to clues about the following oddness, which I think still hasn't been fully explained?

@gnprice [said](https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-514845971):
> * A request to something like `https://example.zulipchat.com//api/v1/events?queue_id=1234567890%3A12345&last_event_id=-1` -- note the double-slash -- returns 404, and doesn't make it to `tornado.log` at all.
> * Other routes (`//api/v1/register` and everything else) are fine, though; only `events` is affected.

Here's where the extra slash is getting added, in `src/start/AuthScreen.js`:

```
  beginWebAuth = async (url: string) => {
    otp = await webAuth.generateOtp();
    webAuth.openBrowser(`${this.props.realm}/${url}`, otp);
  };
```

where `url` is `.login_url` on an item in `external_authentication_methods`, and all of these have a leading slash, which you can see in, e.g.,

```
curl https://chat.zulip.org/api/v1/server_settings | jq .external_authentication_methods
```

**Comment by timabbott** [comment]
We should probably be using a proper library for joining URLs rather than string concatenation.

**Comment by chrisbobbe** [comment]
> We should probably be using a proper library for joining URLs rather than string concatenation.

Makes sense. I just opened https://github.com/zulip/zulip-mobile/issues/4081 for this, linking to a few other comments along these lines.

**Comment by chrisbobbe** [comment]
(Opened a fix for the duplicated slashes issue as https://github.com/zulip/zulip-mobile/pull/4082.)

**Comment by gnprice** [comment]
We just had a report of this last week, in #4070.

AFAIK that's the first report we've heard from a user other than me. On the other hand... this user sure doesn't sound like they've been using the app since 2017 and just now hit the issue, so that means it is possible for a new user (not only a very old one) to run into in real life.

And because it hits when you first log in, and makes the app just basically not work at all, it's likely to be under-reported due to people simply giving up.

So, we should fix it. Here's the steps I described above:

> Things I expect we'll want to do to clean this up:
> 
> * Tweak `fixRealmUrl` so it strips any number of trailing slashes.
> * Add a migration that strips trailing slashes on `realm` in all existing accounts.

**Comment by chrisbobbe** [comment]
@gnprice [said](https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-623722705):
> So, we should fix it. Here's the steps I described above:
> 
> > Things I expect we'll want to do to clean this up:
> > 
> > * Tweak `fixRealmUrl` so it strips any number of trailing slashes.
> > * Add a migration that strips trailing slashes on `realm` in all existing accounts.

Makes sense. I've got https://github.com/zulip/zulip-mobile/pull/3819 open for this, awaiting review at your convenience.

**Comment by gnprice** [comment]
> clues about the following oddness, which I think still hasn't been fully explained?
> 
> @gnprice [said](https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-514845971):
> 
> > * A request to something like `https://example.zulipchat.com//api/v1/events?queue_id=1234567890%3A12345&last_event_id=-1` -- note the double-slash -- returns 404, and doesn't make it to `tornado.log` at all.
> > * Other routes (`//api/v1/register` and everything else) are fine, though; only `events` is affected.

@chrisbobbe Do you mean the contrast between `//api/v1/events` and `//api/v1/anything-else`? That one, I think we understand well enough for this issue:
* In the client, we're treating those routes the same way -- so that when the realm URL has a trailing slash, we send a double-slash.
* The server is giving different results, though.
* This isn't too surprising, because `/events` uniquely needs to be routed to our Tornado server -- so either Tornado, or something else in the chain leading there, apparently rejects the double-slash URL, while plain Django accepts it.

> I've got #3819 open for this

Ah, thanks for the reminder >_> I'll take a look now.

**Comment by chrisbobbe** [comment]
> Do you mean the contrast between `//api/v1/events` and `//api/v1/anything-else`?

Right.

> This isn't too surprising, because `/events` uniquely needs to be routed to our Tornado server -- so either Tornado, or something else in the chain leading there, apparently rejects the double-slash URL, while plain Django accepts it.

Ah, OK! It sounds like either this solves the mystery you mention [here](https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-515620160) —

> Huh, odd, then.
> 
> Well -- I guess that will stay a mystery, then.

— or you were referring to a different mystery. In any case, it sounds relevant.

**Comment by gnprice** [comment]
Ah, yeah. The really mysterious thing to me was what *changed* on the server -- the same account where things weren't working and that caused me to report this bug, I'd used in the past and it must have worked before.

(But I wasn't sure how recently I might have used that particular test account on that device and seen things working, which helped make it hard to pin down.)
