### ISSUE TITLE
Test Android download/share flows, confirm no filesystem-permission issues

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3577]
Splitting this off from the combination issue #3075:

> * Test downloading files, and sharing images (i.e. our `shareImage`.) There's [a note about `file://` URLs](https://developer.android.com/about/versions/nougat/android-7.0-changes#permfilesys) which I _think_ isn't an issue for downloading, but may be for our sharing; and I don't 100% understand what it's saying anyway. Some grepping finds `file://` URLs are used in several ways in `rn-fetch-blob`, which in turn we use in `downloadFile`, which is used in those two places.

This is about a change in Android system behavior, which took effect for us when we increased `targetSdkVersion` to 26 from 22.

**Comment by chrisbobbe** [comment]
Since this was split off from the issue for bumping `targetSdkVersion` to 26, and we've recently moved the `targetSdkVersion` to 30, in #4284, I think this has gone stale. When we resolved #4284, we thoroughly tested all the Android download/share flows we could think of.
