### ISSUE TITLE
How can I set only message from current user account to right of screen

### ISSUE THREAD

**Issue by wsupajirakit** [zulip/zulip-mobile#3578]
How can I set only message from current user account to right of screen
now all message it's on left of screen
I want to set only message from current user account to right of screen

**Comment by chrisbobbe** [comment]
Hmm, could you please try explaining this again? Is this a new feature request? Some screenshots might help me understand what you're looking for, if this is still an issue. 🙂

**Comment by timabbott** [comment]
I believe this is a feature request for Zulip to render things like how many SMS apps do with messages sent by the current user justified opposite messages sent by other users.  I suspect we should just close this as wontfix.

**Comment by chrisbobbe** [comment]
That sounds right.

This design is a popular way to introduce a metaphor of live speech in a physical space, usually reinforced by some form of speech-bubble graphic, in a casual instant-messaging setting, especially when most of the chat happens between just two people. But I don’t think Zulip’s advantages depend on such a metaphor, for a few reasons, including that messages are editable, that most conversations involve more than two people, and that discussion happens at a variety of registers above casual chit-chat.
