### ISSUE TITLE
Messagebox clips if the message is too long

### ISSUE THREAD

**Issue by Cogitri** [zulip/zulip-mobile#3579]
Hello, 

it seems like the text in the messagebox clips if it gets too big (see the attached screenshot), making it impossible to see what I type (as it's hidden by the keyboard). 

I'm on Android Oreo on a Oneplus 6T. I use Zulip v25.6.120, which seems to be the latest version in the Playstore.

![Screenshot_20190729-174830](https://user-images.githubusercontent.com/8766773/62090102-eed9b280-b26b-11e9-9f7d-a69fa946b153.jpg)

**Comment by gnprice** [comment]
Thanks @Cogitri for the report!

This looks to be issue #3369. I've just bumped the priority of that, taking this as evidence that people are continuing to run into it :slightly_smiling_face:

**Comment by Cogitri** [comment]
Oh, thanks for that! :)
