### ISSUE TITLE
New messages don't appear in mentions narrow

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3592]
Forking from [here](https://github.com/zulip/zulip-mobile/pull/3542#issuecomment-523670583), where I noticed this in reading the code.

The `narrowsReducer` relies on `isMessageInNarrow`, which has this logic:

```
  return caseNarrow(narrow, {
    home: () => true,
    stream: name => name === message.display_recipient,
    // ...
    starred: () => message.type === 'starred',
    mentioned: () => message.type === 'mentioned',
    allPrivate: () => message.type === 'private',
```

Those `starred` and `mentioned` conditions can't ever be true.

And indeed, if you open the @-mentions narrow and then (from some other user on another device) send a message with an @-mention that should appear there, it doesn't.

This "mostly" works, because most of the time the user will enter that narrow cold and so we'll load the messages from the server. But we should fix it.

I think it's trickier to reproduce buggy behavior here for the `starred` case, but we should fix that too.

Note that the correct condition for `mentioned` will include both the `mentioned` flag and the `wildcard_mentioned` flag; see [this other comment](https://github.com/zulip/zulip-mobile/pull/3542#issuecomment-523673571) .

In addition to the new-message case, we should fix the `EVENT_UPDATE_MESSAGE_FLAGS` case too. That one currently handles the "starred" narrow but not the "mentioned" narrow.

**Comment by gnprice** [comment]
> Note that the correct condition for `mentioned` will include both the `mentioned` flag and the `wildcard_mentioned` flag; see [this other comment](https://github.com/zulip/zulip-mobile/pull/3542#issuecomment-523673571) .

Over on the linked thread we're still sorting out exactly how to handle `wildcard_mentioned`. So for this issue, let's not worry about it. We'll handle `wildcard_mentioned` in whatever way is simple to implement, and if it doesn't quite have the right behavior in those cases, we can take care of that after we've sorted those semantics out in the other thread.

For this issue, the goal is just to get the exact right behavior for `mentioned` (and `starred`) in cases where `wildcard_mentioned` isn't involved.

**Comment by chrisbobbe** [comment]
@zulipbot claim
