### ISSUE TITLE
unspecified problem with self-hosted zulip service

### ISSUE THREAD

**Issue by danielecr** [zulip/zulip-mobile#3597]
The mobile app works only with zulip service, and this is not specified anywhere.

**Comment by danielecr** [comment]
Android 8.0

connect to via browser is ok. Browser in pc, browser in the mobile phone. I change machine. No execption needed. We are using the same certificate for our customers, they never complain

no problems. with mobile app there is a "cannot connect to server".

it run throw traefik, and as said above, the same traefik serve others domains without any problem.

There is some special requirement from mobile app? port 443 is enough?

**Comment by danielecr** [comment]
subdomain, it is a wildcard certificate. Any problem with wildcard certificates?

**Comment by danielecr** [comment]
> If you’re missing part of the chain, your server may work with some browsers, but not others and not the Zulip mobile and desktop apps.

I just discovered something usefull

**Comment by gnprice** [comment]
> > If you’re missing part of the chain, your server may work with some browsers, but not others and not the Zulip mobile and desktop apps.
> 
> I just discovered something usefull

Great :slightly_smiling_face: Glad that resolved it.
