### ISSUE TITLE
Change titles to the style where only first letter is capitalized

### ISSUE THREAD

**Issue by TomaszKolek** [zulip/zulip-mobile#360]
Examples:
Search Messages -> Search messages
Find Users -> Find users

**Comment by timabbott** [comment]
For context, this is how all of our strings work in the webapp at this point, and consistently is nice for i18n and general consistency of user interface.

**Comment by neerajwahi** [comment]
+1

**Comment by TomaszKolek** [comment]
@zulipbot claim
