### ISSUE TITLE
ios: Opening a notification doesn't navigate if app running in background

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3647]
This is a lot like #3582... except on iOS. Observed just now when testing other notification changes, on my iPhone 7 running iOS 12.4.1. First observed in an alpha-only release made for testing a branch, but then reproduced on 26.8.131 (installed from TestFlight). Haven't yet tried older versions, but it may well have been present for a long time.

We have very little code of our own involved in this path in the iOS case. That code attempts to listen for an event emitted by library code when the user opens a notification, but we might have something wrong there; or there might be an issue in the library code. Debugging required.

Here's the current behavior I observe when the user gets a notification-causing message:
* If app is in foreground: No notification at all. (That seems like an issue of its own.)
* If app is in background: Notification appears. Opening it brings the app to foreground, but no navigation happens -- we stay on whatever screen we were on when the user switched away. That's this issue.
* If app isn't running at all: Notification appears. Opening it launches the app, and causes navigation to the appropriate screen, as desired.

**Comment by chrisbobbe** [comment]
Linking conversation at https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/iOS.20push.20notifications/near/825050, which see.

A workaround has been found; `NotificationsIOS.consumeBackgroundQueue()` must be called after the app is put in the foreground. This could be implemented with an interval of a few seconds, or, much better, with a listener that tells us that the app has just been put in the foreground. Either way, this is a really superficial fix, and more permanent fixes should be considered first. That API has long been deprecated in the react-native-notifications library, and we may even be switching to a different library.
