### ISSUE TITLE
Fix link in documentation file

### ISSUE THREAD

**Issue by victorphoenix3** [zulip/zulip-mobile#3650]
![Screenshot from 2019-10-15 23-56-54](https://user-images.githubusercontent.com/48182195/66858662-61267d00-efa7-11e9-932c-22c211d3f7c1.png)

The backend test failed due to a broken link in one of the documentation files.
The given link is missing a trailing slash.

fixing this with the following commit.

**Comment by gnprice** [comment]
As I gather you detected, but to make it explicit for anyone coming across this issue later: this was about the docs in the zulip/zulip repo, and not this repo :slightly_smiling_face:
