### ISSUE TITLE
Error while building the app

### ISSUE THREAD

**Issue by realabbas** [zulip/zulip-mobile#3655]
I forked the zulip-mobile repository and started a build on my Windows Machine connected to a physical mobile device.

As mentioned in the developer's guide, I used **Yarn Install** 
This is what I encountered

![image](https://user-images.githubusercontent.com/43527087/67160181-afeb6280-f36b-11e9-858d-30c73fa699f9.png)

**Machine:** Windows 10
**react-native-cli:** 2.0.1
**react-native:** 0.59.10
**node** - v8.11.3
**yarn** - 1.19.1

Resolve the issue, or give me suggestions to fix it @gnprice

**Comment by gnprice** [comment]
Hi @realabbas -- thanks for the report!

Would you come join us [in chat](https://zulip.readthedocs.io/en/latest/contributing/chat-zulip-org.html) and say hello in the `#mobile` stream? I think we'll want to do some interactive debugging and ask you to try different commands to find how to fix this properly, and that'll help make that easier.

When you do, would you also please copy and paste the error message? That is more readable (and searchable, and copyable to other places, etc.) than a screenshot, and I'd prefer not to transcribe it from the screenshot.

@ray-kraesig ^ this appears to be from where Gradle attempts to invoke the new build-webview.

**Comment by gnprice** [comment]
Also, some potentially helpful background is in this comment: https://github.com/zulip/zulip-mobile/issues/3178#issuecomment-445090750
(Just ran across that again while creating the `a-Windows-dev` label so I could add it to this issue.)

**Comment by realabbas** [comment]
> Hi @realabbas -- thanks for the report!
> 
> Would you come join us [in chat](https://zulip.readthedocs.io/en/latest/contributing/chat-zulip-org.html) and say hello in the `#mobile` stream? I think we'll want to do some interactive debugging and ask you to try different commands to find how to fix this properly, and that'll help make that easier.
> 
> When you do, would you also please copy and paste the error message? That is more readable (and searchable, and copyable to other places, etc.) than a screenshot, and I'd prefer not to transcribe it from the screenshot.
> 
> @ray-kraesig ^ this appears to be from where Gradle attempts to invoke the new build-webview.

Done @gnprice

**Comment by gnprice** [comment]
> Done

Thanks! Here's a link to the conversation: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Windows.20build/near/792677

We'll circle back here with what we learn there.
