### ISSUE TITLE
On logout and re-login, the org-URL screen flashes by

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3685]
If you log out of an account, and then from the "switch accounts" screen choose the same account again, there's a quick flash of something before we take you to the "choose how to log in" screen.

That's `RealmScreen` -- what's happening is we take you there, and then it promptly redirects on to the next screen. It fetches from `server_settings` first, which is the main reason we don't just go past it already.

This is a low-priority issue, because this flow is pretty uncommon -- I expect very few users ever go through it, other than people working on Zulip itself.

A previous related issue was #2778. A previous PR to do this was #3055 .

**Comment by sumukhah** [comment]
@gnprice 
can i take this?

**Comment by sumukhah** [comment]
@gnprice 
![ezgif-2-fc1567eb8ec2](https://user-images.githubusercontent.com/23723464/69441504-de949880-0d70-11ea-93ea-a4b0be0c1fb3.gif)
seems working,
can i make a pull request?

**Comment by gnprice** [comment]
Some thoughts on how to approach this, copied from my and @ray-kraesig 's comments on #3712:

## UI

I think a good UI here would be:
* When the user hits the button, we immediately navigate to the auth screen, and make the request.
* While the request is pending, the auth screen shows a "loading" animation. A simple version of this would be that it's mostly blank, with a spinner.
  * In a fancier version, the "still loading" version of the auth screen would have a layout made to look like the real thing, with placeholder gray rectangles. This requires more design work to get right; strategy-wise, probably best to leave as a possible followup.

Then if the user wants to cancel, they just navigate back. And if the request fails, the loading animation gets replaced with an error message, and a button to retry; the user can either hit the button, or navigate back.

The translucent overlay with spinner would also work. I think that was a very common UI style a few years ago.

Aside from just feeling more contemporary, I think the main thing the "transition to mockup loading version" approach accomplishes, relative to the translucent overlay with spinner, is that the intermediate state is visually similar to the final state -- so it doesn't much add to the amount of visual busy-ness.  In particular if the request finishes quickly (which is a common case), this makes the visual effect very close to the ideal of just transitioning straight to the fully-loaded state.

---

(@ray-kraesig:)

* You can't just hide the single button the user clicked; you have to hide – or disable – _all_ the buttons, for the same reason. (Hence the suggestion of a translucent overlay.)
* The user must be able to cancel out of the action with the standard back button/gesture (on Android) and/or a "Cancel" button (on iOS).
  * Doing this properly will require react-native v0.60, since that was when `AbortController` [was introduced](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#060); but a version which ignores the fetch result rather than actually cancelling should still be feasible.


## Code

> While the request is pending, the auth screen shows a "loading" animation.

Oh, and then some code-level thoughts on how to do that:
* Probably there should be multiple components here. They can all go in `AuthScreen.js`.
* The exported component handles the network request, and switching between the "still loading", "error", and "loaded" states.
* The "still loading" and "error" states might be just inlined in the outer/exported component's `render` method if they're a few lines each, or if they get more complex they might be their own small components in that file.
* The "loaded" state would be handled by its own component, which would include nearly all the code in the existing `AuthScreen` class. (Perhaps the `Screen` and `Centerer` would move to the new outer component.)

---

(@ray-kraesig:)

An unguarded `await` in a UI handler [which appears in a natural first attempt] makes a race condition possible. If the user taps on the login button, gets impatient while a connection is being made, and taps the button again, the UI will still be responsive to the second tap, and will try to start another login sequence.

(This is handled in `RealmScreen.js` with the `progress` entry in the component state, which simultaneously shows a busy-indicator and disables the relevant button. Some analogous construct seems to be needed here.)

---

(@ray-kraesig:)

[When the race condition above is] addressed, there will likely be enough strongly-similar code [to `tryRealm` in `RealmScreen.js`] that a refactor will be called for. In particular, the work described at the end of #3671, which would presently only require changes to `tryRealm`, would need very similar changes here.

**Comment by sumukhah** [comment]
@gnprice
Can I have one more chance?
Actually I am a newbie, I need some time to understand the codebase.
I will definitely try my level best

**Comment by gnprice** [comment]
@sumukhah I think trying a different issue would be best. For more discussion on that, the #mobile stream on chat.zulip.org would be a good place.

**Comment by awasthishubh** [comment]
I would like to take this issue.

**Comment by awasthishubh** [comment]
> but a version which ignores the fetch result rather than actually cancelling should still be feasible.

@ray-kraesig To ignore the fetch result in general can we do something like:
* Assign each request an id (by incrementing a value) and set the current request's id in the state.
* When the request completes, if request-id is not the same as id in the state (i.e a new request has been made), We'll ignore.

**Comment by ray-kraesig** [comment]
That's a possibility; but I'm actually working on the RN 0.60 upgrade right now, so it might be better to hold off for a bit.

(In particular, I'm hoping it's feasible to "attach" an AbortController to a React Navigation route, such that when the route is removed from the stack any associated network requests are autocanceled. This approach would solve half of this issue and all of #3791.)

**Comment by awasthishubh** [comment]
That shouldn't be hard. We just have to execute all request in same component with same abort signal and send abort signal in componentWillUnmount lifecycle.
We have AbortController-polyfill currently but I too think it's worth to wait and update RN. 
I would love to work on this if possible in future. :)

**Comment by gnprice** [comment]
This issue has been fixed, after we duplicated it as #4604 (I'd forgotten about this previous issue thread, oops.)

I'd also forgotten about the nice design in https://github.com/zulip/zulip-mobile/issues/3685#issuecomment-570012096 above, and our fix for #4604 has a bug which that design would avoid. I've just filed #5010 for that new issue. Closing this one.
