### ISSUE TITLE
Timestamp pills start out visible on stream entry

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#3689]
Upon entering a stream, timestamp pills for visible messages start out extended, and immediately slide inwards.

`git bisect` suggests this behavior was introduced relatively recently, at commit 8fdb93bd4dac796834b639846867c41296653557, titled
`webview css: move base CSS into actual CSS file` – which should not have been a functional change.

This has been confirmed to occur (on `master`) on iOS 11.4, iOS 13.2, and Android Pie and Q. It does _not_ appear to occur on Android Lollipop or Marshmallow.

**Comment by ray-kraesig** [comment]
This is a WebKit bug!

https://stackoverflow.com/a/42969608
https://lab.laukstein.com/bug/input
https://bugs.chromium.org/p/chromium/issues/detail?id=332189
https://bugs.chromium.org/p/chromium/issues/detail?id=167083

(Its invisibility on Lollipop and Marshmallow seems to just have been race-condition-induced.)

**Comment by gnprice** [comment]
LGTM! Thanks for the tweak to the comment (from shoulder review.)

I would merge, were it not that I'm about to get up from the keyboard for the day. Please feel free to merge at your convenience, if you look at this on Monday before I do.
