### ISSUE TITLE
Display lock icon instead of # for invite-only (private) streams that you're subscribed to

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#369]
This is I think important for helping users understand the audience for their messages.  The styling we use on web of:
(1) Displaying the lock icon to the left of the stream name in recipient bars
(2) Displaying the lock icon instead of the `#` in stream listings

Is probably reasonable for indicating this clearly to users.

**Comment by borisyankov** [comment]
A problem with (2) - the stream response does not contain the `is private` type of field, only the subscription response.
Should we add this to the API or am I missing something and it is there already?

**Comment by timabbott** [comment]
You want the `invite_only` field in the `streams` dicts.

**Comment by borisyankov** [comment]
Oh, yeah, of course.
Can a user have streams muted, but not currently subscribed to?

**Comment by timabbott** [comment]
Nope; muted is a subset of subscriptions.

**Comment by TomaszKolek** [comment]
@borisyankov I think its done. Isn't it?

**Comment by kanhegaonkarsaurabh** [comment]
@timabbott @borisyankov  I checked a private stream on RN app in the simulator and there seems to be a lock icon everywhere. Is this issue done? if not, what exactly should I work on, I'm unclear about that.

**Comment by borisyankov** [comment]
Yeah, I checked and the private icon is shown correctly everywhere it should.
Closing the issue as done.
