### ISSUE TITLE
poll is not showing in the app

### ISSUE THREAD

**Issue by hmr-it-jr** [zulip/zulip-mobile#3709]
At the moment it's not possible to see the poll in the app on Android.

It would be really helpful if this could be implemented.

Our usecase: we have poll templates for different takeaway food shops. One member of our team drives to the food shop and orders the requested food. Unfortunately he can't use the app and has to make a screen shot everytime.

So please add participating and viewing for polls to the app.

**Comment by gnprice** [comment]
Thanks @hmr-it-jr -- that description of your use case is helpful context!

We already have issue #3205 for tracking this feature. Would you make this comment there instead?
