### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by alan027** [zulip/zulip-mobile#3719]
so I want to make a website using gulp, when I install npm install to npm install gulp -g everything runs smoothly, but when I will install my "gulp" in Terminal there is an error in File C ... as a result in visual studio My code also can't display dist ... how to fix it

and in the visual studio code that has been installed there are some systems that do not run completely, such as style.css ... there is no effect when I enter CSS into the style.css folder as a result the web that I made does not change anything

**Comment by gnprice** [comment]
Hello!

This question doesn't appear to have anything to do with Zulip, as far as I can understand what it's about.
