### ISSUE TITLE
Add possibility to create new message with topic.

### ISSUE THREAD

**Issue by TomaszKolek** [zulip/zulip-mobile#372]
Maybe I missed something so please correct me if I'm wrong.

I think we don't have possibility to create new message with custom topic.
Is it intentionally or we should add it?

**Comment by timabbott** [comment]
No, that's just something we haven't built yet.

**Comment by TomaszKolek** [comment]
Hm... maybe when we click on new message text box we could show another text box above with possibility to add topic.
Just thinking

**Comment by borisyankov** [comment]
There is a <ComposeOptions> component that will serve to upload images etc. and is currently hidden. This is likely a good place for that option.

**Comment by borisyankov** [comment]
This is implemented.

**Comment by gnprice** [comment]
Exciting! @borisyankov, can you mention what PR or commit this feature landed in? That will help me follow it on its path to a release I can use on my phone :)

**Comment by borisyankov** [comment]
It is already on TestFlight, that is failing for some ;)
Next release (within 1-2 days) will have Sentry installed so we will debug the issue, and should push to App Store.

**Comment by gnprice** [comment]
Ah, I'm one of the people that release is consistently crashing for, so I can't tell. :) Thanks -- looking forward to seeing it!

**Comment by timabbott** [comment]
I do have a concern that the current design for choosing a topic makes the topic way too visible when it's the same as the current topic narrow...

**Comment by borisyankov** [comment]
I had the same concern, I have a WIP rework that makes it a bit less, and is also a fix for Android inconsistent behavior of the compose box. Hopefully, I'll complete it in 1-2 days and we can have it too in the next TestFlight.
