### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by mangral123456789** [zulip/zulip-mobile#3720]
Suppose you have a function, myfib, declared as follows:

int myfib(const int n)

which returns the nth Fibonacci number, using this function:

(a) Write a function, myfibseries, that also takes a single parameter, n, and prints out the entire sequence of Fibonacci numbers up to and including n, with a comma between each (do NOT use loops).

(b) Write a function, myfibseriesR, that also takes a single parameter, n, and prints out the entire sequence of Fibonacci numbers up to and including n, with a comma between each, but in REVERSE order (do NOT use loops).

(c) Write a function, myfibsum, that takes a single parameter, n, and prints out the sum of all the Fibonacci numbers up to and including n (do NOT use loops).

**Comment by gnprice** [comment]
This appears to be a homework problem that has no connection to Zulip.
