### ISSUE TITLE
Can't send messages to streams with commas in the name

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#3729]
If the user attempts to send a message to a stream which has at least one comma in the name, that message will never be sent.

(This is arguably a server-side bug, arising from the Zulip server parsing the `to` field as a comma-separated list even in `stream`-targeted messages. We'll still need a workaround, though.)

**Comment by gnprice** [comment]
Bumping priority because this is one of the handful of most frequent errors in our Sentry logs. It manifests there with the error message "Cannot send to multiple streams".
