### ISSUE TITLE
Messages with whitespace-only topics should not be sent

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#3743]
It should not be possible to attempt to send a message with a topic consisting only of whitespace.

----

Note: this bug interacts with #3731. If an attempt is made to post such a message, then – while such messages remain in the outbox – any future messages with *empty* topic will be unified with that topic, instead of being given the topic `(no topic)` as they ordinarily would.

**Comment by gnprice** [comment]
Reopened by the revert in #3837.

**Comment by gnprice** [comment]
The original fix #3748 caused #3820. See https://github.com/zulip/zulip-mobile/pull/3821#issuecomment-577829292 for a bit more discussion on how the logic might work here.

**Comment by gnprice** [comment]
Hmm. When the topic input is completely *empty*, we allow sending the message -- the server just turns the topic into "(no topic)". That mirrors the webapp.

Seems like when the topic input consists of whitespace, we should just treat that as an empty topic: you can send just fine, but we'll strip the whitespace, and the server will turn the topic into "(no topic)". More generally, we should strip leading and trailing whitespace in the topic.

Reassuringly, that also seems to be what the webapp does, so we'd be matching its behavior.

**Comment by gnprice** [comment]
Bumping priority because this is one of the handful of most frequent errors in our Sentry logs.
