### ISSUE TITLE
Create a documentation website using Github pages

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3746]
It is hard to navigate/search within the Github interface to read the docs for zulip-mobile.

Since zulip-mobile has it's own documentation, separate from that of zulip server, it might be helpful if a documentation website were to be set up at the [https://zulip.github.io/zulip-mobile](https://zulip.github.io/zulip-mobile) sub-domain using **Github pages**, perhaps using Jekyll to manage them easily (https://jekyllrb.com/)

An example of this type of setup can be seen https://crux-bphc.github.io/fest-manager/.
The organization is ```crux-bphc```, and the above link points to the documentation of the ```fest-manager``` project, which resides in the ```docs``` folder of the source repository.

There is already a `docs` folder in the zulip-mobile repository, so setting up the documentation website should not involve significant refactor of the repository.

I will be happy to work on this should this idea be approved.

**Comment by m1-key** [comment]
Can I work on this issue ?

**Comment by ray-kraesig** [comment]
One antifeature of the above solution (as seen at https://github.com/crux-bphc/fest-manager/tree/master/docs) is that, when viewed from the repository itself, links between documents no longer function.

This is not a fatal objection – we've already accepted this downside in the Zulip server repo, as can be seen at https://github.com/zulip/zulip/tree/master/docs – but if there's a reasonable way to avoid that and keep the inline documentation functional, it would be much preferred.

**Comment by timabbott** [comment]
With modern ReadTheDocs at least, it's now possible to make those links work on GitHub as well as in ReadTheDocs, as long as they're not to a hash within the page (those links are still broken).  We use that for the Zulip server repo now, and I imagine eventually recommonmark will fix that too.

I suspect we'd prefer using ReadTheDocs than GitHub Pages, if for no other reason than for consistency with the main Zulip webapp (It's also very convenient to administer and has nice support for things like configuring redirects when you rename a page).  I suspect it might even be possible to make our ReadTheDocs build script for the server project fetch `zulip-mobile` and build its docs in a "mobile" subsection, if desired (though we might need to be somewhat careful to avoid making a build-dependency on the mobile project?), but we could certainly make a `zulip-mobile.readthedocs.org`.

I'm happy to let the mobile folks figure out how to proceed, but wanted to raise that idea. 

@drrosa FYI as he made be able to add more.

**Comment by gnprice** [comment]
The main question I'd want us to answer before trying this is what we're aiming to gain.

The OP says it's hard to navigate/search; but I don't see any way at all to search on the example docs site https://crux-bphc.github.io/fest-manager/, nor any overall navigation, so it doesn't seem like GitHub Pages is helpful for that.

On the other hand ReadTheDocs would be helpful for that problem statement, if we want to work on that -- it provides a prominent overall navbar and a search feature.

One thing that example GitHub Pages site does do is that it looks quite a bit slicker than a GitHub browse page. That'd be under our control with either GitHub Pages or RTD. I'm not convinced that's a priority, though.

**Comment by drrosa** [comment]
@agrawal-d
Notice you can search the zulip-mobile documentation by simply adding a couple of parameters to a normal GitHub search like so: `repo:zulip/zulip-mobile language:Markdown` and you get both [Basic Search](https://github.com/search?utf8=%E2%9C%93&q=repo%3Azulip%2Fzulip-mobile+language%3AMarkdown&type=Code) and [Advanced Search](https://github.com/search/advanced?r=zulip%2Fzulip-mobile&l=Markdown&type=Code) of docs for free.

I know that docs navigation on Github is not ideal, but the zulip-mobile repo has only about 35 Markdown files of documentation compared to 100+ in the server project. I hope the search trick makes things at least a little easier. 

@timabbott 
I think it wouldn't be a bad idea for the mobile project to start using ReadTheDocs at some point, but I'd say the zulip-mobile docs are still small and manageable enough that switching over right now would most likely add a bit of unnecessary overhead to the project.

Also, given the mobile project has been sticking to Github and Markdown only, I think that a neater alternative would be https://rust-lang.github.io/mdBook. mdBook is meant for Markdown files only, looks nice, has both search/nav bar features, and it can be used as a command-line tool so setting it up shouldn't be difficult. It was created for the Rust project and so it continues to be well maintained.

@gnprice 
I think it would be a good idea to put a README in https://github.com/zulip/zulip-mobile/tree/master/docs that includes a table of contents and the basic/advanced search links I provided above just for convenience and to improve navigation a bit.

**Comment by gnprice** [comment]
> Also, given the mobile project has been sticking to Github and Markdown only, I think that a neater alternative would be https://rust-lang.github.io/mdBook. mdBook is meant for Markdown files only, looks nice, has both search/nav bar features, and it can be used as a command-line tool so setting it up shouldn't be difficult. It was created for the Rust project and so it continues to be well maintained.

Interesting, thanks for the pointer! When playing with Rust and Rust-related projects, I have generally felt that the docs are nicely rendered, so that is a point in favor of that tool.


> @gnprice
> I think it would be a good idea to put a README in https://github.com/zulip/zulip-mobile/tree/master/docs that includes a table of contents and the basic/advanced search links I provided above just for convenience and to improve navigation a bit.

That's probably a good idea, thanks.

**Comment by gnprice** [comment]
> I think it would be a good idea to put a README in https://github.com/zulip/zulip-mobile/tree/master/docs that includes a table of contents and the basic/advanced search links I provided above just for convenience and to improve navigation a bit.

OK -- I've just pushed 1ec5b640f and 1ec1d6b75. Please take a look, and thanks again @drrosa for the suggestion!

I'm going to close this issue, because I don't think we'll be pursuing a move to GitHub Pages.
