### ISSUE TITLE
Zulip mobile image load display is slow

### ISSUE THREAD

**Issue by maltokyo** [zulip/zulip-mobile#3754]
Is it possible to create heavily downsized images (after upload from user) in server settings?  My users upload 2-3MB JPEG files etc, and then complain that they are "slow to display".  We cant ask users to downsize them before uploading from their phones etc.

**Comment by gnprice** [comment]
@maltokyo Thanks for the feedback! I definitely agree that the software should take care of this without asking users to downsize the images first themselves.

I believe the server has at this point grown the core pieces of the functionality we need here, but we haven't connected things up to help the mobile app take advantage of that.

It looks like we haven't previously had an issue crisply tracking that feature, but it's an important one. I've just gone and filed it as #3790.
