### ISSUE TITLE
Flow loses track of prop types when we say `export default connect(...`

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3768]
This appears to be a bug in Flow itself. I can't find a report of it in the Flow tracker -- for example, this search comes up empty:
https://github.com/facebook/flow/issues?utf8=%E2%9C%93&q=is%3Aissue+export+empty
so probably I should turn it into a report there. (Though we shouldn't get our hopes up for that leading to a fix in bounded time.)

The symptom is that Flow winds up identifying many of our React components as having type `ComponentType<empty>`, which you can see by hovering over them in the editor wherever they're imported and used. The Flow type called `empty` is the bottom of the type poset, the subtype of all types; in our experience, it's often produced by bugs in Flow, and has the effect of papering over them and hiding related type errors.

Here, if you go and edit a call to such a component to pass some completely bogus props:
```
-        <AccountDetails user={user} />
+        <AccountDetails user={32} foo="bar" />
```
you find that Flow gives no error. So that's bad; there may be some real type errors this is hiding.

In at least a few spot-checked cases, the common pattern in the affected components is that we use `react-redux` on them, saying something like
```
export default connect((state, props): SelectorProps => ({
  realm: getCurrentRealm(state),
  userStatusText: getUserStatusTextForUser(state, props.user.user_id),
}))(AccountDetails);
```

It turns out that to fix the issue, it's enough to edit this like so:
```
const X = connect(/* ... */); // the exact same expression as before

// $FlowFixMe
const y = () => <X />;

export default X;
```
Now when the component is imported in some other module, it has the type it should have, like `ComponentType<{| +user: User |}>`; and a call with bogus props gets the error messages it should get.

It's not enough to separate the `const X = ...` and `export default`; if you comment out the `const y` line, it's back to the status quo with `ComponentType<empty>`.

The mention of `X` in `const y = ...` *should* have no effect on the type of `X`. After all, we don't even mention any props and the call doesn't type-check (hence the `$FlowFixMe`), so this doesn't give Flow any information it didn't already have. That's why I'm confident this is accurately described as a bug in Flow, and not in e.g. the type of `connect`. (A priori, it sure could have been a bug in the type of `connect`; that type is pretty complex.)

We should probably deploy some workaround across all our components that use the `export default connect(...` pattern; either the one above, or some variation we find that's equally effective.

**Comment by ray-kraesig** [comment]
> In at least a few spot-checked cases, the common pattern in the affected components is that we use `react-redux` on them [...]

Note that the converse does not hold – that is, errors of this sort are not suppressed on *all* Redux-connected components. In particular, editing `src/main/MainTabs.js` to give `OwnAvatar` a bogus prop...

```
-	        tabBarIcon: (props: TabNavigationOptionsPropsType) => <OwnAvatar size={24} />,
+	        tabBarIcon: (props: TabNavigationOptionsPropsType) => <OwnAvatar size={24} foo="bar" />,
```

... results in a Flow error, as desired.

**Comment by gnprice** [comment]
> Note that the converse does not hold – that is, errors of this sort are not suppressed on _all_ Redux-connected components. In particular, editing `src/main/MainTabs.js` to give `OwnAvatar` a bogus prop

Interesting, thanks!

Looking at `OwnAvatar.js`, the default-export looks like this:
```
export default connect(state => ({
  realm: getCurrentRealm(state),
  user: getSelfUserDetail(state),
}))(OwnAvatar);
```

So one possible pattern is that it applies when the argument to `connect` ("mapStateToProps") takes two parameters -- `props` as well as `state` -- rather than just one.

**Comment by chrisbobbe** [comment]
Looking into this -- will post my findings after lunch :)

**Comment by chrisbobbe** [comment]
> So one possible pattern is that it applies when the argument to `connect` ("mapStateToProps") takes two parameters -- `props` as well as `state` -- rather than just one.

From a bit of observation, thankfully this does seem to be the case.

I think I've found a workaround, and a small question about how our version of `connect()` works. The Flow bug is definitely still a bug for the reasons you've described, but I believe it may have surfaced because of some inferences we're asking Flow to make.

The correct type checking in uses of <AccountDetails ... /> comes back following this change:

```
- export default connect((state, props): SelectorProps => ({
+ export default connect<SelectorProps, Props, ComponentType<Props>>(
```

like so:

```
export default connect<SelectorProps, Props, ComponentType<Props>>(
  (state, props): SelectorProps => ({
    realm: getCurrentRealm(state),
    userStatusText: getUserStatusTextForUser(state, props.user.user_id),
  }),
)(AccountDetails);
```

What I believe I've done is pass explicit values for the type arguments to `connect` as it's defined in src/react-redux.js:

```
export function connect<SP, P, C: ComponentType<P>>(
  mapStateToProps?: (GlobalState, OwnProps<C,
    // Error "property `foo` is missing"?  Add to inner component's props.
    SP>) => SP,
): C => ComponentType<$ReadOnly<OwnProps<C, SP>>> {
  return connectInner(mapStateToProps);
}
```

whereas in current usage, the values for `<SP, P, C: ComponentType<P>>` have been inferred from the mapStateToProps argument. This inference is desirable because we don't want to have to pass <SelectorProps, Props, ComponentType<Props>> with each usage because 1) it's cumbersome, 2) it should be unnecessary if the inference works correctly, and 3) omitting it helps us mirror the default `connect()` behavior.

My question is about P there -- is it being inferred correctly? I'm not sure one way or another, but it's currently difficult for me to see how it could be. If correct inference of P is necessary for the exported component to be typed correctly, this may be worth investigating.

**Comment by gnprice** [comment]
Thanks @chrisbobbe !

> This inference is desirable because we don't want to have to pass <SelectorProps, Props, ComponentType> with each usage because 1) it's cumbersome, 2) it should be unnecessary if the inference works correctly, and 3) omitting it helps us mirror the default `connect()` behavior.

Yep, agreed.

I think that workaround will be a pretty good one to apply to all our affected `connect` calls, if we don't come up with a narrower one (e.g., one we can make once within our definition of `connect`.) It certainly feels less invasive than the `const y = () => <X />;` workaround described above.

As a small tightening, I'd predict that you can drop the second mention of `SelectorProps`, like so:
```
- export default connect((state, props): SelectorProps => ({
+ export default connect<SelectorProps, Props, ComponentType<Props>>(
+   (state, props) => ({
```
because the `connect` type should tie that directly to the first type argument. (Though given that we are dealing with buggy Flow behavior here in the first place, it's hard to say for sure before trying it.)

Oh, and another: I'd predict you can drop the `ComponentType<Props>` in favor of just `_`, i.e. asking Flow to infer that type argument:
```
- export default connect((state, props): SelectorProps => ({
+ export default connect<SelectorProps, Props, _>(
+   (state, props) => ({
```


> My question is about P there (and C because it depends on P) -- does our code lead to a correct inference (or any inference at all)?

Well, it seems to when the workaround in the OP is applied! Also in the case of a one-parameter `mapStateToProps`.

I think the way the inference happens is from this bit:
```
): C => ComponentType<$ReadOnly<OwnProps<C, SP>>> {
```
and in particular that first `C` -- the `connect` call is returning a function, and `C` is the type of that function's parameter. So when we go and apply the `connect` result another time, like `connect(...)(AccountDetails)`, Flow can see that `C` must be (a supertype of) the type of `AccountDetails`. Which in turn tells it what `P` must be.

**Comment by ray-kraesig** [comment]
The bug appears to be due not so much to the inability to infer `P`, but `SP` – the instantiation `<SelectorProps, _, _>` also works.

This seems to arise from the complicated use-site of SP:
```
mapStateToProps?: (GlobalState, OwnProps<C, SP>) => SP,
```
... where `OwnProps` is a decidedly nontrivial type, including two uses of `$Diff` and one type-level object-spread on types that may not be concretely available yet.

Loosening the type of mapStateToProps to avoid use of `SP` catches the bug introduced in the OP without call-site modifications:

```
export function connect<SP, P, C: ComponentType<P>>(
  mapStateToProps?: (
    GlobalState,
    // Error "property `foo` is missing"?  Add to inner component's props.
    $ReadOnly<$Diff<React$ElementConfig<C>, {| dispatch: Dispatch |}>>,
  ) => SP,
): C => ComponentType<$ReadOnly<OwnProps<C, SP>>> {
  return connectInner(mapStateToProps);
}
```

... although unlike the current setup, this incorrectly(?) permits accesses to fields in SP from within `mapStateToProps`. This is probably the lesser evil, but it would be nice not to have any evil here at all.

**Comment by gnprice** [comment]
> The bug appears to be due not so much to the inability to infer `P`, but `SP` – the instantiation `<SelectorProps, _, _>` also works.

Ah, well spotted, thanks! That simplifies the workaround further.


> ... although unlike the current setup, this incorrectly(?) permits accesses to fields in SP from within `mapStateToProps`.

Yeah, that sounds unsound if I'm understanding you right: `SP` is supposed to describe props that `mapStateToProps` provides, and which callers won't pass in. So in this issue's running example:
```
export default connect((state, props): SelectorProps => ({
  realm: getCurrentRealm(state),
  userStatusText: getUserStatusTextForUser(state, props.user.user_id),
}))(AccountDetails);
```

this would mean allowing references to `props.realm` inside that function, and expecting it to be of type `Realm`.

---

BTW I know the placement of that "Error ..." comment looks silly, but there is a reason for it :wink: :
```diff
$ git lsp -G "Add to in" src/react-redux.js
commit 81932ca0e3ae4617de6be1856f22da95f566f97b
Author: Greg Price <greg@zulipchat.com>
Date:   Mon Apr 8 15:51:06 2019 -0700

    connect: Add an error-help comment.
    
    I.e., a comment placed so Flow will show it in error messages. :)
---
 src/react-redux.js | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git src/react-redux.js src/react-redux.js
index 48bfc22aa..a11facc69 100644
--- src/react-redux.js
+++ src/react-redux.js
@@ -68,7 +68,9 @@ export type OwnProps<-C, -SP> = $Diff<
  */
 // prettier-ignore
 export function connect<SP, P, C: ComponentType<P>>(
-  mapStateToProps?: (GlobalState, OwnProps<C, SP>) => SP,
+  mapStateToProps?: (GlobalState, OwnProps<C,
+    // Error "property `foo` is missing"?  Add to inner component's props.
+    SP>) => SP,
 ): C => ComponentType<OwnProps<C, SP>> {
   return connectInner(mapStateToProps);
 }
```

In the relevant error messages, Flow will show that `OwnProps<C, SP>` call. This puts the comment inside that call. :slightly_smiling_face:
