### ISSUE TITLE
Can send private message to yourself,hide that button

### ISSUE THREAD

**Issue by rheo-chiti** [zulip/zulip-mobile#3785]
I don't know whether that's a bug or not but it will be nice if we don't get any "send private message" button when we are viewing our profile

![Screenshot_2020-01-10-14-18-21-53_e2eb6dad386ea79a8c34fb979200da81](https://user-images.githubusercontent.com/43493203/72139577-14d7b700-33b5-11ea-9359-58c4b367c99c.png)

**Comment by rheo-chiti** [comment]
Can I work on this issue?

**Comment by ray-kraesig** [comment]
This isn't a bug; it's a fully-functional feature. Self-PMs are useful as a scratchpad for testing out Zulip formatting features, or as a notepad for self-reminders. 

Closing.
