### ISSUE TITLE
Decouple navigation from Redux

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#3804]
This won't be a priority until we're closer to upgrading to React Navigation v5 (which currently hasn't been released yet, and we're on v2 now), but React Navigation will eventually stop supporting the pattern of storing navigation state in Redux. Here are the indications:

* The [v2 Redux integration doc](https://reactnavigation.org/docs/en/2.x/redux-integration.html) (the version we're on), rather colorfully: "**Warning: in the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work**", and "_Think twice before you consider doing this, there is an incredibly good chance that you do not need to do this!_"
* The [v3 Redux integration doc](https://reactnavigation.org/docs/en/3.x/redux-integration.html#can-i-store-the-navigation-state-in-redux-too), a little less frantic but still firm: "This is technically possible, but we don't recommend it - it's too easy to shoot yourself in the foot and slow down / break your app. We encourage you to leave it up to React Navigation to manage the navigation state."
* The [v4 Redux integration doc](https://reactnavigation.org/docs/en/4.x/redux-integration.html): "404: File not found"
* A [draft of a v4 -> v5 upgrade doc](https://reactnavigation.org/docs/en/next/upgrading-from-4.x.html#navigation-state-in-redux): "We have long recommended not to store navigation state in Redux. We have finally dropped support for storing navigation state in Redux in React Navigation 5.x."

See the discussion at https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/redux.20.2F.20navigation/near/808659.

In the meantime, this issue is a place to document what this coupling currently provides for us, so we don't forget about it when we eventually have to make the change. Since this pattern works for us, currently, incremental changes will be favored over large, dramatic ones.

**Comment by ray-kraesig** [comment]
Possibly also relevant: the existing "upgrade to v3" issue, #3649.

**Comment by chrisbobbe** [comment]
As @gnprice mentions [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M3745.20Server.20version.20to.20Sentry/near/930326), fixing this issue may help us in a somewhat surprising way: it appears that many of our import cycles go through `navReducer.js`. When there are too many import cycles, Flow and Jest sometimes panic and spit out lots of error output.

Concretely, I think one place where incremental work could be done is in gradually reducing our consumption of the `nav` state (switching over to other plumbings that don't use it), before eliminating the `nav` state entirely.

The exports of `navSelectors` make good search terms for where we consume `state.nav`. It would certainly be good to not add any more, but in the meantime, here's a checklist of the current exports (excluding ones only exported for tests):

- [ ] `getNav`: 1 call site, in AppWithNavigation.js
- [ ] `getChatScreenParams`: 1 call site, in eventMiddleware.js
- [ ] `getTopMostNarrow`: 1 call stie, in fetchActions.js
- [ ] `getCanGoBack`: 1 call site, in BackNavigationHandler.js
- [ ] `getSameRoutesCount`: 1 call site, in navActions.js

**Comment by chrisbobbe** [comment]
When we eventually remove react-navigation-redux-helpers, we should also remove @react-navigation/core from our direct dependencies.

See this [note](https://github.com/react-navigation/redux-helpers/releases/tag/3.0.8) on the version of react-navigation-redux-helpers we're using, saying we need to depend on it (they've also made it a peer-dep):

> Back to importing from `@react-navigation/core`. It forces any Flow user to have to install the `@react-navigation/core` libdef as well as the `react-navigation` one, but it's necessary to maintain compatibility with `@react-navigation/web`.

And react-navigation's [note](https://reactnavigation.org/docs/4.x/upgrading-from-3.x/#install-the-new-packages) stating their preference for not having people depend on it directly:

> Note: If you have `@react-navigation/core` or `@react-navigation/native` in your `package.json`, please remove them and change the imports to import from `react-navigation` package instead.
