### ISSUE TITLE
Feature request: delete topics

### ISSUE THREAD

**Issue by andreasoc** [zulip/zulip-mobile#3806]
Some users in my Company use only the APP and the possibility to delete or edit the topics is necessary.
thanks

**Comment by ray-kraesig** [comment]
Editing topics can be done already: long-press on any message. (The interface could definitely be improved, though.)

Deleting topics... isn't something we support at all, as far as I'm aware. Do you just mean "moving all the messages in one topic into another existing topic"?

**Comment by timabbott** [comment]
We do support that in the webapp these days:

![image](https://user-images.githubusercontent.com/2746074/72487751-db8fb480-37c3-11ea-8695-fe57825831df.png)

The API endpoint is `streams/(?P<stream_id>\d+)/delete_topic`; not part of the documentation yet.

**Comment by andreasoc** [comment]
> Editing topics can be done already: long-press on any message. (The interface could definitely be improved, though.)
> 
> Deleting topics... isn't something we support even on the web interface, as far as I'm aware. Do you mean "moving all the messages in one topic into another existing topic"?

I confirm that the topic deletion is present in the desktop app, but not in the mobile app

**Comment by agrawal-d** [comment]
I have made a PR that implements this feature : https://github.com/zulip/zulip-mobile/pull/3824

**Comment by ray-kraesig** [comment]
> I have made a PR that implements this feature : #3824

For future reference: there's no need to post this sort of thing in the GitHub issue, so long as you've used the magic words in the PR itself (which you have). GitHub's automatic backlink suffices.
