### ISSUE TITLE
[iOS]: Crash on adding photo from camera if “Access to photos” permission not granted

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#3813]
I’ll fill this in with more detail tomorrow, but on iOS it seems that we have a crash when trying to add photos from the **camera** (not the media library!) when read access to photos (i.e., the media library) is not granted. Seen on iPhone 6s with iOS 13.3 on v26.20.143.

**Comment by rheo-chiti** [comment]
When access is not granted,an alert should be shown asking for permissions

**Comment by chrisbobbe** [comment]
Sure, thank you! There’s one thing I hadn’t pointed out in my initial comment (and I’ll write up something more tomorrow; I’m currently typing on mobile, so not as quickly, and should sleep soon as it’s 1:30 in the morning).

The native alert requesting permissions did actually display correctly, following the iOS quirk I mention in https://github.com/zulip/zulip-mobile/issues/3814, but the crash happened anyway. The crash also happens when you decline that permission, start up the app, and try again, when the native alert does not show up (again, following that quirk).

**Comment by rheo-chiti** [comment]
On android, I cleared my data and didn't gave permissions to access photos but app didn't crashed .
On second time when I tried to add photo,nothing happened and it didn't asked for permissions.

**Comment by rheo-chiti** [comment]
I fixed it for android ,when permissions are not granted initially,permissions can be granted later on.Like this->
![20200116_224615](https://user-images.githubusercontent.com/43493203/72547413-9e562000-38b2-11ea-87aa-3fd3bd1cbf4d.gif)

**Comment by chrisbobbe** [comment]
Ok! I believe the issue you’re addressing is slightly different (maybe related to #3787?); this issue describes a complete crash of the app process on iOS, forcing a user to reopen the app, and it seems like that’s not happening on Android.

**Comment by chrisbobbe** [comment]
I'll do some digging and see if I can come up with a fix for this today.

**Comment by chrisbobbe** [comment]
Just made a PR -- looks like fileName is not available when this permission is not granted, and instead of coming through as undefined, which is handled, it's null. The PR lets it handle null.
