### ISSUE TITLE
App bar still retains 'Edit Message' title after discarding edit 

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3815]
**Steps to reproduce**
1. Try to edit any message.
2. Don't actually edit it. Just press back.

**What happens**
App bar title becomes 'Edit Message' until app restart - even when you change streams etc.

**What is expected**
The title should revert to stream etc. title.

**Comment by agrawal-d** [comment]
Fixed in https://github.com/zulip/zulip-mobile/pull/3823

**Comment by ray-kraesig** [comment]
This bug is entirely subsumed by #2757 – "Edit Message" remaining in the app bar is actually the less interesting half of the problem.

Closing as duplicate. (This does not imply rejection of the submitted PR.)
