### ISSUE TITLE
App crashes on viewing user profile when timezone is unknown

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3816]
**Steps to reproduce**:
1. Navigate here in the mobile app https://chat.zulip.org/#narrow/stream/48-mobile/topic/App.20crashing/near/809664
1. Tap on Steve Howell's profile picture.

**What happens**
The app crashes. Doesn't crash on viewing any other user's profile

**Error log** :http://p.ip.fi/ywPP

**Comment by agrawal-d** [comment]
**Possible causes?**
1. See https://github.com/necolas/react-native-web/issues/1430#issuecomment-538039400
1. Steve's user profile returns timezone as PRC in the mobile app, but the timezone PRC is not present in timezone_vx.x.x.js. On the other hand, my timezone, Asia/Kolkata is present in the file. That's possibly a cause of the bug?

**Comment by gnprice** [comment]
Fascinating, thanks!

The log linked above says:
```
TypeError: TypeError: Cannot read property 'rules' of undefined

This error is located at:
    in AccountDetails (created by Connect(AccountDetails))
    in Connect(AccountDetails) (at AccountDetailsScreen.js:43)
    in RCTView (at View.js:45)
[...]
```

I think the next question is: what is the thing we're trying to get the property `rules` from?

A timezone sounds like a plausible answer to that -- a timezone basically consists of a bunch of "rules" describing what the offset from UTC is for what intervals. So one direction would be to see if choosing that timezone reliably reproduces the issue.

**Comment by gnprice** [comment]
See also [chat discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/App.20crashing/near/809661).

**Comment by chrisbobbe** [comment]
I hope this isn't a distraction, but we have reports of strange activity related to the "last active" time when viewing a user's profile. Possibly related to a timezone issue?

Observed in mobile: https://chat.zulip.org/#narrow/stream/48-mobile/topic/timestamp.20bug
Observed in web: https://chat.zulip.org/#narrow/stream/9-issues/topic/.22last.20active.22.20incorrectly.20says.20.22never.22

**Comment by agrawal-d** [comment]
**Confirmed - App crashes due to timezone `PRC`**
I changed my timezone to `PRC`. The app crashed on viewing my profile. The timezone `PRC` is not present in `timezone_vx.x.x.js`

I believe we use a third party library to manage timezones?

**Comment by agrawal-d** [comment]
The source code of [timezone](https://github.com/bigeasy/timezone) package also does not contain the timezone `PRC`, so updating it wont fix this.

Also, `PRC` **is** a valid tz timezone  (see [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) ) , so our third party library is outdated/incompatible.

**Comment by ray-kraesig** [comment]
Note that even if the Zulip server's time zone library can be updated, we still need to work with older versions of servers. A server-side fix won't be enough to close this issue.

**Comment by gnprice** [comment]
> Note that even if the Zulip server's time zone library can be updated, we still need to work with older versions of servers. A server-side fix won't be enough to close this issue.

Agreed. In addition, we need to work with *newer* server versions. New timezones come into existence regularly, so new server versions may have new timezones we don't know about. In general, unknown timezones can happen and we need to behave in a reasonable way.

(BTW it's not quite accurate that `PRC` is a deprecated timezone; "`PRC`" was another name for the timezone `Asia/Shanghai`, which is very much in use. What it is is a deprecated *name* for that timezone.)
