### ISSUE TITLE
Send button in private messages is disabled

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#3820]
It looks like https://github.com/zulip/zulip-mobile/commit/a2d6793aeac19259c205a175048f4017bf89ddcb was made to fix https://github.com/zulip/zulip-mobile/pull/3748, but it introduced the side effect of preventing people from sending private messages! Private messages don't have topics, so the added conditional disables the send button.

**Comment by ray-kraesig** [comment]
*Mea culpa* – I should have caught this in testing.

(On which note, this strikes me as a good thing to have a Pirlo test for.)

**Comment by Maskedman99** [comment]
fixed issue by changing 

``state = { topic: this.props.lastMessageTopic, }``    to ``state = { topic: this.props.lastMessageTopic || 'topic', }`` in class ComposeBox
