### ISSUE TITLE
Possible issue management tweaks (zulipbot, "feature parity" label?)

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#3831]
@ray-kraesig mentioned that there were a few things blocking the ability to use zulipbot in this repo, as it's being used in zulip/zulip. Maybe this issue can be a place to list the things blocking it.

Also, while it may or may not affect our prioritization rules, I wonder about making issues easier to understand at a glance by adding a "feature parity" label (or some other, more recognizable word) that just means its solution would fill in a gap in functionality where a feature exists in the web app but not yet in the mobile app. Most new features will fall in this category, I suppose, so it may not end up being necessary.

**Comment by chrisbobbe** [comment]
Maybe an "In progress" label too, which I've seen on zulip/zulip? Maybe this comes with Zulipbot automatically, I'm not sure.

**Comment by chrisbobbe** [comment]
So far I've created the labels "a-documentation" and "a-navigation" (and maybe another? I can't remember now...); I couldn't think of any reason not to.

**Comment by gnprice** [comment]
> So far I've created the labels "a-documentation" and "a-navigation" (and maybe another? I can't remember now...); I couldn't think of any reason not to.

Sounds good! There are probably some more area labels that'd be good to add, too.

The companion task that'd be quite helpful to do whenever making a new label is just to go and search through the existing issues and PRs -- the open ones, anyway -- and add it where appropriate. That helps bootstrap the label's usefulness, and also helps make it discoverable.

**Comment by gnprice** [comment]
> adding a "feature parity" label (or some other, more recognizable word) that just means its solution would fill in a gap in functionality where a feature exists in the web app but not yet in the mobile app.

Hmm yeah -- perhaps "webapp parity", or just "webapp feature"? I agree this is often helpful context to know about an issue; it might be useful to have as a label.


> Maybe an "In progress" label too, which I've seen on zulip/zulip? Maybe this comes with Zulipbot automatically, I'm not sure.

That does come with Zulipbot. But also I'm not sure it really adds anything beyond the "assigned" field -- I think basically that label should be present on an issue exactly when there's someone assigned, and the latter already shows up nicely in lists of issues. Are there ways you'd want to use it that that doesn't cover?

There are certainly plenty of issues that are assigned to someone and aren't really in progress, but I think the fix for that is to unassign them :slightly_smiling_face:; and the reasons that can make that hard apply in the same way to unmarking as "in progress".

**Comment by gnprice** [comment]
On the original question:
> there were a few things blocking the ability to use zulipbot in this repo, as it's being used in zulip/zulip. Maybe this issue can be a place to list the things blocking it.

here's a previous discussion in chat: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/zulipbot/near/642958

Summary [here](https://github.com/zulip/zulipbot/issues/161#issuecomment-422577094); that thread has a bit more discussion too.

I think the basic blocker for enabling it on this repo is the ability to be selective about which features are enabled. Some of its features can be pretty spammy, and are arguably worth it on zulip/zulip but aren't for us. The one feature I'm confident we'd want, if we could enable it without also getting all the others, is `@zulipbot claim` to get Zulipbot to assign oneself an issue.

**Comment by chrisbobbe** [comment]
Ah, since https://github.com/zulip/zulipbot/issues/161#issuecomment-422577094 is open, I'll close this as a duplicate. Next on my list is to retroactively apply those new area labels I've created.

**Comment by chrisbobbe** [comment]
> Hmm yeah -- perhaps "webapp parity", or just "webapp feature"? I agree this is often helpful context to know about an issue; it might be useful to have as a label.

OK! I'll add this to my list of labels to retroactively apply.

> That does come with Zulipbot. But also I'm not sure it really adds anything beyond the "assigned" field -- I think basically that label should be present on an issue exactly when there's someone assigned, and the latter already shows up nicely in lists of issues. Are there ways you'd want to use it that that doesn't cover?

Right, no, that makes sense; unassigning would be a better way to mark something as stale.

**Comment by ray-kraesig** [comment]
> That does come with Zulipbot. But also I'm not sure it really adds anything beyond the "assigned" field -- I think basically that label should be present on an issue exactly when there's someone assigned, and the latter already shows up nicely in lists of issues. Are there ways you'd want to use it that that doesn't cover?

I'm aware of one useful search which is possible with an `in progress` label, but not with the assignee field: searching for stale-but-assigned issues. GitHub provides the special search term `no:assignee` as a search parameter for unassigned issues, but it cannot be negated.

**Comment by gnprice** [comment]
> GitHub provides the special search term `no:assignee` as a search parameter for unassigned issues, but it cannot be negated.

Huh! Wacky. Indeed, here's what [the docs say](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-assignee):

> You cannot search for issues and pull requests that have *any* assignee, however, you can search for issues and pull requests that have no assignee.

where the last bit is a link to the spot that documents `no:assignee`. Seems like a silly limitation on GitHub's side. Good to know about.

That does sound like it'd make an `in progress` label potentially useful as part of an implementation of the Zulipbot nag-then-unassign feature. I think it still doesn't seem very independently useful, though.

**Comment by ray-kraesig** [comment]
> I think it still doesn't seem very independently useful, though.

`is:issue is:open label:"good first issue" -label:"zz-in progress"`

**Comment by gnprice** [comment]
> `is:issue is:open label:"good first issue" -label:"zz-in progress"`

That will be a more compelling use case in a world where the results of just `is:issue is:open label:"good first issue"` don't fit on one page :wink: . (Right now [it gets](https://github.com/zulip/zulip-mobile/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) three results.) Remember that when things are assigned, that shows up in its own column in the results, so it's quick to visually scan.
