### ISSUE TITLE
No notification, even with a missed-message email

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3835]
We've had a couple of reports recently of not getting notifications, where the user *did* get a missed-message email.

I *think* the detail that there was a missed-message email rules out #3699 / #3659 as the cause -- i.e. that it means we weren't seeing the user as present and suppressing a notification for that reason. Also both of these reports came after zulip/zulip#13512, which means the users most likely had the setting to send notifications even when they're active anyway. But this logic is complex and I'm not sure that isn't the cause.

The reports are
* [in chat](https://chat.zulip.org/#narrow/stream/2-general/topic/Testing.20mobile.20client/near/811131), testing on chat.zulip.org on 2020-01-22, with an @-mention on a stream
* in a Play Store review 2020-01-20:
  > Sometimes messages come in. Other times I'm "offline" and get an email. Those messages often never arrive in the app.

  (This one might also be saying they opened the app and didn't find the messages, but either way it must mean they didn't get notifications.)

**Comment by Amolith** [comment]
I'm using Android 10 with ArrowOS and a broken microG installation so Google Services and thus GCM are unavailable. The Zulip app is from F-Droid and version 26.20.143. For Stream messages, I have mobile notifications enabled as well as @all and @everyone. For private messages, @-mentions, and alert words, everything is enabled.

**Comment by Amolith** [comment]
@gnprice also sent me a PM at 2:33. I got an email notification for it shortly after but not one on my phone.

**Comment by gnprice** [comment]
Thanks @Amolith for those follow-up details!

I replied in the chat thread linked above, but to circle back here: it's known that notifications depend on FCM (or APNs, on iOS) and so won't work on an Android phone that doesn't have Google Play Services. It'd be substantial work to build an alternative way of delivering notifications, so that won't change anytime soon, but it'd be helpful for us to have an issue saying so; I'll go file one.

In the meantime, that resolves the mystery here. The Play Store review probably has some other cause (because that person installed the app through the Play Store, so almost surely has Play Services running); but we don't have more details, and it could be something like they're using a private Zulip server that hasn't set up notifications. So, closing this issue.
