### ISSUE TITLE
Opening reactions list from search history results in app crash

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3856]
Steps to reproduce:
1. Search for "happy new year" on CZO using the app.
1. Long press on any reaction.

What happens:
App crashes immediately. Doesn't happen in case of all messages, only for certain messages.

What is expected:
I should be able to see the reactions screen.

Error log:
```js
TypeError: TypeError: Cannot read property 'reactions' of undefined
 
This error is located at:
    in MessageReactionList (created by Connect(MessageReactionList))
    in Connect(MessageReactionList) (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:45)
[...]
```
Complete log: http://p.ip.fi/iAcw

My device is running v26.20.143 (Android Oreo).

**Comment by agrawal-d** [comment]
A bit of debugging shows that `reactions` is a property extracted from `message` in `MessageReactionList.js:89`, but `message` here is undefined. 

In the `connect` function for `MessageReactionList.js:116`,  there is no message corresponding to the messageId `805764` in `state`, which results in mesage becoming `undefined`.

**Comment by agrawal-d** [comment]
Strangely, while I was debugging these crashes, the crashes stopped happening for the messages as time passed. But searching for some other query resulted in a new batch of search results, for which crashes still occurred.

**Comment by agrawal-d** [comment]
Also, adding a reaction is not reflected, but the reaction *does* get added, as re-searching shows the reaction.

**Comment by agrawal-d** [comment]
I believe the cause of this bug is that search results are rendered using API results, and these messages are no present in `state`, so anything that interacts with the message using `state` will not work, while anything that uses the API results will work.

**Comment by chrisbobbe** [comment]
Thanks for the report, investigation, and writeup! 🙂 https://github.com/zulip/zulip-mobile/pull/3854 is definitely relevant (that's the PR for https://github.com/zulip/zulip-mobile/issues/3803), but it won't completely fix this issue, which describes a case where the reactions list definitely needs to be usable, but currently isn't.

**Comment by gnprice** [comment]
Interesting -- thanks for the report!

> I believe the cause of this bug is that search results are rendered using API results, and these messages are not present in `state`

Huh, indeed. I'm looking at `SearchMessagesScreen.js`, and I see we fetch the messages directly with `api.getMessages`, and keep them in local state to pass down to `MessageList` without ever storing in Redux.

To fix this, I think we should probably put the messages into `state.messages` in our Redux state.
