### ISSUE TITLE
Colour of Status bar in splash screen doesn't match with the brandcolor

### ISSUE THREAD

**Issue by Maskedman99** [zulip/zulip-mobile#3860]
![Screenshot_20200202-004353_Zulip](https://user-images.githubusercontent.com/31368194/73597787-f5682000-4555-11ea-836f-cc11a893f7b8.jpg)

Change the color of status bar to match with that of the splash screen color.

**Comment by Maskedman99** [comment]
Can I work on this?

**Comment by ray-kraesig** [comment]
For reference, this is only true on Android. The iOS status bar is effectively transparent:

![Screen Shot 2020-02-03 at 14 29 11](https://user-images.githubusercontent.com/54861490/73696888-1c2b7100-4692-11ea-8e03-2378d00c344b.png)
