### ISSUE TITLE
“See who reacted” button placement inconvenient

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#3871]
A regular user reports (on the Recurse realm):

> [T]he "See who reacted" feature on mobile (which is really really useful!) should probably appear below the "Add reaction" on the press-and-hold menu, so that the muscle memory for pressing "Add reaction" works the same for posts with and without a reaction currently on them - when I try to react with multiple emojis, I usually hit "Add reaction" the first time, then "See who reacted" the second time, since it took the place of the "Add reaction" button.

I thought about appending this as a comment to https://github.com/zulip/zulip-mobile/issues/3798, since it’s in a related area of the UI, but this adjustment is truly bite-size and may be a good first issue, so I didn’t want it to delay on the work being done there.

**Comment by sumukhah** [comment]
Working on the issue....Thank you @chrisbobbe

**Comment by chrisbobbe** [comment]
Ah, I found out by testing on an Android device that this isn't Android-only, and the issue is slightly different than I thought. It's not that the same exact place on the screen is being tapped, but rather, whatever the topmost button in the action sheet is. So, on iOS and Android, both, this should be the Add Reaction button.
