### ISSUE TITLE
Some components/screens break when number of recipients is large in Group PMs

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3891]
Message list:
![group-pm](https://user-images.githubusercontent.com/7714968/74245419-f98bfe80-4d08-11ea-9394-a4b3f077fc43.gif)

PMs list:
![image](https://user-images.githubusercontent.com/7714968/74247478-1ece3c00-4d0c-11ea-972c-d20098fc7669.png)

PM screen:
![image](https://user-images.githubusercontent.com/7714968/74247508-2ab9fe00-4d0c-11ea-872e-e2927ce232ed.png)

**Comment by gnprice** [comment]
Thanks @agrawal-d for this report!

I think this is probably best tracked as three separate issues -- each of these will be good to fix, and the solutions may be independent. (In particular, whatever we do in the message list will probably involve inside-webview code quite separate from those other parts of the UI.) Would you be up for filing those?

One step toward addressing these: I'm curious how group PMs like these wind up looking in the webapp.

**Comment by agrawal-d** [comment]
Closed in favour of #3938, #3939. #3940.
