### ISSUE TITLE
Possible to use offline

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#391]
The app remains usable even when no network is present.
Slack and FB Messenger are good examples of

Currently, we are halfway there.
We need to cache messages, subscriptions, and users from the last run, for this feature to work.
 
* recognize 'Airplane mode', which is different than 'No Network'
* if the app is offline, do not try to get more messages
* cache images and other resources?
* search should be performed client-side

**Comment by borisyankov** [comment]
Closing as complete.

**Comment by nicopace** [comment]
There might be a regression, as right now it doesn't work.

**Comment by nicopace** [comment]
well... it was implented on this app, but not in the new app... will post it there.

**Comment by nicopace** [comment]
Just for completion, mentioned it here: https://github.com/zulip/zulip-flutter/issues/2446
