### ISSUE TITLE
Convert from names to stream IDs to identify streams

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3918]
This is a meta-issue which covers a large number of independent tasks. Filing it in order to have a place to point to refer to the overall effort.

This is parallel to #3764, but for streams. Just like users can change their email addresses, streams can have their names changed, and so the permanent, numeric stream IDs are a better way to refer to a stream.

Most of the discussion in #3764 applies to this as well.

Tasks for specific instances of this include #3244, and #2760 which we fixed last summer.

**Comment by chrisbobbe** [comment]
> Tasks for specific instances of this include #3244, and #2760 which we fixed last summer.

Do I understand correctly that #3244 is the last remaining instance of this? #4635 has a commit that's marked as fixing that.

**Comment by gnprice** [comment]
> > Tasks for specific instances of this include #3244, and #2760 which we fixed last summer.
> 
> Do I understand correctly that #3244 is the last remaining instance of this? #4635 has a commit that's marked as fixing that.

No, unfortunately -- those were just the instances that had specific tasks at the time.

#4333 is the biggest remaining instance of this -- we identify narrows by stream name rather than stream ID. It connects to other instances which may not have specific tasks in our tracker.

#3998 will help, giving us stream IDs on Outbox values. That will let various code that consumes those -- especially all the code that consumes `Message | Outbox` -- stop using names and use the IDs instead.

**Comment by gnprice** [comment]
The victory condition for this issue is basically: if you try removing the `name` property from the definitions of the `Stream` and `Subscription` types, Flow should find only a handful of errors (i.e. places we're still using the property), all of which should be purely legitimate uses. (Which basically means just showing the name to the user in the UI.)

One quick approximation to that is to grep for `streamName` -- I've tried to shift to that name for most locals and function parameters that refer to a stream name. If you try that now, it finds 131 matches (or 103 with `-w`). The bulk of those are uses that ought to be using stream IDs. I believe most of them at this point are part of #4333 -- they're using the stream name to identify a stream or topic narrow.

So I think at this point the sequence for resolving this issue will be:
* Finish #3998. With #5000 merged, the next step there is to wait for a few weeks after a release with #5000 is out; then we can merge a migration that finishes #3998.
  * Then do any easy followups on that.
* Then do #4333. This may be fairly complex. We did the PMs side of this in the series of PRs leading up to #4382.
* Then mop up any remaining instances of this issue. I think at that point these will be small, if there are any.

**Comment by gnprice** [comment]
> * Then mop up any remaining instances of this issue. I think at that point these will be small, if there are any.

OK, with #5205 merged, this is now indeed mostly done!

I went and looked through the codebase for remaining places where we're using the name of a stream. This meant searching the code for the patterns `streamName`, `stream.name`, and `3918`, and also making the `name` property on `Stream` and `Subscription` be write-only/reads-forbidden and seeing where Flow complained.

The results were:
* In notifications, up until `getNarrowFromNotificationData`. This is zulip/zulip#18067, for which a fix was just merged the other day. Servers starting with 5.0 will send the stream ID as well as the name.
* `api.subscriptionAdd`, `api.subscriptionRemove`, `api.createStream`. This is zulip/zulip#10744, currently open.
* The muted-topics model. This is also open in the server: [chat discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/stream.20IDs.20in.20.60muted_topics.60/near/1319924).
* `api.sendMessage`. This got stream-ID support in server 2.0, so it's already in all the server versions we support.
* `showStreamInHomeNarrow`, which will be simple to fix.
* Several references that don't ultimately actually use the stream name, notably around `TopicItem`.
* And then a number of places where the stream name is actually appropriate to use, because it's for showing it to the user in the UI. (The main/unreads screen; the stream-list screens; recipient headers in the message list; the app bar on the message-list and lightbox screens; autocompleting #-mentions; a few others.)

For the places that need server support, I'll want to make sure that
* there's a server issue open, if it's not already fixed in main;
* there's a comment with either `TODO(server-x.y)` or a reference to the server issue;
* where we can't yet rely on server support, we at least rely on stream IDs internally and convert from/to names at the boundary with the server -- so in particular we store muted topics by stream ID.

Then when those are the only remaining uses of stream names that should be IDs, I think it may be time to declare victory on this issue. We'll get to the `TODO(server-x.y)` comments when the time comes, and we can track the still-open server issues in their own way.

**Comment by gnprice** [comment]
> * The muted-topics model. This is also open in the server: [chat discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/stream.20IDs.20in.20.60muted_topics.60/near/1319924).

This got filed as a server issue: zulip/zulip#21015.

There's now a draft API change and backend implementation: zulip/zulip#21251.

**Comment by gnprice** [comment]
Here's also a quote from my description of #5268 which closed this issue. It's an update of my comment above from a month before it was closed, explaining the status of the followup work and how it's tracked separately from this issue:

> As forecast at [#3918 (comment)](https://github.com/zulip/zulip-mobile/issues/3918#issuecomment-1026479673) , there remain some places where we use stream names that should be IDs, but these are limited to interacting with the server in places where it doesn't support IDs. For those, moreover:
> 
> * We nevertheless make sure to convert promptly to stream IDs at the edge (e.g., maintaining the muted-topics model in terms of stream IDs). This means that while we're still exposed to bugs if a stream rename races with another interaction we have with the server about that stream, we at least don't hit a bug simply because a stream was renamed while the app was open -- in other words, the race window is much narrower.
> * Some of them were fixed in the server a while ago, and have comments like `TODO(server-2.0):`. We'll take care of those sometime soon in a followup to [api: Start relying more on non-ancient servers #5100](https://github.com/zulip/zulip-mobile/pull/5100), as we concretely drop support for ancient server versions we already don't support.
> * Some (well, one -- notifications) were fixed in the server recently, and have comments like `TODO(server-5.0):`. We'll take care of those circa late 2023, when we drop support for all server releases that exist today. In the meantime, we make sure to take advantage of stream IDs when the server is new enough to provide them.
> * Some aren't fixed yet: [Switch webapp to subscribe/unsubscribe from streams by ID zulip#10744](https://github.com/zulip/zulip/issues/10744). These have `TODO(server-future):` comments.
