### ISSUE TITLE
Narrow sometimes lands one screenful in the past

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3921]
This is forked off from #3457 -- it's a specific bug we discovered on that thread, which falls into that class of symptoms broadly defined, but appears to be a different bug from the one causing the early reports in that thread.

Specifically, as @ray-kraesig [reported](https://github.com/zulip/zulip-mobile/issues/3457#issuecomment-555234717):
> The test case involved repeatedly entering and leaving a stream (with all messages read) containing a handful of unusually-long individual messages. [...] No reloading of the app or its assets was performed.
>
> When `handleInitialLoad` is called, `document.body.scrollHeight` and `.clientHeight` would take on one of two pairs of values: [one correct, one with a mysterious zero]
>
> The latter, of course, is incorrect; its appearance was consistently associated with the message-list initially being scrolled to a point in the past. Conversely, the former was consistently associated with the message-list initially being scrolled to the bottom, as expected.

We investigated some more. Quoting my summary of what we learned:

---

OK, here are some things we learned in the chat discussion [[here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/clientHeight.20and.20friends/near/798730)]:

* Both in @ray-kraesig 's repro, and when I repro it (both of us in Android emulators), the symptom is we land right about one screenful too high. (To within <2px in Ray's case; about 54px more than a screenful in mine.)
* The observations above, where `scrollHeight` is too big, are kind of puzzling as a cause for that symptom! Because in that case `scrollToAnchor` should be trying to scroll us too far _down_.
* But, we also found a diagnosis for something that puts us a screenful too high! The `resize` handler is getting called as we go from a `clientHeight` of 0 to the actual `clientHeight`. When the viewport gets taller, that handler is meant to scroll us up (as measured from the top of the viewport to the top of the content) in order to keep the bottom of the viewport at the same spot in the content. So, it dutifully scrolls us up by one screenful.
* The following patch, which cuts out that spurious resize, resolves the issue completely in my repro case:

```diff
 let viewportHeight = documentBody.clientHeight;
 
 window.addEventListener('resize', event => {
+  if (viewportHeight === 0) {
+    viewportHeight = documentBody.clientHeight;
+    return;
+  }
   const difference = viewportHeight - documentBody.clientHeight;
```

* I think in fact that should be a 100% fix for the case where the desired location is at the bottom, i.e. the caught-up case. The initial `scrollToAnchor` will try to scroll too far down; we'll get clamped to the actual bottom, and all's well. But if we meant to show the user something in the middle, then scrolling too far down is already bad.
* So I think we need to _both_
  
  * delay the initial `scrollToAnchor` until a point where we have sensible heights, as discussed above; and
  * avoid spurious scrolling on a `resize` from zero.
* More generally, we shouldn't use `viewportHeight` when it has a nonsense value. (Are other nonsense values possible besides zero?) I looked at other places where we use `viewportHeight`, and both of them will make a reasonable approximation of doing nothing if `viewportHeight` is zero:
  
  * `visibleMessageIds` will return an empty range.
  * `findPreserveTarget` will return `{ type: 'none' }`.
  
  (Both will call `someVisibleMessage(0, 0)`, which will return null.)
  It'd be good to make that more direct and explicit, though.

---

[still quoting from that summary:]

I think at this point the main open question may be: what's an appropriate way to wait for the heights to get reasonable values set? Some discussion above in this thread; I don't think we expanded much on that point in the chat thread.

Oh, except I linked to this bit of context that Ray had shown me the other day, [in a spec](https://www.w3.org/TR/cssom-view/#dom-element-clientheight):

> If the element has no associated CSS layout box or if the CSS layout box is inline, return zero.

Where following a link there finds that the term "CSS layout box" is not actually defined.  And that it's been that way since at least 2008, so it's not like this is a recently-drafted fast-moving spec that may get that point filled in any day now.

Anyway, though, that at least explains why zero in particular is a nonsense value we might see -- and offers encouragement that that might be the only nonsense case.

There were also some helpful pointers from Tim into the webapp code, which I haven't yet fully studied. That could be a very helpful comparison.

**Comment by chrisbobbe** [comment]
>   * delay the initial `scrollToAnchor` until a point where we have sensible heights, as discussed above; and

From my reading of this issue, #3457, and the [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/clientHeight.20and.20friends/near/798730), it sounds like this is still an unsolved problem; is that right? Greg, you noted [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/clientHeight.20and.20friends/near/798813) that you've observed that this sequence sometimes occurs:

> * `viewportHeight` initialized (to zero)
> * `resize` handler runs
> * `handleInitialLoad` runs

If we could ensure that this *always* occurs, then "delay the initial `scrollToAnchor` until..." is accomplished — as long as the resize handler contains the `if (viewportHeight === 0) {` patch you quoted above.

**Comment by chrisbobbe** [comment]
I suppose one way forward is to eliminate the use of `documentBody.scrollHeight` from the initial `scrollToAnchor` (n.k.a `scrollToMessage`) (called from `handleInitialLoad`) altogether. This could be done by ensuring there is always a targetNode as long as there is at least one message in the list. This, in turn, could be done by changing `getFirstUnreadIdInNarrow` to return the last message in the list if there are no unreads.

**Comment by gnprice** [comment]
> Greg, you noted [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/clientHeight.20and.20friends/near/798813) that you've observed that this sequence sometimes occurs:
> 
> > * `viewportHeight` initialized (to zero)
> > * `resize` handler runs
> > * `handleInitialLoad` runs
> 
> If we could ensure that this _always_ occurs, then [...]

Yeah. OTOH as I also mentioned there, it's really quite puzzling that that can ever occur! Because that looks like a `resize` event firing in the middle of what textually is just an unbroken string of JS code, namely our `DOMContentLoaded` callback.

I just spent a while (likely longer than I should have) digging into the specs to try to understand this, but only confirmed that it seems like it really shouldn't happen. The [MDN page for the `resize` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event) led me to the [spec for when that fires](https://drafts.csswg.org/cssom-view/#resizing-viewports), which led to the [spec for the overall event processing model](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model)... which only seems to confirm that that shouldn't happen. (I also looked at the [spec for when a `DOMContentLoaded` event fires](https://html.spec.whatwg.org/multipage/parsing.html#the-end:event-domcontentloaded).) I must be missing something, but I don't know where.

We'd probably have to resolve that puzzlement in order to get to a convincing solution for making it always occur :wink:

**Comment by gnprice** [comment]
> This, in turn, could be done by changing `getFirstUnreadIdInNarrow` to return the last message in the list if there are no unreads.

Hmm! Yeah, I agree -- this sounds like a promising solution. As we discussed the other day, it'd be good to have `getFirstUnreadIdInNarrow` (or some other code that's still in the main JS environment with all our data) compute that, so that we can always pass a specific message ID in for the webview JS code to scroll to.

**Comment by gnprice** [comment]
It seems like this may have been fixed! Or at least made much rarer.

Specifically, when testing #4370 just now, I attempted the repro above: repeatedly entering and leaving a stream, without reloading the app. This was on an emulated Pixel 3a running Android 11, from a recent master 602bcc16c. And I couldn't reproduce -- the behavior was perfect every time.

I did reproduce it once, out of a bunch of tries, atop the #4370 branch (in the version before I made it not have any effect on Android.) It could be that that change would have reintroduced this bug at a low rate, or it could be that it's still present at a low rate and it's just chance that that was the only try that turned it up.

At the time of the initial report, both Ray and I could reproduce it frequently (half the time? more?) in Android emulators, so even a low rate would be a substantial change.

---

I don't believe we've made any changes in our code that I'd expect to potentially affect this.

The most likely other code that would have changed is the browser: my testing just now was in Chrome 83 (which shipped with Android 11, and comes in an Android 11 emulator image). It looks like both I and Ray neglected to mention what Chrome (or even Android) version we were using in our previous testing, oops -- but it couldn't have been Android 11. At the latest it would have been Android 10, so... Chrome 74.0.3729.185, as I go and look at an emulator image now. So some change between Chrome 74 and Chrome 83 could well have fixed it.

I'm not sure anyone ever tried this repro on iOS. With #4357 fixed after #4370 , and with the attention we've just paid to exactly the situation where this bug appeared, it seems like if this bug existed there now (at least on iOS 14), we'd know about it.

**Comment by gnprice** [comment]
> The most likely other code that would have changed is the browser

Well, I tested just now in
* an emulated Pixel 3 runing Android 10, with Chrome 74.0.3729.185
* an emulated Nexus 5 running Android 9, with Chrome 69.0.3497.100
* an emulated Pixel 2 XL running Android 8.1 Oreo, with... Chrome 69.0.3497.100, huh

and I couldn't reproduce in any of those.

My own testing in 2019-11, when we first saw this, would have been in one of those emulated devices (or possibly another from the same versions of Android.) So it seems something else is different.

We did upgrade RN, and perhaps more relevantly `react-native-webview`, between the original report and now. So those are certainly candidates for changes in our app that might have brought in a fix.

**Comment by gnprice** [comment]
I'm going to close this issue because it seems we can no longer reproduce it, and because I don't recall seeing it anytime recently and we haven't heard any user reports of it in the year since it was filed. If we spot any symptoms like this again, we'll file a new bug.

There may still be an opportunity here to simplify our interaction with the browser's layout and scrolling: https://github.com/zulip/zulip-mobile/issues/3921#issuecomment-601366187 and https://github.com/zulip/zulip-mobile/issues/3921#issuecomment-601464395 .
