### ISSUE TITLE
Profile icon breaks for group PMs with large no. of recipients

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#3939]
PMs list screen:

![image](https://user-images.githubusercontent.com/7714968/75606143-dab2a800-5b0f-11ea-9bee-cb897908fcf3.png)

**Comment by agrawal-d** [comment]
@gnprice said
>One step toward addressing these: I'm curious how group PMs like these wind up looking in the webapp.

The web app doesn't display icons at all, so it's not an issue there:
Screenshot of list of private messages -
![image](https://user-images.githubusercontent.com/7714968/75606205-780ddc00-5b10-11ea-8b62-571264910693.png)

**Comment by gnprice** [comment]
Thanks @agrawal-d for spotting and reporting this!

I've never been much of a fan of this initials-based pseudo-icon in any case. I'd be happy to see it completely reimagined. But in any case we should fix this bug. :-)

Maybe:
* Use just one initial, not two: use the very first letter of the name (so from the person's first name, in the case of Western name conventions)
* If there are up to 4, write the initials.
* If there are more than that, then write only 3, followed by a plus sign.

Beyond about 4 I think the lists of initials get pretty unreadable anyway. :wink:
