### ISSUE TITLE
Keep the parsed ZulipVersion in Redux state, rather than raw string

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3951]
This is a followup to #3745 that would make the Zulip server version just a bit more convenient to use in our code: in the `Account` type which we use in `state.accounts`, instead of having `zulipVersion` be a string, have it be an already-parsed `ZulipVersion` object.

The main potentially-tricky thing here is that we want to keep that information in persistent storage via `redux-persist`, so we'll need to somehow tell `redux-persist` how to serialize and deserialize it.

That's the same challenge seen in #3950 and #3949. So one valuable side benefit we could get from doing this is to make it a warmup for those. See detailed notes in #3950.

We'll also want to migrate data smoothly from previous versions of the app that had the version as a string in Redux. This isn't particularly critical here -- after all, we re-fetch the version on every `/register` -- but it may be in future more-complicated cases of #3950 and #3949, so it'd be good to include that in the things we're working out a pattern for how to do.

**Comment by chrisbobbe** [comment]
I'll take this, as I started working on it with a redux-persist transform before you created this issue. 🙂

**Comment by chrisbobbe** [comment]
@gnprice, I'm wondering about the logic to select the particular part of state to apply this transform to, i.e., the `accounts` state. The `createTransform` API lets you whitelist some parts of the state; this example uses that, as well as redundant checks within the inbound and outbound transform functions, to show that it can be done either way or both ways.

```
const zulipVersionTransform: Transform = createTransform(
  (inboundState: GlobalState, key) => {
    if (key !== 'accounts') {
      return inboundState[key];
    }
    return inboundState[key].map(account => {
      if (account.zulipVersion === undefined) {
        return { ...account, zulipVersion: undefined };
      }
      return { ...account, zulipVersion: account.zulipVersion.raw() };
    });
  },
  (outboundState: GlobalState, key) => {
    if (key !== 'accounts') {
      return outboundState[key];
    }
    return outboundState[key].map(account => {
      if (account.zulipVersion === undefined) {
        return undefined;
      }
      return { ...account, zulipVersion: new ZulipVersion(account.zulipVersion) };
    });
  },
  { whitelist: ['accounts'] },
);
```

The other way we could go is more general; we apply the inbound and outbound transforms to all fields named `zulipVersion` that appear anywhere in the state.

If this is desired, one way we could avoid implementing our own state traversal logic is to use ["custom serialization functions"](https://github.com/zalmoxisus/remotedev-serialize#passing-custom-serialization-functions) implemented by remotedev-serialize, which we may end up using anyway for #3950. But not only would that delay implementation of the ZulipVersion transform, but it would make the ZulipVersion transform depend on a library whose primary use for us is orthogonal (i.e., to serialize/deserialize ImmutableJS data).

What do you think?

**Comment by chrisbobbe** [comment]
I've expanded that snippet into a WIP PR, #3952.
