### ISSUE TITLE
In "add reaction" search, accept actual emoji as well as names

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3961]
A user [reports](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Reactions/near/829192):
> When you click "add reaction" you get the emoji drop down list and the search field.
>
> On the search field, if you add the smile emoji from the Android keyboard (not the "smile" word) you can't add it as a reaction. The only available action is to search, but it can't find the emoji on the drop down list.

This is a perfectly reasonable thing to want to do -- system emoji keyboards can be pretty great, and many people are accustomed to them and they have the user's frequently-used emoji. So we should make it work.

To do this, I think what we need to do is basically to search through the actual Unicode values of Unicode emoji, as well as the names of the emoji.

**Comment by 7lym** [comment]
Hello, this would be a useful alternative to revamping the emoji picker menu (by using groups for example, just like system emoji keyboards do). 
Is this feature still part of the release roadmap? Thank you.
