### ISSUE TITLE
Support "Sign In with Apple" [Android]

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3965]
This is the Android counterpart of #3964, a client-side companion to zulip/zulip#14168. We need to support this Apple auth service on Android, because people may sign up using it on iOS and then also want to use Zulip on an Android device. Filing as a separate issue because it may have a separate implementation.

In addition to the links at zulip/zulip#14168, some Apple docs that may be specifically relevant:
* https://developer.apple.com/documentation/signinwithapplejs/incorporating_sign_in_with_apple_into_other_platforms

As far as possible, I think we'll want to treat this just the same as Google auth, GitHub auth, SAML, etc., with our `webAuth` flow -- give the user a browser and let them authenticate there.

FWIW as an example, though, here's someone's implementation for Android (Android-native, in Kotlin):
* https://github.com/willowtreeapps/sign-in-with-apple-button-android

I don't know of an implementation for RN which isn't specific to iOS.

**Comment by beinganonymous** [comment]
@gnprice Do you want to authenticate user from directly ``Android`` or ``webAuth`` ?
If you are willing to authenticate from ``Android`` then [this](https://github.com/willowtreeapps/sign-in-with-apple-button-android) library is open-source and good to implement, then i would like to work on this issue.

**Comment by gnprice** [comment]
> If you are willing to authenticate from `Android` then [this](https://github.com/willowtreeapps/sign-in-with-apple-button-android) library is open-source and good to implement,

That's the one I linked in the description as an example :slightly_smiling_face: 

I think we'll want to use the web-based flow, to keep things simple.

This also won't be ripe to work on until the server side zulip/zulip#14168 is done, or at least mostly done. I'll label it accordingly.

**Comment by chrisbobbe** [comment]
Closing this as fixed by #4034! 🎉
