### ISSUE TITLE
Set up CocoaPods

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3983]
CocoaPods is a tool for managing iOS libraries. It's been since forever a thing that many people use in their React Native apps; for example, it's in the standard instructions for integrating RN into an existing app:
https://reactnative.dev/docs/integration-with-existing-apps#3-install-cocoapods
It wasn't in the template sample app, though (the one `react-native init` uses), and so naturally lots of other people didn't use it. We briefly had our own app set up to use it, but then took that out, all back in 2017; see history in 861744be8 (#3870).

In RN v0.60, some work landed that made it work more smoothly with RN than it did before, and that was then followed up by making the template sample app (used by `react-native init`) include it in the build. In RN v0.61, they went further so that IIUC (#3781) it becomes required to use CocoaPods to manage the build for any RN app. So for a while we've planned to switch back to it as one of the things we'll do in the course of #3548, upgrading to RN v0.60.

Now there is a fresh reason to want to do this, with its own deadline! Specifically, for #3964 Apple auth, the handy implementation someone's already made is [a package in Expo](https://github.com/expo/expo/tree/master/packages/expo-apple-authentication) and its install instructions require something called [react-native-unimodules](https://github.com/unimodules/react-native-unimodules) which in turn requires CocoaPods. So, past time we split out an issue specifically for this.

Here's two different sources of instructions on how to go about doing this:
* RN upstream's docs for [integrating into an existing app](https://reactnative.dev/docs/0.59/integration-with-existing-apps), particularly the section ["Configuring CocoaPods dependencies"](https://reactnative.dev/docs/0.59/integration-with-existing-apps#configuring-cocoapods-dependencies).
  * Note that there are tabs near the top of that page for choosing from "iOS (Objective-C)", "iOS (Swift)", and Android. The two iOS tabs have different sample Podfiles there, even though this has nothing to do with which language you write your code in. So that provides two different examples, using the Podspec features in somewhat different ways, which is helpful information for building an understanding of what's going on.
* The install instructions for that [react-native-unimodules](https://github.com/unimodules/react-native-unimodules) library have some pointers of their own for setting up CocoaPods. Naturally this has some overlap with the RN upstream instructions.
  * Note in particular the spot where these instructions have one version for RN <= v0.59 and another for RN >= v0.60. We'll want the former now, and later as part of #3548 we'll presumably move to the latter.

See also some previous discussion [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/cocoapods/near/807626).

**Comment by chrisbobbe** [comment]
> Note in particular the spot where these instructions have one version for RN <= v0.59 and another for RN >= v0.60. We'll want the former now, and later as part of #3548 we'll presumably move to the latter.

Mm, this was useful! The react-native docs website has decided to serve a single page for all react-native versions, for the "Integrating with Existing Apps" page, so https://reactnative.dev/docs/0.59/integration-with-existing-apps#configuring-cocoapods-dependencies has an out-of-date example Podfile. I reported that at https://github.com/facebook/react-native-website/issues/33#issuecomment-601453102.
