### ISSUE TITLE
All the languages are not displayed in Laguage Pick screen

### ISSUE THREAD

**Issue by sumukhah** [zulip/zulip-mobile#3989]
only 21 languages are displayed instead of 30

![Screenshot from 2020-03-20 16-18-59](https://user-images.githubusercontent.com/23723464/77157412-4d87c100-6ac7-11ea-858f-77046c8ec12a.png)
![Screenshot from 2020-03-20 16-15-12](https://user-images.githubusercontent.com/23723464/77157425-537da200-6ac7-11ea-8019-3d092900b631.png)

**Comment by sumukhah** [comment]
working on the issue

**Comment by gnprice** [comment]
Hi @sumukhah! I'm guessing that you were looking at a version of the app from before commit
17bdd67747625925d02a8215b540c8bcc6da8a71, which was included in the last release. Before that commit, we did indeed offer 21 different languages.
