### ISSUE TITLE
Stream subscribe buttons are slow to react

### ISSUE THREAD

**Issue by harshbisle** [zulip/zulip-mobile#3995]
![20200322_224018](https://user-images.githubusercontent.com/41483548/77255512-2f1ff200-6c8e-11ea-9d71-fec0103409db.gif)

The stream subscribe buttons are sometimes slower than usual.

**Comment by sumukhah** [comment]
@harshbisle are you working on this?

**Comment by harshbisle** [comment]
@sumukhah yes.!! Please check the other issues

**Comment by sumukhah** [comment]
@harshbisle, mention if you are working on the issue so that other developers won't spend time at fixing.

**Comment by harshbisle** [comment]
Yes @sumukhah I am working on this issue. 
Thank you.

**Comment by jainkuniya** [comment]
I am assigning this to @harshbisle, for better visibility.

**Comment by harshbisle** [comment]
Thanks @jainkuniya

**Comment by Maskedman99** [comment]
@harshbisle they're slower because a request is being made to the server, and the server has to process the request and reflect those changes. The slowness might be because of the server side slowness or your network bandwidth. 
You can refer to issue #3944

**Comment by harshbisle** [comment]
@Maskedman99 yeah I agree on that. But as @gnprice says "I touch it and it might flicker over to the new value, come right back to the old value, then a second or two later return to the new one. The exact sequence varies."in the  issue #3944 that thing should happen even though it's related to server I think.

**Comment by harshbisle** [comment]
https://github.com/zulip/zulip-mobile/issues/3944#issuecomment-601468373 
you can see the difference.

**Comment by ray-kraesig** [comment]
Ah, not just that it's slow to react, but that it's jumpy! Sorry; it's not always easy to tell if a switch is actually jumping, or if the GIF just has a low frame rate.

Merging this into #3944, which is a preexisting bug about the same behavior elsewhere.
