### ISSUE TITLE
Scroll-to-bottom button has an awkward highlight

### ISSUE THREAD

**Issue by harshbisle** [zulip/zulip-mobile#3996]
![Screenshot_20200322-102914](https://user-images.githubusercontent.com/41483548/77255782-f8e37200-6c8f-11ea-9671-18ea1be08214.png)
When the user clicks on the scroll to bottom button the hover effect looks a little bit buggy(Basically the square around the button).

**Comment by ray-kraesig** [comment]
This highlight is generated by the WebView; as far as I can tell, we have no direct control over its shape – we'd have to eliminate it (`-webkit-top-highlight-color: rgba(0,0,0,0)`) and synthesize a new one.
