### ISSUE TITLE
Support swipe navigation between "Subscribed" and "All streams"

### ISSUE THREAD

**Issue by harshbisle** [zulip/zulip-mobile#3997]
![Screenshot_20200316-122350](https://user-images.githubusercontent.com/41483548/77255976-4ca28b00-6c91-11ea-92d7-02604b1884d4.png)
Add a feature to support the navigation between All streams and subscribed on swiping which makes it easier for users to switch between the both.

**Comment by jainkuniya** [comment]
I am not sure, is this required or not. Because we have nested tabs, user might get confused.
We need to think over, which tabs needs this functionality. 

old PR, focussing on the same. https://github.com/zulip/zulip-mobile/pull/3668

**Comment by gnprice** [comment]
Thanks @harshbisle , and thanks @jainkuniya for that cross-reference!

Here's a previous [chat discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/swipe.20on.20streams.20screen/near/804928) a few months ago.

I agree we should do this. It seems like we're consistently hearing that people expect swiping to work for that pair of top tabs; whereas for the bottom tabs (or "bottom navigation" -- as @ray-kraesig in that chat thread points out that Material Design, at least, reserves the name "tab" for the top kind) we don't hear that.

**Comment by gnprice** [comment]
Looks like there's one other place we have top tabs, which is `MessageReactionList` (the screen you get to from "See who reacted" on long-press on a message.)

That one doesn't currently have swiping working either. We should enable swiping between tabs there too.

**Comment by harshbisle** [comment]
Yes @gnprice we need to improve that part too.
