### ISSUE TITLE
Add sender_id and stream_id properties to Outbox

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3998]
We have a type called `Outbox` that's meant to be a lot like `Message`. It represents messages the user has hit "send" on from the compose box, and that we're still in the process of actually getting to the server (and then hearing back from the server as new messages.)

It doesn't quite have all the same properties as `Message` has, which is fine -- we don't use all those properties.

But in particular, while it has a `sender_email: string`, it does not have `sender_id: number`. This is basically a case of #3764.

Similarly it has this property:
```
  display_recipient: $FlowFixMe, // `string` for type stream, else PmRecipientUser[].
```
which, just like on `Message`, is for a stream message the name of the stream. But it lacks this other property which `Message` has:
```
  stream_id: number, // FixMe: actually only for type `stream`, else absent.
```
So this is basically a case of #3918.

We should add those two properties. Then all Outbox objects (outside tests) are created by `addToOutbox`, so we should fill the properties in appropriately there.

The scope of this issue does *not* include switching to actually use them yet -- and in fact we can't immediately, without some more work. The reason is that we persist outbox messages between runs of the app, so a new version of the app could get `Outbox` values stored by an old version that didn't fill in these properties.

---

Fortunately, outbox messages are inherently perishable -- we already discard them at one week of age, figuring that's better than sending a message which may be badly out of date and out of context. So, here's a low-effort way we can solve this problem.

First, let's:
* Add the two properties to `Outbox`, as *optional*.
* Start filling them in for all `Outbox` values we create.
* Next to the two properties' definitions in the `Outbox` type, have a TODO comment saying we introduced them at such-and-such time.
* Close this issue as having been fixed. :tada: 

Then we wait until a release with the above changes has been out a month or two.

After that, at our leisure, we:
* Switch the properties to required. Add a migration that simply deletes any outbox messages where they're missing.
  * This will only affect users who upgrade from the old version before the above changes, straight to this version, within a week -- and moreover have a message they tried to send on the old version that's still hanging around, unsent, when they start this new version.
  * I expect almost all users, almost all of the time, have zero outbox messages hanging around between runs of the app. So with this timeline, my hope is to reduce to a probable zero the number of users for whom this migration has any effect at all.
  * And if it's not quite zero, that's not a big deal. Once a message is hanging around unsent for more than a few minutes, it's already not an awesome experience even if we do go on to send it. And we already discard such messages if you do something like switch to another account and back, which is much more common than this migration.
* Now we can start actually using these properties! In particular we can go clean up the workaround at https://github.com/zulip/zulip-mobile/pull/3968#discussion_r396830086 that caused me to notice this fact :wink: . There will probably also be other examples of #3764 and #3918 that these properties enable us to cleanly handle.
  * Another place where these will let us make the code cleaner: https://github.com/zulip/zulip-mobile/pull/4899#discussion_r703932340

**Comment by chrisbobbe** [comment]
Just sent #4667 to continue this work.

**Comment by gnprice** [comment]
(I just added to the description another followup opportunity: https://github.com/zulip/zulip-mobile/pull/4899#discussion_r703932340 .)
