### ISSUE TITLE
Add ability to compose new messages

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#4]
This is a large task and will require additions to the UI (for a compose bar and text fields) and API logic to send new messages to the server.

**Comment by rishig** [comment]
Some screenshots from the current android app, as a starting point:
![composebox](https://cloud.githubusercontent.com/assets/890911/17823540/dd8ca2ca-6611-11e6-8d29-886030c495b8.png)
![composeicon](https://cloud.githubusercontent.com/assets/890911/17823751/fd44bebc-6612-11e6-843c-c7769e9ea972.png)
