### ISSUE TITLE
Better structure and refactoring

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#40]
Some issues that I will improve on:
- [x] Rename components from ZulipSomething to just Something
- [x] Rename components that are called SomethingView to SomethingScreen or SomethingScene, when they take up the whole screen
- [x] Rename user reducer into account reducer
- [ ] Add more 'container' components, whose job is to wrap more purely presentational/behavioral components. They will get data from Redux and will request data from the api
- [ ] Better organization of Flow types, some might go in one file
- [ ] Clear distinction of Flow types - data from API vs internal data format

**Comment by neerajwahi** [comment]
@borisyankov why add container components?

**Comment by borisyankov** [comment]
Mostly for separation of concerns. Sometimes for better reusability, but not always.
I've also used before it to convert from Immutable to plain JS objects, but not sure it was consistently a good idea.

Generally a container will take care of retrieving the data (from Redux, via fetch, etc.) but will just render a single component. The behavior and view will be in this component, but it will be 'dumb' about where the data is coming from.

Some of the ideas come from:
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.fakt3m8o4
and some from other discussion places and personal experience.

**Comment by neerajwahi** [comment]
I think we can wait to do this kind of refactoring until it becomes a bigger problem. Thoughts?

**Comment by neerajwahi** [comment]
Also, I'm not sure it's worthwhile to add Flow types to the API calls. Flow is a static type checker but the API results are dynamic, so it won't really be able to do any checking with those types.

**Comment by borisyankov** [comment]
@neerajwahi Yeah, I wanted to document the goals more than necessarily put it as priority.
New stuff will follow this, but not going to rework everything that was written (did the Zulip removing because it was trivial)

**Comment by borisyankov** [comment]
Closing as 'complete'.
