### ISSUE TITLE
can't insert gifs using Android keyboard gif search ("Zulip doesn't support image insertion here")

### ISSUE THREAD

**Issue by nodesetc** [zulip/zulip-mobile#4011]
When I try to do this, I get the error message "Zulip doesn't support image insertion here".

It'd be great if the Android client supported this.  I'm not sure if it works on iOS, as I've just started playing with Zulip.  But I'm spinning up an instance that I'm hosting myself on Digital Ocean, to have a long term searchable chat platform as a modern successor to an old email listserv for some friends and I, and on other chat applications we all use (SMS/MMS, Signal, WhatsApp, Slack) this has become a common (and so important to support) mode of communication.  Image preview for gif links seems to work well in the web UI.

Anyway, very interested to hear whether supporting this would be a priority for y'all.  Having done no mobile development, I have no idea how painful it'd be to implement, but I think it'd be a well loved feature.

This is with an installation of the Zulip app from the Play store this morning, on vanilla Android on a Pixel 2.

Anyway, hope this isn't a deal breaker for getting my friends on board, I'm excited otherwise from what I've seen so far.

**Comment by gnprice** [comment]
Thanks for the feature request! It looks like we ended up filing this again as #4969; consolidating there because that thread now has a few more details.
