### ISSUE TITLE
Translation errors appears on some screen 

### ISSUE THREAD

**Issue by sumukhah** [zulip/zulip-mobile#4013]
Some words are not added for translation resulting in error.

![1](https://user-images.githubusercontent.com/23723464/78057249-0a213280-73a4-11ea-9feb-27992553172c.jpg)

**Comment by sumukhah** [comment]
Working on the issue

**Comment by ray-kraesig** [comment]
Closed by #4013... for now, at least. There are doubtless a few untranslated strings still floating around, but this does clear up a nice chunk of them.
