### ISSUE TITLE
Autocomplete popups don't show up at all

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#4024]
Recently, autocomplete popups (such as for @-mentions, stream name completions) have stopped showing up.

I'm currently on the latest master. ( a7f6cc8bb6813d297d1e8bed6fe7cc171ca26819 )

**Comment by agrawal-d** [comment]
Seems to be working now.

**Comment by ray-kraesig** [comment]
For future reference: [per discussion on CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Autocomplete.20popups/near/849202), this vanished after a `git bisect`; it's assumed to have been due to some stale cache in the build system.
