### ISSUE TITLE
Messages looks broken

### ISSUE THREAD

**Issue by Maskedman99** [zulip/zulip-mobile#4032]
I was building from master branch.
![Screenshot_20200410-111836_Zulip (debug)](https://user-images.githubusercontent.com/31368194/78966291-0bc5c580-7b1d-11ea-85f1-a42c51c80210.jpg)

Happening in Android

**Comment by Maskedman99** [comment]
rebuilding again the error goes away

**Comment by Maskedman99** [comment]
My bad, issues doesn't go away. Has something to do with the commits merged in April 9, 2020

**Comment by agrawal-d** [comment]
Looks like https://github.com/zulip/zulip-mobile/issues/4018.

**Comment by Maskedman99** [comment]
Thanks @agrawal-d, closing the issue since it's a duplicate.
