### ISSUE TITLE
Reply and Forward Fuction

### ISSUE THREAD

**Issue by hanhnguyen121088** [zulip/zulip-mobile#4037]
1. I cannot find forward message function on Zulip app
2. I cannot quote and reply a message sent by another one on Zulip mobile 
3. I cannot double click on the quoted message to see the original position when it was sent  as Viber app can do
 Could you please kindly help me on this because i want to apply this helpful app to my company

**Comment by hanhnguyen121088** [comment]
@gnprice i hope you can help me on this

**Comment by chrisbobbe** [comment]
Hi @hanhnguyen121088!

1. This doesn't sound like a feature that is available in the main app, so I don't think it's ripe for engineering work here in the mobile app. Please let me know (with more details, please!) if you think this is wrong. You might like to discuss a new feature on chat.zulip.org (the Zulip development community) or at https://github.com/zulip/zulip. Is your use case covered, at least for stream messages, by the existing ability to `@-mention` people?
2. This sounds like https://github.com/zulip/zulip-mobile/issues/1975. https://github.com/zulip/zulip-mobile/issues/3436 is related, and Greg says it may be best for work to be done on this one before #1975.
3. This looks like https://github.com/zulip/zulip-mobile/issues/1336.

**Comment by cyphase** [comment]
Duplicate of #1975, I believe.
