### ISSUE TITLE
Exception: Unable to parse color from string: #NaN

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4038]
Here's an error we've started getting recently in Sentry. Happens in 26.25.148 and 26.26.149.

It's an uncaught exception, so it crashes the app.

Message:
`Error: Error: Error: Unable to parse color from string: #NaN`

Stack trace:
```
src/utils/color.js in foregroundColorFromBackground at line 6:3
export const foregroundColorFromBackground = (color: ColorValue): 'black' | 'white' =>
  Color(color).luminosity() > 0.4 ? 'black' : 'white';


src/common/GroupAvatar.js in render at line 55:14
    const textSize = {
      fontSize: size / 3,
      color: foregroundColorFromBackground(frameSize.backgroundColor),
    };

... then framework frames ...
```

Example event (for those with access to Sentry):
https://sentry.io/organizations/zulip/issues/1597595682/events/3dfbe00091684a8c9a5bc5c6a559ae25/?project=191284

In all the events for this issue that I've skimmed through, the breadcrumbs show this was very shortly after a request to `https://zulipchat.com/compatibility` -- which is something we do only just after startup. So that means the app is crashing on launch, which is a pretty bad experience.

**Comment by chrisbobbe** [comment]
One guess is 658003e863030ecd5a16e2553b178ff4313ba751 and https://github.com/zulip/zulip-mobile/issues/3985

**Comment by gnprice** [comment]
Escalating to P0 as this is probably the cause of a [reported situation](https://chat.zulip.org/#narrow/stream/48-mobile/topic/White.20screen.20bug/near/852821) where the app crashes on startup, and then just crashes again even if you force-quit and try relaunching.

**Comment by chrisbobbe** [comment]
Closing, as https://github.com/zulip/zulip-mobile/pull/3991 was merged. 🎉
