### ISSUE TITLE
Store server feature level in Redux

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4049]
(This isn't ripe to do any work on until the server side has been implemented.)

Per zulip/zulip#14618, we plan to add a "feature level" number to the server's API, which appears alongside `zulip_version` but can be used at a finer grain.

Once it's there, we'll want to observe it on `/server_settings` and `/register`, and maintain it in Redux. This will work just like #3839.

Then we'll want to use it instead of the version number anywhere we can -- basically, for any new server feature that's after 2.1.0. In particular:
* `stream_post_policy`, for #3140 
* as an optimization on how we use zulip/zulip#14500 (discussion [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/view.20uploaded.20files/near/855422))
* new Markdown features as discussed [here](https://chat.zulip.org/#narrow/stream/6-frontend/topic/common.20frontend.20markdown/near/816929)

Priority because of #3140.

**Comment by gnprice** [comment]
Unblocked now that zulip/zulip#14618 is merged.

**Comment by hashirsarwar** [comment]
I am working on this issue.

**Comment by chrisbobbe** [comment]
> Then we'll want to use it instead of the version number anywhere we can -- basically, for any new server feature that's after 2.1.0.

@gnprice, do we know the particular minimum server version that will have this flag? The above implies that such a minimum server version exists, but it's not 2.1.0. Maybe 2.1.1?

Just so we can the right comment for `zulip_feature_level` on `ApiResponseServerSettings`.
