### ISSUE TITLE
Spurious(?) `apns_device_token` requests may be made for dead realms

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4057]
We have [an event](https://sentry.io/organizations/zulip/discover/zulip-mobile:16840fd3c7794350a4f6f36cb8f95732/?field=title&field=event.type&field=project&field=count_unique%28user%29&name=All+Events&project=191284&query=&sort=-count_unique_user&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) in Sentry where
* the breadcrumbs show a number of successful requests to URLs like `https://chat.example:1111/api/v1/register` (and `users/me/presence` and `server_settings?`), with a port;
* and then there's a request to a similar URL but lacking the port, like `https://chat.example/api/v1/users/me/apns_device_token`. Naturally it fails, with status 401.

Kind of puzzling why we'd be dropping the port from the URL for that one route but not those others. It'd be good to debug that and fix it.

First spotted at https://github.com/zulip/zulip-mobile/issues/4050#issuecomment-616754046 .

**Comment by ray-kraesig** [comment]
On reviewing the code, there seems to be no mechanism that could result in the port being lost from the URL. In particular, I could not directly reproduce this on Android using a local server listening on an explicitly-named port.

However, `apns_device_token` (like its Android-side equivalent, `android_gcm_reg_id`) is almost unique among routes: it can be fetched for *any* account, not just the currently-logged-in account. This occurs in `sendAllPushToken` in `src/notification/notificationActions.js` – and although the comments state that this is only done for "logged-in" accounts, there is no code to filter out any account.

It seems likely that the user has two accounts set in their app – one for the nonexistent realm `https://chat.example`, and one for the active realm `https://chat.example:1111` – and that only the former query is producing errors. (Note that the initial account may not even have been created erroneously! It's quite possible the Zulip service was initially present on port 80, but was later moved, and that the user simply hasn't bothered to delete the first account.)

If so, I'm actually not quite sure what to do about it! Having a `.filter(acc => acc.apiKey)` in that function would almost certainly improve matters, but it won't catch the case where the account was merely *switched* out of, and the Zulip realm in question was taken offline while the user wasn't looking.

**Comment by gnprice** [comment]
Got it. Thanks for the investigation!

I think this is probably WONTFIX, then. Based on that diagnosis, these requests aren't doing any harm. This is how we enable the server to send us notifications, so if the failure is transient for any reason it's important we eventually get through. I think it therefore makes sense to just keep sending these until the end of time or unless the user actually deletes the local record of the account.

**Comment by ray-kraesig** [comment]
That's reasonable, but I'd argue that there is still a bug here we want to fix – namely, the fact that we're sending up Sentry reports for something that's not a bug in the app, and is expected to occur fairly regularly.

(I think we may just want to discard errors from API calls in `sendAllPushToken`.)

**Comment by gnprice** [comment]
> That's reasonable, but I'd argue that there is still a bug here we want to fix – namely, the fact that we're sending up Sentry reports for something that's not a bug in the app, and is expected to occur fairly regularly.

True, that would be good to fix!

The trick is to do it in a narrow enough way that it won't suppress some future kind of report that do indicate a bug.


> (I think we may just want to discard errors from API calls in `sendAllPushToken`.)

In particular this seems too broad -- we could well develop a bug that causes these to start failing in general for some users. The consequence would be that they don't get notifications, so that's a high-priority thing to spot.
