### ISSUE TITLE
Narrow contains email 'welcome-bot@zulip.com' that does not map to any user.

### ISSUE THREAD

**Issue by Maskedman99** [zulip/zulip-mobile#4067]
![Screenshot_20200425-153722_Zulip (debug)](https://user-images.githubusercontent.com/31368194/80277799-2d26d400-870f-11ea-94d6-6686893bc121.jpg)

Issue happens while trying to chat with Welcome Bot. Happening in the master branch.

@zulipbot claim

**Comment by Maskedman99** [comment]
Looks like https://github.com/zulip/zulip-mobile/commit/531670135f5f2b7ad411873a27679d62c0d059ac is what introduced the bug, ```getUsersByEmail``` was used instead ```getAllUsersByEmail```

**Comment by ray-kraesig** [comment]
Confirmed. Raising priority.
