### ISSUE TITLE
Unable to receive feedback in the app after sending message, setting to away, setting status

### ISSUE THREAD

**Issue by bogmihut8** [zulip/zulip-mobile#4070]
Hello,

I am having some troubles when trying to send/receive messages, update the status or set
 myself to away. It looks like I don't receive the updates in the app, even though the requests seem to be successful (in the web I do see the messages that I send and also the status updates in real time). This happens on both os simulators and on android device (didn't manage to test on an iOS one).

In the chat, the sent message its stuck with the loading animation:
<img width="397" alt="Screenshot 2020-04-25 at 19 26 25" src="https://user-images.githubusercontent.com/7486491/80285166-b5b36d80-872b-11ea-9240-e8feed28030c.png">

After a logout/login, the updates show. If I get a message, the notification pops up, but when clicking it, the chat does not have the new message. 

I thought that it was something general when sending a request from the app, but if I try to change my notifications settings, it works and I do get the update.

Thank you!

**Comment by ray-kraesig** [comment]
It sounds like you're either not receiving or not processing events from the Zulip server, for some reason.

* Do you receive messages and/or status updates from other users?
* If you run in the simulator with remote debugging turned on, do you see any errors in the developer console of the debugger UI window (`http://localhost:8081/debugger-ui/`)?
* In that same developer console you should see a series of Redux events. Are there any events named `EVENT_NEW_MESSAGE`? (These should occur even for messages you send.) If so, what changes are made to the state during them?

**Comment by bogmihut8** [comment]
- I do not receive messages or other updates from the users (outside of the push notifications), only after logout/login
- didn't see any errors in the console
- for the status updates, there is no redux action at all and for the messages I get: MESSAGE_SEND_START, TOGGLE_OUTBOX_SENDING and MESSAGE_SEND_COMPLETE

**Comment by ray-kraesig** [comment]
This is puzzling! But @gnprice has just pointed out to me that this is similar to behavior we've seen at #3567. Do you by any chance have a stray trailing slash on your realm, on your login screen?

**Comment by bogmihut8** [comment]
Well, thanks a lot ray! That was the problem, it might have took me a while to figure it out. 
Everything works now :) Thank you again!

**Comment by gnprice** [comment]
Thanks @bogmihut8 for the report! I think you're set now -- and I've just merged #3819 so in the next release this should be fixed for everyone, too. :slightly_smiling_face:
