### ISSUE TITLE
Use new API for determining which user reacted

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#4072]
See https://github.com/zulip/zulip/pull/14711 and the corresponding issue thread for details, but basically:
* We now have a `user_id` field alongside the inconsistent `user` object in both the events and `GET /messages` code paths.
* The zulipchat.com/api/get-messages documentation now has basic coverage of the `reaction` element format and the changes here, though we don't bother discussing the non-user-id fields of the Legacy `user` dicts, as clients shouldn't be using them anyway.

**Comment by chrisbobbe** [comment]
Interesting; this should make our code nicer too. Looks like the change was released in feature level 2, from the [API changelog](https://zulip.com/api/changelog).
