### ISSUE TITLE
People typeahead has a broken search-by-initials

### ISSUE THREAD

**Issue by rk-for-zulip** [zulip/zulip-mobile#4075]
(Originally from observations at https://github.com/zulip/zulip-mobile/pull/4030#discussion_r416213980.)

The "search by initials" feature – which finds, *e.g.*, `Tim Abbott` with a search for `ta` – makes strange assumptions about the way in which the user's name is written.

In particular, using this feature:
* _Иван Иванов_ will be found with `ив`, but not with `ии`;
* _João da Silva_ will be found with `jãs`, but not with `js`, `jd`, or `jds`;
* _john doe_ will not be found with *any* nonempty search term.

(All such users are still findable with exact-text matches.)

**Comment by gnprice** [comment]
Here's the code in question:
```js
      && user.full_name
        .replace(/(\s|[a-z])/g, '')
        .toLowerCase()
        .startsWith(filter.toLowerCase()),
```

I agree that logic is pretty unreasonable.

The place this code is used is in autocomplete/typeahead for @-mentions.

We'll end up fixing this as part of #3902, sharing that code from the webapp.

In the meantime I think we probably may as well just delete this `filterUserByInitials` function. I doubt it's serving much useful purpose for anyone, so it just adds noise to the results.

**Comment by chrisbobbe** [comment]
> In the meantime I think we probably may as well just delete this `filterUserByInitials` function. I doubt it's serving much useful purpose for anyone, so it just adds noise to the results.

It looks like this was done in ba683877caeafe125ecd995a5875b49cef47b4c3. Closing.
