### ISSUE TITLE
Loading spinner ring is wobbly

### ISSUE THREAD

**Issue by ray-kraesig** [zulip/zulip-mobile#4080]
![Peek 2020-05-01 13-40 trimmed twice](https://user-images.githubusercontent.com/54861490/80841523-74501180-8bb4-11ea-9267-a725142aa94a.gif)

It's tricky to tell, but I don't *think* it's an optical illusion.

**Comment by chrisbobbe** [comment]
You're right — I've noticed this too, it's definitely not an optical illusion. I wasn't sure if it was a style choice or just something wrong with the dimensions.

**Comment by chrisbobbe** [comment]
Marking as "good first issue" with the hope that a fix will be as straightforward as adjusting the dimensions of the image.

**Comment by agrawal-d** [comment]
It's not an illusion - the image resource itself is misaligned.
Bottom:
![image](https://user-images.githubusercontent.com/7714968/81810181-2803ba80-9540-11ea-9deb-0631e37955f9.png)
A gap of 6 squares to the boundary.

Top:
![image](https://user-images.githubusercontent.com/7714968/81810209-34881300-9540-11ea-9cea-609acdbcaaae.png)
A gap of 2 squares. to boundary.

*square!=pixel, it's a dynamic image-editor thing.

**Comment by agrawal-d** [comment]
Wow, @ray-kraesig, you managed to record a perfectly looping GIF! :tada:
