### ISSUE TITLE
Upgrade to a react-native-unimodules without privacy-sensitive dead code

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4091]
See [chat discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/apple.20purpose.20strings/near/869917).

We've successfully worked around this for now by including the boilerplate that the r-n-unimodules authors recommended as of the older version we're on. From our workaround commit c8d0c8df5e:

> These are needed because (a) some of the code in react-native-unimodules apparently refers to these APIs, and (b) for Calendars, Contacts, and Microphone in particular, Apple refuses to allow an app to be uploaded if it has code referring to these APIs and doesn't have a purpose string. That means this [before the workaround] blocks uploading a release for iOS.

But r-n-unimodules upstream has since fixed the problem so that's not needed, and we should upgrade. Ray finds:

> The need to do this [seems to have been removed as of 0.8.0](https://github.com/unimodules/react-native-unimodules/commit/3cac0d72a6cfe6f4ba6f4e874dc6b32c70172a48)

(Now moot because we've completed the RN v0.60 upgrade:
~~There's some uncertainty about just how far we can upgrade while still on RN v0.59. The details we've learned are described by @chrisbobbe [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/apple.20purpose.20strings/near/869947).~~

~~Possibly the cleanest way to do this is to first finish the RN v0.60 upgrade, #3548 -- I believe at this point we've done all the hard parts of that.~~)

**Comment by chrisbobbe** [comment]
Hmm. I'm investigating a reason why we might not be able to do this yet, even on RN v0.60: https://github.com/unimodules/react-native-unimodules/issues/97

**Comment by chrisbobbe** [comment]
There may be a kind of awkward workaround; I've posted some more findings at https://github.com/unimodules/react-native-unimodules/issues/97#issuecomment-637180616.

**Comment by chrisbobbe** [comment]
See discussion [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Podfile.20dependency.20of.20a.20dependency/near/892373).

**Comment by chrisbobbe** [comment]
Blocking this on the RN v0.61 upgrade (#3781); see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Podfile.20dependency.20of.20a.20dependency/near/898933). We're optimistic that this won't take as long as the last one, though! 🙂

**Comment by chrisbobbe** [comment]
Just a note that *just* upgrading Unimodules won't be enough, I think—https://github.com/zulip/zulip-mobile/commit/c8d0c8df5efe808214db78c2a5daad186c9dc91f should be reverted once we're on the new version, IIUC.
