### ISSUE TITLE
Better choose when to build and upload Sentry info

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4100]
This is a followup issue to 7f0d0a78f and #3809.

The way our iOS build scripts decide whether to build and upload debugging info for Sentry is `if [[ $SDKROOT == *\"iPhoneSimulator\"* ]]; then` it skips doing so, else it does it. IOW, if we're building for the iPhone simulator we don't try to upload to Sentry, but if building for a real device (or an iPad simulator, perhaps?) then we do.

This has no false negatives -- if building for the iPhone simulator, it's true that we're not making a release to be published and don't need to send debugging info to Sentry -- and that's the most essential criterion. But it does have false positives.

IIRC the main symptom of this is that when you do development on a physical device, there's an annoying error popup about how uploading to Sentry failed. (It failed because the `sentry.properties` files in the repo don't contain a real Sentry auth token.)

As I wrote at https://github.com/zulip/zulip-mobile/issues/3809#issuecomment-627021750 :
> I think what I want is to make the particular build explicitly request Sentry -- just like we do on Android. For Xcode I think this would look like adding a [build setting](https://help.apple.com/xcode/mac/current/#/dev745c5c974) -- which for these scripts becomes an environment variable -- and then we'd set that on the `xcodebuild` command line in `tools/ios`, like `USE_SENTRY=YES`.

**Comment by chrisbobbe** [comment]
> IIRC the main symptom of this is that when you do development on a physical device, there's an annoying error popup about how uploading to Sentry failed. (It failed because the `sentry.properties` files in the repo don't contain a real Sentry auth token.)

We've had another symptom of this today—`react-native run-ios --device` just doesn't work in the status quo; I get the following at the tail-end of the output of that command:

```
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/chrisbobbe/Library/Developer/Xcode/DerivedData/ZulipMobile-gdifomwwvfiwepckshlwoludvdct/Build/Intermediates.noindex/ZulipMobile.build/Debug-iphoneos/ZulipMobile.build/Script-6FD412E618344A7FB938E4AC.sh
(1 failure)

error Command failed with exit code 1.
```

Noted in [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Crash.20on.20logout/near/1027390).
