### ISSUE TITLE
iOS and Android app won't show uploaded image thumbnails

### ISSUE THREAD

**Issue by ugmac** [zulip/zulip-mobile#4102]
Hi there

We just recently deployed Zulip w/ Docker & Nginx reverse proxy. Everything seems to be working except the uploaded pictures won't display their thumbnails properly on iOS and Android clients. macOS and web clients are unaffected. 

However, the actual picture shows up fine when tapping on them.

I know similar issues have been marked as 'solved' back in 2018 but apparently something is up with our deployment.

> Docker-zulip: 2.1.4-0
> iOS Zulip: Latest from App Store
> Android Zulip: Latest from Play Store.

Any input appreciated.

<img src="https://i.ibb.co/FBYjzpm/IMG-8-FE9-B036-EA81-1.jpg" width="360px">

**Comment by ugmac** [comment]
I found out the issue was because of Cloudflare.

**Comment by maltokyo** [comment]
I have this without cloudflare. Android. Anyone else?

**Comment by gnprice** [comment]
> I have this without cloudflare. Android. Anyone else?

(This report became #4215.)


> I found out the issue was because of Cloudflare.
> 
> Please close

Sure.

@ugmac I would be quite curious if you can say more about what was the issue with Cloudflare! Including how you determined that was the case, and/or what you did to resolve it. That information could be quite helpful for someone else in the future.

**Comment by gnprice** [comment]
Thanks @recklessnl for the report. Let's discuss in the new issue you filed, #5845.

This might be related to whatever was affecting @ugmac above, but it also might not. One interesting difference in symptoms is that in the screenshots above, avatars (aka profile pics) are showing up just fine, whereas they aren't for you.
