### ISSUE TITLE
Upgrade to ESLint 6.8.0

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4120]
EDIT: See https://github.com/zulip/zulip-mobile/issues/4120#issuecomment-632911819, which will make much of these details obsolete — let's go for 6.8.0, instead of 6.1.0, if we can.

-------

Upgrading ESLint to 6.1.0 is included in the [RN v0.59.10 to v0.60.0 upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.0). I've tried doing this before and after the main upgrade commit, and I don't see anything new being flagged, so I think we can treat this as possible to do at any time. As with the Babel-related upgrades there, I haven't been able to trace this to a particular commit in `template/package.json` in the react-native repo. (🤔)

I think the version of `eslint-config-airbnb` we want is ~18.0.0. Both 18.0.0 and 18.0.1 list ESLint under peerDependencies as "^5.16.0 || ^6.1.0". (https://github.com/airbnb/javascript/blob/a204cdf38a3e67a405c191773456d18296a9b37b/packages/eslint-config-airbnb/package.json)

18.1.0 and above have ESLint under peerDependencies as "^5.16.0 || ^6.8.0". (https://github.com/airbnb/javascript/blob/a3355f90c4b52445dbe828fd4e71a7e7d12ef202/packages/eslint-config-airbnb/package.json)

Let's see if we can emulate 58cb26e75 and do the upgrade with a simple script; this is the most easily reproducible way to do it.

One thing that should help simplify things is to remove our direct dependency on `eslint-config-airbnb-base`. We don't ever import it ourselves, and `eslint-config-airbnb` already has it, since it's listed as a `dependency` by that package. It's never been listed there as a `peerDependency`, even as far back as v15.0.2 (https://github.com/airbnb/javascript/blob/c68fa632624f088b4bbe81192a50554b0c6af970/packages/eslint-config-airbnb/package.json), the version we were on when we added `eslint-config-airbnb-base` as a direct dependency, in 984f77157. 984f77157 didn't explain the addition, and the main focus of that commit was elsewhere, so it seems unlikely that it was well-considered.

Running `rm -rf node_modules && yarn` after removing `eslint-config-airbnb-base` gives no errors.

**Comment by chrisbobbe** [comment]
One diff to `package.json` that gets `rm -rf node_modules && yarn` working with no errors at all is this:

```diff
     "babel-eslint": "^10.0.2",
     "babel-plugin-transform-remove-console": "^6.9.4",
     "deep-freeze": "^0.0.1",
-    "eslint": "^5.16.0",
-    "eslint-config-airbnb": "^17.1.1",
-    "eslint-config-airbnb-base": "^13.2.0",
+    "eslint": "^6.1.0",
+    "eslint-config-airbnb": "^18.0.0",
     "eslint-config-prettier": "^6.0.0",
     "eslint-plugin-flowtype": "^3.9.0",
-    "eslint-plugin-import": "^2.18.1",
+    "eslint-plugin-import": "^2.18.2",
     "eslint-plugin-jest": "^22.11.1",
     "eslint-plugin-jsx-a11y": "^6.2.3",
     "eslint-plugin-prettier": "^3.1.0",
-    "eslint-plugin-react": "^7.14.2",
+    "eslint-plugin-react": "^7.14.3",
+    "eslint-plugin-react-hooks": "^1.7.0",
     "eslint-plugin-spellcheck": "0.0.14",
     "flow-bin": "^0.92.0",
     "flow-coverage-report": "^0.6.0",
```

But I got there by inspecting `peerDependencies`, etc., and it would be nicer to have this (or something similar) be the result of a script.

**Comment by chrisbobbe** [comment]
Actually, while on the phone with Greg the other day, it seems to make the most sense to just upgrade to the latest version of ESLint that we can! There are a few things that we use that don't yet support ESLint 7, like `prettier-eslint`, which is fine. But let's shoot for the latest minor version of ESLint 6.

From poking around a bit, one thing we'll need to await, to get guaranteed ESLint 6 support, is a new release of `prettier-eslint`, beyond 10.1.0. The need for that is explained at https://github.com/prettier/prettier-eslint/pull/338#issuecomment-632908721.

**Comment by chrisbobbe** [comment]
This bit from the top, at https://github.com/zulip/zulip-mobile/issues/4120#issue-622056646, still applies:

> One thing that should help simplify things is to remove our direct dependency on `eslint-config-airbnb-base`. We don't ever import it ourselves, and `eslint-config-airbnb` already has it, since it's listed as a `dependency` by that package. It's never been listed there as a `peerDependency`, even as far back as v15.0.2 (https://github.com/airbnb/javascript/blob/c68fa632624f088b4bbe81192a50554b0c6af970/packages/eslint-config-airbnb/package.json), the version we were on when we added `eslint-config-airbnb-base` as a direct dependency, in 984f77157. 984f77157 didn't explain the addition, and the main focus of that commit was elsewhere, so it seems unlikely that it was well-considered.
> 
> Running `rm -rf node_modules && yarn` after removing `eslint-config-airbnb-base` gives no errors.

**Comment by gnprice** [comment]
Reopening after #4223 .
