### ISSUE TITLE
[Android] Downloading from lightbox gives error message, though it works

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4137]
This is sort of a remnant of the symptom of #3124, now that that's been fixed by #4089.

Originally reported at https://github.com/zulip/zulip-mobile/pull/4089#issuecomment-639112733 , on that fix PR just before I merged it.

* Tried downloading an image, for #2115. Steps: Message list > tap an image to get to lightbox > overflow menu > Download image.

  Result: got this error message:
  ![Screenshot_1591303792](https://user-images.githubusercontent.com/28173/83809041-a3055000-a66a-11ea-925b-d97d0e9e5990.png)
  That is a different message from the status quo! So something changed.

  And, notably, it seems like the download actually worked. There was a notification from Download Manager:
  ![image](https://user-images.githubusercontent.com/28173/83809127-cfb96780-a66a-11ea-9326-8dbac13f1a14.png)

  And opening that notification, I get to choose between HTML Viewer and Chrome; and either way, it successfully shows the image. Here's Chrome:
  ![Screenshot_1591304073](https://user-images.githubusercontent.com/28173/83809216-efe92680-a66a-11ea-8263-ee873e6c4e38.png)

  Also the download shows up in my Downloads folder, in the Files app:
  ![Screenshot_1591304197](https://user-images.githubusercontent.com/28173/83809398-39397600-a66b-11ea-997a-b62d9ea23854.png)
  (there's two of them there because I tried the download twice.)

For a lot of users, the error message will make the experience basically equivalent to the download having not worked, even though secretly it did. So this would still be quite good to fix.

One small debugging step (originally at https://github.com/zulip/zulip-mobile/pull/4089#issuecomment-639113880 ):
* I was curious where that error message comes from, with its garbled syntax:
  > Download manager download failed, the file does not downloaded to destination.

  Found it with `grep -r 'downloaded to d'` -- it's in the file `node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java`, so from `rn-fetch-blob`.

**Comment by agrawal-d** [comment]
Hmm, I'm unable to reproduce this issue. Even during development, I never encountered this. :thinking:

**Comment by agrawal-d** [comment]
Further dscussion [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4137.20download.20error.20message.20despite.20working).
