### ISSUE TITLE
Add support for new spoiler syntax 

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#4155]
In https://github.com/zulip/zulip/pull/15281, we're adding support "spoilers", i.e. a block of text that is initially not displayed but if you click on it will appear.  This is useful for a variety of art/fiction conversations where you might want to discuss, well, spoilers, but it can also be used to just improve presentation of large blocks of content that you don't want to overwhelm the rest of what you're saying.

We prioritize making the mobile app correctly display these, as the feature is one where it's pretty bad if an official client just displays the full content by default.

See the `rendered_markdown.js`, `spoilers.js`, and `rendered_markdown.scss` from that PR for the parts that I expect us to need to port into the mobile app codebase.  

(Well, eventually we'll want the local echo stuff, but that'll come automatically through sharing code, and is 100x less important in any case).

I was thinking about whether we could do something reasonable with backwards-compatibility for these, but I think it's pretty hard; we can hide the `spoiler_content` block in the base HTML, but then there's no way to read/see the spoiler part.  So I think our best bet is to try to do a mobile release soon after the feature is there, and imagine that most communities that start using this new feature also have their mobile users using a current app.

**Comment by WesleyAC** [comment]
Any update on this or #4169? It's pretty unfortunate that spoilers have been released on the web for 3 months, but not on mobile yet :(

**Comment by chrisbobbe** [comment]
Thanks for the ping! I believe #4169 is waiting for the web implementation to be finalized, using HTML5 features:

@timabbott [said](https://github.com/zulip/zulip-mobile/pull/4169#issuecomment-647730420):

> Just a quick note -- we're planning to change the syntax for spoilers to use the `<details>` HTML tag.

@timabbott [said](https://github.com/zulip/zulip-mobile/pull/4169#issuecomment-656276614), just before the Zulip Server 3.0 release:

> I suspect that we're not going to change the syntax for this release; unless @andersk is excited about reworking it, overriding the browser interaction design for `<details>` is more focused work than I expect to be available.

I don't find an issue for it in https://github.com/zulip/zulip; Tim, do you know of one?

In any case, it might be fine to land #4169 before that gets done on the server (maybe after another round of review). The mobile app may have to handle both forms eventually anyway (right, @gnprice?), so we might as well start handling the current one.

**Comment by timabbott** [comment]
We decided to skip the plan for changing it to a `<details>` tag, os we should implement the current syntax.  It's unclear if we'll end up switching to details at all at this point, so we should definitely implement the feature as present in the current API.
