### ISSUE TITLE
Support receiving message ids to delete in bulk.

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-mobile#4158]
After https://github.com/zulip/zulip/commit/cda7b2f5393b803f521f45f566b520ebcd9b8d20, client can specify if it supports bulk deletion of messages via passing `bulk_message_deletion = True` in [client_capabilities](https://chat.zulip.org/api/register-queue#arguments) on `/register` request.

See [`do_delete_messages` in action.py on zulip/zulip](https://github.com/zulip/zulip/blob/cda7b2f5393b803f521f45f566b520ebcd9b8d20/zerver/lib/actions.py#L4586) for expected event data formatting in response.

Note that the old event data formatting will be removed in Zulip 2.3 release, so this should be fixed with priority.

**Comment by chrisbobbe** [comment]
Thanks for the heads-up, @amanagr!

IIUC, the `type` of the new bulk-delete event is "delete_message", which is identical to what it is for the now-deprecated event (that only deletes one message): https://github.com/zulip/zulip/blob/cda7b2f5393b803f521f45f566b520ebcd9b8d20/zerver/lib/actions.py#L4596.

This is fine; we can distinguish the new one by its having "message_ids" instead of "message_id".

**Comment by chrisbobbe** [comment]
@gnprice, should we split this into two Redux actions, e.g., the current EVENT_MESSAGE_DELETE action and a new EVENT_MESSAGES_DELETE action, or just modify the existing EVENT_MESSAGE_DELETE action, kind of following the server's choice here?

**Comment by chrisbobbe** [comment]
> Let's follow the structure of the server's event.

Hmm, just so I understand correctly, are you saying we should overwrite our `EVENT_MESSAGE_DELETE` action, reducers, etc., in-place to handle the new (bulk-delete) shape? I agree that we should try to name and arrange things as much as possible to mirror the server API.

But if we want to preserve compatibility with older servers, I think there might have to be some differences, such as having the `EventMessageDeleteAction` type basically be a union of the old shape and the new shape. Does that sound right, and is it a goal to still be able to handle the old shape?

**Comment by timabbott** [comment]
What we do in some server-side testing code is just convert the old shape into the new shape on receipt, and then write all the rest of the code against the new shape.  I think that's an attractive pattern for this (and most other forms of data format migrations, actually).

**Comment by gnprice** [comment]
I agree with Tim's answer completely :slightly_smiling_face:
