### ISSUE TITLE
Size of Avatars inside messages

### ISSUE THREAD

**Issue by apxwn** [zulip/zulip-mobile#4184]
When inserting avatars into messages via `!avatar(id)`, they are currently oversized (or just not scaled down). See screenshot.
Zulip mobile v26.30.153, Android
![Screenshot_20200707_161543_com zulipmobile](https://user-images.githubusercontent.com/15420626/86796284-b8f1a080-c06e-11ea-8b4e-962277d9dfbb.jpg)

**Comment by agrawal-d** [comment]
I just tested this on my device, v26.30.153, Android, and the avatars are tiny for me.

![image](https://user-images.githubusercontent.com/7714968/86919747-58ce2d80-c146-11ea-830a-8caf06106c92.png)

**Comment by apxwn** [comment]
> I just tested this on my device, v26.30.153, Android, and the avatars are tiny for me.

Seems true for the Gravatars, but custom (uploaded) avatars are not scaled correctly. See:

![Screenshot_20200708_173239_com zulipmobile](https://user-images.githubusercontent.com/15420626/86938994-59b09080-c141-11ea-86df-3ee9623ffdf6.jpg)

**Comment by timabbott** [comment]
@apxwn can you talk about how you're using `!avatar()`?  The feature has been removed for the Zulip 3.0 release, having never been documented, inconsistent syntax with the rest of markdown, and no clear use case (we know that it's only been used in a few dozen messages in 2020 in Zulip Cloud).

If there's a compelling use case we could add a new version without those problems.

**Comment by apxwn** [comment]
@timabbott I used it to introduce a bot to the public. That's when I noticed it. The first screenshot here is actually this one use case.

It's not that compelling, of course, though I could think of rendered mentions with a tiny version of the avatar instead of the '@' in front of the name being quite good looking.

**Comment by gnprice** [comment]
Thanks @apxwn for the report! Closing because this feature turns out to have been removed entirely in current Zulip Server releases.
