### ISSUE TITLE
Allow internal links to use stream ID without stream name

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4185]
This is the mobile counterpart to zulip/zulip#15402:

> Apparently we don't support using links of this form to access to a topic:
> 
> https://chat.zulip.org/#narrow/stream/3/topic/send_message.20API
> 
> requiring the stream name (or anything) to be encoded after a dash, like here:
> 
> https://chat.zulip.org/#narrow/stream/3-backend/topic/send_message.20API

The relevant code in our codebase is here, in src/utils/internalLinks.js:
```js
/** Parse the operand of a `stream` operator, returning a stream name. */
const parseStreamOperand = (operand, streamsById): string => {
  // "New" (2018) format: ${stream_id}-${stream_name} .
  const match = /^(\d+)-/.exec(operand);
  if (match) {
    const stream = streamsById.get(parseInt(match[0], 10));
    if (stream) {
      return stream.name;
    }
  }

  // Old format: just stream name.  This case is relevant indefinitely,
  // so that links in old conversations continue to work.
  return decodeHashComponent(operand);
};
```

The webapp now accepts the ID-only form, and we should too. (It still won't *generate* links of that form -- but bots may start doing so.)

**Comment by AdityaYadavalli1** [comment]
Hi, may I take this up?

**Comment by chrisbobbe** [comment]
Sure, thank you, @AdityaYadavalli1! I've just assigned it to you.
