### ISSUE TITLE
Hide user emails in message reaction list according to email_address_visibility setting.

### ISSUE THREAD

**Issue by sahil839** [zulip/zulip-mobile#4188]
Email of users in the message rection list (which is opened by long-press on an existing reaction or by clicking on "See who reacted" from message action sheet) should be hidden when the original email is not visible to the user according to the email_address_visibility settings of the organization.

There is no use of showing the emails generated by user-id (of the form user1888@example.com), as it does not provide any information about the user.

**Comment by gnprice** [comment]
Thanks @sahil839 !

In fact I think the best thing to do is to go farther than that: we should just leave out the email addresses on this screen unconditionally. Even when real email addresses are available, in this context they feel mostly like clutter.

The code that implements this screen is in `src/reactions/MessageReactionList.js`.
