### ISSUE TITLE
Add an account switcher

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#42]
Let users switch between multiple accounts

**Comment by timabbott** [comment]
It'd be awesome if this could support actually being logged into multiple accounts (potentially on different servers), and show the total unread counts for the accounts you're not logged into in the switcher.  I think it may make sense to implement this without that unread counts feature at first, but it's worth thinking about when we design the switcher to ensure there's space to put the unread counts :)

**Comment by borisyankov** [comment]
I am working on it right now (in connection with storing multiple accounts information). 
It will be available both on startup and while logged in.

My todo:

- [ ] On Start, AccountList not empty => login into last logged in account
- [ ] On Logout if AccountList not empty => show list of accounts to login + button 'Add new account'
- [ ] If Login in stored account fails => Set realm to the one in it, but redirect to Email + Password page
- [ ] On Start, if AccountList is empty => go directly to RealmScreen

**Comment by borisyankov** [comment]
@timabbott Not sure if supported, but the 'Teams' in Slack have icons and names associated, which are needed to display a nicer list.

**Comment by timabbott** [comment]
We have names for organizations, available as `realm_name` in the events register response.  We don't have icons organizations at this time.
