### ISSUE TITLE
Handle errors where someone enters zulipchat.com as their zulip server

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#420]
Apparently a super common error when getting started with the mobile app against zulipchat.com is typing in just "zulipchat.com", not e.g. "recurse.zulipchat.com" as the "Server"; the app just gives an "invalid password" error.  

This affects anything with settings.REALMS_HAVE_SUBDOMAINS set on the Zulip server, but that's probably basically just zulipchat.com.

I think we can probably hardcode error handling for now and then make there be a way for the server to suggest that in a future version.

**Comment by borisyankov** [comment]
We can detect if the server url is really a zulip server or just web server. 
The response should differ enough.

**Comment by timabbott** [comment]
Well the zulipchat.com root domain is a Zulip server in many ways -- you just can't login there.  I think the right protocol model is to just add something to the "supported auth backends" response.

**Comment by borisyankov** [comment]
Just tested it.
The server returns 'password' and 'google' as auth backends.

Let's keep the request, but just return an empty array?
Then we can handle this as 'not a server Zulip can connect to'.

**Comment by timabbott** [comment]
I'll add a special key for this specific situation, since it's a bit different from "no valid auth backends".

**Comment by timabbott** [comment]
I just merged and deployed everywhere https://github.com/zulip/zulip/commit/c2bee5a89b6ca1a1e3e273b56808289efdb77f1b, which does the server-side changes needed to do this right.  Now the app will get an JSON error returned when trying to connect to the root domain on a subdomains server such as zulipchat.com.

**Comment by timabbott** [comment]
(Also fixed the fact that invalid subdomains wouldn't return an error)

**Comment by kunall17** [comment]
This can be closed now as the app handles the error's now! 

<img width="200" alt="screen shot 2017-03-25 at 2 26 05 am" src="https://cloud.githubusercontent.com/assets/12700799/24313342/71f7abda-1102-11e7-902e-3d91c5dc58fc.png">

**Comment by timabbott** [comment]
I think we could make a nicer version of the flow where if you enter `zulipchat.com`, and it gets that error, it moves `zulipchat.com` to be the RHS of a text box where you just need to enter the domain (and we could have a "which subdomain on zulipchat.com is your organization"), similar to how Slack's login flow works on mobile.  I think that would be a nice touch.  Maybe worth moving that to a new issue and then closing this since that improvement is probably lower priority than the original bug; if you agree can you take care of that @kunall17?

**Comment by kunall17** [comment]
@timabbott Yeah, that would look nice, will work on it later on, should I create an Issue for it or we should use this one?

**Comment by timabbott** [comment]
Let's create an issue for that, since this issue is somewhat cluttered with irrelevant details.
