### ISSUE TITLE
Use new logo for debug app icon

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4210]
This is a followup to #4200 -- when resolving that issue, we didn't update the icon used for the debug build of the app on Android. (On iOS we don't use a distinct app ID for the debug build and so we don't use a distinct version of the app icon.) It'd be good to fix that. Thanks to @agrawal-d for [reporting](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/new.20logo.20%28debug.20build%29/near/959759) the issue.

To do this:
* The main work involved is to prepare a new version of the debug app icon's design, based on the new logo instead of the old. So this issue is a good one for someone who's excited about spending some time in an image editor (like Inkscape.)
* Here's the current debug icon:
  ![debug-icon](https://user-images.githubusercontent.com/28173/88765370-3dde5000-d12b-11ea-8e8b-3848c6dcf891.png)
  It's the (old) Zulip logo, with a white-on-red banner reading "DEBUG" over it.
* Use a vector format like SVG for the source form of the icon, rather than a raster format like PNG -- this helps enable people to modify it in the future.
* For the Zulip logo, use the zulip/zulip tree's `static/images/zulip-icon-circle.svg`. This is what we use as the source for the main app icon on Android.
* Once a suitable SVG is prepared, the remaining technical step is to edit `tools/generate-logos`, our script which generates all the various formats and sizes we need of different icons based on the Zulip logo, so that it generates this one as well. See in particular the `make_android` function there, which has a TODO comment for this.

  It's probably easiest for me to do this step. If someone does the main work of preparing the icon as an SVG, you can post it to this thread and I'll take it from there. But if you feel like doing some shell-script programming, you can give it a try; follow the examples of the existing code in the script. (The `make_android_icon` and `make_one_android_icon` functions will want to grow another parameter to specify the source set, currently hardcoded to `main`. Then `make_android` will grow another call to `make_android_icon`.)

**Comment by Sumit2399** [comment]
Hey @gnprice I want to start contributing to the organization.I am new to open source contribution, so could you please provide with some pointer on how should I start contributing ?

**Comment by im-adithya** [comment]
I can do this in adobe illustrator!
@zulipbot claim
