### ISSUE TITLE
Android: Animated GIF support broken after RN upgrade

### ISSUE THREAD

**Issue by agrawal-d** [zulip/zulip-mobile#4212]
After the recent RN upgrade, animated GIF support broke again. This should be an easy fix - we only need to upgrade Fresco.

See https://reactnative.dev/docs/0.61/image#gif-and-webp-support-on-android

**Comment by agrawal-d** [comment]
Bumping priority to P1 because this was a working feature that broke after an upgrade.

**Comment by chrisbobbe** [comment]
Makes sense! Just like in a4b446890, it looks like.
