### ISSUE TITLE
App consistently showing me 2-year-old messages

### ISSUE THREAD

**Issue by dannybd** [zulip/zulip-mobile#422]
Launching the iOS app shows me my Zephyr feed from February 20, 2015, at 9:57AM. [This is the message in view](https://zephyr.zulipchat.com/#narrow/near/35413914). Scrolling works, and I can see what my friends and I were talking about on this day as if it were 2 years ago.

Clicking the hamburger button in the upper left hangs for a few seconds, then opens the left drawer. Clicking Home there brings me back to my modern messages, usually scrolled by a few minutes or hours.

**Comment by timabbott** [comment]
@dannybd how many streams are you subscribed to?  If there are tons of them, that's likely to be the cause of the perf problem.

**Comment by dannybd** [comment]
I am subscribed to a bunch of streams, so that would explain that slowness. I can live with that; I just mentioned it because it seemed to be longer when trying to load from 2015's messages than from today's messages.

**Comment by timabbott** [comment]
Yeah, makes sense.  Definitely a bug that it's trying to show you stuff from 2015.

**Comment by borisyankov** [comment]
That is likely related to #416

**Comment by timabbott** [comment]
This is I think caused by having unread messages on 2-year-old muted topics.  I think we need to fix this in the server, not the app.

**Comment by jhurwitz** [comment]
@timabbott cherry-picked and deployed https://github.com/zulip/zulip/pull/4151, and I verified that it resolves the issue for me. Once I write a better test, we can merge that PR for real.
