### ISSUE TITLE
Emoji are not rendered properly in iOS

### ISSUE THREAD

**Issue by ebullient** [zulip/zulip-mobile#4225]
🤦‍♀️ shows as 
![image](https://user-images.githubusercontent.com/808713/90088117-423e6780-dcec-11ea-8a92-28dd3396f4c6.png) in Zulip  v27.154 on iOS (13.6.0)

The selected emoji worked in the previous version of Zulip (old logo), and renders properly on the desktop.

**Comment by gnprice** [comment]
(This issue is zulip/zulip#11767 .)
