### ISSUE TITLE
Upgrade to RN v0.63

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4245]
~~We won't start real work on this until the upgrade to v0.62, https://github.com/zulip/zulip-mobile/issues/3782, is complete.~~ Done!

Released 2020-07-06.

- [Release announcement](https://reactnative.dev/blog/2020/07/06/version-0.63)
- [Changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0632)
- [Upgrade guide](https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.2) (the diff doesn't look huge, and big chunks of it make sense at a glance!!)

Looks like we'll get:

- LogBox, a nice-looking new way to see errors, warnings, and logs
- Pressable, a new API that helps React Native apps' interactions seem more purely native
- Native Colors (PlatformColor, DynamicColorIOS), an API for grabbing system-defined colors from the native platform
- Dropping iOS 9 and Node.js 8 support. Both of these are fine; we're targeting iOS 10.3 (see top of `ios/Podfile`), and we're on Node 12
- Changed iOS LaunchScreen from `xib` to `storyboard` (we did this in #2756)
- Flow v0.122 (see [changelog](https://github.com/facebook/flow/blob/master/Changelog.md#01220))

**Comment by chrisbobbe** [comment]
We'll get at least one Flow bug fixed:

- https://github.com/facebook/flow/issues/8178 (see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M3782.20RN.20v0.2E61.20-.3E.20v0.2E62.20upgrade/near/1006272))

**Comment by chrisbobbe** [comment]
In RN v0.62, we started getting (and suppressing) this new error on calling various methods on a `TextInput` stored in a ref (e.g.,`textInputRef.current.focus()`):

```
Cannot call textInputRef.current.focus because:
 • Either property focus is missing in AbstractComponent [1].
 • Or property focus is missing in object type [2].
```

At first, I thought something was wrong with how we're annotating the variable storing the ref, or that Flow didn't fully understand the `React.createRef` API, which we started using in more places just before the RN v0.62 upgrade. Rather, it seems to be a known issue that wasn't observed on React Native's `master` as of 2020-04-06 [2]. Checking commits around that date, I'm pretty sure we'll have a fix in RN v0.63 (#4245).

The issue is described in point 2 of https://github.com/facebook/react-native/issues/28459#issuecomment-609957836.

**Comment by chrisbobbe** [comment]
With https://github.com/facebook/react-native/commit/232517a5740f5b82cfe8779b3832e9a7a47a8d3d (released in RN v0.63) we can get sub-millisecond resolution when timing things for performance; see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60Immutable.2EMap.60.20performance.20for.20.60state.2Enarrows.60/near/1066838).

**Comment by chrisbobbe** [comment]
Another reason for getting this upgrade has been discovered—using RN v63.2 will [reportedly](https://github.com/zulip/zulip-mobile/issues/4365#issuecomment-753239530) fix #4365! Marking as high priority.

Most of the work has already been done, but the new Flow version has lots of issues with our use of react-navigation, so I've been hoping to finish #4296 before taking up #4245 again.

**Comment by chrisbobbe** [comment]
For cross-reference: #4320 and #4321 are currently open.

**Comment by gnprice** [comment]
And now #4296 is complete too!
