### ISSUE TITLE
Don't generate Jitsi URLs when not the selected provider

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4246]
This is a followup to #3546.

Following #4229, we now have a "video call" button. When a Jitsi server URL is configured, we offer the button, and it inserts a Jitsi link.

There's more in the video-call config the server provides, though, and the intended behavior is more complicated than that.
* There are several other video-chat providers.
* Each can have its own set of details for how to generate a URL.
* But there's also some details that identify *which* provider is the one to be used. This choice is controlled by the realm/org admins. Quoting @chrisbobbe from https://github.com/zulip/zulip-mobile/issues/3546#issuecomment-597260426 :
  > * The choice of video call provider is made by the available and the selected video call providers: `.realm_available_video_chat_providers` and `.realm_video_chat_provider`, respectively, on `page_params`. On chat.zulip.org, Jitsi is available and selected. These params are made available in the `/register` response, so the mobile app has access to them.
  * (I missed this in my subsequent comment there.)
* The intended behavior is that only the selected provider will be used, even if config details exist for other providers.

Details of the webapp's logic are in static/js/compose.js .

I'm not excited about replicating the full logic, particularly for Zoom, where it's fairly messy. But as a minimal fix: when the selected provider isn't Jitsi, we should not offer the icon at all, rather than show it when it'll do the wrong thing.

**Comment by wpj** [comment]
@gnprice just to clarify: is the intention here to disable the video call button when the selected video call provider is unimplemented (all but jitsi) as a short term fix and later implement the other providers?

**Comment by gnprice** [comment]
> @gnprice just to clarify: is the intention here to disable the video call button when the selected video call provider is unimplemented (which is currently all of them except Jitsi) as a short term fix and later implement the other providers?

Yes, exactly. Thanks!
