### ISSUE TITLE
Unable to close image preview dialog on iphone

### ISSUE THREAD

**Issue by CameronAckermanSEL** [zulip/zulip-mobile#4267]
On the iphone, the close button for the image preview renders behind the status bar for ios. As a result, users are unable to close the image preview dialog without killing the mobile app entirely.

**Comment by chrisbobbe** [comment]
Hi, thanks for the report! Which iPhone and which iOS version are you on?

**Comment by CameronAckermanSEL** [comment]
Hey, sorry. I was meaning to go back and add a screen cap and some info and got side tracked 😆  Thank you for the follow up.

I have an iPhone XR, iOS 13.7

**Comment by chrisbobbe** [comment]
I've just sent https://github.com/zulip/zulip-mobile/pull/4268 for this.

**Comment by chrisbobbe** [comment]
Oh—as a workaround until a fix lands, you should be able to swipe right from the extreme left edge of the screen, as a "back" gesture, to get out of the lightbox, so you don't have to quit and relaunch the app. 🙂

**Comment by gnprice** [comment]
(For cross-reference: this was a particularly bad case of the general issue #3066.)
