### ISSUE TITLE
Crash on sending message

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4270]
In a release build of v27.155 -- the release I tagged yesterday but haven't yet rolled out even to beta -- I had the app crash shortly after I sent a message.

See investigation [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/crash.20at.20.2EgetWrappedInstance%28%29/near/1024873); I pulled the uncaught exception from the log, and we seem to have a diagnosis.

**Comment by chrisbobbe** [comment]
Thanks for catching this! I just sent #4271; I'll merge it in ten minutes or so (or at your approval) unless you'd like to change anything.
