### ISSUE TITLE
timestamp formatting is broken

### ISSUE THREAD

**Issue by lebensterben** [zulip/zulip-mobile#4272]
In our discussion it's been reported that the timestamp converion is not working on both iOS and Android client.

Using the example from [here](https://zulipchat.com/help/format-your-message-using-markdown#mention-a-time), it outputs as
>Our next meeting is scheduled for <time:2020-05-28T13:30:00+05:30>

instead of what's expected

> Our next meeting is scheduled for Thu, May 28 2020, 1:00 AM.

**Comment by teor2345** [comment]
I see a similar thing in the iOS app v27.154 on iOS 13.6.1.

It looks like the app is stripping the time tag, but not doing any time zone conversion.

(Note that the app is entirely *capable* of converting times - Zulip message times are in my local time zone. But the time tag is not.)

Can someone label this issue as a Rust community request?
It's causing us some issues planning meeting times.

**Comment by aryanshridhar** [comment]
Hey , this does seems to work fine for me in the debug mode . However , while viewing messages in stock android app (The one downloaded from <a href = 'https://play.google.com/store/apps/details?id=com.zulipmobile&hl=en_US'>play store</a>) the timestamp seems to be broken . (Maybe there hasn't been a new update)

Also I have noticed that the <code>date-picker</code> isn't rendering after typing <code><time</code> in the compose box . Confirm @chrisbobbe

**Comment by lebensterben** [comment]
Is there TestFlight for zulip? I can check whether the formatting works in iOS debug release.

**Comment by gnprice** [comment]
This feature was #4162. We implemented it in #4175, which was first released in v27.155. So that's why at the time of the discussion above, it was present in the main/master branch but not in the current release.

> Also I have noticed that the `date-picker` isn't rendering after typing `<time` in the compose box

This part is #5079, which remains open.
