### ISSUE TITLE
Fix image capture + image upload to work with Android "scoped storage".

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4283]
Android 10 introduces significant changes in how apps access the device's photos, other media of several types, and files in general. Gone, in that future, are the days where your photos and documents live in a single shared storage area which lots and lots of apps have unrestricted access to, like on a desktop OS. The new model is called "scoped storage".

That future is opt-out for apps targeting Android 10, and we've had to take that opt-out -- see https://github.com/zulip/zulip-mobile/issues/3665#issuecomment-713238913 and #4282. But it will be mandatory for apps targeting Android 11, and targeting Android 11 will presumably be mandatory for updates on Google Play in about a year. So our opt-out is only a temporary extension of the deadline; we'll need to adapt to scoped storage

The known issues we currently run into with scoped storage are all within the react-native-image-picker library, which we use both for taking a photo to send via Zulip and picking an existing image on the device to send via Zulip. Both of those features encounter trouble:
* On trying to take a photo (the "camera" icon), an error modal appears before the camera widget even shows up. Detailed report: https://github.com/zulip/zulip-mobile/issues/3665#issuecomment-713199695
* On trying to pick an existing image (the "photo" icon), the symptoms are different; I saw them earlier today but have forgotten exactly how it went wrong. ISTR the picker appeared successfully, but then an error occurred upon actually choosing an image.

The basic problem is that r-n-image-picker tries to handle the photos as if it had unrestricted access to them as files, and with scoped storage it no longer does. Several upstream issues seem related (I think some of them are duplicates): at least
* react-native-image-picker/react-native-image-picker#1269,
* react-native-image-picker/react-native-image-picker#1350,
* react-native-image-picker/react-native-image-picker#1393,
* react-native-image-picker/react-native-image-picker#1443;
* and there's an open PR react-native-image-picker/react-native-image-picker#1439.

The PR is quite simple, and the main reason it isn't already merged seems to be (https://github.com/react-native-image-picker/react-native-image-picker/pull/1439#issuecomment-702876251) that it gives up entirely on putting the captured image, when you use the camera, into the central "Pictures" folder shared with other apps. That is a useful feature. As a Zulip user, I prefer to keep that feature too.

The Android [release notes on this change](https://developer.android.com/about/versions/10/privacy/changes#scoped-storage) point to [a guide doc](https://developer.android.com/training/data-storage/shared/media) on how to handle media files in the new world. I believe these are the key points for us, and for react-native-image-picker:
* We [still need READ_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/shared/media#storage-permission) permission, to read images/etc. added by other apps.
* We [no longer need WRITE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/shared/media#storage-permission) permission, and shouldn't request it on newer Android versions.
* Whenever we're creating an image file ourselves -- either with the camera, or by resizing or rotating:
  * We need to do it in our own storage area; in other words [`storageOptions.privateDirectory`](https://github.com/react-native-image-picker/react-native-image-picker/blob/master/docs/Reference.md#options) should be ignored and effectively treated as true.
  * If we want to make the new image available to other apps (so, if `storageOptions.cameraRoll` is true), we can add it to the MediaStore.Images "media collection". (Or MediaStore.Video, for videos.) Once we do that, other apps that have READ_EXTERNAL_STORAGE permission [will be able to see the image](https://developer.android.com/training/data-storage/shared/media#scoped_storage_enabled). Here's [an example showing how to add it](https://developer.android.com/training/data-storage/shared/media#add-item).
* It might not be possible [to go and read the EXIF data](https://developer.android.com/training/data-storage/shared/media#media-location-permission), which the existing code does in order to perform auto-rotation. But instead, we should be able to get it with a MediaStore query, using the [`MediaStore.MediaColumns.ORIENTATION` column](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#ORIENTATION). That should be more efficient anyway, because it's already there in the database rather than having to parse through the image file. (In Zulip we don't use this feature.)

**Comment by devzsolt** [comment]
@gnprice Could you please check if perhaps a quick dep update to react-native-image-picker 3.x would resolve this issue? It was released these days. Thanks a lot!

**Comment by chrisbobbe** [comment]
It's possible that we should try v3 of react-native-image-picker; v3 was reportedly a ["complete rewrite"](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.0) of the library. Taking that version will have implications for #M4475.

**Comment by gnprice** [comment]
Google has given us a reminder about this in the Play Console, which had me concerned today that they were imposing a tight new deadline to deal with it. I'm pretty sure now that they aren't -- the deadline is later this year, via #4284, same as it's been -- but that caused me to look into the status of this again ([chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/storage.20permissions/near/1167782)).

The new react-native-image-picker 3.x doesn't seem to say anything in the README or the release notes about handling this. But I took a quick look at the implementation, and it [does have code](https://github.com/react-native-image-picker/react-native-image-picker/blob/710aea39e1d1e2352cbce3fc5f4aa348ebcf6c1c/android/src/main/java/com/imagepicker/Utils.java#L72-L83) that looks like it's using the relevant APIs you'd want to use to handle this. So that's at least somewhat promising!

I think the next steps here are then for someone to:
* try upgrading react-native-image-picker to the latest (3.x);
* then try removing `requestLegacyExternalStorage` from our manifest -- i.e. reverting 571ed4b8a;
* and thoroughly test the camera and image-picker flows, and see if things work or find what breaks.
