### ISSUE TITLE
Perform action on a message press

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#429]
We are not having a clear story on the 'act on a message' group of actions.
Let's use this issue to discuss and plan.

We probably don't want to do anything on a simple 'press'. We have 'Reply to message' on a press (implemented by me).
This certainly clashes with the 'long press' action. We should have only 'long press'. Also, maybe we don't want the touching to be visible (using TouchableWithoutFeedback).

Ideally, we want:
* Only long press
* Some other visible way to press on a message (hard to think of a good approach here, but we need it visible for usability)
* ... then show a list of options

**Comment by borisyankov** [comment]
Ok, the 'visible' part now seems obvious. We should have a light down arrow on all messages that will open the same menu that opens on a long press.

Same as Facebook news feed (on the right):

![http://i2.wp.com/www.johnhaydon.com/wp-content/uploads/2015/11/Facebook-Donate-Button-in-Newsfeed.jpg?resize=800%2C671](http://i2.wp.com/www.johnhaydon.com/wp-content/uploads/2015/11/Facebook-Donate-Button-in-Newsfeed.jpg?resize=800%2C671)

**Comment by timabbott** [comment]
That arrow spot in Facebook is where we currently put the message timestamp, which is problematic (unless we want to go with touching the timestamp)

From a practical perspective, all actions other than narrow and reply are pretty rare, so we might want to have optimized ways to do those two things, and just put everything else in a long press (or caret) menu.

**Comment by borisyankov** [comment]
Implmented.
