### ISSUE TITLE
Fix build on Windows, at webview rsync step

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4297]
The build is currently failing on Windows, inside tools/build-webview. The error is from rsync, which apparently is taking the absolute paths we give it to copy from and to (like `/d/zulip-mobile/…`) and interpreting them somehow as remote locations, where the leading `/d/` means to go to a remote host called `d`. [See chat discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/rsync.20windows.20issue/near/1043864), including diagnosis and workaround.

Here's that workaround as a branch:
https://github.com/zulip/zulip-mobile/compare/master...gnprice:dev-rsync-relative
The solution is to use relative paths. We already take care to *pass* relative paths to this script -- see its caller in `android/` -- but we absolutize them inside the script. So just the script itself needs to be edited to not do that.

That workaround branch does that, but has some collateral damage. To solve this issue, we'll want to make similar changes to those in the branch, but:
* There are some checks on the paths, where we use absolute paths. The branch just deletes those checks, but let's keep them. To do that, we'll want to make absolute paths, but just keep them in their own separate variables.
* The branch assumes the current directory when running the script is the root of the zulip-mobile repo. That happens to be true when it's invoked from our build process, but the script should avoid depending on that.
  * The script should `cd` to that root directory, at the same point where the current code determines it and stores it in the variable `$root`.
  * But: if the current directory starts out somewhere else, the `dest` path argument passed to the script should be interpreted according to the original current directory. That's normal behavior for any command-line interface.

**Comment by tusharojha** [comment]
I am also facing the same issue. Also, I am struggling with installing rsync, please help.

**Comment by gnprice** [comment]
Hi @tusharojha ! Glad to help out with the setup steps. Let's use [the chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Unable.20to.20build.20and.20run.20android.20app/near/1075786) for that.

**Comment by palakyadav1807** [comment]
Is this issue resolved? I am facing same problem , what steps should I follow?

**Comment by gnprice** [comment]
@palakyadav1807 This issue is now fixed! If you update to master and just use our normal setup instructions, it should now work.

If you find you're still running into any trouble, please go ahead and ask on #mobile on chat.zulip.org, and we'll debug.
