### ISSUE TITLE
Use native navigation libary

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#43]
https://github.com/wix/react-native-navigation

**Comment by borisyankov** [comment]
I did implement the Start screen logic, using the new NavigationExperimental that is replacing NavigationIOS...

Do you think we should use that instead?

**Comment by borisyankov** [comment]
I will evaluate these three:

- NaviationExperimental
- https://github.com/aksonov/react-native-router-flux
- https://github.com/wix/react-native-navigation

NavigationExperimental is not native, but is performant so could be a good choice.

**Comment by borisyankov** [comment]
Evaluation:
NaviationExperimental looks, works and performs well. The argument for react-native-navigation is not strong. 
Proceeding with NavigationExperimental.

**Comment by neerajwahi** [comment]
👍 

We can always reevaluate later if it turns out to be an issue

**Comment by borisyankov** [comment]
@neerajwahi I am creating another issue, so I can explain it more cleanly. You can close this.
