### ISSUE TITLE
Status icons on avatars lack contrast

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4306]
This is a followup I originally posted at https://github.com/zulip/zulip-mobile/pull/3417#issuecomment-474641128 just before merging that PR.

The "unavailable" icon lacks contrast on top of an avatar:
  ![image](https://user-images.githubusercontent.com/28173/54651283-66523680-4a6f-11e9-915d-336ccbc6deb3.png)

* Possible fix: give it a partly-opaque background? Or even fully opaque.

* Something similar would probably benefit the other icons too -- if someone's avatar happens to have green or similar bright colors in the lower right, even the "active" color might not stand out. Perhaps a contrasting (white?) border would be good.

I just did a quick test and the behavior is the same as it was then, so this is still live.

**Comment by abhi0504** [comment]
hey greg , 
I Think we can do two things or either of one of below for this issue

1. We can make our back ground partially-opaque for every status , 

2. Or , we can make our icon circular by increasing border radius and then put that status symbol half on avatar and half outside 
for eg. 
![moss_status (1)](https://user-images.githubusercontent.com/56453541/98977056-29895c00-253e-11eb-93dc-8d2c2a654efc.png)

**Comment by gnprice** [comment]
Hi @abhi0504 !

Zulip's avatars are meant to be displayed as rounded squares, not circles. And quoting Tim at #205:
> This is based on a lot of consideration -- circular avatars are problematic because many images that we'd like to use in avatars (e.g. bot logos) don't actually look good in circular form, whereas just about anything looks good in a rounded square.

I think an opaque or partly-opaque background around each status icon, and perhaps an opaque border, would be a good solution. Your example image demonstrates that (in addition to the avatar shape) and I think it works well.

**Comment by abhi0504** [comment]
@gnprice  thanks for your help , ok so we are keeping that rounded squares with partly-opaque background and perhaps an opaque border so should I started working this issue or any other suggestions

**Comment by gnprice** [comment]
@abhi0504 You've already claimed #4307, so let's start with that, and then you can take this one up next.

**Comment by abhi0504** [comment]
@gnprice I have also done some changes and submitted a PR for this issue as we have discussed 
## Before 

![](https://user-images.githubusercontent.com/28173/54651283-66523680-4a6f-11e9-915d-336ccbc6deb3.png)

## After 
![Android Emulator - Pixel_3_API_29_5554 15-11-2020 00_43_23 (2)](https://user-images.githubusercontent.com/56453541/99155228-1a401500-26dc-11eb-9015-51ab5006ab4f.png)

**Comment by abhi0504** [comment]
@gnprice can you review [this](https://github.com/zulip/zulip-mobile/pull/4324) PR for the above issue
