### ISSUE TITLE
Status dot on user-profile screen slightly misaligned

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4307]
This is a followup I originally posted at https://github.com/zulip/zulip-mobile/pull/3417#issuecomment-474641128 just before merging that PR.

The status dot isn't aligned well on the full-screen profile. Here's an updated screenshot:
![image](https://user-images.githubusercontent.com/28173/98896245-616ca280-245d-11eb-9105-7e044b214f9f.png)

In the original comment, the status dot was left of the email address rather than right of the name. But it still doesn't look quite right -- I think it's slightly too high. Alternatively, perhaps there's a better place on that screen to put it.

**Comment by abhi0504** [comment]
@gnprice I want to work on this issue , 
I will slightly lower status symbol or If you want to place it anywhere else on screen we can also do that .
so what would you say.

**Comment by gnprice** [comment]
@abhi0504 Sure. Let's do two things:
* Put it to the left of the name -- that makes it match the webapp's right sidebar.
* Adjust the alignment so it looks correctly aligned.

In your PR, please include screenshots with all four of the possible status states. (The easiest way to do this might be to make some temporary hacks in `PresenceStatusIndicator.js` to control which one is shown, rather than to actually get a user into each state.) That'll help judge how the alignment looks visually for each of the possible icons.

**Comment by abhi0504** [comment]
@gnprice I have placed the status symbol to the left of the name and also adjusted the alignment (slightly lowers the status symbol). Attaching some screen shots : 
### Before : 
![Android Emulator - Pixel_3_API_29_5554 12-11-2020 20_12_49 (1)](https://user-images.githubusercontent.com/56453541/99032639-16a77380-25a0-11eb-8e98-b965816695b8.png)             ![Android Emulator - Pixel_3_API_29_5554 12-11-2020 20_16_08](https://user-images.githubusercontent.com/56453541/99032647-1b6c2780-25a0-11eb-8f64-13fdbef75c41.png)
### After : 
![Android Emulator - Pixel_3_API_29_5554 13-11-2020 10_55_30](https://user-images.githubusercontent.com/56453541/99032661-22933580-25a0-11eb-8ff6-25e7832b2296.png)               ![Android Emulator - Pixel_3_API_29_5554 13-11-2020 10_55_51](https://user-images.githubusercontent.com/56453541/99032664-2626bc80-25a0-11eb-96cc-eddb4e188fdd.png)

**Comment by abhi0504** [comment]
@gnprice can you review this and suggest some changes or is it fine
