### ISSUE TITLE
Open links in default browser, not embedded webview

### ISSUE THREAD

**Issue by jryans** [zulip/zulip-mobile#4323]
We should change tapping on links to open them in the default browser, not the webview. (description edited by @WesleyAC, original below)

---

In many iOS apps these days, tapping links will open them by default in your preferred browser (recently added as option in iOS 14).

Zulip on iOS doesn’t appear to offer this, and only has an embedded webview, which adds extra steps, since each link needs to be shared over to the actual browser.

Please add some route to open links in the user’s chosen default browser, preferably by just tapping the link.

**Comment by shaurya2612** [comment]
I am working in this

**Comment by shaurya2612** [comment]
I am working on this !

**Comment by gnprice** [comment]
Thanks @jryans for the report!

It looks like we actually switched from opening in Safari to an embedded Safari view, a few years ago, in #1721. There's no record of what the motivation for that was, though, unfortunately.

I'm not personally a real frequent iOS user, so I don't have a strong view myself on the best UX here. From a quick web search, I found this article fairly persuasive that an embedded Safari view might have been best a few years ago but opening in a full browser is the best choice now:
https://pspdfkit.com/blog/2019/open-links-in-safari-not-safari-view-controller/
So I agree, we should make this change.

**Comment by WesleyAC** [comment]
I think we should do this for both iOS and Android, see #4562 for the reasons there. I'm going to edit this issue to be for both, rather than iOS specific.

**Comment by gnprice** [comment]
For future reference: We ended up making this change by default on iOS, but leaving the in-app browser the default on Android, and offering a setting in either case. Rationale in [chat discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/in-app.20browser/near/1143087).
