### ISSUE TITLE
@stream doesn't appear in the autocomplete list

### ISSUE THREAD

**Issue by schrej** [zulip/zulip-mobile#4325]
On the web app, `@stream` is autocompleted, but on the mobile app it isn't.
Since `@**stream**` is hard to type on mobile keyboards, it should be included in the auto-completion there as well.

**Comment by abhi0504** [comment]
@schrej , Yeah we can Add this autocompletion by which `@stream` is autocompleted to `@**stream**` via 
`zulip-mobile\src\autocomplete\TopicAutocomplete.js` @gnprice @chrisbobbe plz comment

**Comment by TarunTomar122** [comment]
Hi @schrej. I would like to work on this issue if it's fine? Also can you please elaborate on what's the problem?

**Comment by schrej** [comment]
Entirely fine with me, but I only reported it, not part of the project ;)

When you type `@every`, `@everyone` appears in the auto-complete dropdown, and so does `@all` (but you can't click it, maybe a second bug worth of another issue @abhi0504 ?.
I assume `@everyone` and `@all` are also supposed to be autocompleted to `@**everyone**` and `@**all**`.

`@stream` doesn't appear in that auto-completion list, and also doesn't get autocompleted to `@**stream**`. Therefore you'd have to type the asterisks yourself if you want to mention an entire stream, which is very tedious on mobile (as well as desktop) keyboards.

**Comment by abhi0504** [comment]
@schrej yes , `@all`and `@everyone` is appearing in the dropdown menu but we are not able to click on It , reporting it as another issue .

**Comment by schrej** [comment]
@abhi0504 Doesn't work for me, iOS 14.2 and Zulip v27.156

**Comment by birchamp** [comment]
This continues to be a problem on the Android app

**Comment by chrisbobbe** [comment]
Thanks for the bump, @birchamp! PR #5508 would fix this. I'm working on a new revision for that now, following Greg's latest code review.
