### ISSUE TITLE
Identify narrows with user IDs and stream IDs, not emails and names

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4333]
This is a major component of both #3764 and #3918. Currently we describe PM narrows (both 1:1 and group) by emails of the people involved, and stream and topic narrows by the stream name (and in the latter case the topic.) We should instead use the numeric user IDs and stream IDs, for all the reasons described in #3764 and #3918.

This has been a stubborn issue to resolve because there are *so many* places in the code that we create and consume `Narrow` objects, and so many different places the data for them comes from, and all of those need to migrate. I've had several draft branches for doing this, starting with some in 2020-02. The work I'm currently doing on #4035, of which #4332 just now is the latest, will bring it closer by centralizing the fiddly bits in the PM case, and in particular making it so that we always have user IDs on hand at the points where we construct PM narrows.

One symptom of this issue is described at #3230. (Though probably a rare one; found internally, and has no user reports.)

**Comment by Ayushdubey86** [comment]
I would like to work on this!

**Comment by gnprice** [comment]
Hi @Ayushdubey86 ! This issue is a pretty complex one, and I'm already working on it. To find good issues to take on, take a look at our ["help wanted" label](https://github.com/zulip/zulip-mobile/labels/help%20wanted). See also our [contribution guidelines](https://github.com/zulip/zulip-mobile/blob/master/CONTRIBUTING.md), and say hello [in #mobile on chat.zulip.org](https://github.com/zulip/zulip-mobile/#discussion).

**Comment by timabbott** [comment]
Just adding a note that we'll want to open a zulip/zulip issue for doing the cleanup discussed here:
https://chat.zulip.org/#narrow/stream/3-backend/topic/stream.20administrators/near/1124311 (noting we need to wait 6 months before doing it) once we're no longer using the `name` field in subscription/update events.

**Comment by chrisbobbe** [comment]
Thanks, Tim!

> once we're no longer using the `name` field in subscription/update events.

I was mistaken about this; we actually don't use it, so the `name` field can be removed right away, as Greg points out in the [CZO discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/stream.20administrators/near/1126755).
