### ISSUE TITLE
Narrow lands far in the past, every first time, on iOS

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4357]
This is an instance of symptoms like #3457, with a specific repro recipe. It can't explain some of the previous reports on #3457, so it doesn't replace that one. It's a pretty annoying bug that will come up frequently for anyone on iOS, so it's a priority to diagnose and fix.

To reproduce:
* Launch the app, on iOS.
* Navigate to "streams", and then to some particular stream that has a long history. (I'm using one that has no unreads.)
* Observe that the messages being shown are from months ago, and several screenfuls up from the end. That's the bug.

Then for further color:
* Navigate back out to "streams", and then back in to that stream.
* Observe that the messages being shown are from very near the bottom.
  * For me it's actually not quite at the bottom -- in fact it looks like I'm getting the bottom of the viewport right at the top of the very last message. Or in other words, it's showing the last messages *except* the very last one, which I have to scroll down to see. That seems likely to be its own separate bug. In any case it's a somewhat milder symptom than the "many screenfuls back" symptom we're focusing on in this discussion.
* To repeat the repro: close the app entirely, then launch it again.

My repros just now were on an iPhone XR, running iOS 14.2, and v27.157 of the app.

By contrast, when I try this on Android -- specifically on a Pixel 4 running Android 11, and again v27.157 of the app -- the issue doesn't reproduce. I get shown the very latest messages, just as I should, every time.

The behavior that's going wrong here is in the scroll position of the message list, so inside the webview we use for the message list. We have some logic in the JS inside that webview to try to scroll the right part of the message list into view. Because this is iOS-specific, the issue is probably in some way that Safari's behavior differs from Chrome, and how our scrolling logic interacts with that.

The next step for debugging this will probably involve connecting the Safari developer tools to the webview:
https://github.com/zulip/zulip-mobile/blob/master/docs/howto/debugging.md#debug-webview-on-ios
and using those to study what's happening.

Because the bug happens just as we open the webview, this might not be enough on its own -- by the time you connect the dev tools, it'll be after the bug happened. You can get further information by editing the webview JS code (in `js.js`) to report information with e.g. `console.log`, or making other changes and seeing what happens.

**Comment by gnprice** [comment]
A few more details from my repro observations, in case they're helpful for further debugging:
* From the point in the past where the message list first shows, it's 5 screenfuls (exactly, to within the precision of my measuring by scrolling a screenful at a time) to get down to the bottom. The messages are from about 8 months ago.
* When I touch the screen and start scrolling slightly, a scroll indicator appears (as usual). It looks like it's about 75-80% of the way through.
* In addition to landing in the wrong place, there's a bit of jitter, or flicker, before it lands there.
  * On the first entry (the one where it winds up far in the past), it starts out just slightly higher -- about the height of one single-line message -- and then after a fraction of a second the messages jump upward a bit / our scroll position jumps downward.
  * On subsequent entry (where it winds up just slightly scrolled into the past, much less than a screenful), it starts out actually showing the very end, just as it should. Then after a fraction of a second, we jump a bit upward so that the latest message is out of sight.
  * (Note that these jumps are in opposite directions.)
* The behavior on subsequent entry actually varies slightly from time to time. AFAICT it's random each time which of these behaviors happens:
  * We start out showing the very end, but then jump up to just above the very latest message (the behavior I described above.)
  * We start out showing the very end, but then jump up about 2-3x that far (still less than half a screenful). It seems like there may be a handful of discrete amounts that it jumps up by.
  * Once I even spotted it not jumping at all (or maybe it jumped and jumped back?), and landing at the very end, just where we intend it to be.

**Comment by gnprice** [comment]
Also reproduced just now on an iPhone 7 running iOS 12.4.1. So a smaller screen; some other hardware differences, like no "safe area" or screen cutouts; and an older OS.

All the substantive details are the same. Details that differ:
* Visiting the same stream, it lands a bit further in the past, by a fraction of a screenful: the iPhone 7 shows about 1 more message at the top, and 7 fewer at the bottom. (All the messages in this section of history here are one-line messages, all from the same sender to the same topic.) Then it's about 6 screenfuls from there to the bottom.
* On subsequent entry, the iPhone 7 seems to more often jump up a larger fraction of a screenful, and to an earlier point in the history. (Still just a handful of messages representing less than a screenful.)
  * Some times, the jump is exactly one message, just as it is on the iPhone XR.
  * Other times, it's something like 4-6x that far.
  * I don't think I've yet seen it jump by an amount in between, like the iPhone XR routinely does.

**Comment by titanous** [comment]
@zulipbot claim
