### ISSUE TITLE
No margin for main bottom nav on iPhone 12

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4369]
@titanous reports on #4365:
> […] Additionally, the margin for the "home swipe bar" appears to be missing.
> 
> ![Simulator Screen Shot - iPhone 12 - 2020-12-29 at 21 29 32](https://user-images.githubusercontent.com/13026/103326172-17e01300-4a1d-11eb-8c8e-094d0e9d14e7.png)

and adds at https://github.com/zulip/zulip-mobile/issues/4365#issuecomment-752779450 :

> It only reproduces in the simulator for the 12/12 Pro/12 Pro Max and on my physical 12. The simulator 12 mini, and various models of the 11 have the correct margin. This is another case where the App Store version has the correct margin on my physical 12, but all local builds are broken.

The symptom is reminiscent of #3066. It seems like there's a new behavior with the layout of the iPhone 12 screen (but not the 12 mini), which we're not handling properly. 

As for why local builds differ from the version in the App Store -- those local builds were with Xcode 12.3, whereas the latest App Store version was built with Xcode 11.7 (or possibly earlier). For the main issue of #4365, @titanous suggests
> I wonder if perhaps the App Store version was built against an older SDK version or with an older version of Xcode and so there's a compatibility layer that's being inserted?

and that seems quite plausible here too -- i.e. perhaps as long as the app was built with Xcode 11, the iPhone 12 doesn't expect it to know about the iPhone 12's new behavior, and treats it with a compatibility mode.

**Comment by Gautam-Arora24** [comment]
@gnprice Can I work on this issue?

**Comment by chrisbobbe** [comment]
This was fixed in 12284502bb68df733ed1f384bd5da5944b56e7fe; see my comment at https://github.com/zulip/zulip-mobile/commit/12284502bb68df733ed1f384bd5da5944b56e7fe#commitcomment-45962457.

**Comment by Gautam-Arora24** [comment]
No worries @chrisbobbe Will start working on another issue 👍
