### ISSUE TITLE
Links to previous messages doesn't work on latest Android client

### ISSUE THREAD

**Issue by panomitrius** [zulip/zulip-mobile#4377]
Clicking on a link to a previous message, in the form of `https://a-private-zulip-server.eu/#narrow/stream/6-AStream/topic/ATopic/near/294` doesn't work on the Android client, but works fine from a desktop web browser.

**Comment by chrisbobbe** [comment]
Thanks for the report, @panomitrius!

The codepath for handling those links properly goes through an area that was cleaned up quite recently, in #4350, and I expect that will probably fix this issue.

That PR was merged, but it hasn't been released yet; I hope we'll at least have a beta with it out by the end of this week. 🙂

Alternatively, if you're already set up to [build and run zulip-mobile](https://github.com/zulip/zulip-mobile/blob/master/docs/howto/build-run.md) locally (or if you'd like to; feel free to chat about any issues you run into, on chat.zulip.org), you can check out the latest `master` branch and try it there.

**Comment by panomitrius** [comment]
Alright, cool! Sounds good @chrisbobbe :) I might check the chat out later.

**Comment by chrisbobbe** [comment]
Ah, I should have asked earlier—I'm curious what the symptoms are/were, more specifically. What happened when you tried to follow a link to a message; did it kick you out of the app and put you in a browser and load the web app, or did nothing happen at all, or did something else happen? 🙂

The fix I mentioned above, #4350, was released in v27.158, so it'd be helpful to know if you see something different happening on that version or later.

@WesleyAC mentioned [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/message.20links/near/1171186) that this might actually be #3604, and that seems quite plausible. The symptom there would be that the app loads the narrow that the message is in, but doesn't highlight the message or even make sure that it's visible on the screen.

**Comment by gnprice** [comment]
I think this is in fact a report of #3604. In particular, the reference to "a previous message" sounds like it's about an earlier message in the same conversation, perhaps as linked to by the quote-and-reply "said" link.
