### ISSUE TITLE
Crash on trying to log into a second account

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4388]
Repro:
* Be logged into an account, and in the main app UI.
* Profile > Switch account > Add new account.
* Type an org URL, and hit enter.
* The app crashes.

Here's an alternative repro that doesn't quite as much show how easy this bug is to hit, but is easier to reproduce repeatedly in a loop while changing things:
* Have at least two accounts in the list: one logged in, and one logged out. (E.g., log out of one account, if you already have two logged in.)
* Choose the logged-in account, to get the main app UI.
* Profile > Switch account.
* Choose the logged-out account.
* The app crashes.
* (On next startup, you'll be at the pick-account screen, and can choose the logged-in account to repeat.)

I did a `git bisect` (using that handy second repro), and the bug begins at commit c59e286ab. That indeed introduces a `getAuth` where we didn't have one before:
```diff
+  const auth = useSelector((state: GlobalState) => getAuth(state));
```

That should be perfectly fine to do. It's in `UserAvatar`, which is part of the app's normal UI. If we're trying to render this component when we don't have our normal set of data, that's a bug. So we should fix that bug.

Because of the severity of this issue, and particularly because I'd like to get a release out soon because it's been a while, I may try fixing this first with a workaround: e.g., if we're not logged in, return normally from `UserAvatar` but just don't render anything.

**Comment by chrisbobbe** [comment]
Thanks for the report, and for working on a fix (I see you've self-assigned this); let me know if I can help, e.g., by clarifying anything from my commits.

**Comment by gnprice** [comment]
Thanks! I've just sent #4389 with a fix -- take a look.

I suspect that resolving the underlying issue will ultimately lie in the subtleties of how we use the navigation framework we're using. So that part may make most sense to approach after #4296 / #4300 is complete and we've upgraded to react-navigation v5.
