### ISSUE TITLE
Move stream list to modal window

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#44]
The stream list is currently contained in a sliding drawer (which slides in from the left when the user swipes or clicks a button in the navigation bar).

We could move this feature to a modal window that expands when the user clicks the stream title (or a little arrow next to it). Doing so leaves the left navigation button and left swipe available to be used for a 'back' action.

**Comment by borisyankov** [comment]
We should hold off on that before some discussion and maybe design mockups?
I have some suggestions, based off of other popular mobile apps (Facebook Messenger, Skype, Slack)
I totally agree about the direction though. Drawers are not ideal, are not that typical on iOS, and are preferably just one on the left etc. etc.

**Comment by timabbott** [comment]
Yeah, this seems worth discussing...

**Comment by neerajwahi** [comment]
Sure, we should definitely discuss. @borisyankov would love to hear your suggestions.

I already have a branch that implements this actually that I quickly wrote up a few days ago. I'll share that as a pull request so you can take a look at the interactions.

**Comment by borisyankov** [comment]
There are other tasks that track this in more details. Closing this issue.
