### ISSUE TITLE
Execution failed for task ':react-native-photo-view:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by santhoshivan23** [zulip/zulip-mobile#4435]
I'm trying to set up the development environment. The build failed with an exception.

`/Users/santhoshivan/zulip-mobile/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ImageEvent.java:12: error: package android.support.annotation does not exist
import android.support.annotation.IntDef;
                                 ^
/Users/santhoshivan/zulip-mobile/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ImageEvent.java:21: error: cannot find symbol
  @IntDef({ON_ERROR, ON_LOAD, ON_LOAD_END, ON_LOAD_START, ON_TAP, ON_VIEW_TAP, ON_SCALE})
   ^
  symbol:   class IntDef
  location: class ImageEvent
/Users/santhoshivan/zulip-mobile/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/PhotoView.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/santhoshivan/zulip-mobile/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/PhotoView.java:60: error: cannot find symbol
                          @NonNull ResourceDrawableIdHelper resourceDrawableIdHelper) {
                           ^
  symbol:   class NonNull
  location: class PhotoView
/Users/santhoshivan/zulip-mobile/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/PhotoView.java:143: error: cannot find symbol
    public void maybeUpdateView(@NonNull PipelineDraweeControllerBuilder builder) {
                                 ^
  symbol:   class NonNull
  location: class PhotoView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-photo-view:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
`

I'm running this on  MacOS

**Comment by chrisbobbe** [comment]
Thanks for the report! First, please make sure your working tree is clean; the output of `git status` should include `nothing to commit, working tree clean`.

Then, could you please try running the following commands:

1. `cd android` (to get into the `android` directory)
2. `rm -rf .gradle` (to delete the `.gradle` directory)
3. `./gradlew clean`
4. `cd ..` (to get back to the project root)
5. `yarn`

Then, try building again.

If that doesn't work, let's further debug on chat.zulip.org, in the [#mobile stream](https://chat.zulip.org/#narrow/stream/48-mobile).

If it does work, please let me know too. 🙂

**Comment by santhoshivan23** [comment]
@chrisbobbe Thanks! That worked!
