### ISSUE TITLE
HTMLTimeElement is not defined, says a WebView error

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4451]
Looking in Sentry at our WebView errors (while investigating #4449), I'm seeing error reports that look like [this one](https://sentry.io/organizations/zulip/discover/zulip-mobile:e9525e624b6a4774889bf8e3efeebfb8/):

> Uncaught ReferenceError: HTMLTimeElement is not defined
> source: file:///android_asset/webview/index.html
> column: 53
> line: 276

The impact of an error like that is:
* A red banner shows at the top of the message list, saying "Oh no! Something went wrong. Try again?". This means the user knows that they're seeing a bug.
* Whatever our code inside the webview was trying to do at the time got interrupted. This can mean that arbitrary other functionality in the webview breaks.
  * For this particular error, I think the main effect is likely to be that (a) scroll behavior will be wrong, because the last part of `handleInboundEventContent` doesn't get to run; (b) if visiting a conversation that's so short it fits on one screen, the messages won't get marked as read. Basically one annoying symptom for long conversations, and a different annoying symptom for short ones :slightly_smiling_face:

We don't currently have a great way to sort through the different WebView errors -- they all get aggregated together -- but when I look through a [firehose](https://sentry.io/organizations/zulip/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=191284&query=message%3A%22WebView+error%22&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) of the most recent of them and just sample a few to look at individually, the ones I find are
* some instances of #4449 which appear to be from myself;
* and some of these, from at least a few different people (I see three different OS versions.)

So this is at least one of the most frequent WebView errors we have, likely the majority of them. And WebView errors in aggregate are one of our handful of [most frequent and widespread types of errors](https://sentry.io/organizations/zulip/issues/?project=191284&query=is%3Aunresolved+level%3Aerror&sort=user).

From the error message, it's presumably thrown here:
```js
const rewriteTime = (element: Element | Document) => {
  // Find the time elements to act on.
  const timeElements = [].concat(
    element instanceof HTMLTimeElement ? [element] : [],
    Array.from(element.getElementsByTagName('time')),
  );
```
(We have one other reference too, later in that function.)

Seems like the browser doesn't have `HTMLTimeElement`.

Not sure what browser versions this is happening on. The handful of these events I'm looking at are on Android versions from 6.0 to 7.1.2. According to our notes in docs/architecture/platform-versions.md, Android 7 Nougat shipped with Chrome 51, so the device with Android 7.1.2 must have at least that new of a Chrome. (We should report browser versions in WebView error events; ~~I'll file an issue for that.~~ filed as #4452.) The great majority of Android devices have a current version of Chrome, no matter how old they started with, but some don't.

Our support levels at the top of `js.js` say we currently accept graceful degradation for older than Chrome 58 (which shipped with Android 8 Oreo.) So it's OK if this particular feature (the Zulip ["mention a time" feature](https://zulip.com/help/format-your-message-using-markdown#mention-a-time)) doesn't work on those browsers; but we need to ensure core functionality keeps working, which we support back to Chrome 44 which shipped with Android 6.

To fix this issue, it will probably suffice to check if HTMLTimeElement exists, and have `rewriteTime` just return without doing anything if it does. Before merging that solution, the work required in order to verify it is:
* Reproduce the error. The easiest way to do this is probably to run the app in an Android 6 Marshmallow emulator. (Stock emulator images keep the original Chrome version that their version of Android shipped with.)
* Verify that on Chrome 58, the "mention a time" feature works properly. The easiest way to do this is probably to run the app in an Android 8 Oreo emulator. Double-check that the Chrome version you're getting is indeed Chrome 58.

**Comment by abhi0504** [comment]
@gnprice I want to work on this issue could you assign it to me?
