### ISSUE TITLE
webview errors: Report browser version

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4452]
At #4451, which is about an error reported by our code inside the WebView, I wrote:

> Not sure what browser versions this is happening on. [... then some approximate information to make a rough guess ...] (We should report browser versions in WebView error events; I'll file an issue for that.)

This is that issue.

The relevant code is first in `js.js` at this call:
```js
  sendMessage({
    type: 'error',
    details: {
      message,
      source,
      line,
      column,
      error,
    },
  });
```
where we'll want to include one more property in that "details" object, for the browser version. This might be just the user-agent string, or possibly there's some better-structured information we can get our hands on. Because this is an Android or iOS webview, the only browsers we're concerned with here are Chrome and Safari.

Then that information gets passed up through `handleOutboundEvents.js`, and a `logging.error` call there sends it to Sentry.

**Comment by Gautam-Arora24** [comment]
@gnprice I would like to work on this issue
