### ISSUE TITLE
"t.get is not a function" on state.narrows at startup

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4458]
Looking at our [Sentry errors that are new in v27.158](https://sentry.io/organizations/zulip/issues/?project=191284&query=is%3Aunresolved+firstRelease%3Acom.zulipmobile%4027.158%2B158&sort=user&statsPeriod=30d), the current beta, [this one](https://sentry.io/organizations/zulip/issues/2138980382/events/oldest/?project=191284&query=is%3Aunresolved+firstRelease%3Acom.zulipmobile%4027.158%2B158&sort=user) has affected a substantial number of our beta users:
> t.get is not a function. (In 't.get(v.ALL_PRIVATE_NARROW_STR)', 't.get' is undefined)

where the stack is
```js
    const pmIds = narrows.get(ALL_PRIVATE_NARROW_STR) || NULL_ARRAY;
```
in `getPrivateMessages` < reselect < `UnreadCards`'s mapStateToProps < react-redux < redux-persist dispatching its REHYDRATE action. It looks like this would cause a crash; the symptom might look like staying at the loading screen forever upon launch.

So here `narrows.get` is undefined. Which means `narrows` wasn't *itself* undefined -- else we'd have had an error trying to read the property `narrows.get` -- but it's some object that doesn't have a `get` property. E.g. it could be an empty object.

This is concerning because `narrows` there comes straight from a selector that returns `state.narrows`, and the latter is supposed to be an `Immutable.Map`. Which would certainly have a `get` property.

This error is the kind of thing that could happen if a migration didn't run. Indeed, in previous releases including v27.157, `state.narrows` was a plain Object used as a map, and it would not have had a `get` property. But we did have a migration for that, and indeed v27.158 has some later migrations which are simply `dropCache`; I don't see anything wrong with our migrations here. So if the migration *did* go wrong, or somehow get skipped, that's concerning because it suggests something wrong in the underlying layer that manages migrations.

I think we won't want to roll the release out to users in general until we've fixed this, or otherwise are confident it won't affect lots of users in general. So that makes this a top priority.

**Comment by chrisbobbe** [comment]
Ack; thanks for reporting this.

**Comment by gnprice** [comment]
> So here `narrows.get` is undefined. Which means `narrows` wasn't _itself_ undefined -- else we'd have had an error trying to read the property `narrows.get` -- but it's some object that doesn't have a `get` property. E.g. it could be an empty object.

Hmmm or here's another thing it could be, other than an empty object -- it could be an object like `{ '__serializedType__': 'ImmutableMap', data: { … some data … } }`. I.e., it could be the thing that our `replacer` function in `src/boot/replaceRevive.js` returns, and that our `reviver` is supposed to turn back into an `Immutable.Map`.

That hypothesis comes to mind because of [this other error](https://sentry.io/organizations/zulip/issues/2156959430/events/aadb1965725f4671ad16c0b24a13c9cf/) that's new in v27.158 -- we've seen it just once, so it's not a priority in itself, but it may be a clue:
> f.get is not a function. (In 'f.get(l.PixelRatio.getPixelSizeForLayoutSize(h))', 'f.get' is undefined)

where the stack is
```js
            uri: avatarUrl.get(PixelRatio.getPixelSizeForLayoutSize(size)).toString(),
```
in `UserAvatar` < React < Redux < redux-persist dispatching its REHYDRATE action.

So that's the same shape of error, where this time `avatarUrl` is the value that isn't itself undefined, but is lacking an expected property. (Which happens again to be named `get`.)

Unlike `state.narrows`, this `avatarUrl` isn't one of the top-level branches of the state tree. So if some kind of trouble with migration just dropped the data and made up `{}`, or something, then we wouldn't get this far in the first place -- that'd affect the entire `state.users` tree. But this could happen if for some reason the `reviver` didn't get a chance to do its job.

There's also a migration affecting this one too:
```
  // Convert `UserOrBot.avatar_url` from raw server data to
  // `AvatarURL`.
  '18': dropCache,
```
So if that -- and the other couple of migrations which are also `dropCache` -- got skipped for some reason, then perhaps that could also produce this error.

**Comment by gnprice** [comment]
> So if that -- and the other couple of migrations which are also `dropCache` -- got skipped for some reason, then perhaps that could also produce this error.

Yeah, in particular: if the `avatarUrl` were a string, then that would behave just the same as a plain Object that didn't have a `get` property. At least, here's what the Chrome dev console says:
```
> "abc".get
< undefined

> ({}).get
< undefined
```

OTOH if it were `null`, then there'd be a TypeError at even trying to get the property:
```
> (null).get
< Uncaught TypeError: Cannot read property 'get' of null
```
We're not seeing that, so the value isn't null; but it could be a string, or an unexpected type of object.

**Comment by chrisbobbe** [comment]
Discussion has continued [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4458.3A.20.22t.2Eget.20is.20not.20a.20function.22.20on.20state.2Enarrows.20at.20sta.2E.2E.2E/near/1112340). We've come up with #4463 and #4472 for a couple of latent bugs, and discussed several ideas for what could be causing these symptoms, but haven't gotten to the bottom of it yet.

**Comment by Gautam-Arora24** [comment]
I will work on this once I complete #4224 😀

**Comment by Gautam-Arora24** [comment]
I would like to work on this! 😀

**Comment by chrisbobbe** [comment]
@Gautam-Arora24, sure! Unfortunately you don't have direct access to the Sentry events themselves, as Greg and I do, but let us know if you'd like us to check them for something. Feel free to get caught up with the discussion I mentioned above (in https://github.com/zulip/zulip-mobile/issues/4458#issuecomment-778675311), then join us there with your ideas. 🙂
