### ISSUE TITLE
Crash in getUserFromMention

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4460]
One of our more widespread issues reported by Sentry is [this one](https://sentry.io/organizations/zulip/issues/1968822455/events/4fa22161f82c49e2b6171095ccb6e67c/):
> undefined is not an object (evaluating 'o.split')

with stack
```js
    const [userFullName, userIdRaw] = unformattedMessage.split('|');
```
in `getUserFromMention` < `MentionWarnings`.

So it seems that `unformattedMessage` here is `undefined`. The fuller source listng is
```js
  getUserFromMention = (completion: string): UserOrBot | void => {
    const { usersById } = this.props;

    const unformattedMessage = completion.split('**')[1];
    const [userFullName, userIdRaw] = unformattedMessage.split('|');
```
so it looks like this would happen if `completion.split('**')` returns an array of less than two elements. In particular this would happen if `completion` doesn't contain `'**'`.

Because this is regularly affecting users, and I believe it's causing a crash for them, it would be good to fix.

I think this is ripe for some debugging.
* The first goal would be to try to reproduce it -- go to the compose box and try to enter some text that triggers this bug.
* A useful step for trying to do that would be to read a bit more of the code that leads to here, and try to see when `getUserFromMention` is called. It seems like that function is assuming that its argument string will contain `**` whenever it gets called, but that that isn't always true.
* Once we have a clear reproduction, I suspect the fix may be relatively easy -- the debugging may be the main part of the work.

**Comment by im-adithya** [comment]
Hey @gnprice! I have tried to reproduce this but failed to do so...
I found that the function getUserFromMention is being called because of handleMessageAutocomplete which is used whenever we type :, # or @... So when the case is @ --> `**Username**` is added by default (hence it is checking whether the lastWordPrefix is '@' or not in order to ensure the presence of **s) which is then used to split to get `unformattedMessage`.
> It seems like that function is assuming that its argument string will contain ** whenever it gets called, but that that isn't always true.

I tried to replicate this by typing @username but it then doesn't trigger autocomplete so that doesn't even get invoked.
So I think it is correct to assume that the function's argument always contains ** whenever it gets called...

**Comment by Gautam-Arora24** [comment]
@gnprice I would like to work on this?

**Comment by im-adithya** [comment]
> @gnprice I would like to work on this?

Hey Gautam, I'm still investigating this issue to reproduce it and will work on this once I find it...

**Comment by chrisbobbe** [comment]
@Gautam-Arora24 found, in #4474, that `unformattedMessage` is undefined for user-group mentions (like `@*mobile*`). 

I notice that there's already some code for handling `unformattedMessage` being `undefined`, and it quite helpfully mentions user groups. [Here](https://github.com/zulip/zulip-mobile/blob/v27.158/src/compose/MentionWarnings.js#L52-L57):

```js
    // We skip user groups, for which autocompletes are of the form
    // `*<user_group_name>*`, and therefore, message.split('**')[1]
    // is undefined.
    if (unformattedMessage === undefined) {
      return undefined;
    }
```

That snippet comes from just below the problematic `.split` call. So perhaps a good solution is to just move that code just above the `.split` call.

**Comment by gnprice** [comment]
> @Gautam-Arora24 found, in #4474, that `unformattedMessage` is undefined for user-group mentions (like `@*mobile*`).

Great, glad to have that repro recipe.

Having tried it out, it turns out this is not a crash -- in fact, from the user perspective, nothing at all goes wrong. That's a bit of a relief, because this bug has been around for a while and it's good that it wasn't so severe.

Looking back at the code, the reason this didn't cause any user-visible problems is:
* This is inside `handleMentionSubscriberCheck` on `MentionWarnings`. So it interrupts that function from doing its work; but that's harmless because no individual user was @-mentioned, so we wouldn't show a warning in any case. (In fact, after the fix, what happens instead is that that function just returns on the very next line.)
* That function's caller, in turn, is `handleMessageAutocomplete` on `ComposeBox`. But this was already the last line of that function, so there's nothing it was going to do that gets interrupted. (Before this point, it's already done the job of updating the text input with the autocompleted text.)
* That function, in turn, just propagates up ultimately to the `onPress` handler of a native touchable component, either `TouchableNativeFeedback` or `TouchableHighlight`. So that handler has an uncaught exception, but the app carries on just fine.

**Comment by Gautam-Arora24** [comment]
That's the beauty of exception handling, the app continues to perform even if there is an error encountered 😀
