### ISSUE TITLE
iOS: streams in left menu difficult to scroll in landscape

### ISSUE THREAD

**Issue by feorlen** [zulip/zulip-mobile#447]
In the left menu, only the list of streams scrolls. Landscape orientation restricts how many streams are visible, and with large fonts it's even fewer. At the largest accessible sizes, the left side menu doesn't display any streams. 

A better option would be to not have the top items fixed, but allow the entire menu to scroll.

This example displays one stream in the menu, and the scrollable area is very small:
![zulip_ios_landscape_sidebar](https://cloud.githubusercontent.com/assets/95028/24077032/50aa4866-0bfd-11e7-8cc6-56581d1eef1d.PNG)

**Comment by nashvail** [comment]
@timabbott @borisyankov @neerajwahi I was wondering if the left SideBar can be left exclusively for streams and the main 4 navigations (Home, Private Messages, Starred & Mentions) could be moved to a [TabBar](https://developer.apple.com/ios/human-interface-guidelines/ui-bars/tab-bars/).

**Comment by borisyankov** [comment]
Not only that! I am pushing for more tabs :) There is some work done in 'main-tabs' folder though it was long ago and not sure if it is even working at the moment.

I don't forsee this to be something to be implemented immediately, but I would push for that after we have stable iOS and Android apps in the app store.

**Comment by vishwesh3** [comment]
Now list is scrollable. Can be closed now :)
We can open another issue with more details about new UI :)

**Comment by borisyankov** [comment]
Indeed. Closing.
