### ISSUE TITLE
Progress bar while uploading medias.

### ISSUE THREAD

**Issue by hkpanchani** [zulip/zulip-mobile#4503]
Add a support to show progress bar while sending medias from mobile devices.. Right now sending media in blind and not able to tell if something is being sent or not.

**Comment by Gautam-Arora24** [comment]
Yes, I agree @hkpanchani There is no progress bar kinda thing in the mobile app right now. Maybe @chrisbobbe and @gnprice can give us better direction on how to implement a progress bar. If the mentors are ready to implement such thing in the app, I would be happy to work on this issue.😀

**Comment by chrisbobbe** [comment]
Thanks for the report! I think the issue you're describing is already in the tracker as #2684, and PR #4129 has been sent to fix it. So I'll close this, so we can better focus the conversation in those threads. 🙂
