### ISSUE TITLE
Depreciation warning for "PushNotificationIOS" module of core React-Native.

### ISSUE THREAD

**Issue by Gautam-Arora24** [zulip/zulip-mobile#4510]
**What is this issue for?**
The core ```PushNotificationIOS``` module has been depreciated from React-Native. We can see this error in the console window when we start the server.
This is where official RN [docs](https://reactnative.dev/docs/pushnotificationios) mention this.
![Screenshot 2021-03-06 at 2 36 35 PM](https://user-images.githubusercontent.com/53913514/110248495-81d5e500-7f97-11eb-9b91-113ef556cbfc.png)

**Steps to solve this issue**
We will use the react-native-community/push-notification-ios package. Instead of using PushNotificationIOS from react-native we will use the same from the above-mentioned package in /src/notification/index.js. The docs of the package mention the use of the PushNotificationIOS.

**Comment by Gautam-Arora24** [comment]
Working on this!

**Comment by chrisbobbe** [comment]
Thanks, @Gautam-Arora24!

This deprecation warning is covered in issue #4115, which has PR #4163 open for it, so I'll go ahead and close this.

I probably could have done a better job of writing #4115, to include search terms like `PushNotificationIOS`, to make it easier for you to find; sorry about that. 🙂
