### ISSUE TITLE
Markdown tables with long text can get cut off

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4530]
A markdown table such as:

```
| a | b |
| --- | --- |
| `ajkljdslkgjalkfjksldjfk lsjdf jsdlfkjds lkfjdksl jfkldsj kldsjfl kjds lkjdsklfj ldskjf lsdkjfl ksdjfkl jsdlkfj klsdj fldsj klfjdslkfjldsk jkldsj fdsl kfdsj l` | supercalifragilisticexpialidocious |
| 1 | 2 |
```

Will have the text "supercalifragilisticexpialidocious" cut off on the right side. Instead of cutting off the text, the table should scroll horizontally.

**Comment by gnprice** [comment]
Agreed.

This is probably just a line or two of CSS to fix -- the main work needed is finding the right change like that to make.

For whoever wants to take this up, I'd suggest taking a look at how we handle LaTeX math displays: https://zulip.com/help/format-your-message-using-markdown#latex . I believe if you have a message with a long equation that doesn't fit on the screen, we'll have that scroll horizontally. So it may be a matter of using the same bit of CSS here as we do there.

**Comment by rajprakash00** [comment]
@gnprice  Can i work on this issue?

**Comment by timabbott** [comment]
It's also worth looking at `static/styles/rendered_markdown.css`, both for whether we have the same bug and if not, whether we can use the same solution.
