### ISSUE TITLE
Don't immediately send attachment on upload

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4540]
When a user uploads a attachment or image, it's immediately sent. Instead, we should change the behaviour to be more like the webapp: the input field should have the markdown for displaying the image inserted, but the user should be allowed to edit before sending. This will also allow people to add multiple attachments (see [this CZO thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Multiple.20Attachments) requesting this).

Related: #1903

**Comment by AlaaElden98** [comment]
I would like to work on this issue, can you assign it to me?  @WesleyAC

**Comment by vaibhavs2** [comment]
may I get assigned to this? :)

**Comment by chrisbobbe** [comment]
Also related: #2684

**Comment by chrisbobbe** [comment]
We've had another report of this: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292530

Marking as P1.
