### ISSUE TITLE
There is no obvious way to go to the beginning of a topic

### ISSUE THREAD

**Issue by AlaaElden98** [zulip/zulip-mobile#4549]
It's hard to scroll all the way up to reach the first post of a topic, currently the app have a button to navigate to the last post in a topic
![IMG_20210318_204320_449](https://user-images.githubusercontent.com/34111697/111680129-8ff2f380-882a-11eb-83cc-329a3b533cf3.JPG)

I think a good UX/UI is to add "The start of the topic" -or something nicer- option on long-press at a topic name.
![IMG_20210318_204806_642](https://user-images.githubusercontent.com/34111697/111680834-4951c900-882b-11eb-86b2-0ebded83aee7.JPG)

If this sounds good, i want to work on this issue.

**Comment by gnprice** [comment]
(See discussion [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Navigate.20to.20the.20beginning.20of.20a.20topic/near/1136213).)
