### ISSUE TITLE
Consider disabling in-app browser, or providing an option to do so

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4562]
I personally am not a fan of the embedded browser in Android, and I don't think I know many people who are. The first two Google links I see for "android in-app browser" that are not about how to implement this open with things like:

> Want to disable in-app browser for Android apps? Well, the majority of applications these days offer an in-app browsing feature for opening URLs and webpages directly within the app without leaving it to your phone’s default browser. This is apparently done by developers to keep users locked within their apps for as much as time possible.
> 
> Now while this offers convenient and faster access to web content, some of you may not like the lackluster approach. As a result, it becomes a two-step process to open links from the applications on your primary browser. In this article, let’s see how you can disable the in-app browser for certain Android apps.

(from [How to Disable In-App Browser for Android Apps](https://gadgetstouse.com/blog/2019/12/21/how-to-disable-in-app-browser-for-android-apps/))

> In olden times, when mobile apps wanted to show web content, they would open the URL in the default browser. This caused the browser to become the active application, and depending on the platform, may have also required the user to perform more than just a single tap to return to the previous app. Keep in mind that this was happening while apps were just beginning to gain traction and marketers were scrambling to identify valuable metrics in this new app space. In the effort to keep metrics going “up and to the right”, it was only natural that publishers would want users to stay in “their” app for as long as possible, and lo! The in-app browser was conceived as a means to this end.*

(from [In-App Browsers: What You Need to Know](https://www.addthis.com/blog/2017/04/04/in-app-browsers-explained/))

We should either disable the in-app browser altogether, or provide an option to do so. I'm not sure which is best, I'd love some feedback from users on this.

I wasn't able to find any explanation of why we have an in-app browser currently, I'm not sure if it was just enabled by default by React Native, or if we added it. However, I wasn't able to find any commits explicitly *enabling* it, which I suspect means that it was just a default.

**Comment by vaibhavs2** [comment]
@WesleyAC 
>We should either disable the in-app browser altogether, or provide an option to do so. I'm not sure which is best, I'd love some feedback from users on this

links are opening in in-App browser and then there is an option to open in separate browser(open in browser), I liked the way it is implemented , as sometime I see single page and navigate back, sometime If I like the content then starts more search and like to open new tabs and so on. For this I saw there is already an option to to select and surf in separate browser and its good.

**Comment by WesleyAC** [comment]
See also #4323, where a user requested this on iOS. I'm going to close this issue, and edit that one to be for both iOS and Android.
