### ISSUE TITLE
Bug when switching account

### ISSUE THREAD

**Issue by AkashDhiman** [zulip/zulip-mobile#4569]
![switch-account-bug](https://user-images.githubusercontent.com/40268170/112720618-72f2aa80-8f25-11eb-92b4-4ba3f3e0fb94.gif)

steps to reproduce:

- be already logged into an account
- go to profile window and tap switch account
- type in another valid realm, wait till it redirects to method of sign in screen
- you will be able to navigate back from this screen

At this stage you are not logged in to any realm yet you see the data from last logged in session, interacting with any component that requires auth, breaks the app.

In between the flow we land at this screen: 
![Screenshot from 2021-03-24 21-00-36](https://user-images.githubusercontent.com/40268170/112720643-9fa6c200-8f25-11eb-92ef-b3e5acbfe3c3.png)

It is possible to remove all the accounts from this screen, and doing so leads to no account found error.

**Comment by chrisbobbe** [comment]
Thanks for the report! I haven't yet had a chance to look at this in detail, but initially, I suspect that fixing #4416 might solve this, or might partially solve it. I've got #4491 open for that; @gnprice, FYI. 🙂

**Comment by AkashDhiman** [comment]
#4491 solved this issue.
