### ISSUE TITLE
Show logged-in/logged-out state in account picker.

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4579]
`AccountPickScreen` shows all the accounts the app knows about, whether or not they're logged in.

Each item in the list should indicate if the account is logged in (it has a non-empty `.apiKey`) or logged out (it has an empty `.apiKey`).

**Comment by gnprice** [comment]
More details, copied from #4491:

In `AccountPickScreen` we should display an account differently if it's logged out -- it should look "grayed-out" or disabled, or be marked with a label like "Signed out".
* Google does this with a "Signed out" label; see screenshots like [here](https://vaadin.com/learn/tutorials/google-login) or [here](https://www.carlsetzer.com/2020/03/03/google-tip-deleting-old-google-sign-in-accounts/).

**Comment by vaibhavs2** [comment]
can it be assign to me?

**Comment by chrisbobbe** [comment]
Thanks, @vaibhavs2!
