### ISSUE TITLE
Support a future event (shape TBD) that marks messages unread.

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4600]
See [discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/Make.20the.20message.20unread.20if.20it's.20edited.2E/near/1152595).

**Comment by gnprice** [comment]
API discussion is in [this thread](https://chat.zulip.org/#narrow/stream/378-api-design/topic/mark-as-unread.20.28update_message_flags.29/near/1204350) (long).

A server-side draft is at https://github.com/zulip/zulip/pull/19307 .

**Comment by gnprice** [comment]
Oops, we ended up duplicating this issue as #5361.

I think that one has wound up with more things linking to it, so I'll close this one as a duplicate in favor of that one.
