### ISSUE TITLE
PasswordAuthScreen: Crash in `WebLink` following #4491.

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4605]
The `WebLink` in `PasswordAuthScreen` depends on the current realm being stored in Redux. We stopped storing it there in #4491, so we get a crash in `PasswordAuthScreen`.

**Comment by gnprice** [comment]
Glad we caught this before it went into a release :smile: 

Looking at your PR now.

**Comment by gnprice** [comment]
Ah, is this specific to the "Forgot password?" link?

If so I think this is P1 but not P0. That's a flow that any given user rarely needs and probably most users never need; and there's always the workaround of doing it on web and coming back to mobile. If this were preventing a large class of users from logging in at all, that'd definitely be P0.

Still -- good to have caught this!

**Comment by chrisbobbe** [comment]
> If this were preventing a large class of users from logging in at all, that'd definitely be P0.

Ah, I should have been more specific: the symptom _is_ that a large class of users are prevented from logging in at all. It's a white-screen "crash" on viewing the password-auth screen at all; it doesn't require clicking on the link.

**Comment by gnprice** [comment]
Ahh I see, because the exception happens at the selector passed to `connect`. :+1:
