### ISSUE TITLE
change in messageActionSheet in dark theme UI

### ISSUE THREAD

**Issue by abhi0504** [zulip/zulip-mobile#4609]
When we long press on any stream then the `messageActionSheet` opens up , in light theme it looks quite good but its not matching the dark theme UI 

- Its background color must be dark 
- text color must match the dark theme UI font i.e. text color must be white

Current status : 
  
![WhatsApp Image 2021-04-06 at 3 35 00 PM](https://user-images.githubusercontent.com/56453541/113694688-b1d6ec00-96ed-11eb-9a35-355245c7c690.jpeg)

Status : Working on this issue

**Comment by alya** [comment]
Definitely! Dark theme should have dark theme action sheets, similar to the topic selection widget:
![Screenshot_20211203-120730_Zulip](https://user-images.githubusercontent.com/2090066/144666929-ce09a263-a882-4d03-aded-ae02b3fca016.jpg)

**Comment by WesleyAC** [comment]
Took a quick peek at this — the actionsheet library we're using wants you to use their [containerStyle](https://github.com/expo/react-native-action-sheet#containerstyle-optional) prop for this, they don't have any support for it built in. That means we'll need to pick some colors, and wire through our theme selector bits, but that shouldn't be hard.

**Comment by thisisnitish** [comment]
Hi @chrisbobbe!, can I give it a shot to this issue? Thanks 🙂

**Comment by thisisnitish** [comment]
Hi @chrisbobbe!, I would like to take this issue. Thanks 😊

**Comment by thisisnitish** [comment]
Please refer: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/message.20action.20sheet/near/1341074

**Comment by gnprice** [comment]
Folding this into the similar #5274.
