### ISSUE TITLE
Avatars pixelated in user view

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4614]
If you click on an image of a user, you see a large image of their avatar, along with some info about them. That image is pixelated.

This probably has a solution like the other problems like this, which are described in #4305.

**Comment by chrisbobbe** [comment]
Interesting, thanks for the report! Are you seeing this pixelation on all avatars, or just some? Shortly after merging work to prevent pixelation, I did identify an exception that that work didn't cover; it'd be good for me to load that back into my brain and write it down. But if it's happening to all avatars, that's something else.

**Comment by WesleyAC** [comment]
It's happening on every avatar I've looked at.

**Comment by WesleyAC** [comment]
Oh, wait, nevermind, your avatar on CZO looks fine... Will investigate further.

**Comment by chrisbobbe** [comment]
> Shortly after merging work to prevent pixelation, I did identify an exception that that work didn't cover; it'd be good for me to load that back into my brain and write it down.

Interesting; this seems to be different from the exception I had in mind.

(That one was, when we use the `/avatar/{user_id}` redirect endpoint, we can't express the size we want. You can read more about `/avatar/{user_id}` in `FallbackAvatarURL` which we construct at the edge for [crunchy shell](https://github.com/zulip/zulip-mobile/blob/master/docs/architecture/crunchy-shell.md), and on the point about `user_avatar_url_field_optional` at https://zulipchat.com/api/register-queue. So in cases where we use that endpoint, avatars might be pixelated even when we have the right idea of what size we want to use. In practice, though, the current implementation means we use that endpoint for long-term idle users (though this is a server implementation detail that may change without notice), and naturally people don't run into those users often.)

I'm seeing https://zulip-avatars.s3.amazonaws.com/13/90692a74cc962341be54c66a576896500725b5ff?x=x&version=3 as the avatar URL on my user object on Recurse, when I get it in the `/register` response. So, naturally (according to `AvatarURL.fromUserOrBotData`), we store this in an `UploadedAvatarURL` instance; there's no `FallbackAvatarURL` involved. As you can see, that URL points to a pretty small image, and I do see it pixelated in my user-profile page on the mobile app. Looking at that URL, I'm not sure what the right way is to ask for a specific size from an s3 avatar URL, or if it's possible; it may be that the current implementation of `UploadedAvatarURL#get` can only specify a size for URLs like https://chat.zulip.org/user_avatars/2/08fb6d007eb10a56efee1d64760fbeb6111c4352.png?x=x&version=2&s=50:

```js
      const match = new RegExp(/(\w+)\.png/g).exec(result.pathname);
      if (match !== null) {
        result.pathname = result.pathname.replace(match[0], `${match[1]}-medium.png`);
      }
```

I don't think there's always been a widespread breakage of uploaded avatar URLs on realms that use s3; I likely would have noticed while working on #4230, etc.

-----

@timabbott, could the way we're supposed to request a specific size for an avatar image from s3 have changed recently? For example, did the smaller-image URL used to contain `.png` and have a `-medium.png` variant, and now it doesn't?

**Comment by gnprice** [comment]
> https://zulip-avatars.s3.amazonaws.com/13/90692a74cc962341be54c66a576896500725b5ff?x=x&version=3
 
> ```js
>       const match = new RegExp(/(\w+)\.png/g).exec(result.pathname);
>       if (match !== null) {
>         result.pathname = result.pathname.replace(match[0], `${match[1]}-medium.png`);
> ```

Yeah, that sure looks like a diagnosis! Our logic assumes that a Zulip-uploaded avatar URL will have a `.png` extension, and that turning `.png` into `-medium.png` is the way to get a larger-size image.

So the question is what's now the supported way to get that larger-size image. If it happens that Tim doesn't see the @-mention above and reply, probably the next step is to ask in chat, in #mobile-team or perhaps #backend.

**Comment by chrisbobbe** [comment]
OK! Just started a chat discussion [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4614.20Avatars.20pixelated.20in.20user.20view/near/1156659).
