### ISSUE TITLE
NavigationExperimental is deprecated

### ISSUE THREAD

**Issue by vihanggodbole** [zulip/zulip-mobile#462]
Going through the docs I found that `NavigationExperimental` [is deprecated](http://facebook.github.io/react-native/docs/navigation.html#navigationexperimental) as of version 0.43 and will be removed from the codebase later on.
We should switch to other components like the `Navigator` or `NavigatorIOS` to avoid issues in the future.

**Comment by vihanggodbole** [comment]
@zulipbot label "bug"

**Comment by huyanhh** [comment]
Could this be a potential replacement? [Wix 60fps Navigation](https://github.com/wix/react-native-navigation)

**Comment by vihanggodbole** [comment]
@huyanhh Yes! I'll look into that. Thank you.

**Comment by borisyankov** [comment]
The first candidate would be [React Navigation](https://github.com/react-community/react-navigation). Others are Wix, AirBnB, ReactRouter.

We do not need to replace immediately. Most other good solutions are still maturing and finalizing.

Wix's one is being rewritten for 2.0, React Navigation is not yet at v1 etc.

**Comment by kunall17** [comment]
Done, this can be closed now!
