### ISSUE TITLE
feature: Navigate to top when clicking on the tabs button.

### ISSUE THREAD

**Issue by Gautam-Arora24** [zulip/zulip-mobile#4622]
Sometimes, when in Home Tab the collective list of all streams and topics can be too long and there is no way to navigate to the top other than scrolling. We can see this as an example in Whatsapp where clicking once on the `Chats` tab, the user gets navigated to the top of the list. 

PS - Working on this issue 😀

**Comment by gnprice** [comment]
(See discussion in chat: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Navigate.20to.20top/near/1155106 )
