### ISSUE TITLE
Not able to react with some emojis.

### ISSUE THREAD

**Issue by nikhilmaske-2001** [zulip/zulip-mobile#4638]
Issue: I am not able to react with some emojis like 😄 1️⃣ 2️⃣  and some more in the chat on the messages.
I am using the latest version of mobile app (i.e 27.161) that is available on play store.

**Comment by WesleyAC** [comment]
For the numbers, this was fixed in #4551, which I guess hasn't hit the play store yet. @gnprice, any idea when we're going to do a release?

We were actually just talking about the smile one last night, I'll make a PR fixing that soon as well.

**Comment by gnprice** [comment]
BTW @nikhilmaske-2001 thanks for the report!

If you see any other emoji with these symptoms (any other than `:smile:`, `:slight_smile:`, and the numerals), please file an issue about it. We should make this systematically not a problem -- that's #2956 -- but until then, fixing any given emoji ad hoc is quick and we want to do so for things people run into.

> @gnprice, any idea when we're going to do a release?

Yeah, we should do this soon. #mobile-team is probably the best place for discussion.
