### ISSUE TITLE
Migrate from `realm_filters` event format to new `realm_linkifiers` format

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#4657]
In https://github.com/zulip/zulip/pull/17596, we changed the format for `realm_filters` events to a new `realm_linkifiers` format that is more rational and extensible.  We should migrate clients to this new format.  (See the backwards-compatibility notes in the API documentation, but I expect a correct implementation will choose whether to send `realm_filters` or `realm_linkifiers` in `event_types` when doing a `register` post, and then have handled code for `GET /events` for both formats).

(This will be an important prerequisite for adding stream-specific linkifiers in the future).

**Comment by chrisbobbe** [comment]
As I understand it, https://github.com/zulip/zulip-mobile/issues/4242 is needed for this. We do one thing with `realm_filters`, which is pass it to a `parseMarkdown` function for local echo. That function was forked from the web app in 2017 and naturally hasn't been kept up-to-date.

Once #4242 is done, we can take the new event format—presumably the shared code we use will be able to handle it. The next step for #4242 is to respond to my review of his PR zulip/zulip-markdown-parser#5.

**Comment by timabbott** [comment]
I'm not sure this needs to block on that -- can't we just write a block of event handler code that takes a `realm_linkifiers` object and turns it into a `realm_filters` style tuple before passing the data to the markdown implementation?  

(And then when moving to a shared markdown implementation, one would potentially switch that around?)

I would expect that as a general rule, we want to handle feature level logic in the code directly adjacent to the network (E.g. a first step after receiving responses from the server) -- so that other code can be clean and simple (either against the old API, or the new, depending on how we want to convert the data).

**Comment by chrisbobbe** [comment]
> The format change is I think just `obj => [obj.pattern, obj.url_format_string, obj.id]`

Interesting; yeah, if the new `realm_linkifiers` objects can be converted to old-format `realm_filters` ones, this shouldn't have to block.

**Comment by chrisbobbe** [comment]
Just sent #4666.
