### ISSUE TITLE
Improve UI for "All streams" subscription status

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#4658]
The "All streams" view currently uses slider toggles to indicate stream subscription status and allow the user to change it. This UI feels off, because toggles are generally used for settings, and the stream itself is not a setting.

We should try changing the UI to something that feels more appropriate. A good candidate is using "+" for streams the user is not subscribed to, and a checkmark for streams the user is currently subscribed to. See screenshots below.

Related Zulip thread: https://chat.zulip.org/#narrow/stream/48-mobile/topic/.22All.20streams.22.20subscribe.20toggles

Current Zulip UI:
![toggles](https://user-images.githubusercontent.com/2090066/114610906-493fc000-9c55-11eb-87bf-f568411a1b05.png)

Alternative pattern (screenshot from Pocket Casts podcast app):
![Screenshot_20210411-150500_Pocket-Casts](https://user-images.githubusercontent.com/2090066/114612568-26aea680-9c57-11eb-95f6-65f4de229f1c.jpg)

**Comment by vaibhavs2** [comment]
I am working on this.

**Comment by thisisnitish** [comment]
Hey @alya, Looks like no works has been done so far. Can give it a shot to this. Thanks 😊

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!, 
* The idea is to build a Zulip button because when I was going through the code and I realised that, We are using `ZulipSwitch` component which uses `Switch` in itself.
* So, I think we have to do the same thing, like we have to build the custom button for this issue such as `ZulipSubscribe` button which will behave the same way the only difference will be to change the icon on respective event.
Thanks 😊

**Comment by thisisnitish** [comment]
I moved over to the `react-native-vector-icons` I found these two icons which we need
<img width="170" alt="Screenshot 2022-04-09 at 11 06 20 PM" src="https://user-images.githubusercontent.com/48220369/162585239-74d47a29-ece1-4f22-a59d-a410de1f2931.png">
<img width="165" alt="Screenshot 2022-04-09 at 11 07 09 PM" src="https://user-images.githubusercontent.com/48220369/162585241-3720a496-d1f4-46bd-bf28-3cb2b6ec530e.png">

Both are from `FontAwesome`.
Thanks 😊

**Comment by thisisnitish** [comment]
The reason we need separate component such as `ZulipSubscribe` because later in the future we might need switch button.

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!,
I've figured out some of the parts of related to this issue and UI is kind of done but when I'm pressing the button then event is not getting triggered.

So far what I've understood is we are using `ZulipSwitch` component as our switch button and it takes 3 props which is `value`, `onValueChange`, `disabled`. Now, I got the little idea from the comments that what these props are.

And, I've done the similar thing in my approach but, somehow when I'm pressing the button the event is not getting triggered.
It would be a great help if you could help me, where to look for. Thanks 😊

**Comment by chrisbobbe** [comment]
> It would be a great help if you could help me, where to look for.

Sure. It's probably easiest for me to help if I could take a look at the code. It doesn't have to be polished into a reviewable PR for this purpose; you could make a PR marked as a [draft](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests), or just push your branch and tell me its name. 🙂

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I've made a draft PR. Please have a look at that, #5333. Thanks 😊
