### ISSUE TITLE
Text in messageBox not visible when theme is dark mode and mobile is in landscape mode

### ISSUE THREAD

**Issue by vaibhavs2** [zulip/zulip-mobile#4665]
Tested in android -6 and 10
<img src="https://user-images.githubusercontent.com/31806059/114898402-af803a80-9e2f-11eb-9ff3-c837c8e24914.gif" />

[here](https://drive.google.com/file/d/1tFBiWVyAC9i0iK7SZhQHhcVcZilAxLTG/view?usp=sharing) clear video

**Comment by Gautam-Arora24** [comment]
Hey, @vaibhavs2 I would like to work on this issue.

**Comment by vaibhavs2** [comment]
Welcome but Can't Assign you :D, ask experts

**Comment by rajprakash00** [comment]
Hey @vaibhavs2 ! I have already an issue present for this #4480 and a PR too #4486

**Comment by vaibhavs2** [comment]
ok , didn't see that, don't worry I am closing it then.
