### ISSUE TITLE
stream gets blocked by error message

### ISSUE THREAD

**Issue by dmig** [zulip/zulip-mobile#4691]
Zulip for android, v27.162

An error message "error loading page" blocks any stream if this link https://floor796.com/ is posted there.

After loading a posted message appears for half a second, then "error loading page" appears.

**Comment by dmig** [comment]
![Screenshot_20210422-092105_Zulip](https://user-images.githubusercontent.com/388564/115673470-f6e55a00-a34c-11eb-9a76-421b544ef625.png)

**Comment by chrisbobbe** [comment]
Hi, @dmig!

This reminds me of #4337; it's an error from the system Chrome on your device. I don't think we've yet landed on a way to protect against the error. One workaround (which I know won't be adequate for all cases) is to remove the message containing the link, or edit the message to remove the link.

**Comment by dmig-alarstudios** [comment]
Opening this link in system Chrome doesn't show any errors. Seems to me, app may use some custom SSL certificates, which became outdated.
This site uses Let's Encrypt certificate issued on 8.03.2021 -- may be this can give a clue?

**Comment by WesleyAC** [comment]
This should be fixed in the most recent beta release — let us know if you see this problem after updating! (See #4726 for details)
