### ISSUE TITLE
Play Store doesn't offer app when no camera on device

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4722]
A user [reports](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Zebra.20Mobile.20Computer.20compatibility/near/1174306) that they can't find the app in the Play Store on a Zebra MC3300X, a mobile computer for warehouse that's running Android 10.

And indeed the Play Console [tells me this](https://play.google.com/console/developers/8060868091387311598/app/4976350040864490411/devices?deviceGroupId=Zebra-mc3300x) about that device:
> Reasons the device is unsupported
> Doesn't support required feature: android.hardware.camera

So it seems the Play Store believes our app requires a camera. Of course in reality the situation is that the app can *use* a camera if you have one, but the app is perfectly functional for its core use cases without one. So it seems that some metadata is incorrect.

This is puzzling because in the app's manifest, the closest thing to this that I can find is:
```xml
    <uses-permission
        android:name="android.permission.CAMERA"
        android:required="false" />
```
which seems like it should say that a camera is not required. But evidently something else is going on.

The next step for debugging this is probably some research in the Android docs and/or on the web, to understand just what that bit of the manifest means and to understand how the Play Store decides what hardware features an app requires.

Until we've fixed it, a workaround is to download the APK (e.g. [via GitHub](https://github.com/zulip/zulip-mobile/releases)) and install it manually.

**Comment by andreasoc** [comment]
great!
