### ISSUE TITLE
Logout gives endless loading screen

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4723]
This seems to reproduce reliably for me, on v27.162, on both iOS and Android. Not sure if it's new in v27.162 or was present earlier.

Repro steps:
* I'm logged into an account.
* I hit the "Log out" button. Get a confirmation modal, and confirm.

Expected result:
* Navigate to the account-pick screen. During the nav transition animation, the old account's UI is replaced with a loading screen.

Actual result:
* See just the loading screen -- no nav transition happening.
* [Sometimes](https://chat.zulip.org/#narrow/stream/48-mobile/topic/login.20bug/near/1174900), this goes on apparently indefinitely, at least for a good few seconds, until I kill the app. (Ken Clary [observed](https://chat.zulip.org/#narrow/stream/48-mobile/topic/logout.20bug/near/1173539) this continuing for 30 seconds or so before killing the app.)
* [Sometimes](https://chat.zulip.org/#narrow/stream/48-mobile/topic/logout.20bug/near/1173143), it turns into an error screen, the one our new React error boundary displays. The error message is "Error: Active account not logged in".

We [probably want to change](https://chat.zulip.org/#narrow/stream/48-mobile/topic/logged-out.20state/near/1174548) what the "Log out" button does entirely. But that isn't a trivial change to make, and I suspect that taking care of it will involve basically debugging this issue anyway -- the key thing that should be happening here and doesn't seem to be is the navigation, and we'll still want to make the same navigation after that change.

**Comment by chrisbobbe** [comment]
From a bisect (luckily starting with the first and last commits in #4603) I think a80b4e8da3e7918604430e8ff3ef9b627e7d0396 may have introduced the issue; I'm looking into it.
