### ISSUE TITLE
Inline images with invalid HTTPS certs cause error that prevents use of stream

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4726]
Loading a inline image with a invalid HTTPS cert causes the following:

![Screenshot_20210506-162731](https://user-images.githubusercontent.com/5001092/117269603-00ada800-ae8b-11eb-9529-de4d36132747.png)

While this doesn't appear to have ever happened in the wild in Sentry (???), and changes in Camo in 4.0 will make it impossible for people to construct messages like this in the future, we should still fix it for the sake of being able to view existing messages.

[#integrations > create svg](https://chat.zulip.org/#narrow/stream/127-integrations/topic/create.20svg) will repro this.

(marking a-Android, since I don't think this would affect iOS, and P1 since it's a DoS vector on pre-[`6b7a3fb74`](https://github.com/zulip/zulip/commit/6b7a3fb74acb9e8992d256a2da3b75fcb22befb9) servers.)

**Comment by chrisbobbe** [comment]
I know of two other issues that seem like probably the same thing: #4337, #4691. (I'm getting caught up on things from last week's call, so I don't think I'll have time to deduplicate just now.)

**Comment by timabbott** [comment]
Just updating this thread that we apparently have a similar bug in the desktop app (https://github.com/zulip/zulip-desktop/issues/1119), and that we should still consider this important since (1) Camo doesn't run in docker-zulip, so a lot of 4.0 servers are still affected and (2) inability to read old content before the Camo changes is important in its own right.

**Comment by WesleyAC** [comment]
This was fixed upstream react-native-webview/react-native-webview#1466, which we pulled in in 945848dbbfe8454d957a1eb824dceeeb3573325a. Closing.

**Comment by chrisbobbe** [comment]
> This was fixed upstream [react-native-webview/react-native-webview#1466](https://github.com/react-native-webview/react-native-webview/pull/1466), which we pulled in in [945848d](https://github.com/zulip/zulip-mobile/commit/945848dbbfe8454d957a1eb824dceeeb3573325a). Closing.

Hmm, are you sure this has been fixed? Your screenshot was from 2021-05-06, and the release containing 945848d, [v27.155](https://github.com/zulip/zulip-mobile/releases/tag/v27.155), went out on 2020-09-23.

**Comment by chrisbobbe** [comment]
> I think we *actually* got it in a `yarn.lock` update, likely 78a7763bc9500c5f371139473d0debc377474276

Great, thanks for that investigation! Indeed, the `react-native-webview` PR [says](https://github.com/react-native-webview/react-native-webview/pull/1466#issuecomment-714298176) "This PR is included in version 10.9.3", and we went from 10.8.3 to 10.10.2 in that commit ([link to changed lines in yarn.lock](https://github.com/zulip/zulip-mobile/commit/78a7763bc9500c5f371139473d0debc377474276#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10032-R10035)).
