### ISSUE TITLE
Editing stream name / description puts double quotes around it.

### ISSUE THREAD

**Issue by AkashDhiman** [zulip/zulip-mobile#4747]
![edit-stream-name](https://user-images.githubusercontent.com/40268170/118048087-658c6500-b399-11eb-8f17-07e3c59a7021.gif)

The code at fault is in `/src/streams/streamsActions.js/updateExistingStream.js`.

where `api.updateStream` is called with the response of `JSON.stringify(newValue.name)` as the `value` parameter.

This code was added in  https://github.com/zulip/zulip-mobile/commit/3e1becac570dc8e2d3a163673c5403a47285c820 and  https://github.com/zulip/zulip-mobile/commit/f86e9147cf6101cfd07858440ab7b31667ccf8d0.

Removing the call to `JSON.stringify` will remove this issue.

It is unclear to me what the "unsafe characters" are described in that commit, I don't think removing the call to `JSON.stringify` can have any problem, but still posting it as an issue to ask what other people think of this.

**Comment by Gautam-Arora24** [comment]
Thanks for the detailed explanation @AkashDhiman! Working on this 🙂

**Comment by Gautam-Arora24** [comment]
We need to be sure what does it mean by "unsafe characters" before removing the `JSON.stringify` method.
