### ISSUE TITLE
mentioned messages aren't shown if topic is muted.

### ISSUE THREAD

**Issue by ganpa3** [zulip/zulip-mobile#4791]
I just noticed that if someone mentions me in a message and I have the topic muted, the message isn't shown in the "Mentions" tab on zulip-mobile, whereas it is shown on the web app.

**Comment by WesleyAC** [comment]
Thanks for reporting this! I think this is a duplicate of #3472, so I'm going to close this and follow up there. I think this is pretty important, so I'm going to mark it as a P1.
