### ISSUE TITLE
Editing a message topic doesn't move message from old topic

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4830]
If you edit a message topic from a topic narrow, the message will then appear in two places: the new topic, and the old topic. This is incorrect, it should only display in the new topic.

**Comment by gnprice** [comment]
Yeah. I think this is a manifestation of #2688 -- we have the same bug if it's not you but someone else who edits the topic.

That issue is a bit unclearly described and has some out-of-date details, so I'll go edit it some, and close this as a duplicate.
