### ISSUE TITLE
unreadModel: respond to message topic/stream edits

### ISSUE THREAD

**Issue by WesleyAC** [zulip/zulip-mobile#4840]
We currently don't update unreads when a message topic is edited. We should do so.

See [CZO discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.22No.20messages.20with.20this.20topic.22).

**Comment by gnprice** [comment]
Similarly when a message is moved between streams.

Both of these changes come to us in the form of `update_message` events:
https://zulip.com/api/get-events#update_message
We turn those events into Redux actions with type `EVENT_UPDATE_MESSAGE`.

So the place to implement this will be in `src/unread/unreadModel.js`, in `streamsReducer`, which should get a `case EVENT_UPDATE_MESSAGE:` section.

**Comment by gnprice** [comment]
This causes pretty frustrating behavior when it happens: there's a thread in the unreads list, you tap on it to open, and then we fetch and find no messages, producing a nonsensical screen like this (reported [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1291806); discussion below that from [about here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bug.20reports/near/1292572)):
![image](https://user-images.githubusercontent.com/28173/144919283-0b231fee-ca50-4d61-be93-13daa19496bc.png)

Moreover, thanks to topic resolving, it's now a pretty common occurrence for a topic to get renamed, where once it was an edge case.

**Comment by chrisbobbe** [comment]
Oops, I accidentally assigned myself before remembering that #4980 is in progress. Fixed now.

**Comment by gnprice** [comment]
(I went to add myself as an assignee because I've picked up the PR #4980, but instead it unassigned Wesley. Then I fixed it.)
