### ISSUE TITLE
Preserve left-side unread indicator when not marking messages as read

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#4849]
Within the debug menus, we have an option not to mark messages as read on scroll. We want to make this option more prominent (#4850).

Before doing so, we should fix the fact that the left-side line indicating unread messages still disappears upon scrolling even though messages are not being marked as read.

**Comment by gnprice** [comment]
To do this, we'll want to pass the value of this setting into the webview. The left-side unread indicators are controlled by the within-webview code, in the function `sendScrollMessage` and its callee `setMessagesReadAttributes`. We'll want to just do nothing there, in the case where this setting is enabled.
