### ISSUE TITLE
Move top navigation bar into left-side drawer menu

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#4851]
At present, we have both top and bottom navigation menus, which is a non-standard layout and can cause confusion for the user.

We should create a left-side drawer menu, which would allow us to get rid of the top navigation bar. This is in line with the approach take by Slack and Discord mobile apps, among others. The overall plan would be:

* Move "All messages", "Starred messages" and "@-mentions" into the left-side drawer.
* Consolidate gear and avatar menus into a single item.
* Move search to the bottom navigation bar (replacing the gear).

See [#mobile-team > left-side drawer nav](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/left-side.20drawer.20nav)

**Comment by WesleyAC** [comment]
We should also move the org switcher directly into the drawer nav, instead of burying it under a menu.

**Comment by chrisbobbe** [comment]
Linking discussion at https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/left-side.20drawer.20nav/near/1311269.

**Comment by alya** [comment]
We have decided to take a different approach to navigation, so closing out this one.
