### ISSUE TITLE
Add indicator for topics with unread @-mentions in unread topics view

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#4857]
In the unread topics view, we provide a count of unread messages, but it's still not easy for the user to prioritize which topics to read. 

We should add an indicator to show which topics have unread messages where the user is @-mentioned.

We can do this by displaying a red dot to the left of the unread message count for the topic.

**Comment by gnprice** [comment]
I think the simplest way to do this with acceptable performance is probably to iterate through the list of unread @-mentions in `state.unread.mentions`, and build a nested-`Map` data structure that indexes them by stream and topic.

That will be efficient as long as there aren't a large number of unread @-mentions.

**Comment by gnprice** [comment]
> I think the simplest way to do this with acceptable performance is probably to iterate through the list of unread @-mentions in `state.unread.mentions`, and build a nested-`Map` data structure that indexes them by stream and topic.

To do this strategy in a reasonably performant way, we'll first need #4684.

Here's an alternate strategy, though:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/unread.20mentions/near/1337462
