### ISSUE TITLE
ios: Unwanted in-app notification sound when phone is on silent.

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#4897]
@alya [said](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/notification.20sound.20bug/near/1225469):
> We got the following report from a user:
> 
> "When my phone is on silent, I get a notification noise when I get a new DM when the app is open. This surprises me."

The purpose of the sound has been to alert the user to a message they might want to know about, while they're in the app but not looking at a view where the message appears.

The sound is being played in an audio channel that isn't affected by the device-level silence-notifications setting.

Instead, we should use the native notification-sound functionality.

**Comment by alya** [comment]
Yay!
