### ISSUE TITLE
Execute the `user_settings` object transition

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#4933]
In zulip/zulip#19404, we just added the feature level 89 migration to change how we encode user settings in the Zulip API to use a `user_settings` object.  

The API documentation should explain the transition clearly.  Here's the recommended strategy:
* Clients can immediately switch from processing the `update_display_settings` and `update_global_notifications` event types and process the `user_settings` event type instead.
* Clients may then want to refactor how they store user settings to have a common module/object. 
 The web app did this migration in https://github.com/zulip/zulip/pull/19404/commits/998d7102753e1e2f6dc1096c927bacfe798df4b0.
* Clients can then pass the `user_settings_object` client capability to all Zulip server versions (older servers will ignore it). If the server returns a `user_settings` object in the register response, the client should use that to initialize its `user_settings` object using the `user_settings` portion of the response; otherwise it should use the user personal settings flags that appear in the top-level response.

I've tentatively tagged this as a priority, because there is a decent amount of messy complexity involved in maintaining the legacy API here, and we'd prefer to be able to remove that complexity.

**Comment by chrisbobbe** [comment]
@gnprice it would be great to get your thoughts on https://github.com/zulip/zulip-mobile/issues/4659#issuecomment-890081662 before we proceed with this.

**Comment by chrisbobbe** [comment]
Just sent #5299 as a first step for this.
