### ISSUE TITLE
Store user ID in accounts state

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4951]
Currently for each of the accounts the user is logged in as, we store:
* the URL for that org/realm;
* the user's email that they use to log in there;
* their API key, their secret credential that represents being logged in there;
* a few other bits of metadata.

This is OK, except that instead of email we really want to be identifying a user by their numeric ID: #3764.

And what makes this particularly acute is that the payloads of notification-messages from the server have already performed that migration: they don't contain the user's email, only their ID. As a result, if the user is logged into several accounts on the same org, we have #4631 if they try to open a notification from one of those (we're unable to switch to the appropriate account, because we don't know which one it is); and we'll have a similar issue in that case with #4945/#4861 replying to a notification (we won't be able to do it from one of those, because we don't know which one it is.)

So we need to start storing the user ID in `state.accounts`.

The steps for implementing this will look something like:
* Add a property `userId` to the `Account` type. Follow the examples of how we handled `zulipVersion` and `zulipFeatureLevel`. Use a migration (in `src/boot/store.js`) to fill in the value as `null` for existing accounts.
* Each time we complete an initial fetch, we'll learn the user ID then and so we can fill it in. This will come in a `REALM_INIT` action; see `accountsReducer.js` for where we update `state.accounts`, and follow the example of `zulipFeatureLevel`.
* Then we should be able to start using that information, in particular for #4631.

**Comment by AlaaElden98** [comment]
I think i can work on this.

**Comment by ShristiJain** [comment]
hey @AlaaElden98 are you still working on this? I would like to work on this. This will be my first open source contribution, any kind of help is welcome.
