### ISSUE TITLE
Send presence updates (focusPings) at correct times

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#50]
Tim thinks if we just do the following, we should be good:
- [x] Send when started or restored from suspended state
- [x] Send once per minute while the app is open.

Feedback on how this affect people 'I think activity in the mobile app doesn't mark me as "online" in the Zulip backend. I'm pretty sure that PMs received while I'm online (in the web app) don't trigger emails, yet I'm pretty sure I've received emails for PMs received while I had the mobile app open.'

**Comment by timabbott** [comment]
@borisyankov I just updated the description with the pieces that I think we need to do; the rest is probably not necessary to provide good data.
