### ISSUE TITLE
Couldn't connect to server in android applicaion

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/zulip-mobile#5007]
Hi everyone,

Can you help me with this to troubleshoot the issue. From web it is working properly , I am using traefik as reverse proxy and it has a valid ssl certificate.

Thanks in advance anyone also facing same issue or resolved please guide me.

**Comment by chrisbobbe** [comment]
Hi @amolvishwakarma, thanks for the report! Could you please provide more detail about what it looks like when you see the problem? For example, a screenshot would be helpful.

**Comment by amolvishwakarma** [comment]
I can able to do login from web application and it shows valid ssl but not working from zulip desktop app and android devices not tested in ios , please check below screenshot
```
# Web login screenshot
![image](https://user-images.githubusercontent.com/57523705/133959210-575c0b54-c068-45d7-9df1-0c2344d0868b.png)
```
```
# Desktop screenshot
![image](https://user-images.githubusercontent.com/57523705/133959184-f8bf3b7a-4ae6-4d7e-ae50-752ddfde6a63.png)
```
```
# Android screenshot
![Screenshot (Sep 20, 2021 10_42_47 AM)](https://user-images.githubusercontent.com/57523705/133959316-b100f67c-c308-4382-92ab-587fb89c8ae0.png)

```

If you need any other details please let me know @chrisbobbe

**Comment by amolvishwakarma** [comment]
Hi @chrisbobbe ,
The issue is resolved tested in ssl-labs where it is showing letsencrypt as well as traefik default certificate. 
So I added the same label of traefik in zulip container to use the valid ssl rather than traefik default certificate in my docker-compose.yml file.

```
labels:
- "traefik.enable=true"
- "traefik.http.routers.zulip.rule=Host(`example.com`) && PathPrefix(`/`)"
- "traefik.http.routers.zulip.entrypoints=websecure"
- "traefik.http.routers.zulip.tls=true"
- "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
```
