### ISSUE TITLE
Upgrade to React Native 0.43

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#512]
Stoppers:

- [x] Some 3rd party components were rising warnings on day 1 of release, as React did some maintenance changes. This is not a bug but breaks the build. This is mostly a wait-and-see when they are fixed.
- [x] We should ensure nothing breaks the app (usually nothing does in RN upgrades)
- [ ] NavigationExperimental is deprecated. I'll be replacing it with React Navigation.

**Comment by nashvail** [comment]
Even new list components FlatList, SectionList e.t.c (https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html) depend on RN 0.43, will we be making a swtich to them as well?
