### ISSUE TITLE
Make "+" open an action sheet instead of row of buttons

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5141]
At present, compose box buttons are accessed via a "plus" symbol to the left of the compose box. Clicking on "plus" expands the buttons on the same line as the compose box. This works OK with the buttons we currently have, but is likely to no longer look good as we start adding more buttons (#3427, #5079).

In #5080, we change this behavior so that putting the cursor into the compose box will open buttons *below* the compose box.

Based on the discussion on #5080 and in [this CZO thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M5080.20Move.20compose.20box.20buttons.20into.20a.20row.20below.20the.20compose), we should also make "+" open an action sheet.

Actions (we can discuss/finalize these labels when working on the issue):
* Upload a file (cf. webapp tooltip: Upload files)
* Upload a picture
* Take a picture
* Add a video call (cf. webapp tooltip: Add video call)

This issue may be a blocker for #3427 and #5079. It's possible we can implement one of those without this issue, but not both.

**Comment by sumj25** [comment]
I'm working on this issue and would like to claim it.

**Comment by chrisbobbe** [comment]
As discussed in our meeting on 2022-10-05, I'm marking this as blocked on @alya considering this with the mobile redesign in mind.

It's a priority especially because it's in our plan toward fixing #M5463, a really annoying bug; see https://github.com/zulip/zulip-mobile/issues/5463#issuecomment-1227641703.

**Comment by chrisbobbe** [comment]
Closing, as we took a different design in #5080, with PR #5635.
