### ISSUE TITLE
"Mark all as read" button for PMs

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5156]
Tim has reported a few times ([here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Mark.20as.20read.20bugs/near/1293359) and [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Mark.20as.20read.20in.20PMs/near/1252998)) a bug where there's no "mark all as read" button for a PM conversation. We should add one.

There isn't an API endpoint for marking a whole PM conversation as read (see [chat](https://chat.zulip.org/#narrow/stream/378-api-design/topic/mark.20PM.20narrow.20as.20read/near/1253754)). But Wesley [points out](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Mark.20as.20read.20in.20PMs/near/1253769) that a workaround is to send a list of message IDs. I think that's likely to work in almost all cases, so let's try it.

The most complete list of message IDs we have in the app is found in the unread-messages data, right? A small caveat is that the window included in the initial unreads data is long but not infinite. There could be some missed unreads from before that window that we don't include, so they don't get marked as read.

The following comment from 89cff7c24 suggests that the window really is pretty long:

```js
      // TODO handle MESSAGE_FETCH_COMPLETE here.  This rarely matters, but
      //   could in principle: we could be fetching some messages from
      //   before the (long) window included in the initial unreads data.
      //   For comparison, the webapp does handle this case; see the call to
      //   message_util.do_unread_count_updates in message_fetch.js.
```

**Comment by timabbott** [comment]
I think for all practical purposes, the `unread_msgs` data set should have the complete set of unread message IDs; it'll be the most recent 50K message IDs that are unread; the chances that a user is looking at a PM thread that contains unreads that are older than 50K other unreads are very low (and in that situation, the solution is probably a top-level notice to the user in the UI, not a change to this feature).  So worth a comment that this is theoretically not perfect, but certainly not worth spending more time on than that.

The key thing is to grab the set of IDs to send to the server from the unread messages data set, rather than just what messages are displayed locally.

**Comment by gnprice** [comment]
That strategy sounds good to me.

Once we implement the TODO in that comment quoted above, then the unreads data (what we initialize from `unread_msgs`) will also contain any messages you're looking at now that are unread.

I think the most realistic case where you could have an unread PM that's out of the 50k window is something like: you join some very busy org; you stop being active; you get some PMs, perhaps from people you know who are active there and aren't sure if you're still active there; you keep accumulating tons of unreads in busy streams; then you log in again after a year or two. That's totally a thing that happens, though it isn't a real common case.

**Comment by timabbott** [comment]
Yeah, it's not super common, and also I would expect that having loaded the given narrow would insert into your local `unread_msgs` data structure any unreads in the PM thread, so it'd also have to be the case that you had more unread PMs than fit into the fetch buffer for the view.  

(Actually, I have no idea whether the `GET /messages` code for the mobile app does that sort of unread message logic; the webapp does for legacy reasons but I guess this is a reason to not delete it).

**Comment by gnprice** [comment]
> also I would expect that having loaded the given narrow would insert into your local `unread_msgs` data structure any unreads in the PM thread, so it'd also have to be the case that you had more unread PMs than fit into the fetch buffer for the view.
> 
> (Actually, I have no idea whether the `GET /messages` code for the mobile app does that sort of unread message logic; the webapp does for legacy reasons but I guess this is a reason to not delete it).

Yeah, we ideally should but currently don't; that's exactly what the TODO comment quoted above is about. (The context of where it appears is that it's exactly the spot where we're maintaining the unreads data structure and are presented with the data from having loaded the messages for some narrow.)
