### ISSUE TITLE
Edit message you just sent

### ISSUE THREAD

**Issue by asah** [zulip/zulip-mobile#5179]
![Screenshot_20211226-150820_Zulip](https://user-images.githubusercontent.com/140002/147418954-df5c788a-eab0-4c9b-8fd9-9f6ffb935583.jpg)

**Comment by chrisbobbe** [comment]
Thanks for the report! I think #4671 is likely to be the relevant bug here. We should offer message editing when you're looking at the "All messages" view.

A workaround is to edit the message from where it appears in the relevant stream or topic view.

**Comment by alya** [comment]
Closing as a duplicate of #4671.
