### ISSUE TITLE
Error for @ mentions in unsubscribed private stream

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5206]
When a user has been @-mentioned in a private stream they are no longer subscribed to, this breaks the @-mentions tab (in the current alpha version of the app). The user sees a screen that reports: "Invariant Violation: stream should exist for message," plus additional debugging information.

**Comment by gnprice** [comment]
Thanks for the report!

I believe this was a regression introduced in 9d05bbaf6fc9937ac9a776e28cbc988cc3b47b45, which was merged a few weeks ago and is in the new alpha v27.180 but no other published releases.

**Comment by gnprice** [comment]
Sent a fix as #5207, basically reverting the commit that introduced this regression.

Also wrote up some details on what that commit was trying to do, why that didn't work, and the two basic strategies for how to solve the same problem correctly: #5208.
