### ISSUE TITLE
Bug: I can PM my own profile

### ISSUE THREAD

**Issue by Udit-takkar** [zulip/zulip-mobile#5215]
When I logged in with same email in web and then on Android app. I was able to see my name in active users and i was also PM myself.

 I tried this thing in some other open source chat applications. But none of them allowed me to PM myself. Is this a bug?

![Screenshot_20220129-182525](https://user-images.githubusercontent.com/53316345/151662028-dc97c1b6-8924-42d6-8b63-5c9d461e6897.jpg)
![Screenshot_20220129-182513](https://user-images.githubusercontent.com/53316345/151662034-1f5f8af8-39d3-4e76-9912-41623b78a5b8.jpg)

**Comment by AkashDhiman** [comment]
@Udit-takkar This isn't a bug, it can be useful in some circumstances to be able to private-message yourself, for instance drafting messages or compiling information that you need to keep at hand. I particularly use it to share images, cross platform.
Some other chat apps that also provide such functionality include Signal and Slack.

**Comment by Udit-takkar** [comment]
Oh Okay makes sense
