### ISSUE TITLE
Can't paste org URL into add-account input

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5228]
See discussion: https://chat.zulip.org/#narrow/stream/48-mobile/topic/can't.20paste.20org.20URL/near/1318402

Quoting myself from there:

> As a product question, how much do we really need/like the current "smart"ness of the `SmartUrlInput`, where there's some editable text sandwiched between two non-editable texts whose values are computed?
> 
> This would all be simpler and less bug-prone if the whole line were just a normal text input. I think we could even pre-populate it with something like `https://your-org.zulipchat.com`, with `your-org` selected by default ([doc](https://reactnative.dev/docs/0.64/textinput#defaultvalue), [doc](https://reactnative.dev/docs/0.64/textinput#selection)). If we do pre-populate, then there's a downside if your org doesn't follow the `https://your-org.zulipchat.com` pattern: you have to explicitly clear out the part you don't want and replace it. (Like you'd do with any normal pre-populated text input. :wink:)

**Comment by thisisnitish** [comment]
Hi @chrisbobbe!, can I give it a shot to this issue??

**Comment by chrisbobbe** [comment]
Hi @thisisnitish, thanks for the offer! 🙂 I've actually been working on this one myself. I see I forgot to assign myself in the issue metadata; I've just done so.

**Comment by thisisnitish** [comment]
Sure @chrisbobbe, no problem. I'll find some other issue. Thanks 🙂
