### ISSUE TITLE
Narrow doesn't work as expect for message header clicks

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-mobile#523]
This seems to be a recent regression (probably after #492).

When message headers are clicked, user isn't narrowed to the specific message. Instead it takes user to the end of the narrowed message list.
I am not sure if this change is intentional, but seems different from the behaviour on the web :).

**Comment by borisyankov** [comment]
I noticed that, but I don't think it has ever worked.

**Comment by Sam1301** [comment]
oh right, sorry for the confusion :). 
I actually meant that we had this functionality before
https://drive.google.com/open?id=0B4jK5QX65b0ZaHFlMkF6NEJXOEU

but currently this happens when message header is clicked.
https://drive.google.com/open?id=0B4jK5QX65b0ZQlRZWFpQTDU3T1k

**Comment by borisyankov** [comment]
Hmm, interesting ;)
When I was doing the #492 I noticed that the code had some intent for this to work, but at this point it wasn't working anymore, and I thought maybe it had never worked. I guess it broke at some point before that.

**Comment by borisyankov** [comment]
Closing as fixed and merged.
