### ISSUE TITLE
Option to mark as read only in conversation views

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5241]
At present, we have an option not to mark messages as read on mobile. However, it may be more convenient to have the behavior where:

1. Messages *do* get marked as read in conversation views (single topic or PM thread).
2. Messages *do not* get marked as read in interleaved views. The user can take advantage of interleaved views to skim what's happening without losing unread indicators.

We should add a third option for this behavior.

[CZO thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Recent.20topics.3F/near/1318999)

**Comment by SilentCruzer** [comment]
I would like to work on this issue, 

I just have one doubt, for the third behavior, do you mean we need to add another option in the settings screen called **Mark Messages read on scroll only in Topic narrow**, to trigger the two behaviors?

**Comment by alya** [comment]
The option of when/whether messages get marked as read should be controlled by one setting with three possible values.

**Comment by alya** [comment]
@SilentCruzer please post a comment describing your proposed approach when you're ready. I can assign the issue to you once you [have a rough plan](https://zulip.readthedocs.io/en/latest/overview/contributing.html#picking-an-issue-to-work-on). Thanks!

**Comment by SilentCruzer** [comment]
@alya , We can just modify the method markRead by adding additional boolean values/types to restrict the method to certain narrows: 
https://github.com/zulip/zulip-mobile/blob/777b584a6b066a5daeedb872f252fab33708f73f/src/webview/handleOutboundEvents.js#L185-L198

A new setting can be created like:
**Mark as read on scroll**, which will have a drop down menu on the right having three options:
- all narrow - This is the current behavior, it will mark as read on scroll in every narrow, 
- stream narrow - it will mark as read on scroll in every narrow except all messages narrow,
- topic narrow - it will mark as read on scroll only in topic narrow.
- never - If this option is added we can completely replace the option - Do not mark as read on scroll in the settings menu.

This setting will return one of these three values. We can use the value in the markRead method to restrict the method to the chosen narrows.

**Comment by wilsonfurtado2000** [comment]
can I work on this ??

**Comment by SilentCruzer** [comment]
@wilsonfurtado2000 , I have already made a [draft pull request](https://github.com/zulip/zulip-mobile/issues/5241) for this issue

**Comment by chrisbobbe** [comment]
> **Mark as read on scroll**, which will have a drop-down menu on the right having three options:
> - all narrow - This is the current behavior, it will mark as read on scroll in every narrow, 
> - stream narrow - it will mark as read on scroll in every narrow except all messages narrow,
> - topic narrow - it will mark as read on scroll only in topic narrow.
> - never - If this option is added we can completely replace the option - Do not mark as read on scroll in the settings menu.
> 
> This setting will return one of these three values.

Hmm, there are four items in that list, not three. And it doesn't use the "conversation views" concept in the issue description.

Alya said:

> The option of when/whether messages get marked as read should be controlled by one setting with three possible values.

I think the three intended values are:

Mark messages read on scroll:
- Always
- Never
- Only in conversation views (single topic or private-message thread)

**Comment by alya** [comment]
Yep, that's right -- thanks for the clarification, @chrisbobbe !
