### ISSUE TITLE
Set a stream web-public, in stream settings

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5250]
This is a follow-up on #5014, which was for displaying when a stream is web-public.

In the stream settings screen (which you get to e.g. via the "info" icon in the app bar when looking at the stream narrow), we offer a switch to make the stream private or public.

We should add the option to make it web-public. This probably means replacing the boolean switch UI with a UI to choose from a list.

While we're at it, this is probably a good prompt to add the concept of private streams with shared history (vs. private streams with protected history): #2683. So it'll be a choice between four options:
* web-public
* public
* private, shared history
* private, protected history

See the corresponding UI in the web app for comparison. Note there's kind of a lot of text accompanying each option -- which is probably necessary, because distinctions like "public" vs "web-public", or "shared history" vs "protected history", are a bit subtle.

**Comment by chrisbobbe** [comment]
Closing as fixed by #5389.
