### ISSUE TITLE
Add "Busy" status to emoji status picker

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5255]
In https://github.com/zulip/zulip/issues/21179 / https://github.com/zulip/zulip/pull/21190 we added a "Busy" status to the emoji status picker. We should do this on mobile as well.

@chrisbobbe would you be up for taking care of this, since you've been working on #4925?

**Comment by chrisbobbe** [comment]
Yep! 🙂

**Comment by alya** [comment]
Thanks!
