### ISSUE TITLE
@-mentions count not positioned correctly

### ISSUE THREAD

**Issue by SilentCruzer** [zulip/zulip-mobile#5278]
The count for the total @-mentions displayed in the Top Bar of the homepage is not positioned correctly.

The screenshot below is taken from a pixel 4 emulator. The positioning was also there when tested on oneplus 7T.

Screenshots:
<img src="https://user-images.githubusercontent.com/73246484/157130708-4150b822-87e8-4a16-8193-42c0b6998cdf.png" width=300 height=600>

**Comment by alya** [comment]
Thanks for the report @SilentCruzer !

Related discussion: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/unread.20count.20is.20not.20visible.20properly.20in.20overlay.2E

**Comment by thisisnitish** [comment]
Hey @alya, If it's a bug then Can I give it a try to this one. Thanks 😊

**Comment by thisisnitish** [comment]
Sure @alya I'll let you know my plan. Thanks 😊

**Comment by thisisnitish** [comment]
Hey @alya!, So My plan is like this:

- We are using a component name `CountOverlay` and `CountOverlay` is using `ComponentWithOverlay` which has a prop of `overlaySize`. So we just need to change the size of the overlay.

- Previously, `overlaySize` was `15` and I made it to `19` and It looks pretty good to me. But, if you know any perfect size for this icon then we can also do this. But I don't think it is necessary, because it looks very reasonable.  I've done the work. 

Hoping for your feedback. Then, I'll raise the PR. Thanks 😊

Here is the Preview, Please have a look and let me know your feedback,
**Previously**
https://github.com/zulip/zulip-mobile/issues/5278#issue-1162010470

**Now**
![Simulator Screen Shot - iPhone 12 - 2022-03-09 at 23 23 31](https://user-images.githubusercontent.com/48220369/157502524-be4eea79-a431-4dc9-880f-fc30207bcb39.png)

**Comment by chrisbobbe** [comment]
Thanks, @thisisnitish! Could you please post a screenshot that shows this badge and the unread-PMs badge (in the bottom tab bar) at the same time? You can make the unread-PMs badge appear by having an unread PM, or by changing this line in src/main/MainTabsScreen.js, e.g., like so:

```diff
-            tabBarBadge: unreadPmsCount > 0 ? unreadPmsCount : undefined,
+            tabBarBadge: 1,
```

I think ideally we'd want the badges to match closely, so it's helpful to see them both at the same time.

**Comment by thisisnitish** [comment]
Yeah, Sure @chrisbobbe!, Even I checked this scenario and it was perfectly working. I'll post the screenshot. Thanks 😊

**Comment by thisisnitish** [comment]
Thanks, @chrisbobbe!, I've posted a Screenshot for both the badges at the same time. Please have a look. Thanks 😊 

![Simulator Screen Shot - iPhone 12 - 2022-03-10 at 00 36 51](https://user-images.githubusercontent.com/48220369/157513672-dd3772b0-a24e-490f-b0dd-b316e96e0aad.png)

**Comment by chrisbobbe** [comment]
Thanks, that's helpful! There's a pretty noticeable difference in the badge's position relative to the icon. Could you see if there's a nice way to fix that? Ideally we'd look at the implementation of the bottom-tabs badge in `node_modules/@react-navigation/bottom-tabs` and try to match that, I think.

From the [inspector](https://reactnative.dev/docs/0.64/debugging#integration-with-react-native-inspector), it looks to me like the center of the badge lines up with the top-right corner of the person-icon's rectangle. (This could be wrong, it's just how it looks to me without reading code, playing around with system font size, etc. 🙂)

**Comment by thisisnitish** [comment]
Sure @chrisbobbe!, I didn't realised that.
One question I've, The badge we are seeing on person icon in `bottom tabs`. I think, we need the same kind of visual on top at `mention` icon....right??

**Comment by thisisnitish** [comment]
- Hey @chrisbobbe!, I just revisited to the code of `MainTabsScreen` and `HomeScreen` and found that, we are using `react-navigation` for the `Bottom Tabs` in `MainTabsScreen`.

- But, in `HomeScreen` we have our own component named `TopTabButtonGeneral`. It has wrapped the `IconUnreadMentions` component. 

- When I further dived into the code I found that It is using `CountOverlay` which is again using `ComponentWithOverlay` where we pass prop `overlayPosition`. When I checked the `overlayPosition` It was give option `top-right`, which I feel is correct.

- The style we have given to the `top-right` prop is also I feel is correct.

This was the update so far I have. I'm still trying to fix the badge on mention icon at proper position. But, I'm looking for your suggestions also. Thanks 😊

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!, I made some changes in `ComponentWithOverlay`, actually I was playing with `position` of the badge.
Currently, we have given:
```
'top-right': {
    right: 0,
    top: 0,
  },
```

But, I changed to:
```
'top-right': {
    right: -10,
    top: 10,
  },
```
**Below is the preview:**
![Simulator Screen Shot - iPhone 12 - 2022-03-11 at 22 53 36](https://user-images.githubusercontent.com/48220369/157917040-919d84a1-b576-47fb-90c6-842fa41f61f3.png)

**Comment by chrisbobbe** [comment]
Thanks! It looks more similar now. I think that approach is probably fine for the time being, then we can look closer when we reorganize this part of the UI in #4851 (our latest thinking for that is [here](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/left-side.20drawer.20nav/near/1311269), I think).

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I checked #4851 and [our latest thinking](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/left-side.20drawer.20nav/near/1311269). If you confirm, I'll raise the PR and we can use the above approach for the time being. Thanks 😊

**Comment by chrisbobbe** [comment]
Yep, sounds good, thank you!

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I've raised the PR. Please have a look #5301. Thanks 😊
