### ISSUE TITLE
iOS: Add-video-call button sometimes doesn't insert link

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5291]
Well this has been pretty thorny to debug. 😛 I've gotten far enough that I think the best way forward is to fix #5141, and hope it fixes this.

When you tap the add-video-call button in the expandable menu (the menu we'll get rid of in #5141), we immediately make a Jitsi link and try to insert it into the message input. I've discovered that sometimes the link isn't added there, as it should be.

Around the same time, the menu collapses.

In cab9cb53f3ac674b2bfacb4d84f73332fc28c1b6, we made it so that the `TextInput` switches to multiline when the menu collapses, and single-line when the menu expands.

The message input is [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html). When we want to force a change to its value, instead of setting some state and passing it to the `value` prop, we call `setNativeProps` on the `TextInput`'s ref.

When we `setNativeProps` on the `TextInput`'s ref, to give it a new text value, the backing `RCTSinglelineTextInputView` does seem to get its native props updated. You can check this with logging: add some logs in RCTUIManager's `updateView` method. (For the logging, use `RCTLog`; don't forget to change `RCTSetLogThreshold` in our `AppDelegate`.)

Hypothesis: A split-second later, the `RCTSinglelineTextInputView` is swapped out for a `RCTMultilineTextInputView`, which didn't get its native props updated. (See above about `multiline`.) So the updated text with the link doesn't show up.

**Comment by chrisbobbe** [comment]
(In particular, when we fix https://github.com/zulip/zulip-mobile/issues/5141, I suspect we'll just always make the input `multiline`, so it won't switch between `RCTSinglelineTextInputView` and `RCTMultilineTextInputView` underneath.)

**Comment by chrisbobbe** [comment]
I'd like the first three commits of #5474 to be reviewed and merged before moving forward with #5141.

**Comment by gnprice** [comment]
> I think the best way forward is to fix #5141, and hope it fixes this.

There's also #5080, which is to move the compose menu to go below the content input, rather than to squeeze it from the side. That would also mean we stop swapping the content input from single-line to multi-line, so it seems like it should be equally effective at fixing this.
