### ISSUE TITLE
Font color is black in iOS but Gray/Grey in Android

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#530]
In Android all text color (time, sender name, message) are grey. Which doesn't look good.
![5c895738-ad74-4aa6-8312-215ac9457316](https://cloud.githubusercontent.com/assets/18511177/25403957/cde728ee-2a1b-11e7-913b-9ba786bbfe2f.jpg)
![2083035f-213d-477b-9f33-a37604ee3e6c](https://cloud.githubusercontent.com/assets/18511177/25403959/ce4ec5b2-2a1b-11e7-87eb-e256b928f1ce.jpg)

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
This might be considered fixed by #519

**Comment by vishwesh3** [comment]
Yup! it is fixed.
