### ISSUE TITLE
Follow /near/ links through topic moves/renames

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5306]
This is a new feature on web in zulip/zulip#21426 / zulip/zulip#15290, fixing a regular pain point with resolved topics in particular. We should adopt it on mobile too.

To implement it, we'll probably want to move some of the implementation into shared code so we can reuse it. In particular `message_edit.stream_and_topic_exist_in_edit_history`:
https://github.com/zulip/zulip/commit/2a485289cf507a37bf744e059d2867dcd3f50d63

Note that we'll also need to resume maintaining the `edit_history` property on messages. Currently in `messageReducer.js` we have, since 055f45d610f1643e29914d539fc5a5e52161c1f1:
```js
          ...(oldMessage: M),
          content: event.rendered_content ?? oldMessage.content,
          last_edit_timestamp: event.edit_timestamp ?? oldMessage.last_edit_timestamp,
          // TODO(#3408): Update edit_history, too.  This is OK for now
          //   because we don't actually have any UI to expose it: #4134.
```

**Comment by chrisbobbe** [comment]
See details of a recent API change around `edit_history`: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/edit.20history/near/1342402

**Comment by chrisbobbe** [comment]
Here's a description of an algorithm to implement, on [CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M5306.20Follow.20.2Fnear.2F.20links.20through.20topic.20moves.2Frenames/near/1407930):

> When a user clicks a `/near/` link in a message,
> 
> 1. Get the message, either from our local data structures or (failing that) from a single-message fetch, using the API added in zulip/zulip#21391.
> 2. If the message is currently in the stream and topic encoded in the `/near/` link, open the topic narrow for that stream/topic, and scroll to the message*.
> 3. If the message was *at some point* in the stream and topic encoded in the `/near/` link, according to its `edit_history`, open the topic narrow for the stream/topic that the message is currently in, and scroll to the message*.
> 4. Otherwise (i.e., the message was never in the stream/topic encoded in the `/near/` link), open the topic narrow for the stream/topic encoded in the link, and scroll to the message "nearest" to the message ID*.
> 
> *Actually opening a narrow scrolled to a specific message ID is blocked on #M3604.

with

> Yeah, I think it'd be very reasonable to not do special handling for case 4 at first, leaving a comment and an open issue to record that it's a corner case we don't handle perfectly.
