### ISSUE TITLE
Display names of reacting users when few users have reacted

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#5348]
We're close to merging https://github.com/zulip/zulip/pull/21013 as a Zulip 6.0 release goal, which adds a new (default on) setting for displaying the users who did a particular emoji reaction, when there are few such users. Likely the reasons that motivated this feature apply to mobile as well, though perhaps with a different cutoff given different space considerations. We've intentionally defined the API specification and UI label so that clients can implement this setting in a way that makes sense.

In particular, while the web app rule is currently "up to 3 users", it's possible for mobile the correct number will be 1 or 2; I suppose we may want to tweak the API documentation to make clear the client should decide based on what is best.  (Also, we might change web to have the number vary with screen width down the line).

**Comment by gnprice** [comment]
The back end of this is now merged. The web front end is test-deployed on chat.zulip.org but not yet merged.
