### ISSUE TITLE
Respect unread message status from "mark as unread" in webapp

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5361]
In zulip/zulip#2676, we are implementing a "mark message as unread" option.

When a message is marked as unread in the webapp, we should make sure it appears as unread in the mobile app as well.

**Comment by gnprice** [comment]
(The server side of the feature was merged a few months ago as https://github.com/zulip/zulip/pull/21252 , after the API feedback we got from Wesley's #4790. The web/desktop client side is still pending, or at least the client UI for actually marking things unread is still pending, but having the server side means the API is committed and makes it possible to merge client implementations.)
