### ISSUE TITLE
Support unmuted topics in muted streams

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5362]
In https://github.com/zulip/zulip/issues/2517, we are implementing an option to make a topic inside a muted stream as _unmuted_.

In this case, we should treat the topic as unmuted in the mobile app as well. This includes:

- [ ]  Showing the topic alongside other unmuted topics in All messages and the inbox view
- [ ] @-mention notifications
- [ ] Ideally matching the webapp UI for how the topic is displayed in streams, which likely means:
   - For muted streams, replacing the stream unread count with the unread count total for the unmuted topics in that stream, if there are any such unreads.
   - In muted streams, sorting unmuted topics at the top in the stream topic view.

Note that because the feature has not been completed and the webapp UX has not been tested, details of the webapp UI may change.

**Comment by gnprice** [comment]
From that zulip/zulip thread, it looks like we don't yet have a prototype implementation for the server side, so this isn't ripe to actually build until we do.

However, there is zulip/zulip#21251, which makes a preparatory change to the API. Making that change (and clients moving over to use it) doesn't yet cause any change to user-visible behavior; but it reorganizes how we represent muting a topic, in a way that we'll use as a basis for adding the feature of unmuting a topic. So the thing that is ripe for us to do now on mobile is to implement our side of that API change. I'll file an issue for that and pick it up.

**Comment by gnprice** [comment]
Added "blocked on other work" because this blocks on at least a prototype of a backend implementation. Removed "webapp parity" because this is a feature that doesn't yet exist on web (though as "server release goal" indicates, it's one we hope to have on web pretty soon.)

**Comment by chrisbobbe** [comment]
#5382 is for using the new API.

**Comment by gnprice** [comment]
Relabeling because the server-side implementation has landed: https://github.com/zulip/zulip/pull/24236 and we're again hoping to ship this feature in general sometime not too far in the future.
