### ISSUE TITLE
Show selected custom profile fields in user profile

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5363]
In zulip/zulip#21215, we are adding an organization-wide option to show a small number of custom fields in the user profile popover.

We should show the selected fields in user profiles in the mobile app as well.

- The fields can be shown just below the user's name, in the order selected in the settings.
- The name of each field should also be shown.

Note that all field types other than "Long text" or "Person" may be selected.

**Comment by chrisbobbe** [comment]
Plan discussed today:

1. Show custom profile fields at all
2. Emphasize (by ordering things?) "selected" profile fields

**Comment by gnprice** [comment]
Chat thread on the API: https://chat.zulip.org/#narrow/stream/378-api-design/topic/custom.20profile.20fields.20in.20small.20profile/near/1390650

Server (and web) prototype implementation: https://github.com/zulip/zulip/pull/21588

**Comment by gnprice** [comment]
After thinking about the UI of this for a bit, I think the right solution may be to pretty much leave it alone. (Now that we show custom profile fields at all, #2900.) Perhaps reorder the selected fields to the top of the list, if they aren't already, but no more than that.

The main relevant difference from the web app is that in mobile, when we're showing a user's profile at all, we're now showing their full list of custom profile fields. It looks like this:
![Screenshot_1655147565](https://user-images.githubusercontent.com/28173/173427497-f498ed30-57a4-4c67-b912-b01b52f9295f.png)
So unless the screen is very short, the first few custom profile fields will already be there with no scrolling or further interaction.

The most natural way we could bring selected fields further up would be to put them in amongst the items that go above them now: above the user's local time, and perhaps their presence state and their user status.  Then we'd also give the fields that larger text size, and horizontal centering.

But then we'd probably also want to drop the label. That's what the prototype web implementation #21588 does, according to its one screenshot of the display:
![image](https://user-images.githubusercontent.com/28173/173428839-5f1200e5-a4ac-4b9a-904a-fb2afdd67497.png)
And here, having the field label in that big font size feels like it'd make that part of the screen awfully wordy.

Then:
* I'm not sure the change would actually have the effect of making the fields more conspicuous -- it could make them less so. They'd blend in amongst the "Active now" and "Local time" boilerplate.
* If the reader isn't quite sure what a field means from seeing its value, and wants to see its label, there'd no longer be anywhere in the UI for them to find that. (Unless we keep the field, redundantly, in the main list of fields below.) On web, they can "View full profile". But on mobile, this screen already is the full profile.

---

I don't totally love the design of this screen in general. Even before #2900 / #5398:
* The presence dot, plus status emoji and text, plus presence text like "Active now", feels overlapping and incoherent. (Though that's in large part an issue of the Zulip presence system in general.)
* The local time feels over-emphasized.

And then more recently, I don't feel like the design I added in #5398 for custom profile fields coheres super well with the rest of this design.

So this screen will probably be a good target for redesigning at some point, and a new design might well have an appropriate place to put the selected fields that's distinct from the other custom profile fields. But in this screen as it is, I think the best place for them is just at the top of the list of custom profile fields.

**Comment by alya** [comment]
Thanks for the detailed write-up @gnprice !

We plan to change the web UI to make all the fields left-aligned: https://github.com/zulip/zulip/pull/21465

![image](https://user-images.githubusercontent.com/2090066/175425265-0ecb068c-cc7d-4cef-8c2d-d2203f21739f.png)

It might now look great on mobile, since there the avatar doesn't take up the entire width of the window.

**Comment by alya** [comment]
On mobile, ordering the selected fields above all the other custom fields, with no other special indication, sounds like a fine solution for now.

**Comment by gnprice** [comment]
> On mobile, ordering the selected fields above all the other custom fields, with no other special indication, sounds like a fine solution for now.

Great, thanks for the feedback!



> We plan to change the web UI to make all the fields left-aligned: [zulip/zulip#21465](https://github.com/zulip/zulip/pull/21465)

Interesting, good to know.


> The equivalent change might not look great on mobile, though, since there the avatar doesn't take up the entire width of the window.

Yeah.

We could do it by left-aligning to a box (even an invisible one) that hugs the width of the avatar… but then I think we'd want to limit the text's width on the right as well as the left, as it'd look ragged if the person's name stuck out on just one side. But wrapping their name would be likely not to look good either.

And then I think the key difference in design that's reflected there is in the ratio of the font size to the avatar size. You can roughly quantify that difference by looking at the lines "11:46 PM Local time" vs. "12:10 PM Local time" in the screenshots above: in web, it's less than half the width of the avatar, while in mobile, it looks to be over 90% of the width of the avatar.

That means that someone's name, or their status text, can easily run to more than the width of the avatar in mobile. Which looks fine when center-aligned and extending out both sides, but I think would not look so good either left-aligned and sticking out to the right, or left-aligned and wrapping.

It's possible we should make this text smaller in mobile. But the text in that popover in web definitely feels too small to me -- at least for key information like the person's name. So I wouldn't be eager to just copy that.

(I also feel like cutting off the person's name with an ellipsis at the length of "Othello, the Moor of Ve…" isn't great either, FWIW; plenty of people's names are longer than that.)

**Comment by alya** [comment]
Mm, yeah, good points.

We may need to think more about long names in the web UI. I think we tried wrapping, but it didn't look great, which is why we went with using the tooltip to show the full name.

**Comment by gnprice** [comment]
> We may need to think more about long names in the web UI. I think we tried wrapping, but it didn't look great

Yeah. One direction would be to get the status disk and @ and envelope icons out of that row (not sure where instead), so that the name can use the full width of the popover.

I think that would at least greatly reduce the fraction of people whose names don't fit on one line (and therefore end up either wrapping, or being relegated to the tooltip.) It might also make wrapping look more OK.
