### ISSUE TITLE
Make it possible to view read receipts

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5367]
In zulip/zulip#3618 / https://github.com/zulip/zulip/pull/18935, we're making it possible to view read receipts in the webapp. We should add an option to the long-press message menu to make this possible on mobile as well.

This feature should of course respect the user privacy setting for whether to allow others to view read receipts from them. Where possible, it should follow the webapp design in terms of headings, sorting, etc.

**Comment by timabbott** [comment]
Just as a note on the privacy setting -- that's implemented server-side, so there should be nothing the app needs to do there. (Specifically, the server will just not send the client information about readers who have disabled sharing read receipts).
