### ISSUE TITLE
Show email address on a user's profile

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5400]
Each Zulip user has an email address associated with their account, which [depending on settings](https://zulip.com/help/restrict-visibility-of-email-addresses) may be visible to other users.

We should display the user's email address, when we have it, on their profile screen -- the one you get to on long-pressing their name or avatar where they sent a message, or from the "info" icon on a PM thread with them. (In the code this is currently `src/account-info/AccountDetailsScreen.js`.)

When doing so, we should avoid showing an email address that's actually just one of the fake placeholder emails Zulip generates when the user's email is hidden -- much like #4889.

Thanks to @Alt37 for mentioning this at https://github.com/zulip/zulip-mobile/pull/5398#issuecomment-1146783907 .

**Comment by daleshort** [comment]
Hi - I'm interested in claiming this issue.  I can put forward some options tomorrow but do you already have a strong preference on how the email should be displayed?  My initial thoughts are it could be displayed as the first item in CustomProfileFields (but mixing custom profile fields with a default one may be confusing?) or displayed as centered text beneath the users name (but really want to keep people in the mindset of 
getting to that "send a private message button" at the bottom and not emailing someone if they want to DM).

<img src="https://user-images.githubusercontent.com/11655234/193957335-895eb5f1-4f1c-4bde-9267-bd88a037184c.png" width="200" height="400" />

![Simulator Screen Shot - iPhone 13 - 2022-10-04 at 20 58 28 | width=100]()

**Comment by chrisbobbe** [comment]
Let's reserve the `CustomProfileFields` component for the [custom profile fields](https://zulip.com/help/add-custom-profile-fields) feature.

**Comment by daleshort** [comment]
I realized the easiest way to answer my own question was to look at how the other zulip platforms handle it.  I'll make it match the desktop client and just put it beneath the name.

![Screen Shot 2022-10-05 at 6 36 49 PM](https://user-images.githubusercontent.com/11655234/194176528-0bc8d673-54b6-409b-b764-c62358f68470.png)

**Comment by daleshort** [comment]
Sucess!
![Simulator Screen Shot - iPhone 13 - 2022-10-05 at 21 40 50](https://user-images.githubusercontent.com/11655234/194195460-c799d18d-ef66-4a3c-854b-b2df86ef6c3f.png)

**Comment by daleshort** [comment]
And here it is on a server with an admin only visibility policy
![Simulator Screen Shot - iPhone 13 - 2022-10-05 at 21 44 14](https://user-images.githubusercontent.com/11655234/194195801-19e0e2cc-6487-45b3-9038-2c9e9159c7b4.png)

**Comment by daleshort** [comment]
I have submitted PR #5515 for this. 

Per #4889 the email address is not displayed if email address visibility policy is not set to "everyone"

**Comment by daleshort** [comment]
I'm having an error on the CI test but I think I have this fixed.

**Comment by alya** [comment]
Thanks! I noticed that #5515 is the PR, but appears to be closed. Let's make sure we have an open PR where we can discuss the details. Thanks!

**Comment by daleshort** [comment]
Oops you weren’t supposed to see that PR yet. 😉yeah it got late last night and I didn’t know I could put the PR back to Work In Progress so I closed it since I wanted to squash the commits and look at the CI tests tonight.

**Comment by alya** [comment]
Got it. I just think a PR or the [development community](https://zulip.com/development-community/) will be better for discussing the UI than the issue thread. Thanks!

**Comment by daleshort** [comment]
PR #5515 is ready
