### ISSUE TITLE
Move "All streams" link below subscribed streams

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5424]
At present, the Streams screen has two tabs -- "Subscribed", and "All streams".

However, in the mobile app, the Subscribed tab is much more commonly useful than the "All streams" tab.

We should:

1. Replace the tab navigation at the top with a single "Streams" heading. Only subscribed streams will be shown.
2. Add an "All streams" link at the bottom that takes the user to the view that shows both subscribed and unsubscribed streams. (Title bar: "All streams")

[CZO discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/UI.20redesign/near/1395254)

**Comment by gnprice** [comment]
As a quick pointer: the existing code for these screens lives in `src/main/StreamTabsScreen.js` and the two components `SubscriptionsCard` and `StreamListCard` that it invokes.
