### ISSUE TITLE
Add space at the bottom of user profile view

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5431]
At present, we don't leave any space below the "Send private message" button in the user profile view when the screen is full. It would be better to allow the user to scroll up further.

![Screen Shot 2022-06-28 at 5 15 22 PM](https://user-images.githubusercontent.com/2090066/176325130-6822215f-15a4-4951-b81c-325e4f475faf.png)

Adding some bottom margin on that button, like 8px or 16px, should solve the problem nicely. Posting a couple of screenshots on the [CZO discussion thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/space.20below.20profile.3F/near/1398051) for this issue would be a good start.

**Comment by chrisbobbe** [comment]
Thanks, @olof-sky! I've just assigned this issue to you.

**Comment by olof-sky** [comment]
I couldn't get the setup done correctly, other people had same issues but the solutions didn't fix anything for me. I think It's better to reassign this to someone else. @chrisbobbe

**Comment by chrisbobbe** [comment]
OK! I'm sorry that the development environment setup didn't work for you, and I'm curious what went wrong. It's possible that the answer could help us improve our setup documentation.

Thanks for trying, and we're always available to help in the [Zulip development community](https://zulip.com/development-community/) if you decide to try the setup again.

**Comment by olof-sky** [comment]
I might post the issue in the community later, maybe someone have a clue on what went wrong. Would be nice to help out with the development! 

I'll comment here again and take the issue if i get it to work properly.

**Comment by shram-laabh** [comment]
Hi Alya, Chris,
 I've raised PR to address this issue. 
I've tested the same on my end on ios-simulator.
I'm not aware if any other tests are needed.

Kindly help me with review.

**Comment by shram-laabh** [comment]
@zulipbot claim
