### ISSUE TITLE
Replace "Unavailable" status with "Invisible" mode 

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5445]
To align with the removal/replacement of the "Unavailable" status in the web app in https://github.com/zulip/zulip/issues/21178, we should replace the "Set yourself to away" option in the user's personal profile with an "Invisible mode" toggle. This toggle should control whether or not the user's presence is [being shared](https://chat.zulip.org/help/status-and-availability#disable-updating-availability).

**Comment by alya** [comment]
This issue is ready to be worked on; @laurynmm is planning on picking up the corresponding webapp issue.

**Comment by alya** [comment]
CZO discussion regarding the migration process: https://chat.zulip.org/#narrow/stream/2-general/topic/.22unavailable.22.20status/near/1431122

**Comment by alya** [comment]
The server/webapp work on this issue has been completed! API documentation is up to date.

**Comment by chrisbobbe** [comment]
Great! 🙂 I've posted some questions on CZO [here](https://chat.zulip.org/#narrow/stream/2-general/topic/.22unavailable.22.20status/near/1454517).
