### ISSUE TITLE
Unexpected behaviour when device is rotated.

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#548]
![18254374_788806757979801_600287718_n](https://cloud.githubusercontent.com/assets/18511177/25597010/f0f0fa0e-2ee9-11e7-9d94-d861461cd897.gif)

I think it is due to the drawers. Will try by using native drawer and react navigation drawer, still it persists or not.

**Comment by borisyankov** [comment]
I think the Drawer component had something to do with it.

**Comment by vishwesh3** [comment]
Fixed by react-navigation and new drawers.
