### ISSUE TITLE
Create a "Users"  panel

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5495]
In preparation for the mobile app redesign, we should create a "Users" panel, similar to the right sidebar of the webapp.

Heading: Users
Icon: The people icon currently used for PMs. The PMs screen should use an envelope icon instead. This icon should be added to the bottom shortcut bar, to the right of PMs.

- Following the webapp, users should be sorted by availability, and alphabetically within each availability level.
- We should at least show all active/idle users. The webapp hides some inactive users (but shows them when doin a search); we can do something similar if it's needed for performance reasons.
- Clicking on a user should open their profile.
- The screen should have a search, but this can be a follow-up if needed.

**Comment by manila** [comment]
@zulipbot assign

**Comment by manila** [comment]
@zulipbot claim

**Comment by Seundede** [comment]
@alya can I work on this?

**Comment by alya** [comment]
@Seundede Sure, you can start by reviewing the open PR #5506 and leaving suggestions. Thanks!

**Comment by alya** [comment]
Closing in favor of #5512.
