### ISSUE TITLE
Reason for TaggedView and AnchorScrollView

### ISSUE THREAD

**Issue by sapkra** [zulip/zulip-mobile#552]
What's the specific reason to use native components for the scroll view?
The native components are TaggedView and AnchorScrollView.

**Comment by borisyankov** [comment]
There are few features that the standard ScrollView did not support.
AnchorScrollView is based on ScrollView, but allows us to keep the scroll position as we update the contents. TaggedView allows us to assign some data to these Views.

It is possible that we switch to the new components FlatList and ScrollList, if they fit our requirements better, or if it is easy to modify them to fit the requirements.

**Comment by sapkra** [comment]
I will try to replace it if these reasons are the only reasons.

**Comment by borisyankov** [comment]
I have prototyped it with a SectionList but it still seems not polished enough.
Replacing it is not a simple task and is also not urgent.
There are many other interesting things one can work on. Have a look at all the issues that are not assigned to anyone.

**Comment by sapkra** [comment]
I'm working on something special. For this I need to remove all Native Components. I'll show you the result when it's done. :)

**Comment by borisyankov** [comment]
Have fun. Just consider that the more a thing is special, the less likely it is to be a good idea 🍡

**Comment by sapkra** [comment]
Yeah right, that's mostly true. ^^
Twitter also works on the same special thing. It's pretty crazy, but a good idea. ;)
