### ISSUE TITLE
Messages sent once get received multiple times.

### ISSUE THREAD

**Issue by shreyanjoshi** [zulip/zulip-mobile#5525]
In group chats, the receivers are getting the same sent messages repeated for some reason. Please fix this!

**Comment by alya** [comment]
@shreyanjoshi Could you please provide more details? Is everyone seeing the message multiple times? Is it possible the sender has a bad connection when this happens (which is a known issue)?

**Comment by gnprice** [comment]
Closing because this report won't be actionable without more details.

FWIW it sounds likely to be another case of #2374. That's among the symptoms of #3881.
