### ISSUE TITLE
Show user role in profile

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5534]
In the webapp, the user's profile includes their role in the organization (admin, member, etc.). It would be helpful to show this in the mobile app as well.

Just below the email address would probably be a good placement, and would be consistent with the webapp:

![Screen Shot 2022-11-04 at 1 56 24 PM](https://user-images.githubusercontent.com/2090066/200073326-46723587-7991-411d-98cf-be6fdf056321.png)

`/help/view-someones-profile` should be updated accordingly when this change is made.

**Comment by niranjana1997** [comment]
Can I please do this?

**Comment by BrandonNgoranNtam** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by alya** [comment]
@BrandonNgoranNtam please post a comment describing your proposed approach when you're ready. I can assign the issue to you once you [have a rough plan](https://zulip.readthedocs.io/en/latest/overview/contributing.html#picking-an-issue-to-work-on). Thanks!

**Comment by ABHINAV-JHA-27** [comment]
Hey @alya, I would like to work on the issue.

**Comment by BrandonNgoranNtam** [comment]
Sorry for the late response! My plan is to update the getOwnUserRole() that has already been created in the permissionSelectors.js file and display its value in the ProfileScreen.js and AccountDetails.js files. I already have a working version of this feature but I'm still working on the finishing touches because right now, my method returns a String which might not be ideal when it comes to translation.

**Comment by BrandonNgoranNtam** [comment]
My new method returns a String value of the current user's role (Owner, Admin, Moderator, Member and Guest)

**Comment by alya** [comment]
@chrisbobbe @gnprice In case you have any comments on the proposed approach.

**Comment by BrandonNgoranNtam** [comment]
Hello @chrisbobbe, my PR is almost finished, but I have a question. I've asked it in the Zulip #mobile stream, but I will ask it again. 

10:30 AM

I was wondering how to proceed with translating the role into different languages. I used the TranslationContext to be able to translate the role into other languages automatically. For example, if the user's role is a Member, my implementation shows "UNTRANSLATED-Member-UNTRANSLATED" in the app. After some research, I found the string translation folder in the project (zulip-mobile/static/translations) which contains multiple JSON files in different languages to help translate strings in the app. I was wondering if I had to manually translate all 5 possible roles (Owner, Moderator, Admin, Member, Guest) in their respective languages using Google Translate, for example, to have the correct translation in every language or is there another way to proceed? To test my theory, I added the French and English translations to the messages_fr.json and messages_en_GB.json files respectively and I got the appropriate outputs in the app.

Thank you in advance for your help!

**Comment by BrandonNgoranNtam** [comment]
Here is some screenshots of what I get in English, French and Spanish (not translated) : 
![French](https://user-images.githubusercontent.com/62793833/203024075-72bacdcf-dcdb-408b-94ed-15ceffdac35a.jpg)
![English](https://user-images.githubusercontent.com/62793833/203024079-fe704752-42bb-4f1a-a9e4-28fb65099ad0.jpg)
![Spanish](https://user-images.githubusercontent.com/62793833/203024085-5d3df87f-d6f6-46ee-99f3-e1f958dd945d.jpg)

**Comment by chrisbobbe** [comment]
Thanks! I've answered your translation-workflow question on chat.zulip.org, [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/translation/near/1468091).

**Comment by BrandonNgoranNtam** [comment]
Hello, @gnprice and @chrisbobbe,

I submitted a pull request for this issue 2 weeks ago and I was wondering if you could review it for me. I applied all the changes that @chrisbobbe requested. 

If you have any questions, don't hesitate to ask me!

**Comment by TusharMinche** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by BrandonNgoranNtam** [comment]
I'm currently working on this issue unfortunately. I have to redo one commit before completing this issue which I will do soon!

**Comment by TusharMinche** [comment]
Okay. Do you know any other good first issue for me to start contributing.
