### ISSUE TITLE
Wrong french translation for the streams privacy settings

### ISSUE THREAD

**Issue by Tignus** [zulip/zulip-mobile#5555]
When you edit a stream privacy settings, one label and one description are wrong.

Original text in the [french translation file](https://github.com/zulip/zulip-mobile/blob/main/static/translations/messages_fr.json) (mistakes in bold italic) :

> "Private, shared history": "Privé, historique **_protégé_**",
   "Must be invited by a subscriber; new subscribers can view complete message history; hidden from non-administrator users": "Doit être invité par un abonné; les nouveaux abonnés peuvent afficher l'historique complet des messages; caché aux utilisateurs non administrateurs",
   "Private, protected history": "Privé, historique protégé",
   "Must be invited by a subscriber; new subscribers can only see messages sent after they join; hidden from non-administrator users": "Doit être invité par un abonné; les nouveaux abonnés **_ne peuvent voir les messages envoyés qu'après leur inscription_**; caché aux utilisateurs non administrateurs",

- The label is juste plain wrong copy/paste and should be "historique partagé"
- The description is misleading because a litteral translation french to english would be "new subscribers can only see previously sent message (as in, complete history) after they join" which is kinda nonsens and how a shared history works, not the protected one.

On a side note, but my english is not perfect at all, I believe a better translation of "protected history" in english would be "historique limité" (as in limited scope).

Here is my proposed fix in case someone just wants to copy/paste it into the file :

  "Private, shared history": "Privé, historique partagé",
  "Must be invited by a subscriber; new subscribers can view complete message history; hidden from non-administrator users": "Doit être invité par un abonné; les nouveaux abonnés peuvent afficher l'historique complet des messages; caché aux utilisateurs non administrateurs",
  "Private, protected history": "Privé, historique limité",
  "Must be invited by a subscriber; new subscribers can only see messages sent after they join; hidden from non-administrator users": "Doit être invité par un abonné; les nouveaux abonnés peuvent voir uniquement les messages envoyés après leur inscription; caché aux utilisateurs non administrateurs",

**Comment by alya** [comment]
Thanks for those notes, @Tignus !

Zulip translations are managed via Transifex, and we'd love to have your contributions there. Please see https://zulip.readthedocs.io/en/latest/translating/translating.html for instructions on how to get started.

**Comment by chrisbobbe** [comment]
Further discussion on CZO [here](https://chat.zulip.org/#narrow/stream/371-translation.2Ffr/topic/contributing/near/1465563).

**Comment by Tignus** [comment]
Thanks @Plankter for fixing this !
