### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [zulip/zulip-mobile#5563]
...since we build reanimated first and we hit this issue: https://github.com/facebook/react-native/issues/35210

I've hacked around it by bumping react-native to 0.67.5: https://gitlab.com/fdroid/fdroiddata/-/commit/4a750ce2145dd4773092ed3ac551e59d47dccdb3 _(based on https://github.com/laurent22/joplin/pull/7307/files)_ 

Can you do this update project wide instead?

**Comment by licaon-kter** [comment]
I could.

What I don't know is, where is this hash coming from at the end of .tgz: https://github.com/zulip/zulip-mobile/blob/main/yarn.lock#L13512 ?

**Comment by licaon-kter** [comment]
Google Services sneaked in :( 
https://github.com/zulip/zulip-mobile/commit/0f6cf399b85fe46bc1118c0f1395b0b926cae682

**Comment by gnprice** [comment]
> Google Services sneaked in :(
> ref: [0f6cf39](https://github.com/zulip/zulip-mobile/commit/0f6cf399b85fe46bc1118c0f1395b0b926cae682)

Nothing snuck in. We've been quite clear all along that we use Google Play Services for getting notifications. This is part of that.

What happened is that the way you chose to make an F-Droid build involves some sed scripts that depend on the exact details of our source code. We never promised that those details would stay the same. In fact, I specifically warned you that they would probably change, and that your approach was likely to break: https://github.com/zulip/zulip-mobile/issues/1270#issuecomment-1218619026
> Just to make sure we have a shared set of expectations: there's a lot of stuff in that prebuild recipe that we can't guarantee will keep working. It's entirely likely that some of that recipe will break in the future.

If you have specific questions, we can try to help. But this isn't the right tracker for a build failure in the F-Droid script, so I'm closing this issue for now. If you have a specific question to ask, just reply (or feel free to open a new issue) and I can reopen.

**Comment by licaon-kter** [comment]
I guess I forgot what the workflow is for this app. My bad.

**Comment by eighthave** [comment]
How about making an `fdroid` build flavor?  That works well for lots of other apps in a similar boat.

**Comment by gnprice** [comment]
> How about making an `fdroid` build flavor? That works well for lots of other apps in a similar boat.

Sure, we'd be open to a PR for that. Here's previous discussion of what it would look like:
https://github.com/zulip/zulip-mobile/issues/1270#issuecomment-1145476504
