### ISSUE TITLE
Feature parity with the native Android app

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#558]
- [x] notification support
- [x] starring messages #706
- [ ] message editing #402
- [ ] lightbox for viewing images #473
- [ ] create a group chat functionality #546

**Comment by vishwesh3** [comment]
one more: - update read status (mark message as read). As of now on scroll, we are returning. 
https://github.com/zulip/zulip-mobile/blob/master/src/chat/Chat.js#L19
