### ISSUE TITLE
"Mark all as read" button clears client-side view of other message flags

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5596]
(Marking P1 because this came up during work to have Flow check flagsReducer-test.js, toward #5102, disallow ancient servers.)

To reproduce:

- Go to the "All messages" view
- Star a message
- Tap "Mark all as read"
- See that the starred message's "Starred" tag disappears
- (You can verify with a different client that the message is still actually starred)

What's going on?

Well, when we generate a new flags state on a mark-all-as-read event, we build the state from the initial (blank) state, not the current state. See that we pass `initialState` to `addFlagsForMessages`, here:

```js
const eventUpdateMessageFlags = (state, action) => {
  if (action.all) {
    if (action.op === 'add') {
      return addFlagsForMessages(initialState, Object.keys(action.allMessages).map(Number), [
        action.flag,
      ]);
    }
```

@gnprice, should we be passing `state` there instead of `initialState`?

**Comment by gnprice** [comment]
> @gnprice, should we be passing `state` there instead of `initialState`?

Seems like it, yeah.

Also we clearly should have better tests on this file.

**Comment by chrisbobbe** [comment]
It looks like it was `initialState` since the feature to handle "mark all as read" was added, in 57b9e3481b5f32a0052a970340f1fbf28ffd2bee, and I don't see an explanation for the `initialState`.
