### ISSUE TITLE
"Mark all as read" appears to mark all as _unread_

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5597]
(Marking P1 because this came up during work to have Flow check flagsReducer-test.js, toward https://github.com/zulip/zulip-mobile/issues/5102, disallow ancient servers.)

To reproduce:

- Arrange to have just a few unreads in the "All messages" view, and go to that view
- Tap "Mark all as read"
- See that the unread marker doesn't disappear from the unread messages in the list
- See also that an unread marker *appears* on all the other loaded messages in the list

As long as the API request succeeds, the server does actually mark the messages as read. So what's going on?

Well, we have this `Object.keys` in flagsReducer.js:

```js
const eventUpdateMessageFlags = (state, action) => {
  if (action.all) {
    if (action.op === 'add') {
      return addFlagsForMessages(initialState, Object.keys(action.allMessages).map(Number), [
        action.flag,
      ]);
    }
```

But note that:
- `allMessages` is a `MessagesState` value, so it's an `Immutable.Map<number, Message>`.
- If you `Object.keys` one of those, then you get… `['size', '_root', '__ownerID', '__hash', '__altered']`. _That's_ not [how you're supposed get keys from an Immutable.Map](https://immutable-js.com/docs/v4.1.0/Map/#keys()). 😛 (By the way, did you know that https://immutable-js.com/ sets up the dev-tools console as an `Immutable` playground?)
- We map those string keys through `Number`, giving `[NaN, NaN, NaN, NaN, NaN]`.
- We wipe any data in the flags state (see the `initialState` in the quoted code above, and see #5596)… but then, when we _mean_ to fill in the IDs of the messages you've just marked as read, we instead put an object with `NaN: true` as `state.read`.

**Comment by gnprice** [comment]
Yikes.

Just to highlight this, though (and to make sure I understand correctly): *appears* is a key word in this title, right? That is, what actually happens on the server, as seen by other clients (and as seen eventually by the same client) is correct. So definitely a bug we should make sure to fix, but the effects aren't catastrophic like they seem at first glance.

**Comment by chrisbobbe** [comment]
Yes, that's right.

**Comment by gnprice** [comment]
One root cause here is that the tests for this reducer, in `flagsReducer-test.js`, are one of the few remaining files (all of them test files) that we don't have Flow type-checking for us. In fact it's the largest such remaining file:
```
$ git grep -L '@flow' 'src/*.js' | xargs wc -l | sort -rn
 1857 total
  349 src/chat/__tests__/flagsReducer-test.js
  303 src/user-groups/__tests__/userGroupsReducer-test.js
  233 src/presence/__tests__/presenceReducer-test.js
  184 src/topics/__tests__/topicsReducer-test.js
[… 11 more …]
```

If we'd had type-checking on those tests, Flow would have pointed out that the test data needed to change when we changed the definition of `MessagesState`, which would have alerted us that `flagsReducer` was consuming data of that type and given us a better chance to see we needed to update that logic.

**Comment by chrisbobbe** [comment]
Yeah, I discovered this (and #5596) while working to get `flagsReducer-test.js` type-checked.
