### ISSUE TITLE
local echo when sending messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#562]
I've gotten some feedback from users that they find it frustrating when on a poor network that they can't start typing a new message while a previous message is waiting to send.  

We should probably implement some sort of more advance setup for handling outgoing messages.

We have a local echo mechanism from the webapp codebase that we can use for doing a lot of the book-keeping here.  I can imagine doing this in a few phases:

(1) First, we just implement a feature where after you hit the send button, the (raw) message body goes into the message feed, maybe with a loading indicator on it or something to make clear it hasn't sent successfully yet.  Might need some sort of outgoing queue or other storage mechanism to make sure the message sends eventually.

We can use the same `local_id` mechanism from the web app's `static/js/echo.js` to be able to keep track of the to-be-sent message and replace its entry in the message feeds once it's successfully sent.  

(2) We do proper rendering of the locally echoed message, presumably using the `marked.js` logic from the webapp.

I think it's worth doing (1) even without completing (2), since not being able to start typing a next message is really annoying, though we'll eventually do both.

**Comment by borisyankov** [comment]
(1) is a must, I agree. Skype has a rather sophisticated implementation of that part. If a message fails there is a button to retry, though maybe we should just be retrying ourselves. Also while a message is being sent a small spinner is shown for each unsent message.

(2) even if implemented is going to be a half measure anyways, as I expect many things like site preview and other features to cause a message update anyways.

**Comment by timabbott** [comment]
Yep, agreed.  https://zulip.readthedocs.io/en/latest/markdown.html is relevant BTW.

**Comment by borisyankov** [comment]
Closing as implemented.
