### ISSUE TITLE
No messages screen before loading placeholder in chat page

### ISSUE THREAD

**Issue by anshuman-8** [zulip/zulip-mobile#5636]
In every chat page, the "No messages" text displays for a second before showing a loading placeholder.

For a better experience, the chat page should start with a loading placeholder and then continue to show no messages or all chats.

"No messages" text before placeholder
<img src="https://user-images.githubusercontent.com/90995338/211165969-4efc3378-8f7c-4f4d-9c47-decf379b9d5d.jpg" width="300" alt="No messages">

<img src="https://user-images.githubusercontent.com/90995338/211165965-709ecf6e-9acb-448b-986a-3908e2a5626c.jpg" width="300" alt="Loading placeholder">

**Comment by alya** [comment]
Thanks for the report! I haven't noticed this myself, but I agree that we should not show "No messages" before the loading screen.

@anshuman-8  assigning this issue to you, since you mentioned that you'd like to take it on.

**Comment by chrisbobbe** [comment]
Thanks for the report and those screenshots, @anshuman-8!

This sounds like #5152; please read the discussion there on the path to your fix. I'll close this as a duplicate and assign #5152 to you, but please let me know if you think this actually a separate issue that should stay open. 🙂

**Comment by chrisbobbe** [comment]
Oddly, I don't seem to be able to assign you on that other issue. Perhaps GitHub will let me do so if you leave a brief comment there, so it knows you're part of the discussion?
