### ISSUE TITLE
App Store thinks we support iOS 12 when we don't

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5672]
We recently bumped our minimum version of iOS to 14: 783e56b236c82e275fa20250ba5ec0f53c922f98 / #5627.

But a user with iOS 12 (and an old iPhone model that can't update past that) nevertheless ended up with the upgrade to the newer Zulip app that had dropped that support: #5670 

Looking [on the App Store](https://apps.apple.com/us/app/zulip/id1203036395), it says we support iOS 12:
![image](https://user-images.githubusercontent.com/28173/222826156-d742b875-286e-40d8-8b0d-7823766e179b.png)

So there's something wrong in our metadata on the App Store, and potentially in the uploaded artifact. We should fix that.

**Comment by chrisbobbe** [comment]
Hmm, interesting! I was also surprised to see iOS 12 in #5627, but with the user's wording of "manually installed an update" I assumed our threshold of 14 was working reasonably and they'd just found a way around it. I'll investigate.

**Comment by DanWaLes** [comment]
by 'manually installed an update' this is how i did it
i disable automatic app store updates. i also use the Apple Screen Time feature to disable installing apps.
to get the update i allowed installing apps again then went to the Updates part of the App Store and dragged my finger down the screen to cause checking for updates. i then tapped Update All
