### ISSUE TITLE
SettingsScreen: Make rows consistent in having (or not having) an icon

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5687]
Currently, some rows in the settings screen have icons, and some don't. Probably we should either remove all the icons, or add icons for the rows that don't have them. Screenshot:

<img width=400 src="https://user-images.githubusercontent.com/22248748/225412980-b7a46c4d-305b-4bb9-997c-4899445ba140.png" />

cc @terpimost @alya @gnprice

**Comment by saadkhan011** [comment]
Hi chrisbobbe,
           I want to work on this issue can you assign me please.

**Comment by chrisbobbe** [comment]
We haven't yet decided whether to keep or remove the icons, so this isn't yet ready to be worked on.

**Comment by terpimost** [comment]
I don't think the current state of things is a problem. In the new redesign we will have icons but we also might not have them. That is ok:
![image](https://user-images.githubusercontent.com/1903309/227808139-73ca9383-3474-426f-bf3d-bbf46d102bd5.png)

**Comment by gnprice** [comment]
Thanks @terpimost for the input. We'll leave this as is, then, until we get into implementing the redesign.
