### ISSUE TITLE
UI to unmute a topic in a muted stream

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5691]
This is a companion to #5362, as part of the feature zulip/zulip#2517.

Issue #5362 is for respecting the setting once a user has set it, perhaps through the web app. This issue is for offering UI to set it in the first place.

The existing UI for muting a topic, and for making a topic no longer muted, is in the topic action sheet, which you get by long-pressing on a topic. (Either on the inbox screen, or in the list of topics for a stream, or as the title in the app bar on a topic narrow's message list, or as a recipient header inside the message list.)

Probably that will be the natural place for the new UI too. Here's the UI we have planned for web (in https://github.com/zulip/zulip/issues/24243 ):
>  For topics in muted streams, replace the "Mute topic" option in the three-dot topic menu with an "Unmute topic" option, which should make the topic unmuted. For unmuted topics in muted streams, show the regular "Mute topic" option, which should specifically mark the topic as muted, as usual.

We should aim for something analogous in mobile. /cc @alya for thoughts on the desired UI.

**Comment by abdulmoiz37** [comment]
@zulipbot claim

**Comment by alya** [comment]
Yeah, using the action sheet, with the logic quoted from the web issue for what to show, sounds good to me.

**Comment by gnprice** [comment]
@abdulmoiz37 Please see our contributing guidelines. Note this issue is not labeled "help wanted".
