### ISSUE TITLE
Links to unknown/nonexistent streams open in browser, which should be futile

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-mobile#5698]
We have this TODO in src/message/messagesActions.js:

```js
    // TODO: In some cases getNarrowFromLink successfully parses the link, but
    //   finds it points somewhere we can't see: in particular, to a stream
    //   that's hidden from our user (perhaps doesn't exist.)  For those,
    //   perhaps give an error instead of falling back to opening in browser,
    //   which should be futile.
```

One way to fix this is to allow the navigation to `ChatScreen`, which will gracefully show an error message (`InvalidNarrow`) instead of crashing. So, for the link

https://chat.zulip.org/#narrow/stream/489238476928736-mobile/topic/Issue.20-.20iOS.20Notification.20Badge/near/1536060

(note fake stream ID) you would be taken to this:

<img width=400 src="https://user-images.githubusercontent.com/22248748/228400753-d48f2142-abd9-477c-9674-539273dae68d.png">

There are some visible issues with that screen (see umbrella issue #5210), but I think this is a fine approach modulo those, and still I think my preference.

Alternatively, we could prevent the navigation to `ChatScreen` and show an error dialog.

**Comment by gnprice** [comment]
Hmm. Is that screen really a better experience than the web? Given the issues with it, I'm not sure — it may just give an impression of "the app is broken", rather than "this link is broken".

**Comment by chrisbobbe** [comment]
Sure, that's reasonable. I'll change #5699 so it gives an error alert instead of opening that busted-looking screen.
