### ISSUE TITLE
Quote and reply deletes topic and moves cursor to topic 

### ISSUE THREAD

**Issue by samtuke** [zulip/zulip-mobile#5718]
Using quote and reply always results in me:
Starting to type a reply, realising it has typed it in the topic field, then having to close the onscreen key board and scroll up to see what the correct topic was and should again be, then deleting the reply I've started typing from the topic field, then typing the original correct topic again, searching and selecting in the list, then scrolling to the actual message field, then trying to remember the reply I started typing when it was wrongly entered in the topic field. Very frustrating and time wasting. Repeats about 5x daily, 6 days per week. 

Desired behaviour:
When using quote and reply: use the same topic as the quoted message by default, and start with the cursor in the message field below the quoted text. 

Thanks!

**Comment by alya** [comment]
Thanks you for the report! I expect that we'll fix this in the flutter version of the app (https://github.com/zulip/zulip-flutter).

**Comment by chrisbobbe** [comment]
Thanks for the report! I think this won't be too difficult to fix.

I think I know what's going on:

When you want to compose a new message from an interleaved stream narrow, the app isn't good at choosing a reasonable value for the topic input; in fact, it doesn't choose any value. Instead, it has a (kind of awkward) mechanism to nudge the user to specify a topic: when the user taps the message input and the topic input is empty, we auto-focus the topic input. I guess that mechanism accomplishes its purpose, but it sure is annoying when it _seems_ like the app could choose a reasonable topic for you.

I think that's what's going on here: when you do a quote-and-reply and the topic input is empty, probably you want the topic of the selected message, and the app should use that. PR coming soon. 🙂
