### ISSUE TITLE
Handle lack of permissions to move a message gracefully

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5719]
In https://github.com/zulip/zulip/issues/21739, we revamped topic editing permissions. See issue for full details, but in summary:

- Topic editing and message editing permissions are now entirely separate
- Special cases (moving one's own messages and no-topic messages) have been removed

Permissions controls:

![Screen Shot 2023-04-13 at 1 21 15 PM](https://user-images.githubusercontent.com/2090066/231874175-ea0d729b-f522-4ed7-8ce4-d611161c6df2.png)

In addition, partial moves are offered when the user does not have permissions to move all the messages they are trying to move:

![image](https://user-images.githubusercontent.com/2090066/231874508-be22a5e6-d3c0-41d5-9927-7cf05ec720e6.png)

There is some follow-on work in progress to improve the interaction for resolving topics when the user doesn't have full permissions to move all the messages in the topic. (Partial moves are not recommended in that situation.) The eventual plan (after the 7.0 release) is to handle resolve topic permissions separately (#21811). 

The above resolves a number of bugs in how the webapp handled topic moving permissions previously.

As a result of all these changes, users in some organizations may more frequently encounter a situation where they only have partial permissions to move messages in a topic.

The goals for mobile support for this work are:

- [ ] Do not move messages when the user does not have permission to do so.
- [ ] Make sure that the user is presented with a reasonable error/information when they attempt to move messages they don't have permission to move. Potential situations for this include:
   - [ ] Renaming a topic
   - [ ] Moving a topic to a different stream
   - [ ] Resolving topics

Likely outside the scope for this issue:
- Offering partial topic moves like the webapp now does
- Being very careful to not offer a topic move / resolve option any time the client knows the user won't have permissions to go through with it.

**Comment by chrisbobbe** [comment]
Does this mean the issue as described is done already? 🙂 @alya @gnprice

**Comment by alya** [comment]
Could you show a screenshot of what the user sees?

If possible, we don't want to refer to moving messages as "editing" messages. Possible terms are "move message", "move topic", "rename topic". See:

https://zulip.com/help/move-content-to-another-topic
https://zulip.com/help/move-content-to-another-stream
https://zulip.com/help/rename-a-topic

**Comment by chrisbobbe** [comment]
Sure. Here's resolving a topic, then editing a message to change its topic. In both of these examples, the alert dialog's title is chosen by us, and its body is text taken directly from the server's error response. Let me know if you'd like me to show something else too.

<img width=400 src="https://user-images.githubusercontent.com/22248748/231900922-0119e80e-6f3d-4c0f-97b5-c1865fafba64.gif"> <img width=400 src="https://user-images.githubusercontent.com/22248748/231900926-8d4fde13-15eb-4422-b649-087edc0042dd.gif">

Ah, and I think I didn't read this closely enough:

> - [ ] Renaming a topic

Mobile doesn't yet have a feature like this, covered by the https://zulip.com/help/rename-a-topic doc: you can move a single message through the edit-message UI (second screenshot above), but you can't apply a whole-topic rename in a single interaction. (Resolve/unresolve is implemented as a whole-topic rename, but that doesn't let you choose the words in the topic.)

**Comment by chrisbobbe** [comment]
(Also I notice in the first screenshot that the server's message says "move" in response to a resolve-topic request, probably as a side effect of resolve-topic being implemented as a topic rename.)

(And in the second screenshot, the server's message says "editing this message's topic" when perhaps it wants to say "moving this message" instead?)

**Comment by gnprice** [comment]
Cool. I think it looks like we're in good shape, then.

We have an existing issue #2792 for avoiding showing the "Edit message" option in the first place when the user isn't going to be able to edit the message. That issue remains open, but given that we do show the option (and don't have a "move/rename topic" option in the first place), it looks like we're covered for the recent changes in how these permissions work.

> For the edit-message screenshot, maybe we should check client-side and see if it's a message content edit, a topic move, or both, and title the dialog appropriately for each case: "Failed to edit message", "Failed to move message", "Failed to edit/move message", or something?

I think "Failed to edit message" is appropriate because the UI the user was using was one for editing the message. If we had a UI that was more for moving a message, or a UI that was for both but had more of an explicit delineation between doing one or the other or both, then it'd make sense to mirror that distinction in the error alert.

**Comment by alya** [comment]
Sure, makes sense to me. I guess we should have a period after "... has passed", but I don't super care. :) Marking this issue as resolved in any case.
