### ISSUE TITLE
Rename "private messages" to "direct messages"

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5731]
In https://github.com/zulip/zulip/pull/24224 and follow-up work, we renamed "private messages" to "direct messages" in the web app. We should do the same in the mobile app. This issue is specifically for user-facing stings.

The mobile instructions on `/help/direct-messages` and in `/help/include/send-group-dm.md` will need to be updated accordingly, either as part of this issue, or as an immediate follow-up.

**Comment by gnprice** [comment]
> This issue is specifically for user-facing strings.

Just to underline this part: let's defer any renames or other refactoring, leaving non-user-facing uses of "private" alone for now.
