### ISSUE TITLE
change navigation when trying to return after creating a PM

### ISSUE THREAD

**Issue by wilsonfurtado2000** [zulip/zulip-mobile#5737]
**How to produce it**
 Go to the page where you can create the new PM -> try to search users whom you want to PM -> click on the intended profile -> press the "previous page" icon 

**expected behaviour**
it should return back to screen where all the users are present , but it navigates to the PM page which contains our PMs

**video demonstration**

https://github.com/zulip/zulip-mobile/assets/72563697/cf4a538e-7996-4c68-95de-b605c79ce647

**Comment by gnprice** [comment]
This is intended behavior. You can think of the "New PM" screen as an interstitial where you select which PM thread you want to navigate to. Once you've done that, the interstitial has served its purpose and doesn't remain in the history stack.
