### ISSUE TITLE
Error when uploading an image from the zulip mobile application

### ISSUE THREAD

**Issue by ZulipFan** [zulip/zulip-mobile#5744]
Good night.

I need a help. Install the application and associate it to the mobile application. All good, set up perfect. The problem I have is that when I use the mobile application, and only there, I get an error to upload the image. This error does not happen to me in the desktop application. Any idea what it could be?

![imagen](https://github.com/zulip/zulip-mobile/assets/138643168/5feeb77d-6c21-4226-95e3-90e93aefff4b)

Thank you
Manuel

**Comment by chrisbobbe** [comment]
Thanks for the report, @ZulipFan!

Is the Zulip server on Zulip Cloud (does it have "zulipchat.com" in the URL)?

**Comment by chrisbobbe** [comment]
Also, do you get errors when you try to do other things, like sending a message? Or is it only when you try to upload an image?

**Comment by ZulipFan** [comment]
<img width="280" alt="Captura de pantalla 2023-07-05 a la(s) 19 32 27" src="https://github.com/zulip/zulip-mobile/assets/138643168/7f2a35de-c125-4bc6-9331-7f6e35565214">

Hello friend, I attach the version. I am using the version in my own hosting. And as I was telling you, it only happens to me in the mobile AP, in the PC AP it doesn't happen to me, nor in the web version

Thanks for any advice you can give me.

**Comment by ZulipFan** [comment]
It's just the error when I try to upload an image. All other functionalities work without problems. It happens to me both with images and with files that I want to upload.
<img width="280" alt="Captura de pantalla 2023-07-05 a la(s) 19 32 27" src="https://github.com/zulip/zulip-mobile/assets/138643168/94f601fc-92bd-4dff-a189-6e99b870b633">

I can send messages, make a link for video calls, but I can't upload files or images from the mobile AP

**Comment by chrisbobbe** [comment]
Thanks for those details! This seems like a server bug; I've started a discussion [here](https://chat.zulip.org/#narrow/stream/3-backend/topic/image-upload.20malformed.20response/near/1604634) for further debugging.

**Comment by Ajay-singh1** [comment]
I think there is a problem with the server.
