### ISSUE TITLE
Reporting of iterations by Stream and topic

### ISSUE THREAD

**Issue by ZulipFan** [zulip/zulip-mobile#5745]
Is there the possibility of being able to generate reports of the iterations that users carry out for each flow and topic? The serious idea is if you can consider adding new kpi to the reports for administrators or moderators to better understand the communication results

Thank you

**Comment by chrisbobbe** [comment]
I don't yet understand the request. Is this a feature request for the mobile apps?

**Comment by ZulipFan** [comment]
Edit and formulate the idea better
