### ISSUE TITLE
Render @topic wildcard mentions correctly when displayed in a message feed.

### ISSUE THREAD

**Issue by prakhar1144** [zulip/zulip-mobile#5746]
[CZO discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/.40topic-mention.20data-user-id.20.2326195/near/1605762)

For stream wildcard mentions (all, everyone, stream), the rendered content is:
```
<span class="user-mention" data-user-id="*">@{stream_wildcard}</span>
```
As a part of the @topic wildcard mentions project ( [#22829](https://github.com/zulip/zulip/issues/22829) ) , we have introduced `@topic`; the rendered content is:
```
<span class="topic-mention">@{topic_wildcard}</span>
```

Since we are not using `user-mention` class (and data-user-id="*" attribute), the `@topic` mention is not rendered correctly.

[#26195 (comment)](https://github.com/zulip/zulip/pull/26195)

**Comment by chrisbobbe** [comment]
Just added metadata to make this appear in the [Zulip Server 8.0 project board](https://github.com/orgs/zulip/projects/6/views/3); FYI @alya and @gnprice.
