### ISSUE TITLE
Re-enable Sentry on Android (without crashes)

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#5766]
In order to resolve the crash bug #5757, we've disabled Sentry error reporting for our Android releases. See details at https://github.com/zulip/zulip-mobile/issues/5757#issuecomment-1728692990 , and the (long) chat thread around https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.20crashes/near/1643296 .

We should re-enable Sentry so that we have error reporting again, but without the crashes.

Possible ways to do that include:
* Wait for Sentry upstream to find and release a fix. Their issue thread is https://github.com/getsentry/sentry-java/issues/2955 .
* Re-enable Sentry reporting of events that arise in our JS and Kotlin code (both those we explicitly report, and uncaught exceptions), but without enabling Sentry's native code.

  It's not clear whether this is possible; see chat discussion at https://chat.zulip.org/#narrow/stream/48-mobile/topic/Sentry.20crash.20bug/near/1644261 .

  If the price of this were that we didn't get reporting of errors that happen within native code, [that would be fine](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Sentry.20crash.20bug/near/1644279).
* Some other workaround.

**Comment by gnprice** [comment]
(#5768 is what does the disabling in `main`; we already did it for a release, v27.213, in a release branch based on v27.211.)

**Comment by darren1713** [comment]
Quickly tagging #5741 here as possibly relevant as this release is the first time my Android 14 Pixel 5 has stopped crashing every 30 seconds. It has been non-stop crashes for a few months. I'm running zulip mobile android v27.213 which is finally happy / not crashing.

**Comment by gnprice** [comment]
@darren1713 Very interesting! Thanks for that update. Glad the app is running crash-free for you again.

Just to repeat for this thread some of the context in that one: you first reported the crashes 2023-06-06, and they'd started when you upgraded to Android 14.

At that time I suppose you can't have been on the Google Play system update dated August 2023. That's interesting because it otherwise appears that this Sentry-related bug is only triggered (or only triggered frequently, at least) with that update; so perhaps that only applies to Android 13 and Android 12, and Android 14 is enough to trigger it on its own.

**Comment by chrisbobbe** [comment]
> Android 14 is enough to trigger it on its own

I think we're getting events with #5741's error output much more frequently on Android versions other than 14, than on Android 14. And in both cases, the frequency graph doesn't have the ominous-uptick shape that was characteristic of the crashes that became the focus of #5757.

- [Android 14](https://zulip.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=191284&query=Attempt+to+invoke+virtual+method+%27android.graphics.drawable.Drawable+android.graphics.drawable.Drawable%24ConstantState.newDrawable%28android.content.res.Resources%29%27+on+a+null+object+reference+os%3A%22Android+14%22&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)
- [Not Android 14](https://zulip.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=191284&query=Attempt+to+invoke+virtual+method+%27android.graphics.drawable.Drawable+android.graphics.drawable.Drawable%24ConstantState.newDrawable%28android.content.res.Resources%29%27+on+a+null+object+reference+%21os%3A%22Android+14%22&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)

(These observations came up in an [internal conversation](https://chat.zulip.org/#narrow/stream/176-mobile-core/topic/.23M5741.20Android.20NullPointerException/near/1635306) but looks like I never updated #5741 with that information, oops.)

**Comment by gnprice** [comment]
Ah thanks. I replied over on #5741, at https://github.com/zulip/zulip-mobile/issues/5741#issuecomment-1747636217 ; that's probably the thread for further discussion in that direction.

**Comment by gnprice** [comment]
The PR #5765 which fixed this was effectively reverted in commit 033a9d63d6fec7b19bed411dea122fa704f211c8. I've filed a fresh issue for trying again:
* #5782
