### ISSUE TITLE
Consider replacing the hamburger menu with the realm icon for the menu

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#578]
This is a discussion that came up with @borisyankov while writing the iOS app store description.  It might make sense to replace the hamburger with something cooler, and a good choice might be the icon for the realm (might want to improve the defaults for those, but we want to do that anyway...).

There's precedent for that UI approach in Slack's Android app, and it'd be a nice way to simplify.

**Comment by wilsonandusa** [comment]
Hi, could you give more description about "the icon for the realm"? Are you talking about changing the vertical layout into something like a grid?  Maybe I misunderstand it, but I see no major difference between the current menu and the menu in Slack's Android app.

**Comment by anurag1018** [comment]
Hello @wilsonandusa to the extent I perceive, @timabbott is referring to replacing the hamburger menu icon with the icon of the organization to which the user is currently logged in.

**Comment by borisyankov** [comment]
We no longer have a hamburger menu, so closing this as no longer relevant.
