### ISSUE TITLE
PhaseScriptExecution failed with a non-zero exit code

### ISSUE THREAD

**Issue by xgenem** [zulip/zulip-mobile#5780]
I made sure my env variables are properly configured, for bash/zsh. But nothing worked.

Also, added permissions to the script already.

```
...zulip/tools/lib/ensure-coreutils.sh: line 75: brew: command not found
This script requires GNU coreutils.

Install from upstream:
  https://www.gnu.org/software/coreutils/
or from your favorite package manager.

If you have any questions, ask in #mobile on https://chat.zulip.org/
and we'll be happy to help.
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by alya** [comment]
Please drop by the [#production help](https://chat.zulip.org/#narrow/stream/31-production-help) stream in the [Zulip development community](https://zulip.com/development-community/) to get help with your question.

**Comment by xgenem** [comment]
Forcing  us to get into the system so we can get help doesn’t really look
good. I’m dropping this.

Thanks though
