### ISSUE TITLE
Improve messaging when realm push notifications are not enabled

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5785]
There are several places in the mobile app where we communicate that a user will not receive push notifications when `realm_push_notifications_enabled` is `false`. We should improve the messaging and flows for those notifications.

## Home screen banner

- Text: "Push notifications are not enabled for {realmName}." (same for admins and non-admins)
- Buttons:
  - "Dismiss" to dismiss for 2 weeks (unless we prefer the current "Remind me later")
  - "Learn more" to:
     - Dismiss the banner for 2 weeks
     - Go to Notifications screen 

## Notice in Settings (Notifications button)
- Change text to: "Push notifications are not enabled for {realmName}."

## Notice on login screen
- Change text to: "Push notifications aren not enabled for {realmName}."
- For all situations where we warn that notifications may not be working, details button can link to https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications.

### Notices
- Just in the case of `realm_push_notifications_enabled = false`: "Push notifications are not enabled for {realmName}."

- For all situations where we warn that notifications may not be working: "View [trouble-shooting guide](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications) for mobile push notifications." 

### New setting
A switch labeled:  "Silence warnings about disabled mobile push notifications" (off by default)

If you enable the switch, the warning banner on the home screen and the notice on the login screen are turned off. (The info is still available in the settings.)

**Comment by gnprice** [comment]
Chat thread: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Feedback.20when.20server.20not.20set.20up.20for.20notifications/near/1675362

**Comment by alya** [comment]
Updated the issue with that change.

**Comment by chrisbobbe** [comment]
On the "Notifications" screen, here's what the gray-shaded per-account area currently looks like when the server hasn't enabled notifications (`realm_push_notifications_enabled` is false), vs. when there's some other problem:

| Server hasn't enabled | Some other problem |
| --- | --- |
| ![image](https://github.com/zulip/zulip-mobile/assets/22248748/85d227e3-7895-47ad-b2a7-0c0e1a129c85) | ![image](https://github.com/zulip/zulip-mobile/assets/22248748/5b836ea4-be4d-4e26-8920-d35d4f3db484) |

Quoting from the current issue description:

> ## Notifications screen
> ### Notices
> * Just in the case of `realm_push_notifications_enabled = false`: "Push notifications are not enabled for {realmName}."
> * For all situations where we warn that notifications may not be working: "View [trouble-shooting guide](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications) for mobile push notifications."
> 
> ### New setting
> A switch labeled: "Silence warnings about disabled mobile push notifications" (off by default)
> 
> If you enable the switch, the warning banner on the home screen and the notice on the login screen are turned off. (The info is still available in the settings.)

For this part—

> * Just in the case of `realm_push_notifications_enabled = false`: "Push notifications are not enabled for {realmName}."

—that's an easy change to the "not set up" row's text. When you tap the row, should it open the [troubleshooting article](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications), so you can learn what it means for push notifications to be enabled for your org?

And for the "New setting" part, probably we want that setting to only appear when the server hasn't enabled push notifications, I think.

For this other part—

> * For all situations where we warn that notifications may not be working: "View [trouble-shooting guide](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications) for mobile push notifications."

—I wonder if the change to be made is to add a link to the troubleshooting guide from the "Troubleshooting" page itself. If not, I'd like some guidance on what change we want to make to the "Notifications" screen in cases where there's a problem other than `realm_push_notifications_enabled` being false. Depending on the notification issue, the path to resolving it might be quicker if you visit the "Troubleshooting" page before reading the troubleshooting guide. (In one case, we offer a "Retry" button that could in theory fix the issue within a second of pressing it.)

**Comment by alya** [comment]
>When you tap the row, should it open the [troubleshooting article](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications), so you can learn what it means for push notifications to be enabled for your org?

I think this heading would be most appropriate when notifications are not enabled on the server:

https://zulip.com/help/mobile-notifications#enabling-push-notifications-for-self-hosted-servers

**Comment by alya** [comment]
> And for the "New setting" part, probably we want that setting to only appear when the server hasn't enabled push notifications, right?

I think the setting can always be there. There may be other reasons why users get nagged about push notifications, and they can just ignore it if they've never seen a banner.

**Comment by alya** [comment]
> I wonder if the change to be made is to add a link to the troubleshooting guide from the "Troubleshooting" page itself.

Sure, let's try that.

**Comment by chrisbobbe** [comment]
> > When you tap the row, should it open the [troubleshooting article](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications), so you can learn what it means for push notifications to be enabled for your org?
> 
> I think this heading would be most appropriate when notifications are not enabled on the server:
> 
> https://zulip.com/help/mobile-notifications#enabling-push-notifications-for-self-hosted-servers

Oh indeed, yeah. I just checked and that's actually the heading I ended up using in the PR :)
