### ISSUE TITLE
Auto complete suggestions are not being displayed outside the compose box for Android

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#579]
Android : (checked on current master as well) 
<img width="487" alt="screen shot 2017-05-12 at 10 35 31 am" src="https://cloud.githubusercontent.com/assets/12700799/25983022/37f3b186-36ff-11e7-9bf4-ff8ec57d4834.png">

Expected (iOS):
![simulator screen shot 12-may-2017 10 36 40 am](https://cloud.githubusercontent.com/assets/12700799/25983021/37ef6a0e-36ff-11e7-9dc9-d4de7eafa3bb.png)

**Comment by vishwesh3** [comment]
on it!
I tried current master, auto complete are not shown on Android.
https://drive.google.com/file/d/0BxdL5qgQdmMHbHJ0NF9SN053YlU/view
