### ISSUE TITLE
Add button to test mobile push notifications

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5796]
The server now supports test push notifications. We should make it convenient to trigger such a notification from the mobile app.

- Button: "Send a test notification"
- Placement: Notifications settings panel. I think it would make sense to put it at the top, because this button wouldn't test anything about the settings that can be configured in the rest of the notifications panel.
- Notification: 
  - Heading: Zulip test notification
  - Text: Congratulations! Zulip push notifications are working for [organization name].

**Comment by chrisbobbe** [comment]
> Placement: Notifications settings panel. I think it would make sense to put it at the top, because this button wouldn't test anything about the settings that can be configured in the rest of the notifications panel.

We do have a shaded section for things that are specific to the current account, as this button would be. If we put it in that section, it would reinforce that the button is only about one specific account. You could be logged into other accounts in the app, and you won't get the same behavior from this button as you would with a different account. (A different account usually means a different server, and you could have some servers where notifications are busted and some where they aren't.) That's helpful to be clear about.

That's also an advantage of putting the "Troubleshooting" button in that section. That button's job is similar, so it might be good to put them together, either in or out of the section.

What do you think?

| Current | Proposed |
| --- | --- |
| <img width=400 src="https://github.com/zulip/zulip-mobile/assets/22248748/e72eaefe-cb02-47ee-a616-e59e8c044768"> | <img width=400 src="https://github.com/zulip/zulip-mobile/assets/22248748/1e9b9de9-938c-4ad0-80c4-a6a69b15c3ea"> |

**Comment by chrisbobbe** [comment]
Also, is there a reason not to also add a test-notification button on the notification troubleshooting screen?

**Comment by chrisbobbe** [comment]
> Notification:
> * Heading: Zulip test notification
> * Text: Congratulations! Zulip push notifications are working for [organization name].

For iOS, the heading and text are defined in the push bouncer: https://github.com/zulip/zulip/blob/78440033dc7b7f0dbf323215def7d9c784f04ad4/zerver/lib/push_notifications.py#L1283-L1290

```python
            "title": _("Test notification"),
            "body": _("This is a test notification from {realm_uri}.").format(realm_uri=realm_uri),
```

so we would need to change it there.

I slightly prefer the more neutral "this is a test notification" text. Saying that "notifications are working" doesn't seem helpful if you're trying the button because your notifications have been severely delayed, whether or not the test notification itself arrives on time. You could also have an issue with how notifications are presented (the sound/banner/etc.), or just want to remind yourself how they're presented, and a neutral-sounding message seems appropriate for those cases too.

**Comment by alya** [comment]
> Also, is there a reason not to also add a test-notification button on the notification troubleshooting screen?

Are you thinking both that screen and the general notifications screen? That seems reasonable to me...

**Comment by alya** [comment]
Thanks for framing up all the questions!

**Comment by chrisbobbe** [comment]
> Could you start a thread on CZO to discuss the text? I was thinking of a different use case, which is an IT person who just set up a Zulip server; I guess we should consider both.

Sure! Here: https://chat.zulip.org/#narrow/stream/378-api-design/topic/.2323997.20Endpoint.20for.20test.20notification/near/1690482
