### ISSUE TITLE
On sending a new message, message list should scroll to bottom

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#581]

**Comment by timabbott** [comment]
We probably don't want to do it if it'll mark messages as read, or if you're scrolled up more than a few screens (in which case you're probably there for a reason).  Obviously should also be conditional on sending messages that will appear in the current narrow. 

But if you're close to the bottom and caught up, yeah, this should scroll you to see the thing you just sent.

**Comment by kunall17** [comment]
Done, this can be closed now!
