### ISSUE TITLE
Connection failed, The network request to *** failed (self-hosted)

### ISSUE THREAD

**Issue by jeehoonkang** [zulip/zulip-mobile#5811]
From today, connecting from Android to a self-hosted Zulip server (community plan) fails with the above message.
Connecting to the official Zulip server (*.zulipchat.com) works fine.
Connecting from iOS or the web works fine.

I wonder if anything has changed so that it affects Zulip server connectivity.

**Comment by chrisbobbe** [comment]
Hmm. What versions of the Android app and the [self-hosted Zulip server](https://zulip.com/help/view-zulip-version)? Was one or the other updated recently?

**Comment by gnprice** [comment]
In addition to those questions: the fact that the app works with zulipchat.com, and that other clients work with your server, sounds like it could potentially be a TLS/SSL issue. We've sometimes seen the Android networking stack in particular (as used by the Zulip Android app) be pickier about such things than iOS is or than some browsers are.

Is your server on the public Internet? If so, what does the SSL Labs tester say? See detailed suggestions here:
https://zulip.readthedocs.io/en/latest/production/ssl-certificates.html#testing

**Comment by gnprice** [comment]
Closing for now, since there's nothing we can do with this report pending answers to our questions above. @jeehoonkang if you're still having this issue, feel free to reply with those, and we can reopen.
