### ISSUE TITLE
ios build is not loading css/static files correctly.

### ISSUE THREAD

**Issue by knakul853** [zulip/zulip-mobile#5820]
I am building an ios build of the Zulip app, initially had an issue with all the fonts mentioned in info.plist file

```
<array>
		<string>zulip-icons.ttf</string>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>Feather.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>Zocial.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
	</array>
```
	
	after dowloading all the fonts I got the issue fixed and the character is getting parsed correctly. 
	
	but when i switch to message/dm panel the css doesn't seems to be working
	
![Simulator Screenshot - iPhone 15 - 2024-02-08 at 00 49 37](https://github.com/zulip/zulip-mobile/assets/32031946/77c9b007-da6e-4fb8-bf8c-7edb7036a595)

here messaged and profile is not formated/styled correctly. Anyhelp with this would be appreciated.

**Comment by gnprice** [comment]
Chat thread: https://chat.zulip.org/#narrow/stream/48-mobile/topic/css.20missing.20.23M5820/near/1733900

**Comment by gnprice** [comment]
Conclusion here: https://chat.zulip.org/#narrow/stream/48-mobile/topic/css.20missing.20.23M5820/near/1740985

It turned out the issue was that CocoaPods hadn't been installed. That's one of the required setup steps for iOS in [our setup instructions](https://github.com/zulip/zulip-mobile/blob/7b033bd508bb26eafb86a5f233aeb83b98af3de7/docs/howto/build-run.md).

Quoting one of my messages there:

> So if we had the information to debug what went wrong for you and why, then I'd want to add the needed code to either take care of it, or give a clear error instead of the half-working result you originally got.
>
> But because this app is now in maintenance mode as we build the new app in Flutter, we won't have time to drive that debugging ourselves. Glad you got the app working, in any case.
