### ISSUE TITLE
Android notifications don't works

### ISSUE THREAD

**Issue by long76** [zulip/zulip-mobile#5826]
hi, don't works notify from app. Version **v27.223**, server version **7.1**. I use Huawei P40 Lite with **HMS**, my teammate with phones with **GMS** don't receive notifications too. You can use [default notifications](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder) for Android? Thanks!

**Comment by chrisbobbe** [comment]
Please send a screenshot of the notification settings page in the app.

**Comment by long76** [comment]
```json
{
  "realm": "",
  "email": "",
  "isSelfHosted": true,
  "platform": {
    "OS": "android",
    "Version": 29
  },
  "nativeApplicationVersion": "27.223",
  "manufacturer": "HUAWEI",
  "brand": "HUAWEI",
  "model": "JNY-LX1",
  "nativeState": {
    "systemSettingsEnabled": true,
    "googlePlayServicesAvailability": {
      "isSuccess": false,
      "hasResolution": false,
      "errorMessage": null,
      "errorCode": 9
    }
  },
  "problems": [
    "GooglePlayServicesNotAvailable",
    "TokenUnknown"
  ],
  "isLoggedIn": true,
  "devicePushToken": null,
  "ackedPushToken": "dMcx5RgIT6o:APA91bFruFB-xuOo7wwMWnLjpm22d-RDNGIsJcQOk-txPglox8YlKt1h-bVhP9qExgPzS8eVhGBlC43D42fD0uZE3020uqtvKnE_EYt2vZ5vaB4EhDnWC74bRi5PoXMmcdubsr_XTEsu",
  "registerPushTokenRequestsInProgress": 0,
  "serverData": {
    "zulipVersion": "7.1",
    "zulipFeatureLevel": 185,
    "pushNotificationsEnabled": true,
    "pushNotificationsEnabledEndTimestamp": null,
    "endTimestampIsNear": false,
    "offlineNotification": true,
    "onlineNotification": true,
    "streamNotification": true
  }
}
```

**Comment by chrisbobbe** [comment]
I see, thanks for sending that. Is it fixed if you enable Google Play Services? Or is this not possible for you?

**Comment by long76** [comment]
> I see, thanks for sending that. Is it fixed if you enable Google Play Services? Or is this not possible for you?

It's not possible for Huawei, i try on other phone with GMS and no notifications too. Fallback to native notifications will be great.

**Comment by gnprice** [comment]
The notifications we show are indeed native.

The `NotificationCompat.Builder` class you linked to documentation for is a class we already use. It's part of the Android SDK's support for an app showing you a notification in the UI, after the app has already learned somehow that it needs to show a notification.

But the other side of things is how the app gets to that point. When someone sends a Zulip message you want a notification for, something has to tell your device to wake up, and to let the Zulip app run, and to pass the Zulip app a blob of data telling it about the notification it should show. That's the job that Google Play Services does when it comes to notifications.

If you can post the same information for the device that has GMS and no notifications, we can see about trying to resolve why that one isn't working.

**Comment by long76** [comment]
![915631DB-AFEE-44F6-801C-C8BCD4856666_edit_404842088104888.jpg](https://github.com/zulip/zulip-mobile/assets/18124433/e7e384ae-ba21-4795-a5df-604fb8f63c69)

**Comment by long76** [comment]
> The notifications we show are indeed native.
> 
> The `NotificationCompat.Builder` class you linked to documentation for is a class we already use. It's part of the Android SDK's support for an app showing you a notification in the UI, after the app has already learned somehow that it needs to show a notification.
> 
> But the other side of things is how the app gets to that point. When someone sends a Zulip message you want a notification for, something has to tell your device to wake up, and to let the Zulip app run, and to pass the Zulip app a blob of data telling it about the notification it should show. That's the job that Google Play Services does when it comes to notifications.
> 
> If you can post the same information for the device that has GMS and no notifications, we can see about trying to resolve why that one isn't working.

yes i don't see source) but why don't use `Background Service` for creating notifications? it's all works on all android GMS/HMS/no one. yes system can kill service on some firmware but many user can change it behavior for every app. it better than nothing) you can add setting in app use GMS for notifications or Service

**Comment by long76** [comment]
or you can use `Worker` for check updates every 5 minutes for example

**Comment by gnprice** [comment]
> but why don't use `Background Service` […] or you can use `Worker` for check updates every 5 minutes for example

Those solutions involve constantly waking up the user's device — both the CPU and the radios — in order to check for updates. That drains the user's battery.

Because the effect is so bad when an app does that, OSes tend not to allow it, unless the user goes deep into a settings tree to enable it. Even then, some vendors' OSes will silently turn the setting back off after a while.

If it's truly only every 5 minutes, the impact is low, but the user experience is pretty bad. You can get notifications much faster than that by email:
https://zulip.com/help/email-notifications

Either way, it's not a good experience, so it's not something that will make sense for our small team to spend time building.

---

I'm still interested in debugging the issue that your teammate is having on a device that does have Google Play Services installed. Please file a new issue for that, so we can keep it separate from the discussion of Huawei/etc. devices here. The screenshot you posted above is helpful, but the more important information will be what's on the troubleshooting screen — the same kind of information as in your comment https://github.com/zulip/zulip-mobile/issues/5826#issuecomment-1969889507 above.

**Comment by long76** [comment]
> > but why don't use `Background Service` […] or you can use `Worker` for check updates every 5 minutes for example
> 
> Those solutions involve constantly waking up the user's device — both the CPU and the radios — in order to check for updates. That drains the user's battery.
> 
> Because the effect is so bad when an app does that, OSes tend not to allow it, unless the user goes deep into a settings tree to enable it. Even then, some vendors' OSes will silently turn the setting back off after a while.
> 
> If it's truly only every 5 minutes, the impact is low, but the user experience is pretty bad. You can get notifications much faster than that by email: https://zulip.com/help/email-notifications
> 
> Either way, it's not a good experience, so it's not something that will make sense for our small team to spend time building.
> 
> I'm still interested in debugging the issue that your teammate is having on a device that does have Google Play Services installed. Please file a new issue for that, so we can keep it separate from the discussion of Huawei/etc. devices here. The screenshot you posted above is helpful, but the more important information will be what's on the troubleshooting screen — the same kind of information as in your comment [#5826 (comment)](https://github.com/zulip/zulip-mobile/issues/5826#issuecomment-1969889507) above.

i see, i wrote small app with worker(do api request getmessage) for me and thats works, it not true push but it works(battery usage in background work, if trust app battery usage, 16 seconds / 1,33 mAh for 24 hours). i found https://unifiedpush.org and https://gotify.net/ maybe it's not bad solution(first support FCM). 

what about teammate i think we can close question - our admin found this message and forgot about it:
```
Because you’re the registered server administrator for zulip.krista.ru, we are writing to inform you that your server is no longer eligible for free access to Zulip’s Mobile Push Notification Service.

In December, we announced new pricing plans for self-hosted Zulip installations, and sent an email notice to all registered Zulip server administrators. Signing up for a plan is required for continued access to the Mobile Push Notification Service, except for organizations with 10 or fewer users. Legacy customers like you had a grace period until February 15 to sign up.

If you intend to sign up for a plan, but have not yet done so, we recommend reaching out to sales@zulip.com to request an extension on your grace period.

Going forward, your options are:

    Do nothing. As always, we remain fully committed to Zulip’s 100% open-source model, so you do not have to purchase a plan in order to use Zulip. We are not turning Zulip into a proprietary product with an “open core” demo version — Zulip’s open-source software is the product. Organizations with 10 or fewer users get continued free access to the Mobile Push Notification Service, provided the server is uploading the basic metadata required to verify eligibility.

    Apply for Zulip Community. The Community plan is free of charge, and available to many open-source projects, research groups, educators, and community organizations. It includes unlimited push notifications.

    Upgrade to a paid plan. All paid plans include unlimited access to the Mobile Push Notification Service. The Business and Enterprise plans additionally include commercial support for dozens of features and integrations that help businesses take full advantage of their Zulip implementation. Discounts are available for education organizations, non-profits, organizations based in the developing world, and in other situations where standard pricing is not affordable. To discuss pricing options for your organization, reach out to sales@zulip.com.

    Move to Zulip Cloud. If you would like to switch to Zulip Cloud hosting, with its professionally managed, always up-to-date experience, our high-quality export tools make it easy to move your organization.

Our goal is that every organization should be able to use Zulip at a price that it can afford. If paying for Zulip Basic is a burden for your organization or makes you consider switching to an alternative, please contact us at sales@zulip.com, and we’ll do our best to help.

— Tim Abbott, for the Zulip team
```

**Comment by gnprice** [comment]
> what about teammate i think we can close question - our admin found this e-mail and forgot about it:

Got it, thanks for the followup. That explains why they're not getting notifications, then.

(There's still a mystery somewhere in why they weren't getting a warning about the lack of notifications. In general we aim for the app to always show a warning, just like the one you had in your first screenshot above, when either the device or the server isn't set up to support notifications. And from your later screenshot, it looks like it wasn't showing a warning for them.)

**Comment by gnprice** [comment]
> There's still a mystery somewhere in why they weren't getting a warning about the lack of notifications.

Ahhh, and figured this out too. It looks like your server (taking the server's hostname from the quoted email) is still on an older version of Zulip, namely 7.1:

```
$ curl -sS https://zulip.krista.ru/api/v1/server_settings | jq .zulip_version -r
7.1
```

That's from last June, and the current version is 8.2. One of the many improvements in more recent versions of Zulip Server is that it knows to warn about this situation.

**Comment by gnprice** [comment]
Sure, done.
