### ISSUE TITLE
Rename "stream" to "channel" , conditioned on server version

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5835]
In https://github.com/zulip/zulip/issues/28468, we plan to rename [streams](https://github.com/zulip/zulip/issues/28468) to [channels](https://github.com/zulip/zulip/issues/28468). We should make the corresponding change in the mobile apps.

As [discussed on CZO](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/stream.20-.3E.20channel.20renaming/near/1746523), the mobile app change should be conditioned on the server version, so that the terminology always matches between the user's web app and mobile app experience.

Web app / server issue:
- https://github.com/zulip/zulip/issues/28468

**Comment by gnprice** [comment]
Is this the same issue as #5827?

**Comment by alya** [comment]
Oops, yes, just noticed that.
