### ISSUE TITLE
Notification badge count not showing in iOS

### ISSUE THREAD

**Issue by jimjohnson8** [zulip/zulip-mobile#5844]
New user here. Is the badge count supposed to be working in iOS? I'm seeing the banners just fine, but nothing is triggering a notification count on the app icon for me in iOS 17.3.1.

Badges are enabled for the app. I toggled that off and on. Badges show up for other apps as expected. Force restart did not change this.

**Comment by gnprice** [comment]
Thanks for the report. This is a longstanding issue, unfortunately, and tracked as #438.

For details on the status, see the update I just posted there: https://github.com/zulip/zulip-mobile/issues/438#issuecomment-1989665091
