### ISSUE TITLE
Fuzzy keyword search needed 

### ISSUE THREAD

**Issue by fdenzer** [zulip/zulip-mobile#5867]
The docs (for web?) have no mention of glob/wildcard or regex search.
As a user, i need to find words starting or ending with my search keyword.
https://zulip.com/help/search-for-messages#keyword-search

Example, german words:
`Fräs` is searched, as a want to match `fräse`, `fräsvorrichtung`, `oberfräse`, `frästisch` as well as `tischfräse`.
Currently, I am going through a dictionary by hand to search. This is unbearable.

1. Ideally, the full text search is fuzzy, in at least using `contains` instead of `equals`.
2. Alternatively: Having placeholders, like `*` or `.*` would work, but a hint in UI would also be useful, because nobody RTFMs.

**Comment by fdenzer** [comment]
PS
Should I duplicate this issue to zulip/zulip, as it affects both mobile and web UI?

**Comment by gnprice** [comment]
@fdenzer Thanks for the feedback. Yeah, please open a discussion either in zulip/zulip or in the #feedback channel [on chat.zulip.org](https://zulip.com/development-community/). This behavior is primarily driven by the Zulip server, not clients, so those would be the places to discuss it.

(The existing behavior is more complex than "equals", but one of those venues will be a better place to go into detail.)
