### ISSUE TITLE
Make use of thumbnails

### ISSUE THREAD

**Issue by alya** [zulip/zulip-mobile#5875]
In https://github.com/zulip/zulip/issues/16210, we're implementing thumbnailing for uploaded images.

We should use thumbnails in the mobile app. In particular, the message view should show thumbnails, while the lightbox should download the full-scale images.

Blockers:
- https://github.com/zulip/zulip/issues/16210

Flutter issue:
- https://github.com/zulip/zulip-flutter/issues/799

`#api design` threads:
* https://chat.zulip.org/#narrow/stream/378-api-design/topic/thumbnailing.20transition.20for.209.2E0/near/1886620
* https://chat.zulip.org/#narrow/stream/378-api-design/topic/thumbnailing.20URLs/near/1843871
* https://chat.zulip.org/#narrow/stream/378-api-design/topic/thumbnail.20placeholder/near/1833796

**Comment by gnprice** [comment]
The current state of this is ([release-management chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/release.20management/near/1890603), and see also the `#api design` threads linked above):
* The server side might be ready to test on chat.zulip.org later today; if not, then hopefully by tomorrow at latest.
* We'll verify nothing goes horribly wrong already with existing clients; if it does, figure out on `#api design` how to deal.
* We'll verify that once there is a thumbnail, the existing client behaves well and there's nothing to do.
* We'll implement styling for the thumbnail placeholder.

**Comment by gnprice** [comment]
> * We'll verify nothing goes horribly wrong already with existing clients; if it does, figure out on `#api design` how to deal.
> * We'll verify that once there is a thumbnail, the existing client behaves well and there's nothing to do.

Confirmed!

> * We'll implement styling for the thumbnail placeholder.

Sent this as #5880.

Details in chat thread: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/thumbnails/near/1892137
