### ISSUE TITLE
Sometimes the emoji reactions don't work/do anything when clicked on. 

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#590]

**Comment by nashvail** [comment]
Could the optimistic reaction PR be a fix for this?

**Comment by borisyankov** [comment]
I am not sure. This was reported by @brockwhittaker but I haven't reproduced.
First step is to find out the cause ;)

**Comment by nashvail** [comment]
Looking into it. Noticed this  2 or 3 times when my internet connection was super laggy

**Comment by borisyankov** [comment]
We would likely want to work exclusively for some time on issues when the connection is bad.
But that is likely not the cause.

**Comment by borisyankov** [comment]
This will be fixed by https://github.com/zulip/zulip-mobile/pull/572 but need someone else testing it at least briefly :) (it can be you!)

**Comment by nashvail** [comment]
Pulling the PR to test if it resolves this issue

**Comment by nashvail** [comment]
Couldn't reproduce the bug since #572 got merged :) Would be helpful if more people tested it. @vishwesh3 @Sam1301 @kunall17 can you confirm?

**Comment by borisyankov** [comment]
I can't either. We can reopen if someone does.
