### ISSUE TITLE
App Store Requirements

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#591]
We might need to implement some or all of these:

* Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
* A method for filtering objectionable content
* A mechanism for users to flag objectionable content
* A mechanism for users to block abusive users
* The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

**Comment by timabbott** [comment]
I don't think other group chat tools like Slack have these mechanisms, which makes me think that probably we're not being processed correctly by Apple.

**Comment by borisyankov** [comment]
@timabbott Maybe we can argue for most of these that the administration functionality in the backend serves this purpose?

**Comment by borisyankov** [comment]
Closing, since app got accepted.
