### ISSUE TITLE
Show when a message has been edited

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#600]
On the web app, we indicate when a message has been edited from its original version, by putting the text "(EDITED)" in light text next to the sender's name.

On mobile, I don't see such an indicator. This is sometimes confusing when following a conversation, because other people have replied to the original version of the message and their replies no longer make sense in context.

I think the same design -- "(EDITED)" in light text next to the sender's name -- will work nicely on mobile too. (It'll get crowded if someone has a super-long name; not sure what should happen in that case, but this is similar to a case we already have to somehow handle where someone has a slightly more super-long name.)

**Comment by vishwesh3** [comment]
@zulipbot claim
