### ISSUE TITLE
Features that need back-end changes

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#605]
- [ ] Large images in the message list kill scrolling speed on Android (and wastes bandwidth on both iOS and Android)
- [ ] Simpler and limited HTML/CSS message generation by back-end - no 'float', more focus on 'flex-box' styling
- [x] Unread message count API call

**Comment by gnprice** [comment]
I believe there's nothing actionable remaining in this item, so closing it. If there's a followup still outstanding, let's open a specific issue for that.
