### ISSUE TITLE
Decide on how deep to pass Immutable

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#63]
We should discuss and document the outcome of the decision.

Several considerations
- Keep immutables deep, for all components. Pros - simple. Cons - immutables are not as convenient to use for all cases. Good to have a lot of components depend on simple standard types.
- toJS() them everywhere in mapStateToProps - Pros - simple. Cons - is a bad idea. Mentioning it intentionally. Kills performance because breaks shouldComponentUpdate - always is true because new objects. Should not use.
- Strategically use toJS() at some depth. Likely the best solution but needs thinking through.

**Comment by neerajwahi** [comment]
I think we should avoid Immutable unless we need it. I don't like the pattern of calling `toJS` everywhere. Ideally we shouldn't have to call it at all.

**Comment by borisyankov** [comment]
Immutable *is* needed. Or any other strategy that will not cause a full render of everything, on any single prop changing. Definitely crucial for expensive to render components like list of items (users, messages, streams)

**Comment by neerajwahi** [comment]
I don't mean we shouldn't use Immutable at all, but rather that we should only use it where we need it (such as the list of messages) and nowhere else. And if we do use it, we should pass the Immutable container around instead of calling `toJS` and converting it to a JS object.
