### ISSUE TITLE
Error on start of the app

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#648]
Steps : 

- fetch current master

- react-native run-android

Here is the screenshots : 

![screenshot_20170531-000956](https://cloud.githubusercontent.com/assets/21558765/26599557/93dfb3a0-4596-11e7-9d50-4905a8a7dfc5.png)

And sometimes

![screenshot_20170531-000908](https://cloud.githubusercontent.com/assets/21558765/26599556/93dfee06-4596-11e7-9632-59cbcbf89233.png)

**Comment by vishwesh3** [comment]
I think some translations string are missing for Hindi language. @saketkumar95  Can you please check by switching languages (to English or any other) in Setting page.

**Comment by saketkumar95** [comment]
Yeah already did that. But can't find any. Maybe i missed out something?

**Comment by borisyankov** [comment]
@saketkumar95 is this fixed in latest `master`?

**Comment by saketkumar95** [comment]
@borisyankov No. I still got this error.
