### ISSUE TITLE
Features to be Implemented in Settings Screen

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#649]
- [x]  About Option 

- [x]  Notification settings (whether to receive the push notifications or not ON/OFF State)  

- [x] 24-hour format or AM/PM

- [x] Display emoji’s as text or as emoticons ( To allow the user to display the emoji as :100 : instead of :100: 

Any other suggestions? 
@borisyankov @neerajwahi @timabbott

**Comment by timabbott** [comment]
I would start with settings that are important on mobile, e.g. namely the push notification settings (and we may find we need to add sound/vibrate/etc. controls for that too).  Most other things are going to be low priority in comparison.  But keep it simple: do 1 setting first (probably "receive mobile push notifications").

One question for the group is whether we want to have both global settings for the user and device-local settings, or whether every one of these should be synced to the server for all your devices.  I imagine some things like whether to vibrate or make a sound we might want to make device-local, so you can do something different on your tablet vs. your phone.

**Comment by borisyankov** [comment]
We do not need to add the notification settings to our Settings screen.
They are controlled by the OS.

**Comment by timabbott** [comment]
OK, so what remains is probably just the couple mobile-related items from https://chat.zulip.org/#settings/notifications ?

**Comment by kunall17** [comment]
Any more settings to be implemented?

**Comment by borisyankov** [comment]
I don't think there are any right now.
I'll close it, and we can add more as they come.
