### ISSUE TITLE
Improvement in Actionsheet (pops on message long press)

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#651]
- When Narrow to conversation is selected for a PM (not group, self and one other person), it handles it like group.
**Expected**
It should do a private narrow.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/18511177/26635573/d6e46244-4637-11e7-96a1-887c7e96a00c.gif)

- If user is already at bottom most narrow (private or topic narrow) then there is no need of Narrow to conversation option.

- After coping it will be better to show a message (via Toast or any other way).

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Good ideas 👍

**Comment by vishwesh3** [comment]
Closing this as completed
