### ISSUE TITLE
Getting error on long pressing messages in SearchMessageScreen.

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#653]
<img width="380" alt="screen shot 2017-06-01 at 10 18 24 pm" src="https://cloud.githubusercontent.com/assets/18511177/26691712/c8dea300-471b-11e7-8e9f-5f2243171cf1.png">

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
I think the simplest solution is to not support that for the search results, which is also reasonable.

**Comment by vishwesh3** [comment]
Got the problem :) it is because `ActionSheetProvider` is not present as parent of `MessageList` in `SearchMessageScreen.js`.

It will helpful to narrow to whole conversation using some searched keywords (through Narrow to conversation option). (Most of the time I do this)
