### ISSUE TITLE
Render message timestamps intelligently

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#70]
We should probably show a time (such as 8:00) when the message is recent (within the last few days), or a month and day otherwise (such as Apr 25)

**Comment by timabbott** [comment]
I think we should go with the same model we use in the currently planned webapp changes, which is to show the timestamp inline in the message, and dates in the recipient bars (only if the date of the messages is different from the previous recipient bar, or different from today in the case of the floating one at the top).
