### ISSUE TITLE
Message not rendered properly when there is <br> in the content

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#701]
When user have used `enter` to compose message.
`content:  "<p>line 1<br>line 2<br>line 3<br>line 4<br>line 5</p>"`

on mobile
![f94057d9-1f43-4fde-b8b1-040378480064-2](https://user-images.githubusercontent.com/18511177/27214469-4ed42cf4-528a-11e7-876e-b710a82a8299.jpg)

on web
![f94057d9-1f43-4fde-b8b1-040378480064](https://user-images.githubusercontent.com/18511177/27214471-4f873c4a-528a-11e7-808d-1ad5324f1736.jpg)

**Comment by saketkumar95** [comment]
@zulipbot claim

**Comment by vishwesh3** [comment]
This can be closed now. Fixed by https://github.com/zulip/zulip-mobile/commit/8898fd8e1e9c4e4e2cabd5d214c995f385a2850e
