### ISSUE TITLE
Improve Auto complete suggestions pop up

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#705]
- [x] Search by initials.

- [ ] Highlight filtered text in suggestions row.

- [ ] Show (in relatively small font size) and search in email as well.

- [ ] Move suggestions to outside Compose Box (above Topic field, i.e StreamBox). As input changes, size to list changes and topic field floats, which doesn't look good.

<img width="374" alt="screen shot 2017-06-16 at 4 12 51 pm" src="https://user-images.githubusercontent.com/18511177/27224083-f185db02-52b0-11e7-8915-83375a6a8092.png">

- [ ] Improve style. (dark theme etc)
<img width="388" alt="screen shot 2017-06-16 at 4 15 36 pm" src="https://user-images.githubusercontent.com/18511177/27224084-f26df6ee-52b0-11e7-8697-1ccd94a8156c.png">

screenshots w.r.t [current master](https://github.com/zulip/zulip-mobile/tree/c1ca982542f0b2af0dbee837cb5ade07b2336ef4)

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
>  Highlight filtered text in suggestions row.

I don't think this is needed.

**Comment by borisyankov** [comment]
@vishwesh3 should we close?

**Comment by vishwesh3** [comment]
yes 👍
