### ISSUE TITLE
Menu for long press on an app icon

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#766]
Long pressing on icons in Android can show a menu with options. (maybe something like that is possible for iOS on force touch?)

Apps like Hangouts, Allo and Telegram have these, like people who you conversed with last etc.

**Comment by pulkonet** [comment]
This can be done easily on android but requires writing native java code. If this is somewhere in the priority list we can do that, but I don't think implementing this should be on our plans as of now as the longPress app shortcuts are only supported by Android 7.0.0 and above.

**Comment by borisyankov** [comment]
I think it is so low priority that there is no need to keep it as an open issue.
