### ISSUE TITLE
Landscape mode of lightbox

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#771]
In landscape mode of light box , the "Shared with you" option is not visible.

Portrait Mode: 

![screenshot_20170630-053143](https://user-images.githubusercontent.com/21558765/27715577-d811eb8e-5d55-11e7-9ea5-a1e1895d5693.png)

Landscape Mode :

![screenshot_20170630-053152](https://user-images.githubusercontent.com/21558765/27715578-d823d09c-5d55-11e7-9d6e-7b18a1890f26.png)

cc: @borisyankov @Sam1301

**Comment by saketkumar95** [comment]
@zulipbot claim

**Comment by Sam1301** [comment]
Good catch! I missed to test in land orientation. After going though a couple of competitor apps, I find that the apps which provide full land support tend to be orientation agnostic and provide all features in both orientations (if feasible). So probably we should provide the lightbox header and footer (with limited details - to account for the change in dimensions between orientations) and let them be animatable to better support small screen devices.

@saketkumar95 if you'd like, I can send a pr for this :).

**Comment by saketkumar95** [comment]
@Sam1301 I just started with adding a landscape orientation support. No worries, you can go ahead. 👍

**Comment by saketkumar95** [comment]
@zulipbot abandon

**Comment by saketkumar95** [comment]
bdw , Try testing on small iOS devices. It worked on tablet. Only small devices were having this issue.
