### ISSUE TITLE
[Android] Anchor position not maintained on first message list load

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-mobile#773]
The anchor position is not maintained whenever the message list is loaded for the first time.

**Comment by Sam1301** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Not sure if related, but when switching narrows the position tends to not be correct. This is Android specific.

Another tangentially related issue is that the message read events that you worked on, again specifically for Android, seem to be working but off by a bit - when I scroll through a whole stream narrow, most messages are marked as read, but not all. This works correctly on iOS.

**Comment by Sam1301** [comment]
Thanks for these details! 👍 
> Not sure if related, but when switching narrows the position tends to not be correct. This is Android specific.

verified this is related to this issue, which doesn't seem to be a regression.
> Another tangentially related issue is that the message read events that you worked on, again specifically for Android, seem to be working but off by a bit - when I scroll through a whole stream narrow, most messages are marked as read, but not all. This works correctly on iOS.

should be fixed by #775, verified all visibleIds are sent.
