### ISSUE TITLE
Inline previews in messages

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#78]
Add rendering of inline previews for embedded content (such as tweets)

**Comment by borisyankov** [comment]
@neerajwahi What does this mean?

**Comment by timabbott** [comment]
Is this about inline image previews?

**Comment by neerajwahi** [comment]
Updated the description. I think I had things like tweets in mind when I created this. We already have inline image previews

**Comment by borisyankov** [comment]
These are heavy html/css responses, and after discussing with Tim, it seems the weight will be on the app, not on the server to make it work. So I am doing a deep-html parsing & rendering that will improve the rendering.

That being said, the twitter styling is very bad IMHO (in the main site). Ideally they will look more like what you get when you embed a tweet.

**Comment by timabbott** [comment]
Yeah, we should do a pass of revisions of our twitter cards on web.  They looked like what tweets did 3 years ago, which is when that twitter card implementation was originally done :).
