### ISSUE TITLE
[Android] Issues in clear button

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#810]
I got some issues with clear button in dark theme.

Dark theme :
![picsart_07-06-04 08 35](https://user-images.githubusercontent.com/21558765/27888155-372a6ca8-6202-11e7-80ce-02c07ab84055.jpg)

Light Theme :
![picsart_07-06-04 14 39](https://user-images.githubusercontent.com/21558765/27888156-3731a8d8-6202-11e7-906a-1553ffdbf773.jpg)

Dark Theme : 

![picsart_07-06-04 08 56](https://user-images.githubusercontent.com/21558765/27888172-4abb1b14-6202-11e7-8b5a-63fdec1d4472.jpg)

Light theme : 
![picsart_07-06-04 09 25](https://user-images.githubusercontent.com/21558765/27888173-4abf006c-6202-11e7-8d24-ee85642eb77d.jpg)

**Comment by saketkumar95** [comment]
@zulipbot claim

**Comment by nashvail** [comment]
While you're at it, just noticed the ClearButton in iOS could use a little right margin. Please consider doing that too :) 

![](https://puu.sh/wCXZl/ef38e62c8e.png)
