### ISSUE TITLE
Have null object constants

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#819]
We should have a nullObjects.js file which exports constants of empty objects that are returned on 'not found' conditions.

Benefits:
 * consolidating logic
 * do not create a new object on each failure but reuse
 * does not cause repaint

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
@vishwesh3 I did some initial work here:
https://github.com/zulip/zulip-mobile/commit/263b10ccd6219fd8168be47b9e6a663fe50dc53f

There is more work that can be done though, so continue on it.
