### ISSUE TITLE
@mention suggestions disappear after typing a space

### ISSUE THREAD

**Issue by jrowan** [zulip/zulip-mobile#823]
(nevermind, the issue I was having was on the android app not the react app, I posted this on the wrong repository, sorry)

**Comment by Sam1301** [comment]
@jrowan Thanks for the bug report. From the screenshots I infer this is the native java android app. Would be great if you could file this bug there (https://github.com/zulip/zulip-android). 
Thanks!

**Comment by timabbott** [comment]
@Sam1301 is the issue present in the mention typeahead on mobile here, though?  If so, we may want to fix anyway.

**Comment by Sam1301** [comment]
Oops, this issue seems to be in RN app too.
Linking the android issue for further details https://github.com/zulip/zulip-android/issues/511.

**Comment by borisyankov** [comment]
Fun stuff ;)
@vishwesh3 did some improvements in that area, maybe he wants to do this fix too?

**Comment by borisyankov** [comment]
Closing as fixed.
