### ISSUE TITLE
Layout issues on iOS mobile

### ISSUE THREAD

**Issue by trbabb** [zulip/zulip-mobile#842]
Not sure if this is appearing in other platforms, but in iOS the layout will often screw up and overlap itself:

![img_2082](https://user-images.githubusercontent.com/5055969/28028958-5658e5d8-656c-11e7-966a-9ab9069f4ae2.PNG)

**Comment by borisyankov** [comment]
Thanks for reporting this issue. It is the first time I see it.
Will investigate!

**Comment by borisyankov** [comment]
Closing as fixed.
