### ISSUE TITLE
Use much less {...this.props} in favor of concrete props and deeper 'connect' calls

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#855]
Good option to explore first is the component `Avatar`. It always needs the `realm` property to retrieve the full url.

**Comment by Sam1301** [comment]
actually this could also be implemented with #835 (in fact did something similar in #845)

**Comment by borisyankov** [comment]
Good thinking. I was actually questioning already if we need to use the state realm since in future we might want to show avatars from two realms at once.
if we have Avatar and AvatarContainer, we can use the first for multiple realms.

**Comment by borisyankov** [comment]
Closing as implemented.
