### ISSUE TITLE
Crash in Android

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#865]
Got a crash on android .
Something related to Crashlytics.

I commented out this [line](https://github.com/zulip/zulip-mobile/blob/master/android/app/src/main/java/com/zulipmobile/MainApplication.java#L75)  and the crash was gone.

**Comment by borisyankov** [comment]
@vishwesh3 make sure to remove any trace of Fabric/Crashlytics from the Sentry PR 🥇

**Comment by vishwesh3** [comment]
We can close this now as Sentry is in. I forgot to mention this issue in commit message.
