### ISSUE TITLE
[Android] Error on message long press.

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-mobile#867]
Tested on 4.4.4, 4.1.1, 7.1.0

<img width="455" alt="screen shot 2017-07-13 at 9 06 54 am" src="https://user-images.githubusercontent.com/18511177/28149381-d004bd68-67aa-11e7-9f2b-2d436f25d5e8.png">

**Comment by vishwesh3** [comment]
this may be auto resolved once we upgrade to react-native 0.44.0
https://stackoverflow.com/a/44100312/5612089

**Comment by borisyankov** [comment]
Yeah, I guess we can either downgrade the ActionSheet library or upgrade React Navigation.

**Comment by vishwesh3** [comment]
@zulipbot claim
