### ISSUE TITLE
Delete sent messages option

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#883]
Currently it is handled by editing the message but the editing message cannot be empty to send the message. 
I was thinking of adding an option of Delete message and using updateMessage api to delete the message same as it is done on web. 

After deleting the message will be show `(deleted)`

@borisyankov Thoughts?

**Comment by saketkumar95** [comment]
@zulipbot claim

**Comment by borisyankov** [comment]
Yeah, sounds like a good idea.
