### ISSUE TITLE
Error when translated to other language

### ISSUE THREAD

**Issue by fragm3** [zulip/zulip-mobile#892]
When I translate to Hindi or any language other then English, I get the following error: 

<img width="395" alt="screen shot 2017-07-18 at 2 51 39 pm" src="https://user-images.githubusercontent.com/18073126/28310077-e91abab0-6bc8-11e7-845d-73836bd01de9.png">

**Comment by borisyankov** [comment]
Thanks for letting us know about this. I'll update the translations.

**Comment by borisyankov** [comment]
Closing as fixed.
