### ISSUE TITLE
Add side menu / drawer with list of users

### ISSUE THREAD

**Issue by neerajwahi** [zulip/zulip-mobile#9]
- Presence fetching
- Presence update sending
- Narrowing to PMs with a user via buddy list

**Comment by borisyankov** [comment]
I am starting with this one.

**Comment by timabbott** [comment]
For presence fetching and sending, `focus_ping` at https://github.com/zulip/zulip/blob/master/static/js/activity.js#L354 is the webapp code that connects to the relevant API.  It's sorta an interesting API -- you send your own presence data, and receive in the reply everyone else's.

**Comment by borisyankov** [comment]
@neerajwahi Fully resolved by #53
