### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-mobile#920]
I thought of adding slide in and out animations for few screens like in 

- Custom tabs, 
- Realm screen to Password Auth screen, 
- When logging out , then Slide out animation.

And many more where required.

@borisyankov Thoughts? 
@zulipbot claim Currently for Custom tabs because I think it's required there because iOS have something similar builtin animation while opening links.

**Comment by borisyankov** [comment]
@saketkumar95 the custom tabs animation PR is merged.
Thanks for it.
Have a look at open issues with tags 'bug' or any issues that make the app break or crash.
Until we have even one of these, they are a higher priority than animations and polish.
