### ISSUE TITLE
Build failed error

### ISSUE THREAD

**Issue by fragm3** [zulip/zulip-mobile#922]
OS: macOS sierra 10.12.5

On running react-native run-ios, I get the following error:

>  ** BUILD FAILED **
> The following commands produced analyzer issues:
> 	Analyze /Users/shubham/zulip-mobile/zulip-mobile/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
> 	Analyze /Users/shubham/zulip-mobile/zulip-mobile/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
> (2 commands with analyzer issues)
> 
> The following build commands failed:
> 	CpResource Build-Phases build/Build/Products/Debug-iphonesimulator/ZulipMobile.app/Build-Phases
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/ZulipMobile.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> Failed to install the requested application
> The bundle identifier of the application could not be determined.
> Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ZulipMobile.app/Info.plist
>

**Comment by borisyankov** [comment]
@Sam1301 is this related to the issues we saw with 'build phases'?

**Comment by saketkumar95** [comment]
@fragm3 Can you try `react-native upgrade` ? Maybe it will solve your's too.

**Comment by Sam1301** [comment]
yes this is because Build Phases dir was removed. @fragm3 this worked for me; open project in xcode (https://github.com/zulip/zulip-mobile/blob/master/docs/developer-guide.md#running-on-an-ios-device), go to root of project -> build phases -> Copy Bundled resources and remove Build Phases from there or alternatively create  empty `Build Phases` dir in `ios/`.

**Comment by kunall17** [comment]
@saketkumar95 Can you please upload the code changes of the changes as it would help in #915 ?

**Comment by kunall17** [comment]
Can be closed after #940 merged!

**Comment by borisyankov** [comment]
Closing, as #940 is merged.

**Comment by akashnimare** [comment]
I was getting the same error. It got fixed magically after upgrading `XCODE` to `v9.2` (previously I was on v8.1) 😅
