### ISSUE TITLE
WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.

### ISSUE THREAD

**Issue by danielmwai** [zulip/zulip-mobile#946]
Running  the  command  react-native run-android  
I get the error 
   error: closed
Could not run adb reverse: Command failed: /apps/DEV_TOOLS/android-sdk-linux/platform-tools/adb -s PBUGUG65U4G6SS5D reverse tcp:8081 tcp:8081
Starting the app on PBUGUG65U4G6SS5D (/home/nzaniela/apps/DEV_TOOLS/android-sdk-linux/platform-tools/adb -s PBUGUG65U4G6SS5D shell am start -n com.zulipmobile/com.zulipmobile.MainActivity)...
WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.
Starting: Intent { cmp=com.zulipmobile/.MainActivity }

and the  app  crashes  on the  android  device

**Comment by Sam1301** [comment]
I couldn't repro this error; @danielmwai maybe its because ANDROID_HOME environment var is not set correctly. Maybe verify this by running adb command alone?

**Comment by borisyankov** [comment]
Closing as not-reproducable.
