### ISSUE TITLE
"Could not connect to server" error

### ISSUE THREAD

**Issue by jhurwitz** [zulip/zulip-mobile#960]
I just updated to 1.0.15 and cleared app data, requiring me to log in again. For both servers I tried logging into (including chat.zulip.org), the following happened:

* I entered the server URL
* I received an error "Could not connect to server"
* Without editing or modifying the URL in any way, I tried clicking the "Enter" button again -- this time it worked

**Comment by borisyankov** [comment]
@jhurwitz it was a bug we introduced. It is fixed now, and will release with next version. Maybe that can be one of the tests on our E2E suite @kunall17

**Comment by borisyankov** [comment]
Actually, I'll close the issue as the bug is merged to `master`
