### ISSUE TITLE
"Message {stream}" text under compose box is cut off

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#962]
See screenshot:
![Image](http://i.imgur.com/hCFCK7E.jpg)

**Comment by gnprice** [comment]
(Filed that issue right from my phone -- whee! The "CodeHub" app on iOS seems to work reasonably well.)

**Comment by borisyankov** [comment]
This issue, together with the better topic input will get fixed next.

**Comment by borisyankov** [comment]
Fixed with new compose box design.
