### ISSUE TITLE
Message input box is broken in latest build.

### ISSUE THREAD

**Issue by brockwhittaker** [zulip/zulip-mobile#972]
Input is broken on the message compose box where text only shows up in a small sliver.
![img_1254](https://user-images.githubusercontent.com/10321399/28896812-ce0d7610-7792-11e7-9452-033cb75c76c1.PNG)

**Comment by borisyankov** [comment]
Something in the latest React Native version broke it.
We are replacing it with a better one anyways.

**Comment by borisyankov** [comment]
Fixed in latest `master` by merging the new compose box design.
