### ISSUE TITLE
Consider using WebView for MessageList/StreamView

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#98]
There is a very strong possibility that WebView is a better choice than custom rendering the messages.

* WebView is natural option for rendering html based content
* ScrollView is very inefficient for large lists, I was strongly considering ListView instead (though there were some issues with it too)
* Cross-platform - current implementation is iOS only
* Likely to be more performant for this part of the app

**Comment by borisyankov** [comment]
@neerajwahi @timabbott This issue is just as a reference and a think piece. Let the idea sink in. It didn't sound as the best approach initially to me either, but the more I think of it the better it looks. We can discuss this again sometime in P2.

**Comment by neerajwahi** [comment]
@borisyankov I'm moving these more exploratory types of tasks (which we are just discussing and not committed to) to an 'Idea' milestone
